### ISSUE TITLE
NPM got extracted into 'node/package'

### ISSUE THREAD

**Issue by gyandeeps** [eirslett/frontend-maven-plugin#101]
On your build machine the npm got extracted into "node/package" folder rather than "node/npm" folder. On my own machine it works fine but on the build machine it is a problem.

Any one has seen this issue?

**Comment by mitchh** [comment]
Hm; this is happening to me of late (using 0.0.16)

**Comment by mitchh** [comment]
Looks like https://github.com/eirslett/frontend-maven-plugin/blame/84105baacb4b45a5d7c1a4372036bf6d032cf508/frontend-plugin-core/src/main/java/com/github/eirslett/maven/plugins/frontend/lib/NodeAndNPMInstaller.java#L154 should make it work - but that is in the 0.0.16 tag so I'm not sure what to make of it
