### ISSUE TITLE
how to disable js minification

### ISSUE THREAD

**Issue by pawee-del** [eirslett/frontend-maven-plugin#1017]
**Do you want to request a _feature_ or report a _bug_?**

**What is the current behavior?**
the js code is automatically minify, how do i disable it
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your frontend-maven-plugin and operating system version.**

**Comment by eirslett** [comment]
Configure your build tool to do so. Look at the documentation for Gulp, Webpack, whatever you're using.
