### ISSUE TITLE
Support for corepack

### ISSUE THREAD

**Issue by timja** [eirslett/frontend-maven-plugin#1032]
**Do you want to request a _feature_ or report a _bug_?**
Feature

The preferred way to manage the version of yarn is now corepack not checking the yarn file into the git repo: https://yarnpkg.com/getting-started/install

**What is the current behavior?**
No support

**What is the expected behavior?**

- A flag to enable [corepack](https://nodejs.org/dist/latest/docs/api/corepack.html) support
- The plugin should run `corepack enable`
- Don't require setting a `yarn` version as it will be set in the package.json and corepack will handle fetching it

**Please mention your frontend-maven-plugin and operating system version.**
-

**Comment by long76** [comment]
up vote here

**Comment by bencope** [comment]
@eirslett any chance of having this one merged?
