### ISSUE TITLE
Environment.prod.ts

### ISSUE THREAD

**Issue by mateo9x** [eirslett/frontend-maven-plugin#1072]
**Do you want to request a _feature_ or report a _bug_?**
Report

**What is the current behavior?**
How to select to build with environment.prod.ts instead of environment.ts ?

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your frontend-maven-plugin and operating system version.**

**Comment by eirslett** [comment]
I think this issue has been opened in the wrong github repository. 🤷 There is no environment.ts or environment.prod.ts in here. Maybe do something like `npm run build:dev` or `npm run build:prod`.
