### ISSUE TITLE
Plugin Validation Issue on Maven 3.9.2

### ISSUE THREAD

**Issue by henderea** [eirslett/frontend-maven-plugin#1085]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behavior?**
With the latest maven 3.9.2, I see a plugin validation issue:
```
[WARNING]  * com.github.eirslett:frontend-maven-plugin:1.12.1
...
[WARNING]   Plugin issue(s):
[WARNING]    * Plugin should declare these Maven artifacts in `provided` scope: [org.apache.maven:maven-plugin-api:3.6.0, org.apache.maven:maven-model:3.6.0, org.apache.maven:maven-artifact:3.6.0]
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Run a maven build with `-Dmaven.plugin.validation=verbose` to see the full details, though you'll get a basic notice with any maven build on maven 3.9.2.

**What is the expected behavior?**
No warning.

**Please mention your frontend-maven-plugin and operating system version.**
frontend-maven-plugin: 1.12.1 (as seen in maven build output above)
OS: macOS 12.6.5
Maven: 3.9.2
Java: 11.0.16

**Comment by xak2000** [comment]
As a note to why this is happening, see Maven 3.9.2 [Release Notes](https://maven.apache.org/docs/3.9.2/release-notes.html#notable-new-features) - the part about "Plugin validation warnings change".

Basically, they are preparing to upcoming Maven 4, so these warnings should be fixed to make plugin compatible with Maven 4.

**Comment by eirslett** [comment]
I think this should be fixed with the latest 1.13.1 release.

**Comment by xak2000** [comment]
@eirslett I tried 1.13.1 and warnings are not completely gone.

```
[WARNING]
[WARNING] Plugin validation issues were detected in 1 plugin(s)
[WARNING]
[WARNING]  * com.github.eirslett:frontend-maven-plugin:1.13.1
...
[WARNING]   Plugin issue(s):
[WARNING]    * Plugin should declare these Maven artifacts in `provided` scope: [org.apache.maven:maven-artifact:3.6.0]
```

You can check it yourself by running:
```
mvnw compile -Dmaven.plugin.validation=VERBOSE
```
on any project, that uses Maven Wrapper 3.9.2 and frontend-maven-plugin 1.13.1.

**Comment by eirslett** [comment]
oh :-( how about 1.13.2?

**Comment by xak2000** [comment]
Tried 1.13.2 - works without warnings! 👍
