### ISSUE TITLE
Warning generated in maven 3.9.2 builds

### ISSUE THREAD

**Issue by cernenwein** [eirslett/frontend-maven-plugin#1090]
Bug:
[WARNING]   Plugin issue(s):
[WARNING]    * Plugin should declare these Maven artifacts in `provided` scope: [org.apache.maven:maven-plugin-api:3.6.0, org.apache.maven:maven-model:3.6.0, org.apache.maven:maven-artifact:3.6.0]
[WARNING]

on a simple maven build

**Comment by basil** [comment]
Duplicates #1085.
