### ISSUE TITLE
Plugin validation isue with Maven 3.9.2

### ISSUE THREAD

**Issue by basil** [eirslett/frontend-maven-plugin#1093]
Even after upgrading to 1.13.1, the issue is not resolved:

[WARNING]  * com.github.eirslett:frontend-maven-plugin:1.13.1
[WARNING]    * Plugin should declare these Maven artifacts in `provided` scope: [org.apache.maven:maven-artifact:3.6.0]

**Comment by eirslett** [comment]
oh :-( how about 1.13.2?

**Comment by alankstewart** [comment]
No warnings for me now with 1.13.3. Thanks

**Comment by basil** [comment]
Thank you, 1.13.3 is working for me.
