### ISSUE TITLE
Using multiple npmRegistryURL for a project

### ISSUE THREAD

**Issue by pmfrontdev2023** [eirslett/frontend-maven-plugin#1101]
Hello,
I was trying to use two different registries by having two different "npmRegistryURL" in a project, but it seems that what this does is to override the one that appear as first with the one that appears in the second place, and so the 3rd parties that are available in the first registry cannot be found since they are only being searched for in the second registry. Is this a bug or is there a limitation of the registries you can have in your project with this plugin? If so, how can I have multiple registries for a project using this plugin?
Thank you
![x](https://github.com/eirslett/frontend-maven-plugin/assets/134928279/96fc96ac-d8c6-48e1-82b1-dc77beeb1daf)

**Comment by eirslett** [comment]
For multiple registries, I think you'll have to remove that option, and instead provide your own `.npmrc` file where you configure your registries and their authentication. Then you might also have to set `<npmInheritsProxyConfigFromMaven>false</npmInheritsProxyConfigFromMaven>` but I'm not 100 % sure.
