### ISSUE TITLE
Plugin is incompatible with AWS CodeBuild

### ISSUE THREAD

**Issue by nkavian** [eirslett/frontend-maven-plugin#1102]
**Do you want to request a _feature_ or report a _bug_?**

Bug

**What is the current behavior?**

Maven builds fail on AWS.

**If the current behavior is a bug, please provide the steps to reproduce.**

Create an AWS CodeBuild project and specify in the `buildspec.yml` to build your Java 11 maven project.

Configure the build server as `Amazon Linux 2 x86_64 standard:corretto11`.

The build fails, and with debug logging it's basically complaining about missing system libraries.

```
[INFO] Running 'npm install' in /codebuild/output/src3170213863/src/git-codecommit.eu-west-1.amazonaws.com/v1/repos/versal/versalpayments-server
[DEBUG] Executing command line [/codebuild/output/src3170213863/src/git-codecommit.eu-west-1.amazonaws.com/v1/repos/versal/versalpayments-server/node/node, /codebuild/output/src3170213863/src/git-codecommit.eu-west-1.amazonaws.com/v1/repos/versal/versalpayments-server/node/node_modules/npm/bin/npm-cli.js, install]
[INFO] /codebuild/output/src3170213863/src/git-codecommit.eu-west-1.amazonaws.com/v1/repos/versal/versalpayments-server/node/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /codebuild/output/src3170213863/src/git-codecommit.eu-west-1.amazonaws.com/v1/repos/versal/versalpayments-server/node/node)
[INFO] /codebuild/output/src3170213863/src/git-codecommit.eu-west-1.amazonaws.com/v1/repos/versal/versalpayments-server/node/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /codebuild/output/src3170213863/src/git-codecommit.eu-west-1.amazonaws.com/v1/repos/versal/versalpayments-server/node/node)
```

**What is the expected behavior?**

If this plugin insists on controlling the NodeJS version, it should also resolve the dependency issues.

Initially I was trying to install node myself into the build pipeline and found out this plugin is specifically against it.

Additional context / workaround:
 - To get the system libraries installed, I chose to still install node separately; and it worked.
 - I'm building using Java11 `corretto11` and based on this matrix, I had to install NodeJS `14` to be able to use `Ubuntu standard:5.0` which is an older system image. Eventually, these images will have mismatches and this workaround will eventually be gone. i.e. I can't install NodeJS `18`.

https://docs.aws.amazon.com/codebuild/latest/userguide/available-runtimes.html

**Please mention your frontend-maven-plugin and operating system version.**

1.13.4

**Comment by eirslett** [comment]
I'm not sure there's anything that can be done 🤷 if using Node 14 is OK then I guess the problem is solved! Or maybe upgrade to Java 17 to get the latest Ubuntu and unlock the newest Node version...

**Comment by nkavian** [comment]
I was hoping for a different outcome. If this plugin is insisting it doesn't want to use Node/NPM installed by the user, then this plugin should manage and take care of the dependencies. Alternatively, I was really hoping that it would be understood that locking Node/NPM this was actually impractical and that users should be allowed to manage it on their own **if they need to**.

I can't for example, just upgrade from Java 11 to Java 17, since I have other Java dependencies that require Java 8/11. I'm caught in the middle since others are locking things.

thanks for the quick response.

**Comment by eirslett** [comment]
This plugin might not be the right tool for the job. For use cases where you would like to use system-provided node/npm binaries (and not lock down the versions), the exec-maven-plugin is a much better alternative:
https://www.mojohaus.org/exec-maven-plugin/
Another option is to use a Docker image with the newer Ubuntu but with JDK 11?
I think you might have stumbled upon an edge case. As far as I know, there are no other reports of this bug.

**Comment by clementepereyra** [comment]
Hi @nkavian, I am facing pretty much the same issue here.
Can you please share the workaround you found?
Thanks.

**Comment by nkavian** [comment]
@clementepereyra sorry for the delayed response

In the AWS build project I use an `Environment` `Image` of `aws/codebuild/standard:5.0`.

In the `buildspec.yml` I use:

```yml
phases:
  install:
    runtime-versions:
      java: corretto11.x
      nodejs: 14.x
```
