### ISSUE TITLE
Feature Req: Add support for Bun

### ISSUE THREAD

**Issue by duttonw** [eirslett/frontend-maven-plugin#1106]
Bun is brand new on the scene and looks to be a great drop in replacement to speed up tool chaining front end builds. 

It would be awesome if we could incorporate the install of Bun via this plugin and allow it to interact like we do for node+npm|yarn.

https://bun.sh/blog/bun-v1.0
https://oven.sh/
https://news.ycombinator.com/item?id=37434117

	

> https://news.ycombinator.com/item?id=37434968 creativeembassy 6 days ago
> 
> Personal experience: Bun has been a flawless drop-in replacement for both NodeJS and npm/yarn since I started using it around v0.4. Not only have I had zero issues running it, but it's been WAY faster. No benchmarks, but very noticeable, from "let's start a new build and go grab a coffee while waiting for it" on NodeJS, to "hit run aaaaand it's done."
> I haven't thought twice about it. Frankly, I forgot that bun has been happily running behind the scenes for me. I highly recommend anyone using NodeJS to give it a go.

**Comment by deemkeen** [comment]
@duttonw you can take a look on the basic draft

**Comment by duttonw** [comment]
@deemkeen , wow, awesome job. Yep Bun on Windows is experimental so leaving that out atm would be best. 

Seems they push you to install the Linux Sub-system on windows to run it which is  :/.  

They have put out hints for it in their blog posts https://bun.sh/blog/bun-v1.0#bun-more-thing  and this pr may make it work. https://github.com/oven-sh/bun/pull/4410 

I'll try and give this a go in the coming days. 

Regards,

@duttonw

**Comment by deemkeen** [comment]
this can be closed, i guess

**Comment by sarveshrulz** [comment]
Windows support is added, so maybe we can discuss on this more?

https://bun.sh/blog/bun-v1.1

**Comment by sarveshrulz** [comment]
Maybe we can enable bun for windows now...

https://bun.sh/blog/bun-v1.1
