### ISSUE TITLE
Change log not recently updated

### ISSUE THREAD

**Issue by hazendaz** [eirslett/frontend-maven-plugin#1112]
Seems no change log updates nor using github releases either.  Can we get change log updated for newer releases so we can see what is changing more easily?

**Comment by melloware** [comment]
@eirslett did a release yesterday but does not seem very active in this project.  I wonder if it is time to fork it if he is no longer merging PR's or active in this plugin?

**Comment by eirslett** [comment]
Fixed in #1117
