### ISSUE TITLE
skipTests is not respected

### ISSUE THREAD

**Issue by sashasochka** [eirslett/frontend-maven-plugin#113]
Hi, if I run `mvn install -DskipTests=true` and have the following in pom.xml:

```
                <execution>
                    <id>js tests</id>
                    <goals>
                        <goal>npm</goal>
                    </goals>
                    <configuration>
                        <arguments>test</arguments>
                    </configuration>

                    <phase>test</phase>
                </execution>
```

My `npm test` script is executed for some reason (note that is should be run only during test phase). I'd really like to have this fixed.

Anyways, thanks for your plugin!

**Comment by Siva563** [comment]
@eirslett , what we can do with npm instead of gulp, I m using gulp, I want to skip my test goal.

**Comment by eirslett** [comment]
Try making `gulp test` a separate gulp command, create a new npm script "test" which is "gulp test", and then make the plugin run `npm test` with `<phase>test</phase>`, something like that?

**Comment by toverly-foreflight** [comment]
Super old, but hey you can always add to the configuration:

```
<configuration>
   <skip>${skipTests}</skip>
</configuration>
```
