### ISSUE TITLE
How to skip downloading & installing Node

### ISSUE THREAD

**Issue by TharinduDG** [eirslett/frontend-maven-plugin#1140]
**Do you want to request a _feature_ or report a _bug_?** _feature_

**What is the current behavior?**
I'm trying to build Apache pinot in my company's CD pipeline.
[Apache pinot](https://github.com/apache/pinot/blob/master/pinot-controller/pom.xml#L192) uses _frontend-maven-plugin_ and it tries to download and install _node_.
But we're not allowed to download anything other than maven dependencies.
Is there an option in this plugin to skip download? If so I think I can run the build process inside _docker_ where _node_ can be allowed.

I couldn't find anything in the docs. 🤔

**Comment by andythsu** [comment]
would like to know too!

**Comment by andythsu** [comment]
@TharinduDG Turns out there's a skip param you can probably use

https://github.com/eirslett/frontend-maven-plugin/blob/5ad126f96120c42e4f5d7856af57434485c26a66/frontend-maven-plugin/src/main/java/com/github/eirslett/maven/plugins/frontend/mojo/InstallNodeAndPnpmMojo.java#L72

something like 

```
<plugin>
    ...
    <configuration>
        <skip>true</skip>
    </configuration>
</plugin>
```

**Comment by TharinduDG** [comment]
Thanks. :-)
