### ISSUE TITLE
unable to download Node.js

### ISSUE THREAD

**Issue by wenic** [eirslett/frontend-maven-plugin#12]
[INFO] Downloading Node.js from http://nodejs.org/dist/v0.10.18/node-v0.10.18-linux-x64.tar.gz to ...

plugin is unable to download node.js, we have a proxy in our network.

if I wget the url used in output I am able to download it, I have our proxy set both in the settings.xml in .m2 and as the env variable, so it seem that the plugin is not downloading through the proxy.

**Comment by OuesFa** [comment]
Hi,

I'm new to all this stuff, i'm trying to use the plugin behind a proxy, i have this error.
_Downloading Node.js from http://nodejs.org/dist/v0.10.18/node-v0.10.18-linux-x64.tar.gz_
_Could not download http://nodejs.org/dist/v0.10.18/node-v0.10.18-linux-x64.tar.gz: Network is unreachable_

So i try to download the binaries but, silly question, what do you mean by _commit them to the  repository_ ??

Thanks for help
