### ISSUE TITLE
Enable to build the web application on a jenkins server

### ISSUE THREAD

**Issue by pythonic6** [eirslett/frontend-maven-plugin#123]
Hi,
i'm developing a web application with the fronted-maven-plugin, and i have to build it on a jenkins server. But thats not possible, because the fronted-maven-plugin downloads the node.exe ?

And if i try to build to project local on my pc, there appear a log of npm ERRORS:
[INFO] npm ERR! npm -v 1.3.25
[INFO] npm http GET https://registry.npmjs.org/load-grunt-tasks
[INFO] npm ERR! TypeError: Request path contains unescaped characters.

Have someone any ideas?

**Comment by eirslett** [comment]
I'll close this. The integration test is running on a Jenkins server, so that shouldn't be the problem?
