### ISSUE TITLE
Add bower as an option to install and run

### ISSUE THREAD

**Issue by gregturn** [eirslett/frontend-maven-plugin#133]
I use certain components that are only released through bower. Having this plugin support bower as well would be handy.

So far, I have worked around it by adding this execution:

```xml
<execution>
	<id>install-bower-components</id>
	<goals>
		<goal>npm</goal>
	</goals>
	<phase>generate-resources</phase>
	<configuration>
		<arguments>run install-bower-components</arguments>
	</configuration>
</execution>
```

And I have this **package.json** file, which includes bower as a **devDependencies**, and the script step **install-bower-components** to run the node module of bower, to thus install my bower dependencies. This would be really handy to not to have to code by hand for every project I go to.

```javascript
{
  "name": "Spring-a-Gram",
  "version": "1.0.0",
  "description": "Demo Spring Data REST by uploading your favorite pics",
  "main": "run.js",
  "scripts": {
    "install-bower-components": "./node_modules/.bin/bower install"
  },
  "repository": {
    "type": "git",
    "url": "git@github.com:gregturn/spring-a-gram.git"
  },
  "keywords": [
    "spring",
    "data",
    "rest",
    "hateoas",
    "hypermedia"
  ],
  "author": "Greg L. Turnquist",
  "license": "ASLv2",
  "bugs": {
    "url": "https://github.com/gregturn/spring-a-gram/issues"
  },
  "homepage": "https://github.com/gregturn/spring-a-gram",
  "dependencies": {
    "jquery": "^2.1.1",
    "requirejs": "^2.1.15",
    "rest": "^1.2.0"
  },
  "devDependencies": {
    "bower": "^1.3.12"
  }
}
```

**Comment by eirslett** [comment]
The plugin already has bower support. Look at the example project, it shows you how to use it!

**Comment by gregturn** [comment]
Great! Didn't see that on the main page.

**Comment by gregturn** [comment]
Okay, it does appear that bower must still be listed in my package.json file for things to work properly. Perhaps an update to README.md to clarify?

```javascript
  "devDependencies": {
    "bower": "^1.3.12"
  }
```
