### ISSUE TITLE
Non-Windows Node.js executable run on Windows in v0.0.19

### ISSUE THREAD

**Issue by kaqqao** [eirslett/frontend-maven-plugin#135]
I have upgraded from 0.0.14 to 0.0.19, and on Linux and Mac, it seems to be working fine, but on Window a wrong executable is getting run. Instead of Windows node.exe, *nix node gets triggered resulting in an error stating that it's not a valid Win32 application.

**Comment by kaqqao** [comment]
Argh. I was reliably reproducing it on 2 different Windows machines yesterday, but not today... No idea what changed, but I'm closing this until I figure out what's going on. If I find something, I'll try contributing a fix.

**Comment by eirslett** [comment]
Ok, good to hear that it works now (and sorry you couldn't reproduce it, oh the joys of maven...)
If you ever experience the same problem again; if you look at the build logs it should show which tar.gz archive it downloads from nodejs.org. If it downloads a *nix executable, then it's probably something wrong with the way the maven plugin detects which OS you are running.
