### ISSUE TITLE
Support for io.js

### ISSUE THREAD

**Issue by bgerrissen** [eirslett/frontend-maven-plugin#136]
Feature request:

See https://iojs.org/

So an option to use io.js instead of node.js

Has some advantages, it uses the latest V8 javascript engine for one.

**Comment by cowwoc** [comment]
@bgerrissen I'm not a committer but out of curiosity, what (if anything), would need to change? Is it a matter of downloading the installer from a different URL and using different filenames? Or are there other incompatibilities with node.js?

**Comment by bgerrissen** [comment]
@cowwoc afaik, just add a new installer url, map to a new binary path and thats it. On the commandline 'node' becomes 'iojs' but I don't think thats relevant for the maven plugin as it executes the binary directly.

**Comment by eirslett** [comment]
I think it should be possible to use this plugin with io.js today, but you'd have to hack a bit, and rename the iojs binary to node. You might have to upload the binary on a local/in-house repository.

**Comment by sagivf** [comment]
@eirslett If I understand correctly I have to upload the binary to my own repository since the binary name "node-" is hard coded. Building my own repository is kind of problematic for me at the moment. could you possibly help out and make the binary name, or at least the prefix configurable - i'm sure this would help a number of people wanting to move to iojs.

**Comment by sagivf** [comment]
If this makes sense i'll create a pull request, might take me some time though.

**Comment by tfennelly** [comment]
Anything on this guys? Is there a clean way of doing it?

**Comment by tfennelly** [comment]
@eirslett seems like a number of node build tools are dropping node now and going to io.js, so it would be nice for frontend to have a clean way of working with either (or some docs to explain how to do it with the current version).

**Comment by FagnerMartinsBrack** [comment]
For those who don't know, iojs and node are merging together: http://thenextweb.com/dd/2015/06/16/node-js-and-io-js-are-settling-their-differences-merging-back-together/

Just need to know if the distribution will change.

**Comment by eirslett** [comment]
Unfortunately, there's no clean way of doing it, one would have to make big changes to the code base to accomodate it. And considering the future of io vs node, it would be good not to have that kind of complexity sitting in the code base. What we could do as a compromise, is to post something on the wiki about how to use io.js by copying it in manually.

**Comment by tfennelly** [comment]
@eirslett @FagnerMartinsBrack right, since I posted my question I saw how they were merging back together again (sorry, relatively new to the node world). Now I'm wondering what to do. Some packages (e.g. [jsdom](https://github.com/tmpvar/jsdom) and zombie) have dropped support for node in recent releases and gone with io.js. I need to use a more recent version of jsdom (a version not dependent on contextify), but now I'm wondering what will be what when they eventually "merge" (whatever that means in reality) back together again. Any thoughts/advise on what I should/could do?

**Comment by tfennelly** [comment]
@eirslett and I totally agree with you ... it would not be a good idea for you to pollute your plugin when things are up in the air like this.

**Comment by tfennelly** [comment]
FYI, I posted a [question on the jsdom mailing list](https://groups.google.com/forum/#!topic/jsdom/5Ya3C8raJP4) too see what they think.

**Comment by tfennelly** [comment]
I hacked my pom, changing it to use the `download-maven-plugin` to download and install both io.js and npm i.e. `frontend-maven-plugin` just executes the node commands and doesn't perform the node/npm install step.

I've only lightly tested it on mac, but it seems to work. I'm sure there are better ways of doing it but I'll post it here for anyone else that wants to try it out as a stop-gap until node and io.js "merge".

Some global pom.xml properties:

```xml
<properties>
	<iojs.dist.baseurl>https://iojs.org/dist</iojs.dist.baseurl>
	<iojs.version>2.5.0</iojs.version>
	<npm.dist.baseurl>http://registry.npmjs.org/npm/-</npm.dist.baseurl>
	<npm.version>2.13.1</npm.version>
</properties>
```

Few profiles to perform the download and install of iojs (as node) and npm:

```xml
<profile>
    <id>node-classifier-linux</id>
    <activation>
        <os>
            <family>Linux</family>
            <arch>amd64</arch>
        </os>
    </activation>
    <properties>
        <iojs.download.file.prefix>iojs-v${iojs.version}-linux-x64</iojs.download.file.prefix>
        <iojs.download.file>${iojs.download.file.prefix}.tar.gz</iojs.download.file>
        <iojs.download.unpack>true</iojs.download.unpack>
        <iojs.download.exe.path>${iojs.download.file.prefix}/bin/iojs</iojs.download.exe.path>
        <node.exe.file>node</node.exe.file>
    </properties>
</profile>
<profile>
    <id>node-classifier-mac</id>
    <activation>
        <os>
            <family>mac</family>
        </os>
    </activation>
    <properties>
        <iojs.download.file.prefix>iojs-v${iojs.version}-darwin-x64</iojs.download.file.prefix>
        <iojs.download.file>${iojs.download.file.prefix}.tar.gz</iojs.download.file>
        <iojs.download.unpack>true</iojs.download.unpack>
        <iojs.download.exe.path>${iojs.download.file.prefix}/bin/iojs</iojs.download.exe.path>
        <node.exe.file>node</node.exe.file>
    </properties>
</profile>
<profile>
    <id>node-classifier-windows</id>
    <activation>
        <os>
            <family>windows</family>
        </os>
    </activation>
    <properties>
        <iojs.download.file>win-x64/iojs.exe</iojs.download.file>
        <iojs.download.unpack>false</iojs.download.unpack>
        <iojs.download.exe.path>iojs.exe</iojs.download.exe.path>
        <node.exe.file>node.exe</node.exe.file>
    </properties>
</profile>
<profile>
    <id>iojs-download</id>
    <activation>
        <file><exists>package.json</exists></file>
    </activation>
    <build>
        <plugins>
            <plugin>
                <groupId>com.googlecode.maven-download-plugin</groupId>
                <artifactId>download-maven-plugin</artifactId>
                <version>1.2.1</version>
                <executions>
                    <execution>
                        <id>get-iojs</id>
                        <phase>initialize</phase>
                        <goals><goal>wget</goal></goals>
                        <configuration>
                            <url>${iojs.dist.baseurl}/v${iojs.version}/${iojs.download.file}</url>
                            <unpack>${iojs.download.unpack}</unpack>
                            <outputDirectory>${project.build.directory}/iojs</outputDirectory>
                        </configuration>
                    </execution>
                    <execution>
                        <id>get-npm</id>
                        <phase>initialize</phase>
                        <goals><goal>wget</goal></goals>
                        <configuration>
                            <url>${npm.dist.baseurl}/npm-${npm.version}.tgz</url>
                            <unpack>false</unpack>
                            <outputDirectory>${project.build.directory}</outputDirectory>
                            <outputFileName>npm-${npm.version}.tar.gz</outputFileName>
                        </configuration>
                    </execution>                        
                </executions>
            </plugin>
        </plugins>
    </build>
</profile>
<profile>
    <id>iojs-npm-install</id>
    <activation>
        <file>
            <exists>package.json</exists>
            <missing>node/${node.exe.file}</missing>
        </file>
    </activation>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>1.8</version>
                <executions>
                    <execution>
                        <phase>initialize</phase>
                        <configuration>
                            <target>
                                <!-- 
                                Rest everything
                                -->
                                <delete dir="node"/>
                                <mkdir dir="node"/>
                                <!-- 
                                Copy the iojs/node and npm exe files to where the
                                frontend-maven plugin expects to find them. 
                                -->
                                <copy file="${project.build.directory}/iojs/${iojs.download.exe.path}"
                                      tofile="node/${node.exe.file}"/>
                                <untar src="${project.build.directory}/npm-${npm.version}.tar.gz" dest="node" compression="gzip" />
                                <move file="node/package" tofile="node/npm"/>
                                <chmod perm="755">
                                    <fileset dir="node">
                                        <include name="node"/>
                                        <include name="node.exe"/>
                                    </fileset>
                                    <fileset dir="node/npm/bin">
                                        <include name="**/*"/>
                                    </fileset>
                                </chmod>
                            </target>
                        </configuration>
                        <goals><goal>run</goal></goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</profile>
```

And then I removed the following `execution` block from the `frontend-maven-plugin` config:

```xml
<execution>
    <phase>initialize</phase>
    <id>install node and npm</id>
    <goals>
        <goal>install-node-and-npm</goal>
    </goals>
    <configuration>
        <nodeVersion>v${node.version}</nodeVersion>
        <npmVersion>${npm.version}</npmVersion>
    </configuration>
</execution>
```

One thing I know is wrong here is that the `iojs-npm-install` profile is executing every time. Not a big deal because the `download-maven-plugin` caches the downloads, but still would be nice to fix.

**Comment by tfennelly** [comment]
@eirslett maybe the above hack could be added/pointed to in the wiki.

**Comment by sagivf** [comment]
+ 1

**Comment by eirslett** [comment]
Thanks for the workaround! I added a link to it in the wiki.
