### ISSUE TITLE
Working directory not right for submodules

### ISSUE THREAD

**Issue by mikesir87** [eirslett/frontend-maven-plugin#137]
I have a base project that has sub-modules for the backend and for the frontend:

```
base
-- pom.xml
-- front-end
---- pom.xml
---- package.json
---- bower.json
---- gulpfile.json
-- back-end
---- src/main/java......
```

If I run a <code>mvn clean install</code> from the base, I get errors that the package.json can't be found, etc.  But, when I run from inside front-end, it works as expected.  

It looks like the workingDirectory isn't catching the case that the build may be a reactor build and the current working directory is a subdirectory from the start of the build.

```
[INFO] --- frontend-maven-plugin:0.0.20:npm (npm install) @ node-tools ---
[INFO] Running 'npm install --color=false' in /path/to/base
[INFO] npm ERR! install Couldn't read dependencies
[INFO] npm ERR! package.json ENOENT, open '/path/to/base/package.json'
[INFO] npm ERR! package.json This is most likely not a problem with npm itself.
[INFO] npm ERR! package.json npm can't find a package.json file in your current directory.
```

**Comment by eirslett** [comment]
Strange... the working directory is supposed to be the same as the directory of the pom.xml file where the plugin is configured. (It's using Maven's ${basedir} property)
You're setting up the plugin in base/front-end/pom.xml right? And not in base/pom.xml?

**Comment by mikesir87** [comment]
Correct.  I have only the pluginManagement in the base/pom.xml, but all execution config in the base/front-end/pom.xml.  I'll try to dig around a little bit and see if I can figure anything out too.

**Comment by mikesir87** [comment]
Ok. Disregard this.  I was dumb.  Haha... I got all mixed up and actually told you wrong.  I had all the plugin execution setup in the base's pom.xml.  It should have been in the pluginManagement, but was not.  So, it was actually blowing up while building the base deployment.  

Might help if I get enough sleep and wait a bit before filing a bug report.  ;)
