### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by cowwoc** [eirslett/frontend-maven-plugin#143]
Why are both `result` and `error` pointing to stdout? https://github.com/eirslett/frontend-maven-plugin/blob/master/frontend-plugin-core/src/main/java/com/github/eirslett/maven/plugins/frontend/lib/ProcessExecutor.java#L40

Shouldn't `error` point to stderr? Is this a bug?

**Comment by eirslett** [comment]
This was fixed, thanks for the PR! I'll close this issue then.
