### ISSUE TITLE
v0.0.21 not available on maven plugin repositories

### ISSUE THREAD

**Issue by jtibble** [eirslett/frontend-maven-plugin#151]
Cannot download v0.0.21 from central plugin repo or others like http://mvnrepository.com/artifact/com.github.eirslett/frontend-maven-plugin

**Comment by andham** [comment]
Yes, v0.0.21 seems to be missing on the Central repository:
http://search.maven.org/#search|gav|1|g%3A%22com.github.eirslett%22%20AND%20a%3A%22frontend-maven-plugin%22

But there is a v0.0.22 now so...

**Comment by eirslett** [comment]
Yup. I releasedversion 0.0.22, because 0.0.21 failed for some reason.
