### ISSUE TITLE
Option to set git proxy environment variables

### ISSUE THREAD

**Issue by jtibble** [eirslett/frontend-maven-plugin#154]
I'd like an option to copy the maven proxy currently being used to the git proxy environment variable http_proxy

**Comment by eirslett** [comment]
What's the use case for that? Sounds like it could live in a separate Maven plugin?

**Comment by jtibble** [comment]
For example, my code is built on an proxy-restricted Jenkins server behind our corporate firewall. The maven proxy settings are correctly applied to download node and npm, etc, but when I run the 'bower install' command, it fails because the git-proxy settings are not configured the same as the maven proxy. If I could mirror the maven proxy settings to the environment variable that git is using, and do that within the plugin, that would be helpful :smile:   Thoughts?

**Comment by eirslett** [comment]
I would have copied the settings. Log in to the CI server, git config --global http.proxy etc.

**Comment by jtibble** [comment]
Unfortunately, because I work for a federally-regulated entity, I don't have console access to the Jenkins server. I've gotten around it so far by adding the http_proxy environment variable to my Jenkins build configuration, but every time the build is run on a new Jenkins, that will have to be set manually as well. I suppose that is not the worst solution, and if you're opposed to adding this functionality, I completely understand.

Cheers,
John

**Comment by eirslett** [comment]
If security is an issue, access to Jenkins should be your smallest problem ;-)
Given you install frontend dependencies via bower - a malicious GitHub user could easily push a security vulnerability to the code base, and you would be affected. People usually deal with this by commiting bower dependencies directly into their repo - they don't run the bower command on every build.
I'm sorry, but I'm trying hard to keep the size of this code base down, and it seems to me that fixing it in the plugin is the wrong approach! For now, you'll have to stick with doing some manual work...
Good luck!

**Comment by jtibble** [comment]
Sure thing, thanks for chatting with me about it.
