### ISSUE TITLE
Plugin ignores projects .npmrc file.

### ISSUE THREAD

**Issue by blindenvy** [eirslett/frontend-maven-plugin#155]
I am downloading npm modules from a private nexus registry that requires authentication. As such I have placed the following properties in the .npmrc file located in my base project folder.

registry=http://example.com:8081/nexus/content/repositories/npmjs/
always-auth=true
_auth=${MAVEN_NPM_AUTH}

It appears the frontend_maven_plugin isn't picking up this configuration file as its still downloading the modules from https://registry.npmjs.org.

Note when I move the .npmrc file to my home folder everything works as expected. However, this is not a viable option as we want to include this within the project so that no extra configuration has to be done on the build server.

Is there some option to tell the plugin to use this configuration file, or is it not supported? If not supported can it be added?

Note: I have confirmed that using my developer install of node works as expected with the .npmrc file in the project directory or in my home directory. So it does indeed appear to be an issue with the plugin. 

Reference: https://docs.npmjs.com/files/npmrc

**Comment by blindenvy** [comment]
I found a workaround for this issue. If you place the .npmrc file in ${basedir} and add the configuration below to the npm goal it will work as intended.

     <configuration>
       <arguments>--userconfig ${basedir}/.npmrc install</arguments>
     </configuration>

**Comment by eirslett** [comment]
Good to hear you solved it! :-)

**Comment by sbley** [comment]
Don't forget the = after the param:
`<arguments>--userconfig=${basedir}/.npmrc install</arguments>`

**Comment by blindenvy** [comment]
The equal sign is not necessary according to npm documentation.

**Comment by sbley** [comment]
Well, it didn't work for me when omitting the equal sign.

**Comment by mevlts** [comment]
i'm also getting this problem. it still uses same registry.npmjs.org

**Comment by sbley** [comment]
@mevlts What exactly did you try?

**Comment by krakhil** [comment]
Hello Team,



We have a multi branch pipeline jo in jenkins where we use mavenfront plguin end plugin which will install and download npm during the run time.



Below tag is used in pom



<npm.registry.url>

            https://url/artifactory/api/npm/reponame/

        </npm.registry.url>

        <npm.download.base.url>http://registry.npmjs.org/npm/-/</npm.download.base.url>

        <node.download.base.url>http://nodejs.org/dist/</node.download.base.url>

        <node.version>v8.11.1</node.version>

        <npm.version>5.6.0</npm.version>

        <npm.auth></npm.auth>





same is working as expected. But when we use GSEP Artifactory as npm & node download base url, we get 401 error.



Configuration  :



        <npm.registry.url>

        https://url/artifactory/api/npm/reponame/

        </npm.registry.url>

        <npm.download.base.url>https://url/artifactory/api/npm/reponame//-/</npm.download.base.url>

        <node.download.base.url>https://url/artifactory/api/npm/reponame/node</node.download.base.url>

        <node.version>v8.11.1</node.version>

        <npm.version>5.6.0</npm.version>

        <npm.auth></npm.auth>





ERROR log :



[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @  client ---
[INFO] 
[INFO] --- flatten-maven-plugin:1.1.0:clean (flatten.clean) @ p---
[INFO] Deleting ..../.flattened-pom.xml
[INFO] 
[INFO] --- flatten-maven-plugin:1.1.0:flatten (flatten) @ client ---
[INFO] Generating flattened POM of project -client:pom:0.0.1.43.6a44016...
[INFO] 
[INFO] --- frontend-maven-plugin:1.6:install-node-and-npm (install node and npm) @ client ---
[INFO] Installing node version v8.11.1
[INFO] Downloading https://url/artifactory/api/npmrepo/nodev8.11.1/node-v8.11.1-linux-x64.tar.gz to /.m2/repository/com/github/eirslett/node/8.11.1/node-8.11.1-linux-x64.tar.gz
[INFO] No proxies configured
[INFO] No proxy was configured, downloading directly
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] .....Parent ........................ SUCCESS [  0.881 s]
[INFO] ... DB Migration ................... SUCCESS [  0.588 s]
[INFO] ....  Assembly Module ............... SUCCESS [  0.036 s]
[INFO] .... Test .......................... SUCCESS [  0.602 s]
[INF  ...lient Module ................. FAILURE [  0.205 s]
[INFO] ................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 18.220 s
[INFO] Finished at: 2019-08-12T10:46:50+02:00
[INFO] Final Memory: 88M/2857M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:install-node-and-npm (install node and npm) on project pia-core-welcomepage-client: Could not download Node.js: Got error code 401 from the server. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :pia-core-welcomepage-client



Could you please help us on this 


Regards
Akhil

**Comment by ermicioi** [comment]
Unfortunately it does not work for me :(
Instead of having a workaround, what would be the solution?

**Comment by vboerchers** [comment]
I needed to change the registry to our private one and with plugin version 1.9.1 the only thing I had to do to fix `npm install` was to add this `.npmrc` next to the `pom.xml` of the frontend module.
```
registry=https://example.com/npm/npm/
strict-ssl=false
```
In addition to that I had to configure `nodeDownloadRoot` and `npmDownloadRoot` for installation.

**Comment by jblayneyXpanxion** [comment]
> I found a workaround for this issue. If you place the .npmrc file in ${basedir} and add the configuration below to the npm goal it will work as intended.
> 
> ```
>  <configuration>
>    <arguments>--userconfig ${basedir}/.npmrc install</arguments>
>  </configuration>
> ```

@blindenvy could you please show me your surrounding config? 

Is it like this? or similar?

```
					<execution>
						<id>install-node-and-npm</id>
						<goals>
							<goal>install-node-and-npm</goal>
						</goals>
						<configuration>
							<arguments>--userconfig ${basedir}/.npmrc install</arguments>
						</configuration>
					</execution>
```
