### ISSUE TITLE
Unable to run mvn clean install

### ISSUE THREAD

**Issue by ksambhav** [eirslett/frontend-maven-plugin#159]
As given in the example, I have declared my plugin with only change being the working directory location:-

< srcdir >src/main/resources/public< /srcdir >
< workingDirectory >src/main/resources/public< /workingDirectory >

Running mvn clean install gives this error:-

 Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.20:npm (npm install) on project optosoft-ui: Failed to run task: 'npm install --color=false'
 java.io.IOException: Cannot run program "my-projects\optosoft\optosoft\optosoft-ui\src\main\resources\public\node\node" (in directory "my-projects\optosoft\optosoft\optosoft-ui\src\main\resources\public"): CreateProcess error=2, The system cannot find the file specified -> [Help 1]

Why the plugin is appending '\node\node' after my working directory?

**Comment by eirslett** [comment]
Did you forget the install node and npm goal? (You need it even though you already have a global version installed)

**Comment by eirslett** [comment]
I believe that was the problem, so I'll close this issue. But you're free to reopen it, if that doesn't solve your problem!

**Comment by rmk1409** [comment]
Please, can you give a link or discribe how to "install node and npm goal?"

**Comment by anuja8275** [comment]
same question can any one help me to know how to install node

**Comment by eirslett** [comment]
@anuja8275 if you read the README, you will find it: https://github.com/eirslett/frontend-maven-plugin#installing-node-and-npm
