### ISSUE TITLE
Bower and npm warnings are now passed as [ERROR] through maven when they should be [WARNING]

### ISSUE THREAD

**Issue by jalbertcory** [eirslett/frontend-maven-plugin#161]
With the frontend plugin version 0.0.22 bower and npm warnings are now showing as errors:
**Bower:**
[ERROR] bower loader.js#1.0.1         mismatch Version declared in the json (0.0.0) is different than the resolved one (1.0.1)
[ERROR] bower handlebars#~1.3.0   invalid-meta handlebars is missing "ignore" entry in bower.json
[ERROR] bower ember-qunit#0.1.8   invalid-meta ember-qunit is missing "main" entry in bower.json
[ERROR] bower ember-data#1.0.0-beta.11     invalid-meta ember-data is missing "ignore" entry in bower.json
[ERROR] bower ember#1.8.1                  invalid-meta ember is missing "ignore" entry in bower.json
**npm:**
[ERROR] npm WARN optional dep failed, continuing fsevents@0.2.1

In 0.0.20 these were passed as [INFO]:
**Bower:**
[INFO] bower loader.js#1.0.1                     mismatch Version declared in the json (0.0.0) is different than the resolved one (1.0.1)
[INFO] bower handlebars#~1.3.0               invalid-meta handlebars is missing "ignore" entry in bower.json
[INFO] bower ember-qunit#0.1.8               invalid-meta ember-qunit is missing "main" entry in bower.json
[INFO] bower ember-data#1.0.0-beta.11        invalid-meta ember-data is missing "ignore" entry in bower.json
[INFO] bower ember#1.8.1                     invalid-meta ember is missing "ignore" entry in bower.json
**npm:**
[INFO] npm WARN optional dep failed, continuing fsevents@0.2.1

This was almost better because scripts looking for errors in the maven build might fail if they are not relying solely on the return code.  It also makes the output bad because it looks like there are build problems when bower and node warnings can be the fault of the module writers and not the individual project.

I love the additions of Bower and Ember to this plugin, and would like to update the version for the project I am involved in, however the [ERROR] messages will get flagged by automated validation that prevents introducing build errors to the code base.

**Comment by eirslett** [comment]
That's correct - it was really an error in the frontend-maven-plugin code that led to ERROR being written as INFO instead of ERROR. It's just forwarding whatever comes from stderr as ERROR logs, and stdout as INFO logs.

Do you get the same errors when you run npm and bower standalone?

**Comment by eirslett** [comment]
And is it an option to fix the underlying errors?

**Comment by jalbertcory** [comment]
The problem with the Bower errors is that they are complaining about the structure of the bower.json in dependencies of my project. (ie Ember)
I guess I have a few options, submit issues with all of the dependencies that are not up to bower's standards, and hope that they update their projects.  I could also branch bower to fix --quiet to make it ignore warnings since they do not want to change it.  https://github.com/bower/bower/issues/1493

Anyway thanks, I will solve my issue elsewhere.  Keep up the good work.

**Comment by DanieleTorino** [comment]
I'm not sure that output from *stderr* should automatically be tagged as errors...

*Stderr* often contains messages that are meant for automatic processing (as opposed to messages that are meant to be read by a human).
I'm not a fan of misusing *stderr* for other purposes than error messages but this has historical reasons and it can be really useful when writing scripts.

But given that you know that you are going to run *npm* and *npm* misuses *stderr*, wouldn't it make sense to just tag it as INFO?

IMHO this confuses the user.

**Comment by eirslett** [comment]
It will confuse people, but npm is clearly the problem here.
If they make a flag like `npm install --stdout-only` then it would certainly be possible to pass that flag as an argument from this plugin. But now I'm being silly, sorry for that.

Maybe it's possible to work around it by setting [log-level=error](https://docs.npmjs.com/misc/config#loglevel) in the `.npmrc` file in the project. Or something like that, I haven't tried.
