### ISSUE TITLE
Cannot download Node pre-0.9.1

### ISSUE THREAD

**Issue by mthmulders** [eirslett/frontend-maven-plugin#168]
Versions of Node before v0.9.1 do not have the same file name structure on http://nodejs.org/dist/. For example:
* v0.9.1 and up follow the node-`version`-`codename`-`arch`.`extension` pattern
* v0.9 and before follow the node-`version`.`extension` pattern. Here, `version` can also be "v0.9.0-x86" when `extension` is _msi_, sigh.

Currently, it's not possible to download Node versions before v0.9.1, because the plugin follows the first layout. Would you consider merging a pull request that adds support for older Node versions?

**Comment by eirslett** [comment]
Sounds like an edge case - why do you need to run the build with an old version of node?

**Comment by mthmulders** [comment]
Yes, it's an edge case. My particular case: I want to push my code to Openshift, which has node v0.6.20 pre-installed. But thinking of it, since the plugin installs Node locally, I might be lucky with a newer version as well...

**Comment by eirslett** [comment]
Ok, I'll close this issue then.
