### ISSUE TITLE
Error: Cannot find module 'C:\svn\2.27\cgbu\ocsi\ui\node\npm\bin\npm-cli.js'

### ISSUE THREAD

**Issue by texag93** [eirslett/frontend-maven-plugin#169]
I see an error (see log below) occasionally when running on Windows. The problem occurs when the plugin tries to run the 'npm install...' command. It is looking for the command in [WORKING DIR]\node\npm\bin\npm-cli.js. It looks like the plugin does the following 1) download npm-2.6.1.tgz to npm.tar.gz, 2) unpack npm.tar.gz to [WORKING DIR]\node (this unpacks to [WORKING DIR]\node\package), 3) rename [WORKING DIR]\node\package to [WORKING DIR]\node\npm. When I see the error, it looks like step 3 has failed. I see NPM installed at [WORKING DIR]\node\package instead of [WORKING DIR]\node\npm where the 'npm install...' command is looking. 

I haven't seen this problem on LInux and I only see it occasionally on Windows (about 30% of the time). I initially thought the npm.tar.gz file might be getting corrupted on the download, so I started using the downloadRoot option pointing to my web server, but this didn't make any difference.

Thanks,
Mike

[INFO] --- frontend-maven-plugin:0.0.22:install-node-and-npm (install node and npm) @ ui ---
[INFO] Installing node version v0.12.0
[INFO] Downloading via proxy ProxyConfig{protocol='http', host='adc-proxy.oracle.com', port=80}
[INFO] Installed node.exe locally.
[INFO] Installing npm version 2.6.1
[INFO] Downloading NPM from http://slc05avk.us.oracle.com:8000/node/npm-2.6.1.tgz to C:\svn\2.27\cgbu\ocsi\ui\npm.tar.gz
[INFO] Downloading via proxy ProxyConfig{protocol='http', host='adc-proxy.oracle.com', port=80}
[INFO] Extracting NPM files in node/
[INFO] Unpacking C:\svn\2.27\cgbu\ocsi\ui\npm.tar.gz into C:\svn\2.27\cgbu\ocsi\ui/node
[INFO] Installed NPM locally.
[INFO]
[INFO] --- frontend-maven-plugin:0.0.22:npm (npm) @ ui ---
[INFO] Running 'npm install --color=false --proxy=http://adc-proxy.oracle.com:80' in C:\svn\2.27\cgbu\ocsi\ui
[ERROR] module.js:338
[ERROR]     throw err;
[ERROR]           ^
[ERROR] Error: Cannot find module 'C:\svn\2.27\cgbu\ocsi\ui\node\npm\bin\npm-cli.js'
[ERROR]     at Function.Module._resolveFilename (module.js:336:15)
[ERROR]     at Function.Module._load (module.js:278:25)
[ERROR]     at Function.Module.runMain (module.js:501:10)
[ERROR]     at startup (node.js:129:16)
[ERROR]     at node.js:814:3
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 19.702 s
[INFO] Finished at: 2015-03-06T08:31:05-06:00
[INFO] Final Memory: 8M/154M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.22:npm (npm) on project ui: Failed to run task: 'npm install --color=false --proxy=
http://adc-proxy.oracle.com:80' failed. (error code 1) -> [Help 1]

**Comment by texag93** [comment]
Any ideas on this one?

**Comment by gyandeeps** [comment]
@texag93 have you tried it with version `0.0.23`?. It works fine on my windows 7 machine.

**Comment by texag93** [comment]
I am using version 0.0.23. 

Is it possible to access a debug log in the plugin that might give more information as to what is happening?

**Comment by texag93** [comment]
It looks like I am having the same issue as this one: https://github.com/eirslett/frontend-maven-plugin/issues/147

**Comment by texag93** [comment]
I created a workaround for this in my pom.xml. This simply attempts to renames the /node/package directory to /node/npm. It uses the maven-antrun-plugin to run an ant task to do the rename. I used phase settings to make sure the ant task executes after install-node-and-npm, but before npm install. So far, this seems to be working.


            <plugin>
                
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <executions>
                    <execution>
                        <id>handle-frontend-maven-plugin-bug</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <tasks>
                                <move failonerror="false" verbose="true" file="${basedir}/node/package" tofile="${basedir}/node/npm"/>
                            </tasks>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>com.github.eirslett</groupId>
                <artifactId>frontend-maven-plugin</artifactId>
                <inherited>false</inherited>
                <version>0.0.23</version>
                <executions>
                    <execution>
                        <id>install node and npm</id>
                        <phase>initialize</phase>
                        <goals>
                            <goal>install-node-and-npm</goal>
                        </goals>
                        <configuration>
                            <nodeVersion>v0.12.2</nodeVersion>
                            <npmVersion>2.7.6</npmVersion>
                        </configuration>
                    </execution>
                    <execution>
                        <id>npm install</id>
                        <phase>process-sources</phase>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <configuration>
                            <arguments>install</arguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

**Comment by eirslett** [comment]
I think this should be fixed in #215.
