### ISSUE TITLE
Build does not fail when sass compilation crashes

### ISSUE THREAD

**Issue by toniedzwiedz** [eirslett/frontend-maven-plugin#171]
Hello,

I'm using the `frontend-maven-plugin` to run Gulp and I'm quite happy with the results, however, I noticed that the Maven does not fail even if there are errors regarding the Gulp task.

In this specific case, I forgot to install Compass properly. 

    build	10-Mar-2015 14:09:47	[INFO] [14:09:47] Starting 'default'...
    build	10-Mar-2015 14:09:47	[ERROR] gulp.run() has been deprecated. Use task dependencies or gulp.watch task triggering instead.
    build	10-Mar-2015 14:09:47	[INFO] [14:09:47] Starting 'styles'...
    build	10-Mar-2015 14:09:47	[INFO] [14:09:47] Plumber found unhandled error:
    build	10-Mar-2015 14:09:47	[INFO]  Error in plugin 'gulp-compass'
    build	10-Mar-2015 14:09:47	[INFO] You need to have Ruby and Compass installed and in your system PATH for this task to work. 
    build	10-Mar-2015 14:09:47	[INFO] [14:09:47] Plumber found unhandled error:
    build	10-Mar-2015 14:09:47	[INFO]  Error in plugin 'gulp-compass'
    build	10-Mar-2015 14:09:47	[INFO] You need to have Ruby and Compass installed and in your system PATH for this task to work. 
    build	10-Mar-2015 14:09:47	[INFO] [14:09:47] Plumber found unhandled error:
    build	10-Mar-2015 14:09:47	[INFO]  Error in plugin 'gulp-compass'

Ideally, I'd like to use the plugin in a Maven job run from Bamboo as part of my project's deployment. For the time being, I ended up making the execution of Gulp a separate bamboo task so I'm not using this plugin. However, I think that the ability to break the build when the CSS compilation and minification fail would be a nice feature to have.

Please let me know what you think.

Cheers,
Tomek

**Comment by eirslett** [comment]
Yes, definitely. It already does - it fails the build based on the exit code of gulp. Are you sure your gulp build is failing? If you run it from the command line?

**Comment by eirslett** [comment]
Did you find the problem here?

**Comment by toniedzwiedz** [comment]
Hi, it was indeed a problem on my side. I was missing an `errorHandler` configuration in my `gulpfile.js`

Thanks
