### ISSUE TITLE
Eclispe m2e integration causes "resouce out of sync"

### ISSUE THREAD

**Issue by toanhuynguyen** [eirslett/frontend-maven-plugin#175]
Hi, I'm currently using frontend-maven-plugin with gulp for JS concaternation & minification. Each time I start a local webserver on Eclipse, it keeps complaining about "resouce out of sync" (those files are output from the JS concaternation & minification). 
Try to refresh the project manually, config eclipse to use hook to automatically refresh the project, change the maven phase of gulp execution but none of them work.
I have to use window explorer to manually delete those files then refresh project again to solve the issue, which is very annoying.
In fact, those files aren't needed for local development, they're in needed when I package the war with other profiles.
Is there any body facing the same issue? Or
Is there a way to ignore certain webapp resource file on eclipse Or another solution on frontend-maven-plugin itself?

Thanks,
Below is the pom snippet.

![1](https://cloud.githubusercontent.com/assets/2412244/6632887/7ad1c10e-c970-11e4-8b26-c3d245d8d3a5.jpg)

**Comment by Arkh1** [comment]
Since nobody else has commented.... I believe this is related to this issue
https://github.com/eirslett/frontend-maven-plugin/issues/164
And as a temporary fix you can shut off automatic builds and run manual builds on the project.

**Comment by toanhuynguyen** [comment]
@Arkh1: Thanks for your comment. Just take a look as that issue & kiwipiet's solution is working for me.
You guys save my day.
Thanks
