### ISSUE TITLE
Plug-in not working with Maven 3.3.1

### ISSUE THREAD

**Issue by shauntarves** [eirslett/frontend-maven-plugin#179]
Plug-in build failure with new version of Maven during the install-node-and-npm goal execution

[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.22:install-node-and-npm (install node and npm) on project cons3rt-gui-server: Execution install node and npm of goal com.github.eirslett:frontend-maven-plugin:0.0.22:install-node-and-npm failed: A required class was missing while executing com.github.eirslett:frontend-maven-plugin:0.0.22:install-node-and-npm: org/slf4j/helpers/MarkerIgnoringBase
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.github.eirslett:frontend-maven-plugin:0.0.22
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/starves/.m2/repository/com/github/eirslett/frontend-maven-plugin/0.0.22/frontend-maven-plugin-0.0.22.jar
[ERROR] urls[1] = file:/Users/starves/.m2/repository/com/github/eirslett/frontend-plugin-core/0.0.22/frontend-plugin-core-0.0.22.jar
[ERROR] urls[2] = file:/Users/starves/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar
[ERROR] urls[3] = file:/Users/starves/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar
[ERROR] urls[4] = file:/Users/starves/.m2/repository/org/apache/commons/commons-compress/1.5/commons-compress-1.5.jar
[ERROR] urls[5] = file:/Users/starves/.m2/repository/org/tukaani/xz/1.2/xz-1.2.jar
[ERROR] urls[6] = file:/Users/starves/.m2/repository/commons-io/commons-io/1.3.2/commons-io-1.3.2.jar
[ERROR] urls[7] = file:/Users/starves/.m2/repository/org/apache/httpcomponents/httpclient/4.3.1/httpclient-4.3.1.jar
[ERROR] urls[8] = file:/Users/starves/.m2/repository/org/apache/httpcomponents/httpcore/4.3/httpcore-4.3.jar
[ERROR] urls[9] = file:/Users/starves/.m2/repository/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
[ERROR] urls[10] = file:/Users/starves/.m2/repository/commons-codec/commons-codec/1.6/commons-codec-1.6.jar
[ERROR] urls[11] = file:/Users/starves/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
[ERROR] urls[12] = file:/Users/starves/.m2/repository/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar
[ERROR] urls[13] = file:/Users/starves/.m2/repository/com/google/guava/guava/10.0.1/guava-10.0.1.jar
[ERROR] urls[14] = file:/Users/starves/.m2/repository/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar
[ERROR] urls[15] = file:/Users/starves/.m2/repository/org/sonatype/sisu/sisu-guice/3.1.0/sisu-guice-3.1.0-no_aop.jar
[ERROR] urls[16] = file:/Users/starves/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
[ERROR] urls[17] = file:/Users/starves/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.0.0.M2a/org.eclipse.sisu.inject-0.0.0.M2a.jar
[ERROR] urls[18] = file:/Users/starves/.m2/repository/asm/asm/3.3.1/asm-3.3.1.jar
[ERROR] urls[19] = file:/Users/starves/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[20] = file:/Users/starves/.m2/repository/org/apache/maven/plugin-tools/maven-plugin-annotations/3.2/maven-plugin-annotations-3.2.jar
[ERROR] urls[21] = file:/Users/starves/.m2/repository/com/googlecode/slf4j-maven-plugin-log/slf4j-maven-plugin-log/1.0.0/slf4j-maven-plugin-log-1.0.0.jar
[ERROR] urls[22] = file:/Users/starves/.m2/repository/org/sonatype/plexus/plexus-build-api/0.0.7/plexus-build-api-0.0.7.jar
[ERROR] urls[23] = file:/Users/starves/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.8/plexus-utils-1.5.8.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

**Comment by tylerprete** [comment]
I'm experiencing the same issue.

**Comment by skoftoby** [comment]
Same here, the issue occurs when building http://github.com/Athou/CommaFeed using Maven 3.3.1.

**Comment by eirslett** [comment]
I guess it's the SLF4J issue that is fixed in master, but not released. I'll release the fix as soon as I can!

**Comment by damnhandy** [comment]
Pretty sure it's SLF4J. When I run with `-X`, I see the following:

```
Caused by: java.lang.ClassNotFoundException: org.slf4j.helpers.MarkerIgnoringBase
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 40 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
```
Looking forward to 0.0.23 :)

**Comment by damnhandy** [comment]
A temporary work around is to roll back to at least 3.2.5. Homebrew on OS X makes this easy.

**Comment by eirslett** [comment]
There we go. Version 0.0.23 is released, that should fix this problem.

**Comment by shauntarves** [comment]
Confirmed fix is working. Thanks for the quick turnaround. This plugin is fantastic.

**Comment by pschulten** [comment]
thanks a lot!

**Comment by dpkg** [comment]
thanks.

**Comment by jschulz79** [comment]
Version 0.0.23 is released worked for me, thanks.

**Comment by nepeta70** [comment]
It does not work with maven 3.3.3

**Comment by nepeta70** [comment]
I changed my maven version by 3.3.1 but I still get the error Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.23:install-node-and-npm (default) on project backend: The plugin com.github.eirslett:frontend-maven-plugin:0.0.23 requires Maven version 3.1.0 -> [Help 1]

**Comment by nghialunhaiha** [comment]
for maven 3.16.0-23 npm version 0.0.16 is not compatibility, i changed it to 0.0.23 and it worked fine, 
Thanks Slarson

**Comment by amolnr1987** [comment]
I am getting below error while installing angular JS application  

[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:install-node-and-npm (install node and npm) on project mediapp-ui: Execution install node and npm of goal com.github.eirslett:frontend-maven-plugin:1.6:install-node-and-npm failed: A required class was missing while executing com.github.eirslett:frontend-maven-plugin:1.6:install-node-and-npm: org/codehaus/jackson/map/ObjectMapper
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.github.eirslett:frontend-maven-plugin:1.6
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/Amol/.m2/repository/com/github/eirslett/frontend-maven-plugin/1.6/frontend-maven-plugin-1.6.jar
[ERROR] urls[1] = file:/C:/Users/Amol/.m2/repository/com/github/eirslett/frontend-plugin-core/1.6/frontend-plugin-core-1.6.jar



I am using maven 3.5.2 

Below is the npm execution configuration in POM 

		<execution>
						<id>install node and npm</id>
						<goals>
							<goal>install-node-and-npm</goal>
						</goals>
						<configuration>
							
							<nodeVersion>v8.9.1</nodeVersion>
							<npmVersion>5.5.1</npmVersion>
						</configuration>
					</execution>

and below is the eirslett version :- 1.6

<plugin>
				<groupId>com.github.eirslett</groupId>
				<artifactId>frontend-maven-plugin</artifactId>
				
				<version>1.6</version>

can you please help  me with the solution for this.

**Comment by andrvet** [comment]
Hello, I am getting below problem. How to fix it? Thank you. 

parts of "mvn clean install" output:

[WARNING] 'build.plugins.plugin.version' for com.github.eirslett:frontend-maven-plugin is missing. @ line 286, column 15

>>>>>>>>> line 286 of what/which file? 

[INFO] --- frontend-maven-plugin:1.6:install-node-and-npm (install node and npm [initialize]) @ myproject

[INFO] Installing node version v9.4.0
[INFO] Downloading https://nodejs.org/dist/v9.4.0/node-v9.4.0-darwin-x64.tar.gz to /Users/andrvet/.m2/repository/com/github/eirslett/node/9.4.0/node-9.4.0-darwin-x64.tar.gz
[INFO] No proxies configured
[INFO] No proxy was configured, downloading directly
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:install-node-and-npm (install node and npm [initialize]) on project myproject: Execution install node and npm [initialize] of goal com.github.eirslett:frontend-maven-plugin:1.6:install-node-and-npm failed: A required class was missing while executing com.github.eirslett:frontend-maven-plugin:1.6:install-node-and-npm: org/apache/commons/logging/LogFactory
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.github.eirslett:frontend-maven-plugin:1.6
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/andrvet/.m2/repository/com/github/eirslett/frontend-maven-plugin/1.6/frontend-maven-plugin-1.6.jar
[ERROR] urls[1] = file:/Users/andrvet/.m2/repository/com/github/eirslett/frontend-plugin-core/1.6/frontend-plugin-core-1.6.jar
[ERROR] urls[2] = file:/Users/andrvet/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar

etc
-----------------
Here's plugin section from my pom.xml:

      <plugin>
        <groupId>com.github.eirslett</groupId>
        <artifactId>frontend-maven-plugin</artifactId>
        
        
        
        <executions>
          
          <execution>
            <id>install node and npm [initialize]</id>
            <phase>initialize</phase>
            <goals>
              <goal>install-node-and-npm</goal>
            </goals>
            <configuration>
              <nodeVersion>v9.4.0</nodeVersion>
              <npmVersion>5.6.0</npmVersion>
            </configuration>
          </execution>
         
          <execution>
            <id>npm install [initialize]</id>
            <phase>initialize</phase>
            <goals>
              <goal>npm</goal>
            </goals>
            
             
            <configuration>
               <arguments>install</arguments>
            </configuration>
            
          </execution>
          
        </executions>
      </plugin>
-----------------------------------------------------
And finally here's versions of npm, node and mvn:
$ npm --version
5.6.0

$ node --version
v9.4.0

$ mvn -version
Apache Maven 3.5.2 (138eddXXX...XXXd; 2017-10-18T00:58:13-07:00)
Maven home: /usr/local/Cellar/maven/3.5.2/libexec
Java version: 1.8.0_162, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.2", arch: "x86_64", family: "mac"

thanks!

**Comment by mcahornsirup** [comment]
I have fixed it by remove ~/m2/repository/com/github/eirslett and build again with version 1.6.
