### ISSUE TITLE
Can we change the directory where node is installed?

### ISSUE THREAD

**Issue by rrarunan** [eirslett/frontend-maven-plugin#18]
Like a target folder perhaps, that is cleaned automatically by maven?

**Comment by TomWilkins** [comment]
Is there something similar to a <nodeDirectory> option? I want to use the globally installed bower via node rather than downloading a new version every time I build, meaning I can have one Bower node module to use across all of my projects. Currently if I just try running the bower install goal, it tries to look in project/node/node for Bower, but it needs to look in the global path.

**Comment by chazzlabs** [comment]
@TomWilkins Are you using the "-g" flag when installing Bower?  If not, running

```
npm install -g <module>
```

will install the module globally.

**Comment by eirslett** [comment]
You'll have to leave bower in your package.json file, like in the example project. This plugin doesn't support global installations of any of the tools (node, npm, grunt, gulp, karma, bower...)
There's not much overhead involved, npm caches the local bower package between installs.

**Comment by TomWilkins** [comment]
Ok thanks
@chazzlabs I believe so, but will check tomorrow.
@eirslett what would you recommend doing if you had a server with mutiple projects that shared node modules? E.g. They all used Bower and grunt? Would you have to a package.json profile for each project or is there a way to have a unified one?

**Comment by eirslett** [comment]
Use one package.json for each Maven build. If you are using a Maven reactor build (are you?), with many submodules, apply the frontend maven plugin to each submodule independently (and with one package.json for each submodule).
Your build will take longer, but only the first time. The Node.js binaries and node_modules are cached between runs.
That's my suggestion. Storage space is cheap.

**Comment by TomWilkins** [comment]
@eirslett thanks for the suggestion, I've actually ended up using the exec-mavin-plugin that allows me to directly output the bower command similar to how I would in the terminal, seems when I tried this before I have my configuration wrong or something, all working now :)

**Comment by dantran** [comment]
My company has a convention to place external resource under ${project.basedir}/.external-resources, so having an option where to place an unpack nodejs and npm will be much apprecated

**Comment by willtran-** [comment]
This pull request should take care of things. In a multi-module project, you could use
```
<nodeInstallDirectory>${session.executionRootDirectory}</nodeInstallDirectory>
```
to ensure node is only installed in the root of the project, rather than in the basedir of every module.

**Comment by cowwoc** [comment]
@willtran- Thanks Will.

**Comment by dantran** [comment]
awesome!!

**Comment by cowwoc** [comment]
@eirslett I'm dying to use this new feature :) Any idea when it'll get merged and released?

**Comment by willtran-** [comment]
@cowwoc If you can't wait, it's quite easy to clone and mvn install it yourself :)

**Comment by dantran** [comment]
@eirslett, your thought on this pull request? thumb up or down?

**Comment by dantran** [comment]
I have one more usecase for this, where at the last step,  I need to change directory to a distribution directory prepare by dev team in grunt build, and run

npm install --production

the distribution directory contains minimal set of source and runtime dependencies to be zipped up by maven

it fails becuase that direcotry does not the 'node' directory

**Comment by eirslett** [comment]
What do you think about solving that by using grunt to copy the files?

**Comment by dantran** [comment]
dev seems to have a hard time getting grunt to copy the files and there provide with this solution.  I ended up to use exec-maven-plugin and add some hack using relative path.  

      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>prepare-dist-npm-runtime-dependency</id>
            <phase>prepare-package</phase>
            <goals>
              <goal>exec</goal>
            </goals>
            <configuration>
              <executable>node/node</executable>
              <workingDirectory>dist</workingDirectory>
              <arguments>
                <argument>../node/npm/cli.js</argument>
                <argument>install</argument>
                <argument>--production</argument>
              </arguments>
            </configuration>
          </execution>
        </executions>
      </plugin>

**Comment by cameroncan** [comment]
#156 should probably be merged into this one. I know that I'm late to the game here, but I added some thoughts there before seeing this thread.

After reading all this, the workingDirectory option works great for specifying where to install everything. It seems though that the mentality here is that the workingDirectory should also be where your frontend source lives. I think it would be helpful though to have a separate property for the frontend sources, which are then copied into the workingDirectory. Then everything can be in the same directory while not being in source.

**Comment by klieber** [comment]
+1

**Comment by Rebzie** [comment]
+1

**Comment by dantran** [comment]
@eirslett more users are asking for this feature

**Comment by matt-blanchette** [comment]
+1

**Comment by ChristianLuxem** [comment]
+1 for a property nodeInstallDirectory...

**Comment by xyloman** [comment]
+1 for a property nodeInstallDirectory

**Comment by giacgbj** [comment]
+1

**Comment by mcahornsirup** [comment]
+1

**Comment by deepakkhetawat** [comment]
Hi all , I need one help . I am using grunt for compiling CSS/js .   
i) I have an issue that my node package is getting created with each build and it is taking a lot of space in Jenkins . I am using maven front end plugin for the same .           
 <id>grunt</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>com.github.eirslett</groupId>
                        <artifactId>frontend-maven-plugin</artifactId>
                        <version>0.0.26</version>
                        
                        <configuration>
                            <workingDirectory>DIR
                            </workingDirectory>
                            <nodeVersion>v4.2.1</nodeVersion>
                            <npmVersion>3.5.1</npmVersion>
                            <installDirectory>node</installDirectory>
                        </configuration>

                        <executions>
                            <execution>
                                <id>node and npm install</id>
                                <goals>
                                    <goal>install-node-and-npm</goal>
                                </goals>
                                <configuration>
                                    <arguments>install</arguments>
                                    <installDirectory>node</installDirectory>
                                </configuration>
                            </execution>
                            <execution>
                                <id>npm install</id>
                                <goals>
                                    <goal>npm</goal>
                                </goals>
                                <configuration>
                                    <arguments>install</arguments>
                                    <installDirectory>node</installDirectory>
                                </configuration>
                            </execution>
                            <execution>
                                <id>grunt build</id>
                                <goals>
                                    <goal>grunt</goal>
                                </goals>
                                <configuration>
                                    <arguments>build</arguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>

We are doing a build with maven -P grunt .  For having node globally we are trying maven -P grunt -g , but still it is not working .

2.  So , I saw the group and tried maven exec plugin .


 <plugin>
    <groupId>org.codehaus.mojo</groupId>
    <artifactId>exec-maven-plugin</artifactId>
    <executions>
      <execution>
        <id>prepare-dist-npm-runtime-dependency</id>
        <phase>prepare-package</phase>
        <goals>
          <goal>exec</goal>
        </goals>
        <configuration>
          <executable>node/node</executable>
          <workingDirectory>dist</workingDirectory>
          <arguments>
            <argument>../node/npm/cli.js</argument>
            <argument>install</argument>
            <argument>--production</argument>
          </arguments>
        </configuration>
      </execution>
    </executions>
  </plugin>


But I was not able to see it working . Can anyone help how to run maven to get it working for global node installation and not installing node with each build ?

If any other suggestion to get it working will be grateful .

**Comment by Blyster111** [comment]
![xlarge](https://user-images.githubusercontent.com/23199079/75146558-aa2bd200-56fb-11ea-9e86-f333a6ca0f74.png)
