### ISSUE TITLE
Nexus hosted NPM & NodeJS via HTTPS

### ISSUE THREAD

**Issue by Barnzy** [eirslett/frontend-maven-plugin#181]
Hi,

I've recently managed to get a version of NodeJS and NPM up onto my Nexus box, following the same naming convention and folder structure found on http://nodejs.org/dist/.

I've then added the lines to my pom (downloadRoot etc...) to stop it attempting to go to the internet to download NPM and NodeJS and go to the internal Nexus server instead. However, my Nexus server is hosted over https for various reasons. On mvn clean install, and I keep getting the following error:

```
Could not download Node.js
Remote host closed connection during handshake: SSL peer shut down incorrectly
```

It's obviously having an issue with the https side of things (hence the SSL reference). The easy option will be to serve Nexus over http but due to reasons out of my control, I cannot. Is there something that can be done with the httpClient used by this plugin to tell it to go to a certain port that may alleviate this problem?

It's taken me so long to get to this point and I feel like I'm so close to getting my setup nailed.

**Comment by eirslett** [comment]
Have a look at this one:

https://github.com/eirslett/frontend-maven-plugin/blob/master/frontend-plugin-core/src/main/java/com/github/eirslett/maven/plugins/frontend/lib/FileDownloader.java

It might need some tweaking in order to support HTTPS.

**Comment by Barnzy** [comment]
Thanks @eirslett, will have a look at that! :+1:

**Comment by gymb321** [comment]
I believe I fixed this same issue with my setup by adding npm set strict-ssl false. This can be added to a .npmrc file at the root of the project.

**Comment by eirslett** [comment]
I assume the problem is fixed then :)

**Comment by Barnzy** [comment]
Yes, thank you! :+1:

**Comment by phillipj** [comment]
@AdamBarnwell any tips about how you got Node.js uploaded to nexus which is compatible with this plugin?

**Comment by AdamBarnwell** [comment]
@phillipj, did this a while ago but will describe what I remember.

I remember it being fairly tricky. In the end I had to create a new repository on our Nexus (I called it nodejs.org). I set the 'Type' to hosted and the 'Format' to site. This gave me an empty directory at https://nexus.our-office.com/content/sites/nodejs.org.

The next problem was uploading the files to Nexus. There was no way of uploading and managing files in this repository via the Nexus UI so I had to rsync into the box, find the folder it had created for nodejs.org and drop in the following:

- v0.12.0
    - docs
    - x64
    - node.exe
    - ....
- npm-1.4.9.tgz
- npm-1.4.9.zip

For the v0.12.0 folder, I mirrored the contents of https://nodejs.org/dist/v0.12.0/.

Obviously if you intend to use later versions of Node.js and/or NPM, you will need to get the updated files and folders.

Once this was all setup and accessible, I changed my executions for the frontend-maven-plugin to look like this:
```
<executions>
    <execution>
        <id>install node and npm</id>
        <goals>
            <goal>install-node-and-npm</goal>
        </goals>
        <configuration>
            <nodeVersion>v0.12.0</nodeVersion>
            <npmVersion>1.4.9</npmVersion>
            <downloadRoot>https://nexus.our-office.com/content/sites/nodejs.org/</downloadRoot>
       </configuration>
    </execution>
    <execution>
        <id>npm config</id>
        <goals>
            <goal>npm</goal>
        </goals>
        <configuration>
            <arguments>config set color false</arguments>
            <arguments>config set registry https://nexus.our-office.com/content/groups/npm/</arguments>
        </configuration>
    </execution>
    <execution>
        <id>npm install</id>
        <goals>
            <goal>npm</goal>
        </goals>
        <configuration>
            <arguments>install --quiet</arguments>
        </configuration>
    </execution>
    <execution>
        <id>grunt build</id>
        <goals>
            <goal>grunt</goal>
        </goals>
        <configuration>
            <arguments>build</arguments>
        </configuration>
    </execution>
</executions>
```

The only big downside is having to rsync to the Nexus server if we ever want to upgrade to a new version of Node or NPM. But that will hopefully be rare and this covers us in terms of redundancy so it suits us.

Hope it helps! :-)

**Comment by phillipj** [comment]
> Hope it helps! :-)

Absolutely, much appreciated!

@eirslett would it be in the interest of this plugin to support these offline/isolated network scenarios in some way? As described above, it's a real pain getting nexus to have similar directory structure as nodejs.org. I haven't put too much thought into what changes would be needed in this plugin, but it would probably be less hacky than the trying to force correct directory paths in nexus.

**Comment by jgangemi** [comment]
you can push files up to nexus using curl. see here:

https://support.sonatype.com/hc/en-us/articles/213465818-How-can-I-programatically-upload-an-artifact-into-Nexus-

i did this in our nexus repo and didn't really have any issues at all nexus also supports mirroring of `npm` repositories out of the box provided you're running a recent version.

**Comment by phillipj** [comment]
Uploading directly with curl might be worth a shot, thanks @jgangemi!

As I can't access the nexus server to set up rsync or alter the paths directly, I ended up doing the following:

1) Package the node executable alongside `node_modules/npm` into e.g. node.tgz
2) mvn:deploy that tarball onto nexus as org.nodejs.node v4.2.3
3) Use maven-dependency-plugin to extract the content of that tarball into project's node directory
4) Use frontend-maven-plugin as usual

Was a great success, although using curl might actually remove step 3, so I'll give it a shot next week.
