### ISSUE TITLE
When using a proxy, the password is shown in clear text in the maven output

### ISSUE THREAD

**Issue by cobour** [eirslett/frontend-maven-plugin#182]
When running an maven build during the step "npm install" the complete proxy string is shown in the maven output, including the password.
Any chance to ****** out the password? The rest of the proxy-config-string is informational and should be left untouched imho.

**Comment by eirslett** [comment]
I think this was fixed in 63643260, which is released in version 0.0.23?

**Comment by cobour** [comment]
Indeed, sorry!
I didn't check 0.0.23 (was using 0.0.22). For some obscure reasons (my company) i were using JDK6, which gives an error when executing "s.replaceFirst("//(?<keep>.*):.*@", "//${keep}:***@")", but after upgrading to JDK8 the error was gone.
Thanks and keep up the good work!
