### ISSUE TITLE
Build fails on Linux EC2

### ISSUE THREAD

**Issue by dgraeber** [eirslett/frontend-maven-plugin#183]
Not sure where to go with this, but the end-to-end build works fine locally (I have npm installed locally also), but on a linux box (EC2) I am trying to create a fresh build and I continue to fail:

>  mvn install -DskipTests -Pspark-1.2 -Dspark.version=1.2.1 -Dhadoop.version=2.4.0

[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.20:install-node-and-npm (install node and npm) on project zeppelin-web: Execution install node and npm of goal com.github.eirslett:frontend-maven-plugin:0.0.20:install-node-and-npm failed: A required class was missing while executing com.github.eirslett:frontend-maven-plugin:0.0.20:install-node-and-npm: org/slf4j/helpers/MarkerIgnoringBase

Thoughts?

**Comment by eirslett** [comment]
Try a newer version of the plugin? There were some issues with Maven 3.3 and this plugin because of slf4j. Should be fixed now.

**Comment by dgraeber** [comment]
Ahhh..that looks like the issue.  Locally, I am running maven 3.2.3  On EC2 I installed the latest version of 3.3.  For the record, I changed plugin version from 0.0.20 to 0.0.23 and looks like things build correctly.  Sorry for not catching this!

**Comment by eirslett** [comment]
No worries! Glad to hear it works now!
