### ISSUE TITLE
Fails on Maven 3.3.1

### ISSUE THREAD

**Issue by torarnek** [eirslett/frontend-maven-plugin#184]
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[project>no.finntech.oppdrag-services:oppdrag-app-main:2014-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]
[ERROR]
[ERROR] -----------------------------------------------------: org.slf4j.helpers.MarkerIgnoringBase

**Comment by eirslett** [comment]
This was fixed in 0.0.23.
