### ISSUE TITLE
npm goal does not skip tests when phase is test and -DskipTests=true

### ISSUE THREAD

**Issue by javadoug** [eirslett/frontend-maven-plugin#185]
The npm goal is used to run `npm test` however, tests are not skipped when the skipTests property is set. It should should skip invoking the test phase of any mojo goal that is tied to the test phase. I suspect the other targets bower, gulp, etc. have the same issue.

**Comment by eirslett** [comment]
Yes, you're right. The only thing that is skipped now, with skipTests, is the karma run. To get around it, you'll have to make a "skipTests" Maven profile.
This is not a problem with frontend-maven-plugin in particular, it's a problem with Maven plugins in general, so if you want it fixed I suggest you open an issue at the Maven issue tracker!

**Comment by javadoug** [comment]
ah, right. I experienced the same issue with the exec plugin. fair enough. thanks.
