### ISSUE TITLE
allow configurable m2e integration to trigger npm on more than just package.json

### ISSUE THREAD

**Issue by citizenkahn** [eirslett/frontend-maven-plugin#193]
I have an ember project run via npm and frontend-maven-plugin.  When I modify application.hbs I expect m2e lifecycle mapping to execute npm and run ember.  However, npm only executes on modification of package.json.

Could we allow that to be configured?

**Comment by eirslett** [comment]
Is this similar to https://github.com/eirslett/frontend-maven-plugin/pull/125 ?

**Comment by citizenkahn** [comment]
Yep,  This ia a dup.  Also, if I switch to the new ember mojo instead of calling ember via npm everything works as expected.  So, I'll setup my private copy of 0.0.24-SNAPSHOT until such time as you release 0.0.24.   Thanks for the help.
