### ISSUE TITLE
Specify node architecture to use (x64, x86)

### ISSUE THREAD

**Issue by cecchisandrone** [eirslett/frontend-maven-plugin#199]
Hello,
is there a way to specify node executables to download (x64, x86)?

**Comment by eirslett** [comment]
No. It makes a guess, based on system properties:
https://github.com/eirslett/frontend-maven-plugin/blob/d29b88a476b4cb873fc3332ec424cfa47c892f64/frontend-plugin-core/src/main/java/com/github/eirslett/maven/plugins/frontend/lib/Platform.java#L4

**Comment by cecchisandrone** [comment]
Ok thanks
