### ISSUE TITLE
Error while build

### ISSUE THREAD

**Issue by corporatepiyush** [eirslett/frontend-maven-plugin#201]
[INFO] --- frontend-maven-plugin:0.0.23:install-node-and-npm (install node and npm) @ uitk-client ---
[INFO] Node v0.12.2 is already installed.
[INFO] Found NPM version 2.7.4
[INFO]
[INFO] --- frontend-maven-plugin:0.0.23:npm (npm install) @ uitk-client ---
[INFO] Running 'npm install --color=false' in c:\work\workspace\uitk\uitk-client\src\main\resources\static
[ERROR] c:\work\workspace\uitk\uitk-client\src\main\resources\static\node\npm\bin\npm-cli.js:4
[ERROR] #!/usr/bin/env node
[ERROR] ^
[ERROR] SyntaxError: Unexpected token ILLEGAL
[ERROR]     at exports.runInThisContext (vm.js:73:16)
[ERROR]     at Module._compile (module.js:443:25)
[ERROR]     at Object.Module._extensions..js (module.js:478:10)
[ERROR]     at Module.load (module.js:355:32)
[ERROR]     at Function.Module._load (module.js:310:12)
[ERROR]     at Function.Module.runMain (module.js:501:10)
[ERROR]     at startup (node.js:129:16)
[ERROR]     at node.js:814:3
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.428s
[INFO] Finished at: Thu Apr 16 18:48:09 IST 2015
[INFO] Final Memory: 16M/349M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.23:npm (npm install) on project uitk-client: Failed to run task: 'npm install --color=false' failed. (error code 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by FagnerMartinsBrack** [comment]
I am having the same problem in an Ubuntu machine.

* It works properly in Windows with maven.
* It also works typing `$ npm install --color=false` in the command line for both Windows and Linux.
* It doesn't work using maven.

```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.401 s
[INFO] Finished at: 2015-04-17T19:49:16+01:00
[INFO] Final Memory: 17M/60M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.23:npm (npm install) on project WebStories: Failed to run task: 'npm install --color=false' failed. (error code 134) -> [Help 1]
```

There's a npm file with the following content and execution permissions:

```bash
#!/bin/sh
"node/node" "node/npm/bin/npm-cli.js" "$@"
```

Here is the full `mvn install` log with debug (-X) flag on: https://gist.github.com/FagnerMartinsBrack/34fdb5083d5f2adfe701

using latest version `0.0.23` from maven central.

**Comment by FagnerMartinsBrack** [comment]
Ok now that's insane.

I removed the project, added again, tried to downgrade plugin versions to find the offending release, etc. and then when I came back to 0.0.23 it was magically fixed O.O

**Comment by eirslett** [comment]
That's strange... can you try to delete the "node" directory that is made, and then run the build again, see if if works consistently?

**Comment by FagnerMartinsBrack** [comment]
In project directory:

```shell
$ rm -rf node
$ mvn clean install
```

BUILD SUCCESS with frontend-maven-plugin version 0.0.23

o.O

**Comment by eirslett** [comment]
Ok, it works now, let's close our eyes and pretend it never happened...

**Comment by FagnerMartinsBrack** [comment]
I don't know if the OP can reproduce it yet.
