### ISSUE TITLE
npm install does not work with eclipse m2e

### ISSUE THREAD

**Issue by warcops** [eirslett/frontend-maven-plugin#203]
I am setting up the this plugin with my java project in my eclipse workspace.

following the plugin configuration is the pom.
```
			<plugin>
				<groupId>com.github.eirslett</groupId>
				<artifactId>frontend-maven-plugin</artifactId>
				<version>0.0.23</version>
				<executions>
					<execution>
						<id>install node and npm</id>
						<phase>generate-resources</phase>
						<goals>
							<goal>install-node-and-npm</goal>
						</goals>
						<configuration>
							<nodeVersion>v0.10.18</nodeVersion>
							<npmVersion>1.3.8</npmVersion>
						</configuration>
					</execution>
					<execution>
						<id>npm install</id>
						<phase>generate-resources</phase>
						<goals>
							<goal>npm</goal>
						</goals>
						<configuration>
							<arguments>install</arguments>
						</configuration>
					</execution>
					<execution>
						<id>grunt build</id>
						<phase>generate-resources</phase>
						<goals>
							<goal>grunt</goal>
						</goals>
						<configuration>
							<arguments>--verbose</arguments>
						</configuration>
					</execution>
				</executions>
			</plugin>
```

I get the following error when I do mvn clean install
```
{ [Error: EACCES, mkdir '/Users/xxx/.npm/lodash/0.9.2']
[ERROR] npm ERR!   errno: 3,
[ERROR] npm ERR!   code: 'EACCES',
[ERROR] npm ERR!   path: '/Users/xxx/.npm/lodash/0.9.2' }
```

I guess this is because its trying to install the package globally. As we know, when running from eclipse we cannot start the task as a administrator.

What should I do here?

**Comment by eirslett** [comment]
What does your package.json look like? Maybe there are some components there that are trying to be installed globally?

**Comment by warcops** [comment]
The package.json looks like as follows:
```
{
   "name":"my-tools",
   "version":"0.0.1",
   "dependencies": {
   	  "glob":"~4.3.5",
      "grunt": "~0.4.5",
      "grunt-cli": "~0.1.13",
      "grunt-contrib-jshint":"~0.10.0"
   },
   "devDependencies": {}
}
```

the file is pretty simple. I am just trying to lint all js files. Not sure if I missed something

**Comment by warcops** [comment]
any leads guys?

**Comment by eirslett** [comment]
Seems like there are no modules in there that try to install themselves globally... grunt-cli complains a bit when it's being installed locally, but shouldn't try and write to the ~ folder just because of that...

Can you try running mvn clean install, outside of Eclipse, as an administrator? And then open the project in Eclipse?

**Comment by warcops** [comment]
Hi Eirik,

That solution works.

But my concern is whether i will face similar issue when i deploy it on my
openshift instance. As I would not be having administrative rights there.
Can you suggest of some other solution as well.

**Comment by eirslett** [comment]
Are you running your CI on OpenShift? In that case, I would just try running a build and see what happens...
If you're talking about your production environment, then that shouldn't be a problem, since this is strictly a build-time problem.

**Comment by warcops** [comment]
No, I am not using CI. On running the plugin, it errors out suggesting that the plugin needs maven 3.1. 
In openshift by default maven 3.0.4 is available. Working on making it work. For the time being closing the issue, as there is a viable workaround available for loal.

Thanks for your input

**Comment by tknerr** [comment]
@warcops we are stuck with Maven 3.0.5 for some reason. Did you get it working somehow with Maven 3.0.4?

**Comment by tknerr** [comment]
@warcops I switched back to v0.0.22 of the plugin which does not check for the Maven 3.1 prerequisite.

So far it seems to work well with maven 3.0.5 too (or maybe I just haven't hit the critical code path where it breaks ;-))

**Comment by warcops** [comment]
@tknerr sorry mate...was on a week long holiday...yes i agree v0.0.22 doesn't restrict the maven version. But I was not very confident with an earlier version.
I instead had some node infrastructure at my disposal, which i used to perfrom my grunt job and then assemble it to a s3 server, from where my jenkin picks the file and compiles to war.

I know, its not efficient, but well, it works.
