### ISSUE TITLE
npm install doesn't take arguments

### ISSUE THREAD

**Issue by qiurang** [eirslett/frontend-maven-plugin#207]
for Goal npm, the arguments configured actually doesn't work.
    <configuration>
        <arguments>install</arguments>
    </configuration>
</execution>

Since in the source code NpmRunner.java, it won't pick up this argument.

**Comment by eirslett** [comment]
It's happening in NodeTaskExecutor - the arguments set in NpmRunner are actually "additionalArguments". Or maybe there's a bug in there - do you have an example?

**Comment by qiurang** [comment]
Sorry I must have made some mistake yesterday. It works now.
