### ISSUE TITLE
bower missing in package.json

### ISSUE THREAD

**Issue by ufoscout** [eirslett/frontend-maven-plugin#208]
Hi all,

the bower dependency is missing in the devDependencies section of the package.json.
I think it should be present with the expected version because, indeed, it is a required dependency to perform a full build in environments where bower is not installed in the global scope.
For example, for a project of mine, the continuous integration server fails the build because it cannot find bower in the node_modules folder.

**Comment by eirslett** [comment]
You can look at the example project:
https://github.com/eirslett/frontend-maven-plugin/blob/master/frontend-maven-plugin/src/it/example%20project/package.json
You'll have to add it to package.json yourself. (It's poorly documented)
The reason it's not in devDependencies is that shrinkwrap didn't work with them before, I believe that has changed now though.

**Comment by ufoscout** [comment]
Hi Eirik,

I already added it in my project (it was not so difficult to do even if not documented :wink: ), this issue is just because I think that it should be added by default. However, I clearly understand that it is not possible if it causes issues with other components.

**Comment by eirslett** [comment]
Yup, the main reason is "the less magic, the better", or rather, this plugin should only contain the right kind of magic, so to speak. That way, users also get to choose which version of bower they want to install (via package.json).

**Comment by ufoscout** [comment]
Hi Eirik,

I understood only now that I opened this issue in the wrong place!!!! :scream:
The issue I mentioned is for the generator-gulp-angular github project and not for this one!!!  :cold_sweat:
Sorry guy!

PS: I take this opportunity to thank you for this beautiful maven plugin

**Comment by eirslett** [comment]
Haha, no worries! ;-)

**Comment by asmaier** [comment]
Please document that one has to add bower, gulp and grunt to package.json when trying to run it with the maven-frontend-plugin. It is confusing at first to see a build on jenkins fail because of missing bower, gulp or grunt.
