### ISSUE TITLE
Request to provide multiple directories to be watched and refreshed

### ISSUE THREAD

**Issue by jimMoriarty** [eirslett/frontend-maven-plugin#213]
Hi,

I'm using your plugin to install Node, NPM and run Grunt tasks.
The plugin provides the following option:

                
        	<srcdir>${basedir}/src/main/webapp/resources/js/</srcdir>

        	
        	<outputdir>${basedir}/src/main/webapp/resources/optimizedScripts/</outputdir>

But the trouble is I have multiple directories to be watched over and refreshed.

For instance, one of my Grunt tasks is to use grunt-contrib-jst to pre-compile underscore templates into AMD modules. Then use the various files and these pre-compiled templates functions to build an optimized file using grunt-contrib-requireJs. 

The issue is, my underscore templates are in a different directory and the JS sources are in a different directory. But, the plugin provides only one directory to watch over and one directory to refresh. 

Tomorrow, if I decide to Lint CSS files using grunt-contrib-cssLint then my CSS files would be in another directory which would again be a problem

Please let me know if there is a configuration that I can do for this.

**Comment by eirslett** [comment]
There is no configuration for that, today. The only option is to watch the "webapp/resources" directory and write to "webapp/resources_compiled" (or something like that).

**Comment by jimMoriarty** [comment]
oh :( Is <srcdir> and <outputdir> tags specific to this plugin or is this part of maven's tags ?

**Comment by eirslett** [comment]
It's part of this plugin. @karlvr I think it could be extended to multiple source directories? Or would that be too complex maybe?

**Comment by jimMoriarty** [comment]
Oh.. because I couldn't find references to those tags in the source code .. perhaps I missed it.. Let me re-visit.. Please let me know if there is a plan to support extending to multiple source directories

**Comment by jimMoriarty** [comment]
Awaiting your reply ...

**Comment by eirslett** [comment]
Sorry!
No, there is no plan for extending the current functionality. I'm not sure there's an easy way to extend today's functionality without breaking backwards compatibility. A PR would be appreciated!
