### ISSUE TITLE
NPM fails on command with 'npm run <task>'

### ISSUE THREAD

**Issue by EvgeniGordeev** [eirslett/frontend-maven-plugin#216]
Prerequisites:
1) Maven configuration:
```
<plugin>
        <groupId>com.github.eirslett</groupId>
        <artifactId>frontend-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>install node and npm</id>
            <goals>
              <goal>install-node-and-npm</goal>
            </goals>
            <configuration>
              <nodeVersion>v0.12.2</nodeVersion>
              <npmVersion>2.7.6</npmVersion>
            </configuration>
          </execution>
          <execution>
            <id>npm install</id>
            <goals>
              <goal>npm</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
```
2) package.json:
```
...
"scripts": {
    "postinstall": "npm run wiredep",
    "prestart": "npm install",
    "start": "http-server -a 127.0.0.1 -p 8002",
    "wiredep": "wiredep --verbose --bowerJson bower.json --src src/main/resources/public/index.html"
  }
...
```
3) Node.js/npm is not installed globally.

While running 'mvn install' the following error is thrown:
```
[INFO] --- frontend-maven-plugin:0.0.23:npm (npm install) @ project-web-client ---
[INFO] Running 'npm install --color=false' in C:\work\projects\project-web-client
[INFO]
[INFO] > project-web-client@4.0.11-SNAPSHOT postinstall C:\work\projects\project-web-client
[INFO] > bower install && npm run wiredep
[INFO]
[ERROR] 'npm' is not recognized as an internal or external command,
[ERROR] operable program or batch file.
[ERROR]
[ERROR] npm ERR! Windows_NT 6.3.9600
[ERROR] npm ERR! argv "C:\\work\\projects\\project-web-client\\node\\node" "C:\\work\\projects\\project-web-client\\node\\npm\\bin\\npm-cli.js" "install" "--color=
false"
[ERROR] npm ERR! node v0.12.2
[ERROR] npm ERR! npm  v2.7.6
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! project-web-client@0.0.11-SNAPSHOT postinstall: `bower install && npm run wiredep`
[ERROR] npm ERR! Exit status 1

``` 
Note: if package.json has a command in postinstall phase like 'bower install' it works correctly.

**Comment by EvgeniGordeev** [comment]
Actually error output is for multiple commands `bower install && npm run wiredep` in postinstall phase. First assumption was the error is due to multiple commands but it appeared not. {"postinstall":"bower install && wiredep --verbose --bowerJson bower.json --src src/main/resources/public/index.html"} is executed successfully.

**Comment by issoft-nsiniakevich** [comment]
Seems like npm is not in the path.
Can we try to add npm to PATH temporary after it's downloaded?

**Comment by eirslett** [comment]
You can try copy-pasting the npm helper script(s) from this plugin into your root/working directory, does that help?

**Comment by EvgeniGordeev** [comment]
Could you explain more detailed what I should try?

**Comment by eirslett** [comment]
Copy this file: https://github.com/eirslett/frontend-maven-plugin/blob/master/frontend-maven-plugin/src/it/example%20project/helper-scripts/npm into your project root directory (the same directory as the pom.xml file and/or the package.json file) and try again!

If you're building on Windows, you should add this as well:
https://github.com/eirslett/frontend-maven-plugin/blob/master/frontend-maven-plugin/src/it/example%20project/helper-scripts/npm.cmd

Then try running the maven build again.
If that works, commit these two files into your repository.

**Comment by EvgeniGordeev** [comment]
Thanks, it works with the shell scripts.

**Comment by EvgeniGordeev** [comment]
Actually my previous comment was based on running 'mvn clean install' on Windows. Bamboo build on Linux still fails with:
```
build	20-May-2015 18:16:29	[INFO] --- frontend-maven-plugin:0.0.23:install-node-and-npm (install node and npm) @ project-web-client ---
build	20-May-2015 18:16:29	[INFO] Node v0.12.2 is already installed.
build	20-May-2015 18:16:29	[INFO] Found NPM version 2.7.6
build	20-May-2015 18:16:29	[INFO] 
build	20-May-2015 18:16:29	[INFO] --- frontend-maven-plugin:0.0.23:npm (npm install) @ project-web-client ---
build	20-May-2015 18:16:29	[INFO] Running 'npm install --color=false' in /home/bamboo/bamboo-agent-home/xml-data/build-dir/PRJ-DEV-JOB1/project-web-client
build	20-May-2015 18:16:30	[INFO] 
build	20-May-2015 18:16:30	[INFO] > project-web-client@4.0.11-SNAPSHOT postinstall /home/bamboo/bamboo-agent-home/xml-data/build-dir/PRJ-DEV-JOB1/project-web-client
build	20-May-2015 18:16:30	[INFO] > bower install && npm run wiredep
build	20-May-2015 18:16:30	[INFO] 
build	20-May-2015 18:16:32	[ERROR] sh: npm: command not found
build	20-May-2015 18:16:32	[ERROR] 
build	20-May-2015 18:16:32	[ERROR] npm ERR! Linux 3.14.27-25.47.amzn1.i686
build	20-May-2015 18:16:32	[ERROR] npm ERR! argv "/home/bamboo/bamboo-agent-home/xml-data/build-dir/PRJ-DEV-JOB1/project-web-client/node/node" "/home/bamboo/bamboo-agent-home/xml-data/build-dir/PRJ-DEV-JOB1/project-web-client/node/npm/bin/npm-cli.js" "install" "--color=false"
build	20-May-2015 18:16:32	[ERROR] npm ERR! node v0.12.2
build	20-May-2015 18:16:32	[ERROR] npm ERR! npm  v2.7.6
build	20-May-2015 18:16:32	[ERROR] npm ERR! code ELIFECYCLE
build	20-May-2015 18:16:32	[ERROR] npm ERR! project-web-client@4.0.11-SNAPSHOT postinstall: `bower install && npm run wiredep`
build	20-May-2015 18:16:32	[ERROR] npm ERR! Exit status 127
build	20-May-2015 18:16:32	[ERROR] npm ERR! 
build	20-May-2015 18:16:32	[ERROR] npm ERR! Failed at the project-web-client@4.0.11-SNAPSHOT postinstall script 'bower install && npm run wiredep'.
build	20-May-2015 18:16:32	[ERROR] npm ERR! This is most likely a problem with the project-web-client package,
build	20-May-2015 18:16:32	[ERROR] npm ERR! not with npm itself.
build	20-May-2015 18:16:32	[ERROR] npm ERR! Tell the author that this fails on your system:
build	20-May-2015 18:16:32	[ERROR] npm ERR!     bower install && npm run wiredep
build	20-May-2015 18:16:32	[ERROR] npm ERR! You can get their info via:
build	20-May-2015 18:16:32	[ERROR] npm ERR!     npm owner ls project-web-client
build	20-May-2015 18:16:32	[ERROR] npm ERR! There is likely additional logging output above.
```

**Comment by eirslett** [comment]
Try making "bower" and "wiredep" scripts and commiting them to the root directory, in the same style as npm.sh?
It looks like you're trying to execute those commands directly, as if they were intalled globally.
You could also experiment with replacing "bower install" with "node_modules/.bin/bower install" (or something like that, I cannot remember the path to bower. Same with wiredep)

**Comment by sghosh-01** [comment]
Here is my pom:
<plugin>
                  <groupId>com.github.eirslett</groupId>
                  <artifactId>frontend-maven-plugin</artifactId>
                  <version>1.4</version>
                  <executions>
                   <execution>
                      <id>install node and npm</id>
                      <phase>generate-resources</phase>
                      <goals>
                        <goal>install-node-and-npm</goal>
                      </goals>
                      <configuration>
                        <nodeVersion>v6.9.5</nodeVersion>
                        <npmVersion>3.10.10</npmVersion>
                        <workingDirectory></workingDirectory>
                      </configuration>
                    </execution>

                    <execution>
                      <id>npm install</id>
                      <phase>generate-resources</phase>
                      <goals>
                        <goal>npm</goal>
                      </goals>
                      <configuration>
                        <workingDirectory></workingDirectory>
                      </configuration>
                    </execution>

The second execution, npm install doesn't run. When I run "mvn clean install" I get the following 
--- frontend-maven-plugin:1.4:install-node-and-npm (install node and npm) @ myproject ---
[INFO] Node v6.9.5 is already installed.
[INFO] NPM 3.10.10 is already installed.
[INFO]
[INFO] --- frontend-maven-plugin:1.4:npm (npm install) @ myproject ---
[INFO] Running 'npm install' in /Users/myproject

Waited more than 30 mins but doesn't do anything after this. Tried few times and it is same each time. Would appreciate any help.
