### ISSUE TITLE
 frontend maven plugin : bower install failed 

### ISSUE THREAD

**Issue by SomnathGoswami** [eirslett/frontend-maven-plugin#218]
I have almost same configuration in pom.xml mentioned in the example for this plugin  @ https://github.com/eirslett/frontend-maven-plugin/blob/master/frontend-maven-plugin/src/it/example%20project/pom.xml

but i am getting below error when this plugin tries to run task to install bower packages defined in bower.json file. This plugin worked fine to install all npm package defined in package.json.

Error :

Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.23: bower (bower install) on project example - Failed to run task: 'bower install'

[ERROR] bower angularjs#1.3.15 ECONNRESET Request to https://bower.herokuapp.com/pa... failed: tunneling socket could not be established, cause=socket hang up.

i tried adding proxy setting in .bowerrc file but no luck.

please provide any solution for this.

![bowerinstallerror](https://cloud.githubusercontent.com/assets/12496457/7681206/abe4127a-fd8b-11e4-93d0-084051b05d6e.png)

**Comment by eirslett** [comment]
Looks like a network issue.
Try npm install -g bower and then bower install straight from the command line?

**Comment by SomnathGoswami** [comment]
Hi eirslett,
what i understand about this plugin is that it download/install node and npm,then it wil use npm to download all other package defined in package.json(like bower in my case) and then it uses bower to download all other package defined in bower.json(like angularjs in my case).
so this plugin did well in installing node and npm.
but i think issue is not with the installing bower(npm install -g bower) as this plugin has already installed/downloaded bower using npm( and all other package which i mentioned in package.json) and i can see bower folder ( and all other package folders) under node_modules folder. 

when i tried running bower install angularjs command either from project_root\node_modules\bower folder or default cmd path through cmd its giving 'bower is not an intrenal or external command'  error.

Note : i dont installed node, npm and bower manually and i want that plugin to download all bower packages defined in bower.json when i build my maven project.
it should recognize bower command as its installed in system right?
Also why is this not able to download all bower packages defined in bower.json.

**Comment by eirslett** [comment]
I suggested that you should install node, npm and bower locally/manually and then run bower, to see whether it's this plugin that is causing problem, or it is bower itself. ;-)
After that you can uninstall node etc again.

**Comment by SomnathGoswami** [comment]
Hi eirslett,

you are right  : )

Issue is with bower itself. after installing node,npm and Bower manually, i tried instaling angularjs via bower commnad and  facing below issue -
bower ENOTFOUND     Request to https://bower.herokuapp.com/packages/requirejs fa
iled: getaddrinfo ENOTFOUND bower.herokuapp.com

i tried after setting proxy in .bowerrc file as below but no luck

{
  "registry": "https://bower.herokuapp.com",
  "proxy": "http://proxy.example.com:81",
  "https-proxy": "http://proxy.example.com:81",
  "strict-ssl": false
}

i kept .bowerrc file in bower folder which npm created.
can you please tell me how to resolve this bower issue.

**Comment by eirslett** [comment]
I'm sorry, I cannot help you with bower problems. You have to ask the bower guys for help!

**Comment by SomnathGoswami** [comment]
Hi eirslett,

bower issue got resolved by adding below environment variables in system properties
HTTP_PROXY = http://proxy2.example.com:81
HTTPS_PROXY = http://prox2.example.com:81

and Now this plugin is able to download all the packages mentioned in bower.json file. issue was not with plugin.

Thanks for your help and suggestion.

**Comment by eirslett** [comment]
Great! I think you can also commit a .bowerrc file with proxy settings (I think) but I'm not sure about the details.
