### ISSUE TITLE
Plugin ignores -Dorg.slf4j.simpleLogger.defaultLogLevel=warn

### ISSUE THREAD

**Issue by TheSnoozer** [eirslett/frontend-maven-plugin#222]
Hi,
the project got my attention through the maven class loading issue discussed in https://issues.apache.org/jira/browse/MNG-5787.
We kind of evaluate what's the best way to avoid this issue (https://github.com/ktoso/maven-git-commit-id-plugin/issues/198).
Someone pointed out that you guys fixed this issue with https://github.com/eirslett/frontend-maven-plugin/pull/178.
However it seems that the current version of the plugin ignores  -Dorg.slf4j.simpleLogger.defaultLogLevel=warn and displays [INFO] messages.

```
NodeAndNPMInstaller.java
logger.info("Installing node version " + nodeVersion);


$ mvn clean install -Dmaven.test.skip=true | grep "Installing node version"
[INFO] [INFO] Installing node version v0.12.2
```
Can someone confirm this?
Btw it's totally ok if you close this as Won't fix because I just want to figure out if we can apply the same solution to our project or have to do something different :-)

**Comment by eirslett** [comment]
I haven't tried that before - I'm not sure if it's ignored or not. I guess it's ignored, since that's your result! I have no plans for adding support (I'm not sure what it would take).

**Comment by TheSnoozer** [comment]
Ok, Thanks :-)
