### ISSUE TITLE
Issue In NPM install 

### ISSUE THREAD

**Issue by maheshkaranjkar** [eirslett/frontend-maven-plugin#225]
Hi Guys,

Thanks a lot for this wonderful plugin. 

But unfortunately I getting following error when I do  "mvn clean install" 

<code>

D:\GppWorkspace\globe>mvn clean install
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building globe 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ globe ---
[INFO] Deleting D:\GppWorkspace\globe\target
[INFO]
[INFO] --- frontend-maven-plugin:0.0.23:install-node-and-npm (install node and npm) @ globe ---
[INFO] Node Cannot execute D:\GPPWORKSPACE\GLOBE\SRC\MAIN\RESOURCES\STATIC\NODE\NODE.EXE was installed, but we need version v0.12.2
[INFO] Installing node version v0.12.2
[INFO] Downloading via proxy ProxyConfig{protocol='http', host='proxy.***.com', port=8080, with username/passport authentication}
[INFO] Installed node.exe locally.
[INFO] Installing npm version 2.7.6
[INFO] Downloading NPM from http://registry.npmjs.org/npm/-/npm-2.7.6.tgz to D:\GppWorkspace\globe\src\main\resources\static\npm.tar.gz
[INFO] Downloading via proxy ProxyConfig{protocol='http', host='proxy.***.com', port=8080, with username/passport authentication}
[INFO] Extracting NPM files in node/
[INFO] Unpacking D:\GppWorkspace\globe\src\main\resources\static\npm.tar.gz into D:\GppWorkspace\globe\src\main\resources\static/node
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.813 s
[INFO] Finished at: 2015-06-04T17:17:59+05:30
[INFO] Final Memory: 15M/36M
[INFO] ------------------------------------------------------------------------
</code>

and 

<code>
Could not extract the npm archive: Could not extract archive: 'D:\GppWorkspace\globe\src\main\resources\static\npm.tar.gz': Input is not in the .gz format ->
</code>

Following is my pom.xml 

<code>

<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>com.github.eirslett</groupId>
        		<artifactId>frontend-maven-plugin</artifactId>
        		<version>0.0.23</version>
			
			<configuration>
        		<workingDirectory>src/main/resources/static</workingDirectory>
    		</configuration>
			<executions>

                    <execution>
                        <id>install node and npm</id>
                        <goals>
                            <goal>install-node-and-npm</goal>
                        </goals>
                        <configuration>
                            <nodeVersion>v0.12.2</nodeVersion>
                            <npmVersion>2.7.6</npmVersion>
                        </configuration>
                    </execution>

                    <execution>
                        <id>npm install</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        
                        <configuration>
                            <arguments>install</arguments>
                        </configuration>
                    </execution>
                    
                    <execution>
                        <id>bower install</id>
                        <goals>
                            <goal>bower</goal>
                        </goals>
                        <configuration>
                            <arguments>install</arguments>
                        </configuration>
                    </execution>                    

                    <execution>
                        <id>grunt build</id>
                        <goals>
                            <goal>grunt</goal>
                        </goals>
                        <configuration>
                            <arguments>--no-color</arguments>
                        </configuration>
                    </execution>

                    <execution>
                        <id>javascript tests</id>
                        <goals>
                            <goal>karma</goal>
                        </goals>
                        <configuration>
                            <karmaConfPath>src/test/javascript/karma.conf.ci.js</karmaConfPath>
                        </configuration>
                    </execution>

                </executions>	
		
			</plugin>
		</plugins>
	</build>
</code>

Please help me in resolving this issue .

Regards
Mahesh

**Comment by james-a-woods** [comment]
I am getting the same problem.  From what I can see it is downloading npm-n.n.n.tgz, then unzipping it into npm.tar.gz.  But npm.tar.gz is a raw tar file, not a gzipped tar file.  So when the next step tries to unzip it, it fails.

**Comment by james-a-woods** [comment]
I should also mention that we are using an internal artifactory server for downloading npm, because we are behind a corporate firewall.  The download is working ok from the browser but seems to be getting confused in the java code somewhere.  I am in a workshop for the next couple of days, but then I will investigate if it is an issue with our server configuration or the request headers.

**Comment by eirslett** [comment]
Somebody had an issue with the tar.gz file, that it was compressed once more over the wire or something like that... have you checked the md5 signature of the file that the Maven plugin downloads?

**Comment by james-a-woods** [comment]
I have managed to track down the problem.

When npm is downloaded from http://nodejs.org/dist/npm/ the Content-Type is set to "application/octet-stream", which is then saved correctly.

When npm is downloaded from artifactory (and potentially other mirror sites) the Content-Type is set to "application/x-gzip".  HttpClient then gets a bit too clever for its own good, recognises the type, and decompresses it automatically as it downloads it.

To prevent this, create the HttpClient with:
        CloseableHttpClient client = HttpClients.custom()
            .disableContentCompression()
            .build();

This should then get things working correctly.  Unfortunately my corporate development environment makes it difficult for me to make this fix myself, test it and the provide a pull request.

Cheers
James

**Comment by rustyx** [comment]
Added pull request https://github.com/eirslett/frontend-maven-plugin/pull/280

**Comment by Deklin** [comment]
Is this in 1.0? I am having this issue on a linux system

**Comment by eirslett** [comment]
Yes, it should be in 1.0
