### ISSUE TITLE
install-node-and-npm failed: A required class was missing ...

### ISSUE THREAD

**Issue by jackrabb1t** [eirslett/frontend-maven-plugin#226]
While building my maven project, I get the following failure.

"Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.20:install-node-and-npm (install node/npm) on project ui: Execution install node/npm of goal com.github.eirslett:frontend-maven-plugin:0.0.20:install-node-and-npm failed: A required class was missing while executing com.github.eirslett:frontend-maven-plugin:0.0.20:install-node-and-npm: org/slf4j/helpers/MarkerIgnoringBase"

**Comment by eirslett** [comment]
Use version 0.0.23.

**Comment by mcahornsirup** [comment]
I have fixed it by remove ~/m2/repository/com/github/eirslett and build again with version 1.6.
