### ISSUE TITLE
Running bower commands in another folder than baseDir

### ISSUE THREAD

**Issue by amohabirQAFE** [eirslett/frontend-maven-plugin#228]
Currently the bower commands are executed in the ${baseDir}-folder by default. For example our bower.json is available in ${baseDir}/src/main/webapp. There is no option to overwrite this using a configuration variable.

**Comment by eirslett** [comment]
Try using a .bowerrc file?
http://bower.io/docs/config/

**Comment by amohabirQAFE** [comment]
Already used the .bowerrc file and that worked fine. Couldn't find an option for the command line unfortunately.

**Comment by amohabirQAFE** [comment]
Found it already. Forgot to add the "cwd" to the .bowerrc file. It can now find the bower.json file in another folder. Thanks for the help!

**Comment by eirslett** [comment]
Happy to hear that it works!
