### ISSUE TITLE
Why the depedency on Maven 3.1.0

### ISSUE THREAD

**Issue by ooxi** [eirslett/frontend-maven-plugin#229]
Why does this project depend on Maven 3.1.0? Even Ubuntu 15.04 ships with an older version. I'm not saying, that the dependency is wrong, but the technical reasons for it should be documented :)

**Comment by eirslett** [comment]
It's because of the use of slf4j - you can find the reasons behind it if you look at the history of pull requests (I know commit history is not good documentation ;-))
I think you can use an older version of the plugin - 0.0.22 maybe?

**Comment by ooxi** [comment]
Could you please point out the pull request you reference? I can only find d91d3779094b07784d31638b347ec7e3303d4051 which does not explain the change.

Nevertheless thanks for the fast reply, I will try again with `0.0.22` :)

**Comment by eirslett** [comment]
https://github.com/eirslett/frontend-maven-plugin/pull/178

This plugin used to have SLF4j as a dependency. Later versions of Maven ship with embedded SLF4J, so the two dependencies clash.

That being said, I think the easiest solution, and the one that would benefit you the most in the long term, would be to upgrade Maven.

**Comment by ooxi** [comment]
I totally agree with you, upgrading Maven would be the best option in the long run. But currently every developer uses Ubuntu 15.04 and we'd have to use additional package sources.

But downgrading to `0.0.22` did work for the moment :)
