### ISSUE TITLE
Run grunt in another thread

### ISSUE THREAD

**Issue by samfcmc** [eirslett/frontend-maven-plugin#230]
I am using this plugin to integrate a web application that uses maven to build the backend and grunt for the frontend that uses browserify and bower.
Now, when I run mvn install, in the frontend module, it runs grunt tasks that generate the final bundle with browserify. It is working well.
I am trying to run watchify to watch for changes in javascript files to trigger the generation of the new bundle file while the tomcat embedded server is running. There is a problem which is, when I try to run watchify, I can add an option in the GruntFile (keepAlive) that, when it's true, it keeps the process running forever. But, when I do this, the maven builds does not proceed, because, of course, there is this process running.
Can I configure grunt execution, in maven, to run in a separate thread, so it allows the embedded tomcat server to run and watch for changes in javascript files?

Thanks in advance.

**Comment by eirslett** [comment]
What I typically do is to run grunt-watch separately (from the command line) while the webapp is running. Is that an option for you?

**Comment by samfcmc** [comment]
I can do it but I would like to run the web app and watch for changes with just one command

**Comment by eirslett** [comment]
You could run Maven with a profile -Pdevelop, which adds a ${grunt.args} property: `<grunt.args>--keepAlive=true</grunt.args>`, you run grunt from the plugin with `<arguments>${grunt.args}</arguments>`, and then, in your Gruntfile, you read that command line argument and set the option in the Gruntfile. It's a bit involved, but the cleanest method I can think of. The additional bonus is that you can run "grunt --keepAlive=true" straigt from the command line as well, if you want that.

Will that solve your problem?

**Comment by samfcmc** [comment]
I have a default task and a dev task in my Gruntfile. My dev task has the keepAlive option set to true.
The problem is that, when I try to run the web application using the tomcat embedded container, it executes the grunt file and the process keeps running and the tomcat plugin does not proceed.
I want to use the ```tomcat7:run``` and still listening for changes in javascript files. But to do that, the grunt task needs to run in a separate process.
I know how to this but I have to add an option to the plugin itself. If it is ok for you I can implement this and make a pull request

**Comment by eirslett** [comment]
Thanks for the suggestion! But I don't want to support threading in the maven plugin, because of implementation complexity and feature creep.
We'll have to see if more people ask for the same feature!

**Comment by vermilion1** [comment]
+1 (but for all commands)

**Comment by novomanish** [comment]
+1 I have same requirement. I need to run tomcat and babel transpiler watch. I can do it on separate terminal but that brings an overhead of installing a global node.

**Comment by eirslett** [comment]
> I can do it on separate terminal but that brings an overhead of installing a global node.

You can use the helper scripts (you'll find them in this repository), then you can run the commands in a separate terminal, with the local version of node.

**Comment by samfcmc** [comment]
2 years have passed since I created this issue... I learned that separating the backend from the frontend is a really good idea.
If your backend is a REST API your frontend is just a client for that API... Making it a separated project is a good idea. You should consider this option.
