### ISSUE TITLE
mvn frontend:npm doesn't take <arguments> into account

### ISSUE THREAD

**Issue by nodje** [eirslett/frontend-maven-plugin#231]
```
                 <execution>
                        <id>npm install</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <configuration>
                            <arguments>grunt-cli</arguments>
                        </configuration>
                 </execution>
```
just doesn't work: ```mvn frontend:npm``` will execute ```npm --no-color install``` anyway.

**Comment by eirslett** [comment]
I have no idea why... if you have time to debug it, maybe you can find out why?
I also thought the way to run it was mvn frontend-maven-plugin:npm, but apparently not...

**Comment by talwin88** [comment]
<execution>
                        <id>server-build</id>
                        <goals>
                            <goal>gulp</goal>
                        </goals>
                        <configuration>
                            <arguments>server-build</arguments>
                        </configuration>
                    </execution>

I'm having the same issue when setting arguments in the configuration within execution. It is simply ignored unless it is within the plugin level configuration:


            <plugin>
                <groupId>com.github.eirslett</groupId>
                <artifactId>frontend-maven-plugin</artifactId>
                <version>0.0.23</version>
                <configuration>
                    <workingDirectory>src/main/jcr_root/etc/designs/${project.artifactId}/clientlibs/${project.type}/</workingDirectory>
                    <nodeVersion>v0.10.26</nodeVersion>
                    <npmVersion>1.4.3</npmVersion>
                    <arguments>server-build</arguments>
                </configuration>

But this way it will add it for every goal. My current workaround is to set the 'server-build' task as my default. Any ideas how to fix this?

**Comment by nodje** [comment]
This behavior is consistent across all execution tasks in the plugin config.

I've come to realize that <arguments> are taken into accounts when the plugin is triggered by Maven through the generate-resources phase. But not when called manually with ```mvn frontend:xxx```

I'll try to look into it.

**Comment by eirslett** [comment]
I think this is a general problem with Maven. Reopen the case if you find out more!
