### ISSUE TITLE
"Bower errored" but the frontend-maven-plugin doesn't

### ISSUE THREAD

**Issue by NBardelot** [eirslett/frontend-maven-plugin#232]
When running gulp bower from a frontend-maven-plugin "execution", if the bower command fails bower returns an error but maven does not see the error and the build continues (which should not happen).

12:00:37 [INFO] [12:00:37] 'bower' errored after 58 s Unable to find suitable version for angular

We see the same behaviour when a download fails (which happens sometimes in our project due to proxy shenanigans).

19:42:57 [INFO] [19:42:57] 'bower' errored after 37 s Failed to execute "git ls-remote --tags --heads https://github.com/angular/bower-angular-touch.git", exit code of #128

It might be that frontend-maven-plugin does not correctly check the error code returned by bower.

					<execution>
						<id>gulp bower</id>
						<goals>
							<goal>gulp</goal>
						</goals>
						<configuration>
							<arguments>bower</arguments>
						</configuration>
					</execution>

**Comment by eirslett** [comment]
It does check the error code; which error code does gulp return if you run it in the command line?

**Comment by NBardelot** [comment]
I'm going to upgrade frontend-maven-plugin to the last stable version and debug the issue a bit. I'll keep info here.

**Comment by NBardelot** [comment]
When bower is configured with interactive: true, and we hit the "Unable to find suitable version for angular" bower does not return anything because it waits for an input, and gulp returns 0. Then maven continues as if there were no issue.

If interactive is set to false (batch mode, for Jenkins for example), then bower returns 1, and gulp returns 8.
