### ISSUE TITLE
unable to use plugin - maven 3.1.0 is not available

### ISSUE THREAD

**Issue by kartgk** [eirslett/frontend-maven-plugin#233]
Getting the following error - The plugin com.github.eirslett:frontend-maven-plugin:0.0.23 requires Maven version 3.1.0.   This version is not available in apache site. Tried 3.1.1 but didnt work. Please fix the compatibility issue.

**Comment by khmarbaise** [comment]
The release 3.1.0 is not [available directly](https://archive.apache.org/dist/maven/binaries/) cause you should use alway the last version of the appropriate release line which in this case is 3.1.1. If Release 3.1.1 does not work i would say this sounds like a bug...but the questions is what you mean by 'didn't work'...

**Comment by kartgk** [comment]
when i run 'mvn install' target on my application using 3.1.1 -- I still get 'The plugin com.github.eirslett:frontend-maven-plugin:0.0.23 requires Maven version 3.1.0.'

**Comment by khmarbaise** [comment]
Which Maven Version do you use? I assume you are using Maven 2.2.1 ?

**Comment by eirslett** [comment]
Try Maven 3.3.1?

**Comment by kartgk** [comment]
Tried maven 3.3.3.  still get 'The plugin com.github.eirslett:frontend-maven-plugin:0.0.23 requires Maven version 3.1.0.'

**Comment by eirslett** [comment]
Have you configured Maven to enforce the version somehow?
https://ci.appveyor.com/project/eirslett/frontend-maven-plugin
You can see that the build log here shows it's running Maven 3.2.5, just fine. I've never come across any other developers with the same problem...

**Comment by khmarbaise** [comment]
Can you please post the full output of your problem...starting with the line `mvn clean package`...

**Comment by lukeruth** [comment]
I had this issue originally because I was running it through Eclipse which has an older version of Maven as an embedded installation, even though my machine environment had a newer one. If you're using an IDE I would check to see if it's referencing the correct version of Maven. I've had no trouble with the latest.

**Comment by tknerr** [comment]
@eirslett btw does an earlier version of the your plugin owrk with Maven 3.0.5?

For some reason we are forced to Maven 3.0.5 for the moment and upgrading to 3.1.0 would be a major PITA. Still I would love to use your plugin :-)

**Comment by eirslett** [comment]
I believe it should work with version 0.0.18 or so, if you look at the commit log you can find stuff about SLF4J, everything before that could maybe work. (But I'm not sure)

**Comment by tknerr** [comment]
@eirslett thanks for the quick response. I switched back to v0.0.22 of the plugin which does not *check* for the Maven 3.1 prerequisite.

So far it seems to work well with maven 3.0.5, but maybe I just haven't hit the critical code path where it breaks...

**Comment by richardliechty** [comment]
I can confirm as well that v0.0.22 works with Maven 3.0.5.  Thanks @tknerr!

@eirslett Was there a substantial benefit in switching to use slf4j logging (v0.0.23)?  That is what forced the 3.1 prerequisite.  There are some of us that are still stuck at 3.0.5 because of organizational standards.

**Comment by eirslett** [comment]
The reason for using slf4j (instead of the native Maven logger) is that it is possible to reuse frontend-plugin-core in other build tools (gradle, sbt). Slf4j is also the standard for logging from Maven plugins, in newer versions.

**Comment by gilkerley** [comment]
I was baffled by the failure on the Maven 3.1.0 requirement, since I have a later version.
Then found that my version of the IntelliJ IDE comes bundled with an older version of Maven.  
IntelliJ allows the selection of a local installation, am good now.  

Thanks @lukeruth for noting that an IDE can do this.

**Comment by rafaeleyng** [comment]
Same problem here, IntelliJ was using Maven 3.0.5.
Changed to 3.3.3 (installed with Homebrew) and worked.

**Comment by lukeruth** [comment]
@gilkerley - Glad I could help!

**Comment by mickem** [comment]
Just thought I'd add we have several custom maven plugins running on maven 3.0.5 which all use SLF4J so not sure you actually need newer maven for that reason...

**Comment by eirslett** [comment]
@mickem Do these plugins bundle SLF4J? frontend-maven-plugin assumes that Maven provides it.

**Comment by mickem** [comment]
We are using com.googlecode.slf4j-maven-plugin-log if thats what you mean:


```
	<dependencies>
		<!-- REDACTED -->
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>1.7.5</version>
		</dependency>
		<dependency>
			<groupId>com.googlecode.slf4j-maven-plugin-log</groupId>
			<artifactId>slf4j-maven-plugin-log</artifactId>
			<version>1.0.0</version>
		</dependency>
		<dependency>
			<groupId>org.apache.maven</groupId>
			<artifactId>maven-plugin-api</artifactId>
			<version>${maven.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.maven</groupId>
			<artifactId>maven-core</artifactId>
			<version>${maven.version}</version>
		</dependency>
	</dependencies>
```

**Comment by Salman9545** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.securehops</groupId>
	<artifactId>dot</artifactId>
	<version>1.0</version>
	<packaging>jar</packaging>

	<name>dot</name>
	<description>DoTell Web App</description>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.5.2.RELEASE</version>
		<relativePath/> 
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-rest</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>org.thymeleaf.extras</groupId>
			<artifactId>thymeleaf-extras-springsecurity4</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-thymeleaf</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-websocket</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
		</dependency>
		<dependency>
	        <groupId>com.fasterxml.jackson.datatype</groupId>
	        <artifactId>jackson-datatype-jsr310</artifactId>
	    </dependency>	
	    
		<dependency>
		    <groupId>com.fasterxml.jackson.core</groupId>
		    <artifactId>jackson-databind</artifactId>
		</dependency>
	    <dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-tomcat</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.4</version>
		</dependency>
		<dependency>
		    <groupId>org.thymeleaf.extras</groupId>
		    <artifactId>thymeleaf-extras-java8time</artifactId>
		</dependency>
        
         
	 <dependency>
	  <groupId>org.springframework</groupId>
	  <artifactId>spring-beans</artifactId>
	  <type>jar</type>
          <version>4.3.7.RELEASE</version>
	 </dependency>
         
         <dependency>
        <groupId>joda-time</groupId>
        <artifactId>joda-time</artifactId>
        <version>2.9.1</version>
         </dependency>
	 <dependency>
	  <groupId>org.eclipse.persistence</groupId>
	  <artifactId>eclipselink</artifactId>
	  <version>2.5.2</version>
	 </dependency>
	 <dependency>
	  <groupId>org.eclipse.persistence</groupId>
	  <artifactId>org.eclipse.persistence.jpa.modelgen.processor</artifactId>
	  <version>2.5.2</version>
	  <scope>provided</scope>
	 </dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
                        
			<plugin>
				<groupId>com.github.eirslett</groupId>
				<artifactId>frontend-maven-plugin</artifactId>
                                <version>1.2</version>
				<configuration>
					<installDirectory>target</installDirectory>
				</configuration>
				<executions>
					<execution>
						<id>install node and npm</id>
						<goals>
							<goal>install-node-and-npm</goal>
						</goals>
						<configuration>
							<nodeVersion>v4.4.5</nodeVersion>
							<npmVersion>3.9.2</npmVersion>
						</configuration>
					</execution>
					<execution>
						<id>npm install</id>
						<goals>
							<goal>npm</goal>
						</goals>
						<configuration>
							<arguments>install</arguments>
						</configuration>
					</execution>
                                        
                                      
                                
                                </executions>
			</plugin>
		</plugins>
	</build>


</project>
Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.2:install-node-and-npm (install node and npm) on project dot: The plugin com.github.eirslett:frontend-maven-plugin:1.2 requires Maven version 3.1.0 -> [Help 1]
i use netbeans 8.0.2 jdk 8 mvn 3.1.0 but this error occour

**Comment by eirslett** [comment]
Maybe NetBeans uses its own, different maven version which is older than 3.1.0?

**Comment by Salman9545** [comment]
<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.5.2.RELEASE</version>
		<relativePath/> 
                
                
	</parent>
i use maven 3.1.0 and org.springframework.boot version is 1.5.2.

**Comment by eirslett** [comment]
Try running this without NetBeans, only in the terminal?

**Comment by Salman9545** [comment]
how i can run without netbeans plz tell me
