### ISSUE TITLE
Install NodeJS in specified folder

### ISSUE THREAD

**Issue by operatino** [eirslett/frontend-maven-plugin#241]
Hi,

First of all, thanks for the really useful maven plugin, as a Front-end developer in Java project, I really appreciate it.

Feature request: allow to define folder to install node and npm during maven build. Downloading node from scratch on each `mvn clean install` is painful and takes a lot of time.

In my prev team, we were doing our own integration into ANT, and there we chose to install Node in `$HOME/node`. Different version control also possible by folder names.

**Comment by eirslett** [comment]
This was recently added as a feature, check the pull request log. It's not documented yet.
But by default, node isn't downloaded from scratch (unless you set it up that way). It downloads into the "node" folder of your project. So it should be cached, unless you download your code base from scratch for every build.
