### ISSUE TITLE
Use the installed node version

### ISSUE THREAD

**Issue by rbatllet** [eirslett/frontend-maven-plugin#243]
Why install node if we have it in our system?.It's a nonsense.

Please, add the option to use the default node version.

**Comment by AlbanAndrieu** [comment]
I have the following issue: plugin is installing a specific version of npm and node but in fact it does not seem to use it.
It seems to use the one installed on the server instead.
Is it possible to force the plugin to use the one installed by the maven plugin?

**Comment by eirslett** [comment]
@rbatllet If you want to use the node.js binary installed on the system, use maven-exec-plugin instead, [like this](http://addyosmani.com/blog/making-maven-grunt/). frontend-maven-plugin is not designed for that use-case. (there are some closed issues about this topic already, in the GitHub issue history)

@AlbanAndrieu calling npm from npm (npmception) has lead to some problems like this before. The solution that works (most often) is to copy [the npm helper script](https://github.com/eirslett/frontend-maven-plugin/blob/master/frontend-maven-plugin/src/it/example%20project/helper-scripts/npm) into the root directory of your frontend execution, the same directory as your package.json.

**Comment by AlbanAndrieu** [comment]
Thanks a lot for giving me the right answer.

Solution is:
  "scripts": {
    "preinstall": "node/node node/npm/bin/npm-cli.js link components/*"
  }
is working both on unix and windows

"scripts": {
"preinstall": "./npm link components/*"
}
was not working on windows (./npm instead of npm using the npm helper script)

**Comment by eirslett** [comment]
Yup, your version works!
(For windows, there's also a script called npm.cmd, but I don't think you can use that in the npmception context)

**Comment by AlbanAndrieu** [comment]
Yep thanks, on windows developers are using mingw, so I cannot use this script.
But it is working with cmd. I get the fix from your script... Thanks again

**Comment by nobodyman** [comment]
@eirslett +1 for the  maven-exec-plugin suggestion. We like the front-end plugin because it minimizes our build pre-requisites, but it'd be nice if I could set up an activation profile so that we use it only if 'npm' isn't found in the path.  In your opinion does that sound like a reasonable idea, or am I over-thinking this?

**Comment by eirslett** [comment]
npm isn't huge, it's only like 8 MB. Your hard disk won't crash from having another copy of it lying around :wink:
