### ISSUE TITLE
Global node version used during "npm install"

### ISSUE THREAD

**Issue by Athou** [eirslett/frontend-maven-plugin#250]
Hi,

I'm using gulp-sass in CommaFeed, which depends on node-sass.
node-sass has an install script (which is run during `npm install`) and it seems that the node version used by the script is the globally available one instead of the one downloaded by frontend-maven-plugin.

    [INFO] Running 'npm install --color=false' in /home/athou/commafeed
    [INFO]
    [INFO] > node-sass@3.2.0 install /home/athou/commafeed/node_modules/gulp-sass/node_modules/node-sass
    [INFO] > node scripts/install.js

This causes issues because when gulp runs (with the local node version), node-sass does not find the binary downloaded during the npm install phase.

See also the issue here: https://github.com/Athou/commafeed/issues/747

Do you have any idea on how to fix this?

Thanks!

**Comment by Athou** [comment]
I just built https://github.com/eirslett/frontend-maven-plugin/pull/249 and it seems to fix the issue.

**Comment by jorismeijer** [comment]
I have the exact same problem and it would be great to have this fix integrated. Any plans on doing so?

**Comment by Athou** [comment]
Thanks for the merge!
Do you plan to release a new version soon?

**Comment by hypery2k** [comment]
any update for a new version?
