### ISSUE TITLE
bower install fails

### ISSUE THREAD

**Issue by amitmawkin** [eirslett/frontend-maven-plugin#253]
Getting below error when I run a build
[INFO] --- frontend-maven-plugin:0.0.23:bower (bower install) @ UI ---
[INFO] Running 'bower install' in /Users/abcde/UI
[ERROR] module.js:338
[ERROR]     throw err;
[ERROR]           ^
[ERROR] Error: Cannot find module '/Users/abcde/UI/node_modules/bower/bin/bower'
[ERROR]     at Function.Module._resolveFilename (module.js:336:15)
[ERROR]     at Function.Module._load (module.js:278:25)
[ERROR]     at Function.Module.runMain (module.js:501:10)
[ERROR]     at startup (node.js:129:16)
[ERROR]     at node.js:814:3

**Comment by ccit-spence** [comment]
Is Bower included in your `package.json`?

**Comment by amitmawkin** [comment]
closing this issue , you were correct package.json was missing bower.
