### ISSUE TITLE
"etc" dir created under working dir when running "npm install"

### ISSUE THREAD

**Issue by choonchernlim** [eirslett/frontend-maven-plugin#254]
I have this configuration:-

```xml
<plugin>
    <groupId>com.github.eirslett</groupId>
    <artifactId>frontend-maven-plugin</artifactId>
    <version>0.0.24</version>
    <configuration>
        <workingDirectory>src/main/frontend</workingDirectory>
        <installDirectory>src/main/frontend</installDirectory>
    </configuration>
    <executions>
        <execution>
            <id>install-node-and-npm</id>
            <goals>
                <goal>install-node-and-npm</goal>
            </goals>
            <configuration>
                <nodeVersion>v0.12.7</nodeVersion>
                <npmVersion>2.13.2</npmVersion>
            </configuration>
        </execution>
        <execution>
            <id>npm-install</id>
            <goals>
                <goal>npm</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```
When I run `mvn clean test`, an empty `etc` dir is always created in my working dir... and it appears it's coming from `npm-install` execution. 

See attached screenshot. Thank you.

![screen_shot_2015-07-29_at_7_45_21_am](https://cloud.githubusercontent.com/assets/6835135/8957774/4d587a98-35c6-11e5-9e6d-d08f8005c580.png)

**Comment by eirslett** [comment]
Hmm... does it come from one of the dependencies in package.json? Some of them might have a strange postinstall script.

**Comment by choonchernlim** [comment]
I wiped my `package.json` to just this:-

```xml
{
  "name": "choonchernlim-archetype-webapp",
  "private": true,
  "devDependencies": {
  }
}
```
... and it still creates that `etc` folder. I want to say I didn't recall seeing that in the past, and that it only starts appearing after I decided to move `node/` and `node_modules/` into my custom working directory... but I may not paid much attention in the past too. :)

**Comment by eirslett** [comment]
What happens if you either
1) leave out the NPM run from pom.xml
or
2) Run npm from the command line in that directory?

**Comment by choonchernlim** [comment]
If I commented out `npm-install` execution OR manually run `npm install` from command line in that directory, that `etc` dir is not created.

**Comment by choonchernlim** [comment]
Okay, I did some "brute force" experimentation... it appears npm v2.6.0 or later introduced that `etc` dir. When I went with v2.5.0, it wasn't there. Is this something you are able to replicate on your end too?

I can't find any info regarding the use of `etc` dir from npm site... not sure if it's needed at all.

**Comment by klieber** [comment]
The etc directory is created by npm when `npm install` is executed. The frontend-maven-plugin is not the cause so this should be closed and any questions about the etc directory should be sent to the npm team.
