### ISSUE TITLE
Error: Can't find Python executable "python", you can set the PYTHON env variable.

### ISSUE THREAD

**Issue by atais** [eirslett/frontend-maven-plugin#255]
Hello so my friend today tried to run our project on his Windows machine, and fortunately the message is clear, but could you please include this in the README, that python IS necessary for the library to work?

It would be recommended to test also if both Python2 and 3 are supported. Thanks!

<pre lang="javascript"><code>
[ERROR] gyp ERR! configure error 
[ERROR] gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
[ERROR] gyp ERR! stack     at failNoPython (C:\Users\project\node\npm\node_modules\node-gyp\lib\configure.js:103:14)
[ERROR] gyp ERR! stack     at C:\Users\project\node\npm\node_modules\node-gyp\lib\configure.js:64:11
[ERROR] gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
[ERROR] gyp ERR! System Windows_NT 6.3.9600
[ERROR] gyp ERR! command "node" "C:\Users\project\node\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
[ERROR] gyp ERR! cwd C:\Users\project\node_modules\grunt-browser-sync\node_modules\browser-sync\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil
[ERROR] gyp ERR! node -v v0.12.5
[ERROR] gyp ERR! node-gyp -v v1.0.3
[ERROR] gyp ERR! not ok
</code></pre>

**Comment by eirslett** [comment]
This is a problem with a particular npm package you're using, that requires python to build. (You can see it from the node-gyp stuff, node-gyp is the compiler)
Try running npm install from the command line, do you get the same message?

**Comment by aikrez** [comment]
I had the same issue with BrowserSync and you need to install Python 2.x (currently 2.7.10) not 3.x

**Comment by eirslett** [comment]
Then I guess BrowserSync is the problem here.
