### ISSUE TITLE
npm EACES error running npm install

### ISSUE THREAD

**Issue by fcalfoeworld** [eirslett/frontend-maven-plugin#256]
I suddenly started encountering this error after restarting my Jenkins server which runs my Maven script that includes the frontend-maven-plugin

Why is npm install attempting to install the package globally when package.json specifies local install?

[INFO] Installed node locally.
[INFO] Installing npm version 2.3.0
[INFO] Installed NPM locally.
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.22:npm (npm install) 

[ERROR] npm ERR! node v0.10.36
[ERROR] npm ERR! npm  v2.3.0
[ERROR] npm ERR! path /root/.npm/grunt-contrib-concat/0.5.1/package
[ERROR] npm ERR! code EACCES
[ERROR] npm ERR! errno 3
[ERROR] 
[ERROR] npm ERR! Error: EACCES, mkdir '/root/.npm/grunt-contrib-concat/0.5.1/package'

**Comment by okadri** [comment]
Same here.. No changes were made to the plugin config!

**Comment by eirslett** [comment]
I've never seen that error before... :-/
What happens if you run the npm command manually from the command line, instead of from the plugin?

**Comment by ccit-spence** [comment]
I did experience something like this with Atlassian Bamboo.  We use elastic agents so I have an agent that it is installed globally on.  Could not figure out a way to get around installing globally.  Didn't spend much time looking since it was easy to have a specific agent handle the build.

**Comment by fcalfoeworld** [comment]
I resolved my issue - looks like it was all environmental

My maven build script was being run through the Jenkins server

The etc script that started Jenkins did not reset the HOME env variable

So that led npm to attempt to install modules into the root home dir

Once Jenkins was running with the proper environment then the plugin worked like a charm  (it has been working on local development workstations just fine)

Thanks!
