### ISSUE TITLE
Issue with angular-bootstrap 0.12.2 - $injector.modulerr error

### ISSUE THREAD

**Issue by mavlesreennap** [eirslett/frontend-maven-plugin#258]
Thanks for the plugin.
I have below the pom.xml
<groupId>com.github.eirslett</groupId>
						<artifactId>frontend-maven-plugin</artifactId>
						<version>0.0.14</version>
						<executions>
							<execution>
								<id>install node and npm</id>
								<goals>
									<goal>install-node-and-npm</goal>
								</goals>
								<phase>generate-resources</phase>
								<configuration>
									<nodeVersion>v0.10.26</nodeVersion>
									<npmVersion>1.4.3</npmVersion>
								</configuration>
							</execution>
							<execution>
								<id>npm install</id>
								<goals>
									<goal>npm</goal>
								</goals>
								<phase>generate-resources</phase>
							</execution>
							<execution>
								<id>gulp build</id>
								<goals>
									<goal>gulp</goal>
								</goals>
								<phase>generate-resources</phase>
							</execution>
						</executions>
when npm version is downloaded, it is downloading angular-bootstrap version 0.12.2.

Previously, angular-bootstrap 0.12.0 was downloaded. It was working fine
But with version 0.12.2, $injector.modulerr error occurs when launching the screen.

Tried to download 0.12.0 by using below package.son information. But the version is unavailable.

  "dependencies": {
    "angular": "~1.4",
    "angular-animate": "~1.4",
    "angular-bootstrap": "=0.12.0",
..
..
}  

Kindly, provide us solution on this. Thanks!

**Comment by eirslett** [comment]
Try to run gulp from the command line, without using Maven. Does that work? If not, it's a problem with the node stuff, not this plugin.

**Comment by eirslett** [comment]
I'll close due to inactivity.
