### ISSUE TITLE
Getting failure with install-node-and-npm goal

### ISSUE THREAD

**Issue by michelau** [eirslett/frontend-maven-plugin#26]
I'm hoping it's something simple.  I've gone through the guide a couple of times and I'm not finding what's wrong.  I also tried with 0.0.12 for the plugin, and some other pairs of Node/NPM versions from http://nodejs.org/dist.  Any ideas?

The error message is:

The parameters 'nodeVersion', 'npmVersion' for goal com.github.eirslett:frontend-maven-plugin:0.0.11:install-node-and-npm are missing or invalid

My pom.xml has this:

```
        <plugin>
            <groupId>com.github.eirslett</groupId>
            <artifactId>frontend-maven-plugin</artifactId>
            <version>0.0.11</version>
            <!-- optional -->
            <configuration>
                <workingDirectory>src/main/webapp/websrc</workingDirectory>
            </configuration>
            <executions>
                <execution>
                    <id>install node and npm</id>
                    <goals>
                        <goal>install-node-and-npm</goal>
                    </goals>
                    <configuration>
                        <nodeVersion>v0.10.18</nodeVersion>
                        <npmVersion>1.3.8</npmVersion>
                    </configuration>
                </execution>
            </executions>
        </plugin>
```

**Comment by arsalazarjr** [comment]
For whatever it is worth: seems like this might have to do with namespacing? I was able to get this to work by moving the configuration parameters 'nodeVersion' and 'npmVersion' into the *global* plugin parameters section.

**Comment by satyasreem** [comment]
I had to move the parameters to global configuration to fix this.
<plugin>
                	<groupId>com.github.eirslett</groupId>
	               	<artifactId>frontend-maven-plugin</artifactId>
	                <version>0.0.23</version>
	                <configuration>
	                 	<nodeVersion>v0.10.33</nodeVersion>
	                  	<npmVersion>1.4.21</npmVersion>
                	</configuration>
.......

**Comment by csvan** [comment]
People who are having issues with this, are you:

1) Using Windows?
2) Having a project with multiple related POMs?

**Comment by jpitt42** [comment]
I was definitely not on Windows.  I was on some version of MacOS when this happened.  I'm not on the project anymore, so I don't know if it's still an issue.

**Comment by csvan** [comment]
FWIW, I managed to resolve this by moving the configuration from the `execution` level to the `plugin` level.

**Comment by nsavageJVM** [comment]
same error 
oss ubuntu 16
<exe...><id>install node...</id>...<config....> <nodeVersion>v6.2.2</nodeVersion></con..></exe ..>
 ==>
<plugin>... <config ..> <nodeVersion>v6.2.2</nodeVersion></con..> and it works

**Comment by tom31459** [comment]
Just like @csvan and a couple others mentioned, move the configurations into the plugin level worked.

**Comment by SKrudra** [comment]
I faced the same issue. changed the version to 1.6, it worked.

**Comment by ryanthames** [comment]
I had the same issue in 1.6 with install-node-and-yarn - can confirm moving configuration to plugin level still works.

**Comment by JerzyPlocha** [comment]
I had the same issue in 1.6, moving one level up solved the issue.

**Comment by alessiostalla** [comment]
Same here. Windows with Maven launched from IntelliJ IDEA.

**Comment by glenhein** [comment]
FYI, I just had this problem. In my case, I had a parent pom that was defining frontend-maven-plugin and it was setting the node version. My downstream pom was not able to override the value set in the parent pom. I reworked the parent pom to fix the problem.

**Comment by victorManuelMarquez** [comment]
i try moving this:
<configuration>
	<nodeVersion>v8.11.1</nodeVersion>
	<npmVersion>5.6.0</npmVersion>
</configuration>
from execution tag to plugin tag, and it works!!.
PD: sorry my bad english.

**Comment by mibadim** [comment]
Same problem here. @victorManuelMarquez 's answer worked for me.
