### ISSUE TITLE
Publish a new version?

### ISSUE THREAD

**Issue by brianc** [eirslett/frontend-maven-plugin#261]
Hi -

I know how much work an open source project takes, and I want to let you know we __super__ appreciate the work you've put in here.  This maven plugin has allowed us to bring some rigor to our front-end by integrating with all the node tools the front-end team knows and loves.

Our issue is we're hitting a build error when compiling some native modules.  `npm` is invoked which in turn invokes `node-gyp` to compile the native modules which in turn invokes `node` again (:interrobang:) at some point.  At this point `node-gyp` fails because it can't find node on the path.  The specific error is:

```
[INFO] > contextify@0.1.14 install /var/lib/jenkins/jobs/<redacted>/workspace/<redacted>/src/main/webapp/node_modules/jsdom/node_modules/contextify
[INFO] > node-gyp rebuild
[INFO] 
[ERROR] /var/lib/jenkins/.m2/repository/node/npm/bin/node-gyp-bin/node-gyp: line 3: node: command not found
[ERROR] npm ERR! Linux 2.6.32-431.17.1.el6.x86_64
[ERROR] npm ERR! argv "/var/lib/jenkins/.m2/repository/node/node" "/var/lib/jenkins/.m2/repository/node/npm/bin/npm-cli.js" "install" "--color=false"
[ERROR] npm ERR! node v0.12.1
[ERROR] npm ERR! npm  v2.7.1
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] 
[ERROR] npm ERR! contextify@0.1.14 install: `node-gyp rebuild`
[ERROR] npm ERR! Exit status 127
[ERROR] npm ERR! 
```

We've configured this lovely plugin to install node into `~/.m2/repository/node` so it doesn't install over and over again on jenkins or install into the `src` directory. 

I see you merged [this pull request](https://github.com/eirslett/frontend-maven-plugin/commit/0410ccab83f808d026561e18b4bb5b4b1ad1694e) recently to append the node install folder to the `$PATH` variable so things have access to it when executing...do you think that would fix the issue and if so...would you be able to push a new version of this plugin out with that fix?  I'm trying to come up with jerry-rig ways to patch the Jenkins environment to append the node path directly, but I'm thinking this patch would probably solve our issue?  

Sorry to bug you to publish a new version - I know how time consuming it can be, espesh when you're already super busy with other things...but I just wanted to check in. :smile:

**Comment by eirslett** [comment]
Ok, sorry to be so late! Now I finally released a new version!
