### ISSUE TITLE
Linux build fails

### ISSUE THREAD

**Issue by eirslett** [eirslett/frontend-maven-plugin#262]
Does anybody with more Jenkins experience know why?

**Comment by Athou** [comment]
I guess they upgraded maven to 3.3 which requires java7
See https://cloudbees.zendesk.com/hc/en-us/articles/205311740-A-Maven-build-is-failing-with-ERROR-Failed-to-parse-POMs-Unsupported-major-minor-version-51-0-

**Comment by KostyaSha** [comment]
Where it fails?

**Comment by eirslett** [comment]
It only failed on CloudBees. I changed their java version to 7, that fixed it.
