### ISSUE TITLE
Remove node_modules with "mvn clean"

### ISSUE THREAD

**Issue by mriehema** [eirslett/frontend-maven-plugin#263]
This is a feature request.

We have an issue with this plugin caused by wrong binary files in node-sass. Running "npm install" or "npm install --force" with this plugin will not reinstall existing modules, even if they are uncomplete or broken (not a bug of this plugin, caused by npm). So we don't have any option to remove node_modules to get a clean install during build steps. Only "rm -rf node_modules" fixes this.

If this plugin could delete the folder node_modules during mavens "clean" lifecycle phase would be awesome.

mvn install = call all executions of this plugin
mvn clean = delete node_modules folder
mvn clean install =delete node_modules folder before calling all executions.

**Comment by klieber** [comment]
You can configure maven to do this yourself: http://maven.apache.org/plugins/maven-clean-plugin/examples/delete_additional_files.html

**Comment by mriehema** [comment]
Thanks for this info!

**Comment by mindhells** [comment]
In my case I found more usefull not to include these files into the final package:

`<plugin>
		        <artifactId>maven-war-plugin</artifactId>
		        <version>3.2.0</version>
		        <configuration>
		          <packagingExcludes>angular/</packagingExcludes>
		        </configuration>
		     </plugin>`

In my case I'm writing an angular 4 application and I've configured building process with angular cli to be outside of the sources folder so at the end the sources are not needed when deploying
