### ISSUE TITLE
Bower and Artifactory Integration Not Working

### ISSUE THREAD

**Issue by qazwart** [eirslett/frontend-maven-plugin#265]
We use [Artifactory] by JFrog as our Maven repository. Since version 3.7 and 4.x, Artifactory has the ability to act like a Bower packages repository. This is good for us because we no longer have to define a proxy and we can retrieve Bower packages from our local Artifactory cache rather than going out over the Internet.

Unfortunately, The frontend-maven-plugin does not seem compatible with Artifactory. According to the [Artifactory documentation], you now have a package dependency upon [bower-art-resolver], and [bower-art][bower-art-resolver]. Then you have to use the [bower-art] instead of `bower` as the command line program.

I don't care too much about the package dependency issue. I can fix that in my `package.json` file. The problem is that I have no way of allowing your frontend-maven-plugin to execute `bower-art` rather than `bower`. As far as I can tell, the `bower` goal is tied directly to the `bower` executable inside the `node_modules` packages.

It would be nice to have a way to _override_ the executable for this particular goal, or to have another goal that allows us to specify whatever executable we want. Something like this:

     <goal>execute</goal>
     <configuration>
           <executable>bower-art</executable>
           <arguments>--verbose --no-color</arguments>
    </configuration>

Thanks,

[Artifactory]: http://www.jfrog.com/artifactory/
[Artifactory documentation]: http://www.jfrog.com/confluence/display/RTF/Bower+Repositories
[bower-art-resolver]: https://github.com/JFrogDev/bower-art-resolver. 
[bower-art]: http://www.jfrog.com/confluence/display/RTF/Bower+Repositories#BowerRepositories-UsingtheBowerCommandLine

**Comment by eirslett** [comment]
Looks like there's an inflation of node CLI tools... yes, bower is tied directly to the bower executable. We could add yet another goal for bower-art, but I suspect a better solution would be to rewrite/simplify/generify the whole plugin.
What you can do, for now, is to use npm run-script in order to run bower-art. So you use the npm goal of this plugin.

**Comment by pgarciafc** [comment]
Any plan to implement the suggested feature ?

Using npm run-script is not as clean as being able to change the executable name.

Thanks.

**Comment by eirslett** [comment]
I think this is such an edge-case that it's fine to run as npm run-script, but if more users request it, we can reconsider.
