### ISSUE TITLE
Node is not installed in working directory. 

### ISSUE THREAD

**Issue by msieurtoph** [eirslett/frontend-maven-plugin#268]
Hi,

The node is installed to the root of the project, near the pom.xml. 
I used to use version 0.0.17 and node was installed in the working directory, which was great. It seems to be a minor regression (imply to add node to .gitignore, ... )

**Comment by eirslett** [comment]
The way it's supposed to be (by default) is that node ends up inside a "node" folder in the working directory. Did that change?

**Comment by msieurtoph** [comment]
Yep
Now, the node folder is near the folders src/ or target/ ... at the root of the project.

**Comment by eirslett** [comment]
That's where it has always been... or maybe you had it in src/main/frontend and then src/main/frontend/node or something like that?

**Comment by msieurtoph** [comment]
It is strange.

For the tag `<workingDirectory>src/main/frontend</workingDirectory>`.

When I use 0.0.17 version, `node/` and `node_modules/` folders are in `./src/main/frontend/`.

When I use the 0.0.25 version, `node/` is created in  `./` and `node_modules/` is still in `src/main/frontend/`.

It is probably no big deal, but same behaviour is expected between the 0.0.x versions.

**Comment by eirslett** [comment]
Aah, I guess we didn't test for that... @klieber do you think this is related to your PR about installDirectory? Maybe working directory != install directory now?

**Comment by klieber** [comment]
Yeah those two directories are independent of each other now.  I suppose we could make a change so that the install directory defaults to the working directory if the install directory is not specified.  I can make that change if you want, just let me know.

**Comment by msieurtoph** [comment]
You mean I must add `<installDirectory>src/main/frontend</installDirectory>` to the plugin configuration ?
It sounds good to me, but it was not specified in the README.md ... (I can PR this point if it can help)

Your solution looks good to me too: making install directory default to working one if not specified.

**Comment by eirslett** [comment]
Yes, that would be nice!
