### ISSUE TITLE
Feature request: Cache the downloaded installer

### ISSUE THREAD

**Issue by jbyler** [eirslett/frontend-maven-plugin#27]
It would be great if the plugin could cache the downloaded node installer in one location, and install it to another location (under target, or in a configurable place; see #18).  That way you can install into target and get a fresh, virgin installation every time you do "mvn clean", but you don't have to re-download from a remote internet host on every build.  This is the approach used by the [cargo plugin](http://cargo.codehaus.org/Maven2+plugin).

**Comment by cowwoc** [comment]
@eirslett This library is a very important part the hobby projects I am working on but, like you, I don't have time to work on it full-time. I looked around and there aren't really any good alternative libraries.

I understand that you are currently focused exclusively on PRs but I think we can both agree that the project would be in a healthier place if we found at least one co-developer to help out.

Perhaps you could post a notice in README.md: "Looking for someone to take over / help with this project. Contact X if you're willing to help". I've seen other Github projects do something similar. With the amount of interest in this project, I am hoping that someone will step up.

**Comment by eirslett** [comment]
Yes, it could definitely use some more love. But I'm concerned that it will evolve into bloatware - even more difficult to maintain than it already is. The plugin already works for most people, the cases you typically see in PRs are mostly edge cases. It's a real challenge to try and limit the scope of the plugin and at the same time please as many developers as possible. (You cannot have both) It's also becoming a challenge just to keep the code organised as people are adding more features...

**Comment by tfennelly** [comment]
@eirslett correct me if I'm wrong, but this is only an issue in a clean environment, right? I checked this and, for me, it only downloads the installer if there isn't already a local copy of node. It does not download every time !!

Imo this is fine for dev, but I do appreciate that it might be a bit of an issue (I really think people are exagerating the significance though) for automated builds that have a env on every run.

**Comment by eirslett** [comment]
Yes, it's only an issue for the first, clean build, the downloaded binary is cached inside the project itself. Downloading node adds ~15 seconds to the build, I think, depending on the download speed. Some people intentionally delete the node executable just to get a 100 % clean build every time, that means they won't get the benefit of a cached binary (unless it's cached somewhere else)

**Comment by cowwoc** [comment]
@eirslett Perhaps it's worth splitting the plugin into multiple pieces then? One for installing node/io.js. Then separate plugins for grunt, gulp, karma, etc.

**Comment by fixpunkt** [comment]
A workaround might be to zip the node directory and install it into your nexus, then use maven-dependency-plugin to fetch and unzip it into your project root before frontend-maven-plugin runs. Just an idea.

**Comment by andyp1per** [comment]
One of the reasons people want to download the install is because they have developers on both windows and unix. So checking in the binaries is not an option. Similarly populating a cache is a lot of make work - nexus doesn't support this well and the burden is then on keeping the cache up to date. A better solution would be to do what npm does - keep a cache of the downloads somwhere and use those in preference to a full download. For bonus points make the initial download populate the location specified by nodeDownloadRoot.

**Comment by cowwoc** [comment]
@andyp1per "So checking in the binaries is not an option" is not strictly true. You can public the binaries with different `classifier` values. That's what it's there for.

That said, I think we should keep such artifacts out of central if we can (we need a local cache, not a global one).
