### ISSUE TITLE
Add the ability to disabling proxy settings for npm 

### ISSUE THREAD

**Issue by jkieley** [eirslett/frontend-maven-plugin#271]
We would like to proxy the download of npm and node, but not the npm install. Can we add a flag to disable passing the proxy settings to npm?

**Comment by eirslett** [comment]
No, unfortunately there's no way to disable proxy settings only for npm.

**Comment by jkieley** [comment]
in the maven proxy settings, there is a nonProxyHosts exclusions list, this list is not being honored when the proxy settings are passed to npm. Would it help if we looked at this as more of a bug? As the Maven proxy settings not being honored?
```
<settings>
  ...
  	<proxy>
  		<host>ourproxy.com</host>
  		<username>...</username>
  		<password>...</password>
  		<port>...</port>
  		<nonProxyHosts>registry.npmjs.org</nonProxyHosts>
  	</proxy>
  ...
</settings>
```

**Comment by drautureau** [comment]
+1, I am using a proxy (with a cache) to download at least the NodeJS distribution and have an internal mirror of the NPM registry (using Nexus or Artifactory) so honoring nonProxyHosts would definitively fix it.

**Comment by mgaunin-axway** [comment]
+1 (same use-case than @drautureau)

**Comment by drautureau** [comment]
FYI, bcd8a7883703e28e3c5346e1f34c64332994e442 started to fix this issue:
```
[INFO] Installing npm version 2.7.6
[INFO] Downloading NPM from http://***/content/repositories/npmjs/npm/-/npm-2.7.6.tgz to /home/cijenka/builder11/workspace/accountingintegrator-rulestudio-app_david/web/npm.tar.gz
[INFO] Could not find matching proxy for protocol http
[INFO] No proxy was configured, downloading directly
[INFO] Extracting NPM files in node/
[INFO] Unpacking /home/cijenka/builder11/workspace/accountingintegrator-rulestudio-app_david/web/npm.tar.gz into /home/cijenka/builder11/workspace/accountingintegrator-rulestudio-app_david/web/node/node_modules
[INFO] Installed NPM locally.
```

**Comment by drautureau** [comment]
BTW, npm install still use the --proxy or https-proxy parameter.
I am closed to finish some code modification to fix it and will do a PR soon!
