### ISSUE TITLE
Call default/global node

### ISSUE THREAD

**Issue by jeremychone** [eirslett/frontend-maven-plugin#273]
I know it might be at odd with the whole purpose of the plugins, but in our case, we would like to use the global node install and not use the node install at all (our developers will have to install node before). 

So, I would like use this plugin to call gulp and such, but since I do not have ```node/node``` in the project, I get: 

```
 Failed to run task: 'gulp default --no-color' failed. java.io.IOException: Cannot run program "/Users/jeremychone/_jeremy/_projects/projectmvc/projectmvc_mvnsrc/node/node"
```

Anyway I can configure this plugin to use the global node?

**Comment by eirslett** [comment]
No, you'll have to use maven-exec-plugin for that: [Making Maven Grunt](http://addyosmani.com/blog/making-maven-grunt/), just replace "grunt" with "gulp".
