### ISSUE TITLE
Can't download Node v4.0.0 because the URL has changed

### ISSUE THREAD

**Issue by gymb321** [eirslett/frontend-maven-plugin#276]
This plugin breaks when trying to download Node v4.0.0. The url to download Node has changed. Previously it was:
http://nodejs.org/dist/v0.12.2/node.exe
http://nodejs.org/dist/v0.12.2/x64/node.exe

Now it is:
http://nodejs.org/dist/v4.0.0/win-x86/node.exe
http://nodejs.org/dist/v4.0.0/win-x64/node.exe

**Comment by yoshaul** [comment]
Older downloads are also broken. For example:
`Downloading Node.js from http://nodejs.org/dist/v0.12.3/node-v0.12.3-linux-x64.tar.gz`

**Comment by dnavre** [comment]
Receiving error: 

`Could not extract the Node archive: Could not extract archive: 'XXX/node_tmp/node.tar.gz': Input is not in the .gz format`

**Comment by dnavre** [comment]
They have changed only the http version of the distribution folder. It's now redirecting to their blog for some reason. the https version continues working fine. So a workaround is to add these lines to your pom.xml:

`<nodeDownloadRoot>https://nodejs.org/dist/</nodeDownloadRoot>`
