### ISSUE TITLE
Using an existing node installation

### ISSUE THREAD

**Issue by pussmun-12** [eirslett/frontend-maven-plugin#277]
Hi Eirik,

What would be the best way to use this plugin with an existing node installation?
Also, does this plugin help with deploying an artifact to a remote repository?

/best regards, Håkan Gleissman from Sweden

**Comment by pussmun-12** [comment]
Clarification - I'm offline and I have downloaded node and npm packages on my offline computer. I would like to use your plugin to execute a deploy of a frontent artifact to a remote repository using the existing installation. I am using gulp, so I would like to just be able to use the globally installed gulp module.

**Comment by Sabartius** [comment]
As a workaround you could use symbolic links to node and npm-cli.js. The plugin expects node to be under the path node/ and a npm-cli.js to be under the path node/node_modules/npm/bin/ in your working directory.

**Comment by eirslett** [comment]
No, it's not possible to use the global version of Node. But disk space is cheap,and node.js is just a couple of mb. If you really need to use the global one, you should use maven-exec-plugin.

**Comment by arianitu** [comment]
Why is there no option to use a global version of Node? A couple MB is extra time on the build that I don't want.

**Comment by eirslett** [comment]
It will only download node the first time you run the build - on incremental builds, it will use the cached version.

**Comment by Matmo10** [comment]
@eirslett Just to play devil's advocate here - I'm using this on a build that runs on a jenkins job. The job wipes the workspace inbetween builds. Between downloading node+npm+gulp+gulp/npm dependencies, the time really starts to add up across builds. I'd really like to move the node/npm/npm dependencies into a global location on my jenkins machine so that I don't have to needlessly redownload those things every time I run a build. 

Could you maybe point me in the right direction if I wanted to make these changes myself?

**Comment by eirslett** [comment]
You can download things from nodejs.org into /var/cache/nodejs on the jenkins server (replicate the online directory structure) and then, in the plugin, set nodeDownloadRoot to file:///var/cache/nodejs. (Maybe with a maven profile, so that only Jenkins runs with that profile, not developers)

**Comment by Matmo10** [comment]
Thanks, I will give that a shot. Is there somewhere I can view the online directory structure to make sure mine is setup correctly? Would it be enough to just copy the installation that a normal run of the plugin downloads?

**Comment by eirslett** [comment]
http://nodejs.org/dist/

**Comment by Matmo10** [comment]
Thanks, I've got that taken care of now. But now my package.json is inside my repo, while node and npm are outside of my repo, and it seems that npm needs package.json in the same <workingDirectory>. If you don't have any suggestions for that, I suppose I'll go the maven-exec-plugin route.

**Comment by eirslett** [comment]
What does your pom.xml/plugin configuration look like? If you only set `<nodeDownloadRoot>`, it's supposed to use package.json from your repo.

**Comment by Matmo10** [comment]
Top level config:

       <configuration>
                    <workingDirectory>/external/place/whereI/put/node</workingDirectory>
       </configuration>


install node and npm config:
        <configuration>
                            <nodeDownloadRoot>file:///path/to/node.tar.gz</nodeDownloadRoot>
                            <npmDownloadRoot>file:///path/to/npm.tar.gz</npmDownloadRoot>
                            <nodeVersion>v5.3.0</nodeVersion>
                            <npmVersion>3.5.2</npmVersion>
                            <installDirectory>/external/place/whereI/put/node</installDirectory>
          </configuration>



The reason I specified an install directory is that this seemed to be the only way to avoid extracting the node.tar.gz on every run. I was able to get around the issue I mentioned in my last comment by specifying the following in 'npm install''s config:

                            <workingDirectory>/path/to/my/package.json/directory</workingDirectory>

But the node_modules are then installed inside that directory, and not outside of my project like I desired.
