### ISSUE TITLE
Use https://nodejs.org/ as defaultDownloadRoot

### ISSUE THREAD

**Issue by postmann** [eirslett/frontend-maven-plugin#278]
Currently, http://nodejs.org/dist/ redirects to https://nodejs.org/en/blog/. Adding
```
<nodeDownloadRoot>https://nodejs.org/dist/</nodeDownloadRoot>
```
to my pom.xml solved the problem. Maybe it would be an option to use the HTTPS URL by default?

**Comment by filip1323** [comment]
It does not solve my problem. I get:
`[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.23:install-node-and-npm (install node and npm) on project punchcard: Could not download Node.js from: https://nodejs.org/dist/v4.0.0/x64/node.exe: Got error code 404 from the server. -> [Help 1]`
Maven 3.3.3
npm 2.14.2

**Comment by postmann** [comment]
This is AFAIK due to #276.

**Comment by SlevinBE** [comment]
Looks like this PR should fix this: https://github.com/eirslett/frontend-maven-plugin/pull/270/files

**Comment by fcalfoeworld** [comment]
I was able to download node from the new download root (https://nodejs.org/dist - but we are using node v0.10.36 and npm 2.3.0 and Oracle JDK 1.6

However, now I encounter this error from the build server where we are running IBM JDK 1.6

[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.25:install-node-and-npm (install node) on project famsformff-client: Could not download Node.js: Could not download https://nodejs.org/dist/v0.10.36/node-v0.10.36-linux-x64.tar.gz: RSA premaster secret error: Illegal key size or default parameters -> [Help 1]

I discovered I just needed to update the security policy jars per this doc:

http://www-01.ibm.com/support/docview.wss?uid=swg21663373

and then my build worked successfully with the new https download roots

I'm using plugin version 0.0.25

**Comment by cecchisandrone** [comment]
What about npm downloadRoot? It tries to download from https://nodejs.org/dist/npm-1.4.21.tgz but file is not there anymore, neither in https://nodejs.org/dist/npm/. How did you change that?

**Comment by SlevinBE** [comment]
based on the sourcecode, it used http://registry.npmjs.org/npm/-/ by default for npm. So you have to specify the npm and nodejs download roots separately: 

    <nodeDownloadRoot>https://nodejs.org/dist/</nodeDownloadRoot>
    <npmDownloadRoot>http://registry.npmjs.org/npm/-/</npmDownloadRoot>

**Comment by cecchisandrone** [comment]
Great, thanks!

**Comment by david-gang** [comment]
:+1:

**Comment by mriehema** [comment]
They fixed the download repo links, see https://github.com/nodejs/new.nodejs.org/issues/124
http should work again.

**Comment by fhemberger** [comment]
@eirslett You still may want to change this setting, as https will be the default from now on (saving you one 301 redirect).

**Comment by fcalfoeworld** [comment]
Thanks for the update  downloading node from http://nodejs.org/dist/ is working again  -  what an adventure;)

**Comment by Katharsas** [comment]
Don't know if this is the right place to ask, but where do i fetch latest npm from? http://nodejs.org/dist/npm/ only has npm up to version 1.4.9, the current version is 3.3.3. Nodejs v4.1.1 ships with npm 2.14.3. All tutorials tell me "use the windows installer to get npm"...

Edit: Nevermind, http://registry.npmjs.org/npm/-/ is the way to go. Maybe update the Readme file?

**Comment by eirslett** [comment]
I think #270 solved this issue.
And yes, npm is now downloaded from npmjs.org, the readme is outdated.

**Comment by regi4life** [comment]
Hello,

When i have to add the following lines : <nodeDownloadRoot>https://nodejs.org/dist/</nodeDownloadRoot>
<npmDownloadRoot>http://registry.npmjs.org/npm/-/</npmDownloadRoot>

If i choose to download manually the file. Where should i put it for not having anymore the above error ?

For information, i am using maven for compiling a some code sources.

Thank you for your help.

Regi4life

**Comment by regi4life** [comment]
@SlevinBE
 
Where i have to define the informations you specify above ?

Thank you for your help.

Best regards,
Regi4life

**Comment by Katharsas** [comment]
You should have something similar to this in you pom:
`<execution>
	<id>install node and npm</id>
	<goals>
		<goal>install-node-and-npm</goal>
	</goals>
	<phase>generate-resources</phase>
	<configuration>
		<nodeVersion>v4.1.1</nodeVersion>
		<npmVersion>3.3.3</npmVersion>
		<nodeDownloadRoot>https://nodejs.org/dist/</nodeDownloadRoot>
		<npmDownloadRoot>http://registry.npmjs.org/npm/-/</npmDownloadRoot>
	</configuration>
</execution>
`

**Comment by regi4life** [comment]
Thank you. 

I added the information and i rebuild. i am waiting for.
      <id>install-node-and-npm</id>
                        <goals>
                            <goal>install-node-and-npm</goal>
                        </goals>
                        <phase>initialize</phase>
                        <configuration>
                            <nodeVersion>v4.2.3</nodeVersion>
                            <npmVersion>3.5.2</npmVersion>
                            <nodeDownloadRoot>https://nodejs.org/dist/</nodeDownloadRoot>
							**<npmDownloadRoot>http://registry.npmjs.org/npm/-/</npmDownloadRoot>**
                            <npmDownloadRoot>http://maven.forgerock.org/repo/api/npm/npm-virtual/npm/-/</npmDownloadRoot>
                        </configuration>
                    </execution>

In bold the line that i added.

**Comment by regi4life** [comment]
Thank for replying quickly.

I have maybe a proxy problem.

ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.26:install-node-and-npm (install-node-and-npm) on project openam-ui-ria: Could not download Node.js from: https://nodejs.org/dist/v4.2.3/win-x86/node.exe: Could not download https://nodejs.org/dist/v4.2.3/win-x86/node.exe: Connect to nodejs.org:443 [nodejs.org/104.20.23.46, nodejs.org/104.20.22.46] failed: Connection timed out: connect -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.26:install-node-and-npm (install-node-and-npm) on project openam-ui-ria: Could not download Node.js from: https://nodejs.org/dist/v4.2.3/win-x86/node.exe: Could not download https://nodejs.org/dist/v4.2.3/win-x86/node.exe
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)

Thank you for your help.

Best regards,
Regi4life

**Comment by Katharsas** [comment]
Yes you can.

Lets assume you have a config like this:
```
<plugin>
	<groupId>com.github.eirslett</groupId>
	<artifactId>frontend-maven-plugin</artifactId>
	<version>0.0.26</version>
	<configuration>
		<workingDirectory>src/main/frontend</workingDirectory>
		<installDirectory>.</installDirectory>
	</configuration>
	<executions>
		<!-- Config from: https://github.com/eirslett/frontend-maven-plugin -->
		<!-- phase optional for all executions: default phase is "generate-resources" -->
		<!--  disable some of the following executions to improve build speed -->
		<execution>
			<id>install node and npm</id>
			<goals>
				<goal>install-node-and-npm</goal>
			</goals>
			<phase>generate-resources</phase>
			<configuration>
				<nodeVersion>v4.1.1</nodeVersion>
				<npmVersion>3.3.3</npmVersion>
				<nodeDownloadRoot>https://nodejs.org/dist/</nodeDownloadRoot>
				<npmDownloadRoot>http://registry.npmjs.org/npm/-/</npmDownloadRoot>
			</configuration>
		</execution>
		<execution>
			<id>npm install</id>
			<goals>
				<goal>npm</goal>
			</goals>
			<phase>generate-resources</phase>
			<configuration>
				<arguments>install</arguments>
			</configuration>
		</execution>
		...
	</executions>
</plugin>
```

You need to comment out the first execution (install-node-and-npm) and instead install node.js with npm manually. Then copy the installation directory
The manually install node.js and copy the installed folder to the same folder as is specified in <installDirectory>path</installDirectory>. In my case the path is the project folder. The folder must be named "node" and contain the node executable.

**Comment by regi4life** [comment]
It seems it is going better by just copying the "exe" in the "node" folder and when i rebuid, i have the details below :

[DEBUG] Configuring mojo 'com.github.eirslett:frontend-maven-plugin:0.0.26:install-node-and-npm' with basic configurator -->
[DEBUG]   (f) installDirectory = D:\openam-13.0.0\openam-ui\openam-ui-ria
[DEBUG]   (f) nodeDownloadRoot = https://nodejs.org/dist/
[DEBUG]   (f) nodeVersion = v4.2.3
[DEBUG]   (f) npmDownloadRoot = http://maven.forgerock.org/repo/api/npm/npm-virtual/npm/-/
[DEBUG]   (f) npmVersion = 3.5.2
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@a56783
[DEBUG]   (f) skip = false
[DEBUG]   (f) skipTests = true
[DEBUG]   (f) workingDirectory = D:\openam-13.0.0\openam-ui\openam-ui-ria
[DEBUG]   (f) execution = com.github.eirslett:frontend-maven-plugin:0.0.26:install-node-and-npm {execution: install-node-and-npm}
[DEBUG] -- end configuration --
[INFO] Found proxies: [default{protocol='http', host='127.0.0.1', port=31280}]
[INFO] Node v4.2.3 is already installed.
[INFO] Installing npm version 3.5.2
[INFO] Downloading NPM from http://maven.forgerock.org/repo/api/npm/npm-virtual/npm/-/npm-3.5.2.tgz to D:\openam-13.0.0\openam-ui\openam-ui-ria\npm.tar.gz
[INFO] Downloading via proxy default{protocol='http', host='127.0.0.1', port=31280}
[INFO] Extracting NPM files in node/
[INFO] Unpacking D:\openam-13.0.0\openam-ui\openam-ui-ria\npm.tar.gz into D:\openam-13.0.0\openam-ui\openam-ui-ria/node/node_modules
[INFO] Installed NPM locally.
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.26:npm (npm-install) @ openam-ui-ria ---
[DEBUG] Configuring mojo com.github.eirslett:frontend-maven-plugin:0.0.26:npm from plugin realm ClassRealm[plugin>com.github.eirslett:frontend-maven-plugin:0.0.26, parent: sun.misc.Launcher$AppClassLoader@15d56d5]
[DEBUG] Configuring mojo 'com.github.eirslett:frontend-maven-plugin:0.0.26:npm' with basic configurator -->
[DEBUG]   (f) arguments = install
[DEBUG]   (f) installDirectory = D:\openam-13.0.0\openam-ui\openam-ui-ria
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@a56783
[DEBUG]   (f) skip = false
[DEBUG]   (f) skipTests = true
[DEBUG]   (f) workingDirectory = D:\openam-13.0.0\openam-ui\openam-ui-ria
[DEBUG]   (f) execution = com.github.eirslett:frontend-maven-plugin:0.0.26:npm {execution: npm-install}
[DEBUG] -- end configuration --
[INFO] Found proxies: [default{protocol='http', host='127.0.0.1', port=31280}]
[INFO] Running 'npm install --color=false --proxy=http://127.0.0.1:31280' in D:\openam-13.0.0\openam-ui\openam-ui-ria
[ERROR] npm WARN deprecated lodash@0.9.2: Grunt needs your help! See https://github.com/gruntjs/grunt/issues/1403
[ERROR] npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0
[ERROR] npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0

**Comment by narayanai** [comment]
Hi,
I have a local repository for below node and npm download links like the below..
https://abc.artifactory.com/dist/
http://abc.artifactory.com/npm/-/

And this artifactory links are password protected.. the credentials that I am using in settings.xml is useful here and I an getting the error like 

 http://abc.artifactory.com/......./latest-v8.x/win-x86/node.exe: Got error code 401 from the server. -> [Help 1]
[ERROR] 


However the link is valid and I am able to access the node.exe from the link. Could you please help me on this.

**Comment by pencale** [comment]
Hi all, I am also using artifactory and getting 401 . I have serverid from settings.xml in configuration.

**Comment by senthilkumarselvakesavan** [comment]
Hi all I am from RENAULT NISSAN-CHENNAI.

I have the solution for this, It is working for me and the build got success.
**Don't DO's:**
1. please do not add the any new entry in pom.xml like the below
                  <nodeDownloadRoot>https://nodejs.org/dist/</nodeDownloadRoot>
                <npmDownloadRoot>http://registry.npmjs.org/npm/-/</npmDownloadRoot>
2. It will append extra line the actual url to download node and npm.
**DO's.**
1. please verify the URL for return by maven logs in the browser.
2. It should it should open the down load path.
3. just add the network proxy in Maven's settings.xml file
        <proxy>
      <id>optional</id>
      <active>true</active>
      <protocol>http</protocol>
      <username>username</username> _your username_
      <password>password</password> _your password_
      <host>xxx.xx.xx.xx</host> your company network host name
      <port>*****</port>port number
4. mvn clean install , it will be downloaded and install automatically ... you can see the magic in Maven console.

Regards,
Senthil

**Comment by mariem13** [comment]
hi, I have the same problem:
my pom.xml:

<configuration>
                   <nodeVersion>v6.11.3</nodeVersion>
                    <npmVersion>3.10.10</npmVersion>
                    <nodeDownloadRoot>https://nodejs.org/dist/</nodeDownloadRoot>
                    <workingDirectory>src/main/angularDash</workingDirectory>
                </configuration>
error:

Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.22:install-node-and-npm (install node and npm) on project dashAngular: Could not download Node.js from: https://nodejs.org/dist/v6.11.3/x64/node.exe: Got error code 404 from the server. -> [Help 1]

**Comment by mriehema** [comment]
> Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.22

@mariem13 please update from 0.0.22 to the latest version of the frontend-maven-plugin (1.6)

**Comment by mariem13** [comment]
@mriehema  Thx for reply, i tried with version 1.6 but it find new error in version of maven

> Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:install-node-and-npm (install node and npm) on project dashAngular: The plugin com.github.eirslett:frontend-maven-plugin:1.6 requires Maven version 3.1.0 -> [Help 1]
