### ISSUE TITLE
Node download root not logging in Windows ?

### ISSUE THREAD

**Issue by fcalfoeworld** [eirslett/frontend-maven-plugin#282]
It appears that the download root is not logged when running the plugin from Windows 8:

[INFO] --- frontend-maven-plugin:0.0.25:install-node-and-npm (install node)  ---
**[INFO] Installing node version v0.10.36**
**[INFO] No proxy was configured, downloading directly**
**[INFO] Installed node.exe locally.**
[INFO] Installing npm version 2.3.0
[INFO] Downloading NPM from http://registry.npmjs.org/npm/-/npm-2.3.0.tgz to ...
[INFO] No proxy was configured, downloading directly

While the root is logged when running the plugin from Linux:

[INFO] --- frontend-maven-plugin:0.0.25:install-node-and-npm (install node)  ---
**[INFO] Installing node version v0.10.36**
**[INFO] Downloading Node.js from http://nodejs.org/dist/v0.10.36/node-v0.10.36-linux-x64.tar.gz** **[INFO] No proxy was configured, downloading directly**
**[INFO] Installed node locally.**
[INFO] Installing npm version 2.3.0
[INFO] Downloading NPM from http://registry.npmjs.org/npm/-/npm-2.3.0.tgz 
[INFO] No proxy was configured, downloading directly

Can we get the download root logged when running from Windows?

**Comment by eirslett** [comment]
Sure, just send a PR!
