### ISSUE TITLE
cache problem with parallel builds

### ISSUE THREAD

**Issue by cecchisandrone** [eirslett/frontend-maven-plugin#288]
Hello,

We are largerly using this nice plugin in our CI but often we face some problems related to npm cache. I think that all the jobs are sharing the same cache under C:\Users\...\AppData\Roaming\npm-cache and this is causing problems with parallel builds. Do you know if there is a way to disable cache or make it local to the workspace and not global?

Thanks for your help,
Alessandro

**Comment by eirslett** [comment]
Look at .npmrc, maybe there are some options there?

**Comment by cecchisandrone** [comment]
Thanks...I've solved using:
cache=./node/npm/cache
in .npmrc file
