### ISSUE TITLE
maven build fails on raspian jenkins

### ISSUE THREAD

**Issue by heinzepreller** [eirslett/frontend-maven-plugin#297]
A working mvn Build using maven frontend plugin (0.0.26) with node npm & grunt fails und raspian jessie with following output:

[INFO] Running 'npm install --color=false' in /var/lib/jenkins/jobs/PROJECT/workspace
[ERROR] /var/lib/jenkins/jobs/PROJECT/workspace/node/node: 1: /var/lib/jenkins/jobs/PROJECT/workspace/node/node: Syntax error: "(" unexpected

so i tried to run node from console getting this:
node: cannot execute binary file: error in format"

Also theres a npm.cmd file in the node folder.

Is it possible that the frontend maven plugin downloaded the windows version of node ?

I also tried your example project with version 0.0.26 and got the same result

**Comment by eirslett** [comment]
That's strange... but npm is the same across all platforms (it's just javascript files, not compiled binaries), that's why there's an npm.cmd in there. Have you tried running `node --version` with the binary that this plugin downloads?
The maven log also usually shows which URL the node binary is downloaded from, that could provide some hints...

**Comment by heinzepreller** [comment]
Problem is probably RaspberryPis ARM Architecture needs a special arm node like
http://nodejs.org/dist/v0.10.9/node-v0.10.9-linux-arm-pi.tar.gz

**Comment by eirslett** [comment]
Could you have a look at this one?

https://github.com/eirslett/frontend-maven-plugin/blob/master/frontend-plugin-core/src/main/java/com/github/eirslett/maven/plugins/frontend/lib/Platform.java

I guess it should be simple to add arm support; that would be the right place to do it.

**Comment by heinzepreller** [comment]
thanks - i'll try that later

**Comment by heinzepreller** [comment]
hi there,

so i edited Plaform.java to work with ARM Architecture, tested it & it seekms to work.

Problem is - this is "arm-pi" specific so it doesn't work with any other arm platform. 
Another Problem is not every NodeJS Version got a "arm-pi"-binary file (e.g. node-v0.10.26-linux-arm-pi.tar.gz). I learned that the binaries for arm-pi are send by someone not automatically built.

So would it be possible to specify full path to node not only download roots, or is there any benefit from knowing OS Architecture or OS Name?

**Comment by eirslett** [comment]
Ok, if they don't upload pi binaries for every version, then it's probably better not to support it than to cause a lot of confusion when some of the pi versions don't exist.
What you can do is to commit the correct binary into the "node" folder. If there's already a "node" file there, this plugin won't try to download it, but use the existing one. Commiting binaries into code repositories generally isn't best practice, but in this edge case, there's really no simple, pretty solution.

**Comment by agolovenko** [comment]
Same problem. 
But I build on multiple platforms so comiting binaries isn't the solution.
Possible solutions might include:
1. Accepting full url to the binary file (could be altered with build profiles)
2. Adding support for arm platforms
Would love this issue to be reopened, Thanks!
