### ISSUE TITLE
Specify location of node module files

### ISSUE THREAD

**Issue by annam002** [eirslett/frontend-maven-plugin#304]
In my setup, I use the plugin to execute a grunt task. This works fine, however, I would prefer to have all node-js and npm files in the target folder. If I specify the installation directory the node files end up in the target folder, but the files from my modules still end up in the root folder (in the folder node_modules). Can this be changed?

Here is my configuration:
```
<plugin>
			  <groupId>com.github.eirslett</groupId>
			    <artifactId>frontend-maven-plugin</artifactId>
			    <version>0.0.26</version>
				 <configuration>
		            <installDirectory>target</installDirectory>
		        </configuration>
			    <executions>
			       <execution>
	                   <id>install node and npm</id>
	                   <goals>
	                       <goal>install-node-and-npm</goal>
	                   </goals>
	                   <configuration>
	                       <nodeVersion>v4.2.1</nodeVersion>
	                       <npmVersion>2.14.7</npmVersion>
	                   </configuration>
	               </execution>
	               <execution>
	                   <id>npm install</id>
	                   <goals>
	                       <goal>npm</goal>
	                   </goals>
	               </execution>
	               <execution>
	                   <id>grunt build</id>
	                   <goals>
	                       <goal>grunt</goal>
	                   </goals>
	                   <configuration>
	                       <arguments>--no-color</arguments>
	                   </configuration>
	               </execution>
    </executions>
</plugin>
```

**Comment by eirslett** [comment]
It could possibly be hacked around, but not using this plugin; you would need to change it in npm itself.  (If you google it, people say it's a bad idea)
If the problem is cleaning up before/after a build, you can setup maven-clean-plugin to delete the node_modules folder.

**Comment by ette8899** [comment]
> If the problem is cleaning up before/after a build, you can setup maven-clean-plugin to delete the node_modules folder.

I can maven-clean-plugin to delete node_modules after install, but after that, frontend plugin still execute the gulp execution, which will failed because the node_modules folder has already been delete while installing, I bundle the goal gulp to parse install but doesn't work, any ideas?

here is my pom settings:
`<execution>
						<id>gulp build</id>
						<goals>
							<goal>gulp</goal>
						</goals>
						<phase>package</phase>
						<configuration>
							<arguments>minify</arguments>
							<installDirectory>target</installDirectory>
							<workingDirectory>./</workingDirectory>
						</configuration>
					</execution>`

**Comment by ette8899** [comment]
I think I can just override the method skipExecution in class GulpMojo, that works for me.

**Comment by eirslett** [comment]
You should set `<phase>` for maven-clean-plugin so it deletes the folder at the right moment.
