### ISSUE TITLE
webpack watch or npm run dev in eclipse?

### ISSUE THREAD

**Issue by helt** [eirslett/frontend-maven-plugin#306]
Currently, i have a eclipse project which uses webpack. I use `npm run dev` to run `webpack --watch`, because thats soooo much faster than a complete webpack build. But sadly, i have to refresh the project in eclipse, to make eclipse to deploy the updated webpack files to the tomcat instance.

Is there a way to circumvent this workflow and make maven/eclipse to listen to the updated webpacks and deploy them automatically?

**Comment by eirslett** [comment]
You can change the output directory of the webpack command, so it writes directly to the exploded war directory/target directory, instead of into eclipse first.
