### ISSUE TITLE
Running clean install build on Windows fails it not invoked with administrator permissions

### ISSUE THREAD

**Issue by ir73** [eirslett/frontend-maven-plugin#307]
If you configure this plugin and then run "clean install" then it will fail on the phase that downloads/installs nodejs. This can be fixed by opening cmd.exe under Administrator. However, this is not convenient and crosses out all efforts of that plugin, because none of developer runs their builds under administrator account. 

Can this be change to run under any user?

**Comment by eirslett** [comment]
In my experience, it often asks for a username/password the first time you try to run the build - it wants you to give node.exe access to the internet (for running npm, for example).
Usually it only happens the first time you try to use the plugin. (Or every time it downloads node again)
How does it fail for you? Can you post the output? (Also, is there no password prompt?)

**Comment by ir73** [comment]
I must admit that I cannot reproduce the issue anymore. I did some tweaks though and I cannot say now what caused the problem. Sorry 'bout that. Nice work.
