### ISSUE TITLE
Maven plugin fails with 'npm install --color=false'

### ISSUE THREAD

**Issue by vramachan** [eirslett/frontend-maven-plugin#308]
Hi,

Building the maven project on mac using maven 3.2.5 and java 1.7. I get the following error:
Any suggestions?

[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.26:npm (npm install) on project falcon-ui: Failed to run task: 'npm install --
color=false' failed. (error code 34) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.26:npm (npm install) on projec
t falcon-ui: Failed to run task

**Comment by eirslett** [comment]
Upgrade to the latest Maven version, that should solve the problem?

**Comment by adiviswa** [comment]
I am using Maven 3.6.0 and using a proxy and I observe the same error.
```
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.23:npm (npm install) on project falcon-ui: Failed to run task: 'npm install --color=false --proxy=http://proxy.esl.cisco.com:8080' failed
```
Any idea how to fix this?
