### ISSUE TITLE
Pass command line options to node when executing npm, bower, etc goals

### ISSUE THREAD

**Issue by madoxas** [eirslett/frontend-maven-plugin#309]
I couldn't find the way to pass command line options to node when executing a npm goal.
Node supports options if they are passed before the script file:
```
$ node -h
Usage: node [options] [ -e script | script.js ] [arguments]
```
In my case I want to set `--max-old-space-size` option. Is there anyway to do it with frontend-maven-plugin?

**Comment by ccschneidr** [comment]
I have the very same issue. I get a "process out of memory" while using webpack and would need to pass a node option to solve this. No way to do it?

**Comment by eirslett** [comment]
There's no easy way. I would do something like this in package.json:

```json
{
  "scripts": {
    "webpack": "node --bla --bla --bla node_modules/webpack/bin/webpack.js etc etc"
  }
}
```

and use the npm goal.
