### ISSUE TITLE
How to run NodeJS server along with Spring Boot

### ISSUE THREAD

**Issue by padre629** [eirslett/frontend-maven-plugin#310]
I'm trying to run a little NodeJS server along with your plugin.
One attempt is running "npm start" order, given by
```
                    <execution>
                        <id>npm start</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <configuration>
                            <arguments>start &amp;</arguments>
                        </configuration>
                    </execution>
```
The end of my package.json is
```
"scripts": {
    "start": "node index.js"
  }
```
and when I run Spring-Boot, console is stuck showing server run success, Spring is unable to continue the normal boot process:
```
[INFO] --- frontend-maven-plugin:0.0.22:npm (npm-install-modules) @ FinalDegreeProject ---
[INFO] Running 'npm install --color=false' in /home/sergioguzman/FinalDegreeProject
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.22:npm (npm start) @ FinalDegreeProject ---
[INFO] Running 'npm start & --color=false' in /home/sergioguzman/FinalDegreeProject
[INFO] 
[INFO] > FinalDegreeProject@0.0.2 start /home/sergioguzman/FinalDegreeProject
[INFO] > node index.js &
[INFO] 
[INFO] SkylinkJS server started at 8081 port (HTTP) /// SocketIO server started at 9090 port
```
Last text is what my server (index.js) shows when its executed (console.log). Spring console is still stuck at this phase even if I remove console.log from server (index.js).
If I kill node process, Spring continues its normal booting.

Similar behaviour occurs if I put ampersand (& symbol) at the end of start-script at package.json, and if I remove it from pom.xml custom execution. Sometimes, Spring server runs OK but without node, sometimes node runs without Spring, sometimes neither Spring nor node runs at all... NEVER both servers runs along (this is what I want to perform).

What to do?! How can I execute a node server (a script) along with Spring boot?!
I'm using 0.0.22 version of your plugin, I've updated to current last version without success.

Thanks ;)

**Comment by eirslett** [comment]
This plugin isn't made for running processes in the background, it's just a Maven plugin meant to be used in the build phase.
What you can do is copy the helper scripts for node and npm (you can find them in this repo) into your project root directory, so that whenever somebody runs `npm run start` from the command line, it will use the local node/npm installation.
For development, you will then need to shells open; one for npm run start and another for maven/spring boot.
