### ISSUE TITLE
Working Directory and Install Directory

### ISSUE THREAD

**Issue by dcavanagh** [eirslett/frontend-maven-plugin#311]
Is it possible to have the node and npm install directory be different than the working directory. I am having some trouble figuring out how to set it up. It looks like the npm run build execution is looking for node/npm in the working direrectory.
Thanks for your help!

npm@2.7.6 /Users/dcavanagh/ams/target/node/node_modules/npm
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.633 s
[INFO] Finished at: 2015-11-10T09:47:10-05:00
[INFO] Final Memory: 13M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.26:npm (npm run build) on project ams: Failed to run task: 'npm grunt build --color=false' failed. (error code 1) -> [Help 1]

```xml
<plugin>
<groupId>com.github.eirslett</groupId>
  <artifactId>frontend-maven-plugin</artifactId>
    <version>0.0.26</version>
    <executions>
        <execution>
            <id>install node and npm</id>
            <goals>
                <goal>install-node-and-npm</goal>
            </goals>
            <configuration>
                <nodeVersion>v0.12.2</nodeVersion>
                <npmVersion>2.7.6</npmVersion>
                <installDirectory>target/</installDirectory>
            </configuration>
        </execution>
        
        <execution>
            <id>npm install</id>
            <goals>
                <goal>npm</goal>
            </goals>
            <!-- Optional configuration which provides for running any npm command -->
            <configuration>
                <arguments>install</arguments>
                <workingDirectory>src/assembly/js</workingDirectory>
            </configuration>
        </execution>
        <execution>
            <id>npm run build</id>
            <goals>
                <goal>grunt</goal>
            </goals>
            <configuration>
                <arguments>grunt build</arguments>
                <installDirectory>target/</installDirectory>
                <workingDirectory>src/assembly/js</workingDirectory>
            </configuration>
        </execution>
    </executions>
</plugin>
'''

**Comment by gilkerley** [comment]
Why is your <argument> "grunt build" ?
I would expect just "build" when the <goal> is already grunt.

Gil

**Comment by dcavanagh** [comment]
Thanks Gil! I was able to get it to work based on your comment.

**Comment by gilkerley** [comment]
Nice!

Gil
