### ISSUE TITLE
Incorporate other packages

### ISSUE THREAD

**Issue by papowell** [eirslett/frontend-maven-plugin#313]
Hello,
I see that intern.js is not supported so I 'npm install intern' only to find that the environment (Maven) won't let me run intern.  How can I add intern the the list of supported testing libraries?

I tried some creative things like 'npm install intern' within the maven <execution> tag only to find that there seem to be environment variable errors that I have not been able to overcome.

**Comment by eirslett** [comment]
You could make a copy of the Karma mojo, and make one for intern.
An easier option is to just run it through npm; make a "test" script in package.json that calls intern, and from maven, use the npm mojo with `<arguments>run test</arguments>`.
