### ISSUE TITLE
Maven version 3.1 requirement

### ISSUE THREAD

**Issue by 1inuxoid** [eirslett/frontend-maven-plugin#314]
Hi Eirik 

Why is there a strict requirement of version 3.1 of Maven? The latest recommended release is 3.3.9?

**Comment by eirslett** [comment]
Version 3.1 is just the minumum required. 3.3.9 can be used just fine.
If you use IntelliJ, make sure you're using your system version of Maven, since IntelliJ comes with an old, bundled version of Maven.

**Comment by 1inuxoid** [comment]
Thanks, that was a brilliant answer to a question I should have asked!
