### ISSUE TITLE
Determinating nodePath

### ISSUE THREAD

**Issue by mofd** [eirslett/frontend-maven-plugin#318]
Hello.

Its a great plugin and I would like to use it for our developers and within our CI-platform. The problem I have is the way like the node path will be determinated. This happens with the assumption the node path suffix will be NODE_WINDOWS = "\\node\\node.exe" or NODE_DEFAULT = "/node/node" because node will be download and install in this manner by this plugin. But on our CI we have node installed in another path like this /usr/locl/bin/nodepath and we must use this node installation. Furthermore it isn't allow to install node and other executable during the build process because of proxy problems etc. . I could manage this with the parameter installDirectory but without the node path suffix assumption of \\node\\.. or /node/.. . Do you see possibility to consider this in your plugin?

Thanks

mofd

**Comment by eirslett** [comment]
> But on our CI we have node installed in another path like this /usr/locl/bin/nodepath and we must use this node installation.

That is the problem - you shouldn't use the same node version on all your builds. What do you do when one project uses node 0.10 for the build, and another project uses node 4.1? This plugin works by scoping each node installation to the project, so you get that type of independency.

One thing you could do is to set downloadRoot with a `file:///usr/local/something` so it *copies* that version of node into your project, before using it.

**Comment by mofd** [comment]
I understand this point and I'm generally agree with it. But in our company node version will be set for all projects by the node version on our CI. And at the time I have no possibility to change this.

**Comment by eirslett** [comment]
Ok, I see. What I think would be a better option then, is to not use this plugin, and instead use maven-exec-plugin. [This guide is very good](http://addyosmani.com/blog/making-maven-grunt/). Unfortunately, the frontend-maven-plugin doesn't fit every use case.
I hope that guide will help you!
