### ISSUE TITLE
Support older versions of Maven (3.0.x)

### ISSUE THREAD

**Issue by Cosaquee** [eirslett/frontend-maven-plugin#319]
On Ubuntu 14.04, there is no 3.1 Maven version. It is a problem when it comes to CI systems, like Jenkins.

Support for version 3.0.4 would be nice.

**Comment by eirslett** [comment]
Unfortunately it's not possible... There's a breaking change in Maven, about a dependency on SLF4J. You might be able to use an older version of the plugin, though.
Or go the extra mile and install a newer Maven version on Jenkins anyways ;-)
