### ISSUE TITLE
Support tsd install

### ISSUE THREAD

**Issue by ondrepe** [eirslett/frontend-maven-plugin#320]
Hi can you add support for running at least tsd install task?

Thanks a lot!

**Comment by aciccarello** [comment]
@ondrepe You can run custom npm scripts by adding a `post*` script. I'm running a tsd reinstall after every npm install with the following script in the `scripts` section of our package.json. With the npm scripts, npm uses the locally installed version of a tool.

```
"scripts": {
    "postinstall": "tsd reinstall -o",
    ....
}
```

**Comment by ondrepe** [comment]
Hi @aciccarello , thanks a lot, it solved my problem.
