### ISSUE TITLE
ProxyConfig doesn't allow http proxy for https host

### ISSUE THREAD

**Issue by timja** [eirslett/frontend-maven-plugin#322]
It is not possible to build a project from behind a firewall if they use this plugin and override the default node registry url to an https url and your local proxy runs on http. 

The ProxyConfig (line 32) class checks that your configured proxy matches the URI scheme of the request URI this is not correct behaviour.

As a small fix I propose it be changed to:
```
 for (Proxy proxy : proxies) {
            if (!proxy.isNonProxyHost(uri.getHost())) {
                return proxy;
            }
        }
```

I don't believe this class should exist, the proxy should just be taken care of by the client.

I tried to patch it myself but can't build the project due to it not even finding any proxies when building, unsure why as I can use the released version 0.0.26 from maven central in other projects and it works fine.

Tim

**Comment by timja** [comment]
I've made a PR #353 
I managed to build the project by editing the settings.xml in frontend-maven-plugin/src/it/settings.xml

A note may be worth it in the readme that the maven-invoker-plugin overrides the users settings.xml file with the project one

**Comment by bdellegrazie** [comment]
Hi @eirslett is it possible to get this merged and new release cut?
I realise there are some other outstanding issues with regards to handling proxies but this fixes the *current* behaviour for people with targets that are https
Thanks
