### ISSUE TITLE
Release 0.0.27

### ISSUE THREAD

**Issue by tscheinecker** [eirslett/frontend-maven-plugin#331]
There hasn't been a release since September 23, but several issues have been resolved, so i would greatly appreciate a new release.

**Comment by sebpiller** [comment]
Please please please, do something for the proxy settings (at least handle correctly nonProxyHosts from Maven config)

**Comment by eirslett** [comment]
Ok! I've released it now.

**Comment by tscheinecker** [comment]
awesome! thank you
