### ISSUE TITLE
SSL Error with 0.0.27

### ISSUE THREAD

**Issue by sebpiller** [eirslett/frontend-maven-plugin#332]
I really have no clue about what is going on (and unfortunately I have not much spare time to investigate), but I get the following error when launching a clean-install with my CI system (Jenkins) (empty workspace):

    [INFO] --- frontend-maven-plugin:0.0.27:install-node-and-npm (install-node-and-npm) @ xxx-ui ---
    [INFO] Found proxies: [http-proxy{protocol='http', host='proxyws.xxx.ch', port=8080}, https-    proxy{protocol='https', host='proxy.xxx.ch', port=8080}]
    [INFO] Installing node version v4.2.2
    [INFO] Creating temporary directory /home/tomcat/.jenkins/jobs/XXX - Nightly    Build/workspace/xxx/xxx-ui/node_tmp
    [INFO] Downloading Node.js from https://nodejs.org/dist/v4.2.2/node-v4.2.2-linux-x64.tar.gz to /home/tomcat/.jenkins/jobs/XXX - Nightly Build/workspace/xxx/xxx-ui/node_tmp/node.tar.gz
    [INFO] Downloading via proxy https-proxy{protocol='https', host='proxy.xxx.ch', port=8080}
    [...]
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 02:53 min
    [INFO] Finished at: 2016-01-07T18:31:14+01:00
    [INFO] Final Memory: 97M/806M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.27:install-node-and-npm (install-node-and-npm) on project xxx-ui: Could not download Node.js: Could not download https://nodejs.org/dist/v4.2.2/node-v4.2.2-linux-x64.tar.gz: Remote host closed connection during handshake: SSL peer shut down incorrectly -> [Help 1]
    [ERROR] 
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
    [ERROR] 
    [ERROR] After correcting the problems, you can resume the build with the command

Downgrading to 0.0.26 fixes the issue

**Comment by eirslett** [comment]
It might be the bumping of apache httpclient that introduced the bug? I'm not sure.
Let's wait until more people experience this problem.

**Comment by sushiladokar** [comment]
How to get rid of this ERROR
I have already did strict-ssl=false in npmrc 
What else can I do?

 Could not download Node.js from: https://nodejs.org/dist/v5.0.0/win-x64/node.exe: Could not download https://nodejs.org/dist/v5.0.0/win-x64/node.exe: Remote host closed connection during handshake: SSL peer shut down incorrectly
