### ISSUE TITLE
Required version of maven-compiler-plugin

### ISSUE THREAD

**Issue by yassirh** [eirslett/frontend-maven-plugin#339]
Is there any specific reason why the minimum version of maven-compiler-plugin is set 3.1? if set to a lower value would the plugin still work? Thank you.

**Comment by eirslett** [comment]
Yes, the reason is that Maven 3.1+ comes bundled with slf4j, which earlier versions don't. This plugin used to bundle slf4j but that failed once Maven dit it too.
I suggest you use an older release of this plugin (since before the slf4j change), or upgrade Maven.
