### ISSUE TITLE
npm WARN generates a Maven ERROR

### ISSUE THREAD

**Issue by mriehema** [eirslett/frontend-maven-plugin#343]
In my npm install phase some node_modules generate some warnings about deprecated versions (like grunt). But in the Maven log, this is an ERROR instead of a WARNING. We're using Jenkins as our build tool and these errors cause wrong log analysis.

```
[INFO] --- frontend-maven-plugin:0.0.27:npm (install node, npm and dependencies) @ theme ---
[INFO] Found proxies: []
[INFO] Running 'npm install --color=false' in C:\theme
[ERROR] npm WARN deprecated lodash@0.9.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
[ERROR] npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0
[ERROR] npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
[ERROR] npm WARN prefer global node-gyp@3.2.1 should be installed with -g
```

Changing the logging from ERROR to WARNING would be nice.

**Comment by mriehema** [comment]
Awesome! Thank you. :+1:

**Comment by Q1nt** [comment]
+1 
having problems with bower warn messages

**Comment by breun** [comment]
+1

**Comment by ysangkok** [comment]
Thanks for the fix. Will a release be made now for this fix or should I use Jitpack to use this from master?

**Comment by eirslett** [comment]
I didn't know about Jitpack, it looks nice! Go with that for now :)

**Comment by breun** [comment]
It would be nice if it would be possible to see in what release a particular issue was (or will be) fixed. I can't find that information on an issue page and the releases at https://github.com/eirslett/frontend-maven-plugin/releases also don't have any changelogs, so I never know what changes I'm getting when I update to a new version.

**Comment by eirslett** [comment]
That's right, there's no changelog... you'd have to look at the commit log.

**Comment by breun** [comment]
Maybe attach issues to version milestones (vX.Y.Z or something)? That way it's also easy to generate a link to a list with all issues associated with a specific version milestone, which would essentially be a changelog for a release.

**Comment by mriehema** [comment]
Hey @eirslett, I will create a pull request the next days with a CHANGELOG.md for the last versions. Afaik, it will automatically be attached to the [releases ](https://github.com/eirslett/frontend-maven-plugin/releases) page. Shouldn't be to much work to keep it updated.
But maybe it is time to switch to version 1.0.0. ;)

**Comment by findpritz** [comment]
With plugin version 1.4, I am still seeing this, two npm WARN messages being translated to an ERROR.

```
[INFO]
[WARNING] npm WARN sample-typescript-project@1.0.0 No repository field.
[WARNING] npm WARN sample-typescript-project@1.0.0 No license field.
[ERROR]
[INFO] added 806 packages in 132.853s
```

Any thoughts on how I can resolve this?

**Comment by mriehema** [comment]
They are shown as `[WARNING]`. So it works. 
I don't know, where this empty `[ERROR]` line is coming from. Try with --verbose.

**Comment by findpritz** [comment]
Oh, I thought the 2 WARNINGS are also being falsely translated to an ERROR by the plugin.

I'll try with the verbose flag and see what I get.

**Comment by findpritz** [comment]
Even with the --verbose flag too, I do not see any additional error messages:
```
[WARNING] npm WARN sample-typescript-project@1.0.0 No repository field.
[WARNING] npm WARN sample,-typescript-project@1.0.0 No license field.
[ERROR]
[INFO] added 806 packages in 379.959s
```

Also, tried to with -X command to see if maven prints any additional log messages, still do not really see anything in particular.

**Comment by hectoralicea** [comment]
Following.  I'm also getting this warning and ERROR line, but Jenkins recovers with [INFO] BUILD SUCCESS at the end.

[INFO] Running 'npm install --no-optional' in /opt/sonatype-work/jenkins/workspace/ficamui/ficamadmin build/ficamadmin
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[ERROR]

**Comment by felx** [comment]
Finally fixed this error by setting loglevel to silent on npm install in my build. I guess : no logs > no error on exit (sic)

**Comment by diadistis** [comment]
`--loglevel error` also works well with the added benefit of displaying actual errors.

**Comment by yuvraj1610** [comment]
I am getting a blank error message, however the build is success.

mvn frontend:npm
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building styles 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- frontend-maven-plugin:1.7.6:npm (default-cli) @ nswbc-styles ---
[INFO] Running 'npm install' in C:\Users\Desktop
[WARNING] npm WARN eslint-plugin-react@6.10.3 requires a peer of eslint@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
[WARNING] npm WARN marked-terminal@3.2.0 requires a peer of marked@^0.4.0 || ^0.5.0 || ^0.6.0 but none is installed. You must install peer dependencies yourself.
[INFO] audited 20780 packages in 9.444s
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
[INFO] found 41 vulnerabilities (13 low, 19 moderate, 9 high)
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
[INFO] run npm audit fix to fix them, or npm audit for details
[ERROR]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.584 s
[INFO] Finished at: 2019-06-20T23:22:19+10:00
[INFO] Final Memory: 17M/489M
[INFO] ------------------------------------------------------------------------

**Comment by eirslett** [comment]
Maybe it's better to just change this Maven plugin, so that all npm log output is redirected to stdout/info, regardless of npm's level...

**Comment by stefan123t** [comment]
Dear @eirslett and @mriehema,

I am using a rather old version 1.6 running here, hence still seeing this:

[Exec Stream Pumper] INFO com.github.eirslett.maven.plugins.frontend.lib.DefaultNpmRunner - 

[Exec Stream Pumper] ERROR com.github.eirslett.maven.plugins.frontend.lib.DefaultNpmRunner - 
[Exec Stream Pumper] ERROR com.github.eirslett.maven.plugins.frontend.lib.DefaultNpmRunner - Compiling @angular/core : es2015 as esm2015

[Exec Stream Pumper] ERROR com.github.eirslett.maven.plugins.frontend.lib.DefaultNpmRunner - 
[Exec Stream Pumper] ERROR com.github.eirslett.maven.plugins.frontend.lib.DefaultNpmRunner - Compiling @angular/common : es2015 as esm2015

[Exec Stream Pumper] ERROR com.github.eirslett.maven.plugins.frontend.lib.DefaultNpmRunner - 
[Exec Stream Pumper] ERROR com.github.eirslett.maven.plugins.frontend.lib.DefaultNpmRunner - Compiling @angular/platform-browser : es2015 as esm2015

[Exec Stream Pumper] ERROR com.github.eirslett.maven.plugins.frontend.lib.DefaultNpmRunner - 
...
[Exec Stream Pumper] ERROR com.github.eirslett.maven.plugins.frontend.lib.DefaultNpmRunner - 
[Exec Stream Pumper] ERROR com.github.eirslett.maven.plugins.frontend.lib.DefaultNpmRunner - Compiling @ngxs/store/operators : es2015 as esm2015

[Exec Stream Pumper] INFO com.github.eirslett.maven.plugins.frontend.lib.DefaultNpmRunner - Generating ES5 bundles for differential loading...

[Exec Stream Pumper] INFO com.github.eirslett.maven.plugins.frontend.lib.DefaultNpmRunner - ES5 bundle generation complete.
[Exec Stream Pumper] INFO com.github.eirslett.maven.plugins.frontend.lib.DefaultNpmRunner - Generating localized bundles...

[Exec Stream Pumper] INFO com.github.eirslett.maven.plugins.frontend.lib.DefaultNpmRunner - Localized bundle generation complete.
[Exec Stream Pumper] INFO com.github.eirslett.maven.plugins.frontend.lib.DefaultNpmRunner - 
...
 
I think you would need to parse the loglines coming from NPM log output and mark all lines with "npm WARN" as WARNING (as @mriehema adjusted) and all lines with "npm ERR!" / "Aborted" as ERROR. Everything else (e.g. above Compiling ... messages or the empty lines) in NPMs stderr stream may be downgraded as INFO/WARNING based on your decision (or a parameter).

All output from stdout should be returned as INFO as is.

                if (value.startsWith("Aborted") || value.startsWith("npm ERR!")) {
                    logger.error(value);
                } else if (value.startsWith("npm WARN ")) {
                    logger.warn(value);
                } else {
                    logger.info(value); // feel free to change to warn as it comes from NPMs stderr stream
                }

Kind regards,
Stefan

**Comment by stefan123t** [comment]
Though upgrading to frontend-maven-plugin 1.10.0 fixed it for me.
