### ISSUE TITLE
Ability to specify realtive path to node executable?

### ISSUE THREAD

**Issue by yannislionis** [eirslett/frontend-maven-plugin#344]
I am using the plugin in order to not necessarilly install node, but invoke npm install and then grunt as part of the maven build using an existing node installation.

The issue I am encountering is that the plugin assumes that, for Windows, the relative path of the executable under the installDirectory is "\\node\\node.exe" (specified in NodeExecutorConfig). Node is installed on my local machine via a central enterprise installer (I know, I know) and node.exe doesn't follow the assumption above. Although I can fiddle with the installation to make things work, there will be other developers in the company encountering the same problem and I'd rather be able to add this as an additional config item in the pom, rather than everyone fiddling with their managed node installation.

So what I'm looking for is to be able to say:
<installDirectory>C:\some\folder</installDirectory>
<nodeRelativePath>nodejs\node.exe</nodeRelativePath>

and have the plugin use those rather than the default.

I'm happy to create the pull request myself for this - but I wanted to see if the community feels this is a misuse of the plugin. I get the feel that the base use case is to install npm and execute, not use local installations. Should I go ahead with this, will it be useful to others too, or will it be rejected?

**Comment by eirslett** [comment]
That's correct, I have already closed a number of PRs asking for the same thing, suggesting people should use exec-maven-plugin instead, which is a better fit.
Is there a specific reason why you *don't* want to download node.js with this plugin?

**Comment by yannislionis** [comment]
I suspected so - thanks for the reply. I'll use the plugin you suggested instead.

It's... complicated. All software is installed centrally by the enterprise managed software repo, and the request is that the maven build doesn't pull things in from the internet but rather uses the locally installed version. :-)

**Comment by rnc** [comment]
@yannislionis What we have done to avoid pulling things from an external source is to setup an internal NPM registry and use `-DnpmRegistryURL=....` when invoking the build.
