### ISSUE TITLE
Enforcing Platform (Arch and OS) value during build process?

### ISSUE THREAD

**Issue by IDeepakS** [eirslett/frontend-maven-plugin#348]
Is there any way to enforce Platform (Arch and OS) value during build process? This would be useful if two different platforms are used for build and deployment, for e.g. build is done on UNIX but the deployment has to be done on Windows machine.

**Comment by eirslett** [comment]
No, it's not possible. This plugin is meant for deploying Node, it's only meant for running builds like javascript/css minification and unit tests. If you're looking to deploy Node in production as a runtime dependency, using this plugin is not a good fit.
