### ISSUE TITLE
bower@1.7.5 install fails

### ISSUE THREAD

**Issue by mllrjb** [eirslett/frontend-maven-plugin#350]
```
[INFO] Running 'bower install' in /home/jenkins/workspace/my-app
[ERROR] module.js:339
[ERROR]     throw err;
[ERROR]     ^
[ERROR] 
[ERROR] Error: Cannot find module '/home/jenkins/workspace/my-app/node_modules/bower/bin/bower'
[ERROR]     at Function.Module._resolveFilename (module.js:337:15)
[ERROR]     at Function.Module._load (module.js:287:25)
[ERROR]     at Function.Module.runMain (module.js:467:10)
[ERROR]     at startup (node.js:136:18)
[ERROR]     at node.js:963:3

```

It looks like bower changed their structure to `.lib/bin` from `./bin`, so it breaks builds.

Any reason not to use `node_modules/.bin/bower` instead of `node_modules/bower/bin`?

**Comment by mllrjb** [comment]
I think something odd is happening with Bower, because the previous version was 1.7.2, so I'm not sure why they jumped. Either way, would it make sense to link via `node_modules/.bin` anyways?

**Comment by bornholtz** [comment]
Anyone have a quick fix for this?

**Comment by mllrjb** [comment]
@bornholtz - yes, use `bower@1.7.2` fixes for me.

**Comment by Botffy** [comment]
For the record, the bower issue is bower/bower#2157. It's all fixed now, which is awesome.

**Comment by eirslett** [comment]
Ok, I'll close this then. If anybody wants to fix it thoroughly, by letting all the mojos (grunt, gulp, bower etc) use the correct bin path, feel free to send a PR.

**Comment by mllrjb** [comment]
I'll carve out some time to do that, unless somebody beats me to it :)

On Wed, Jan 27, 2016 at 6:38 AM, Eirik Sletteberg < notifications@github.com [notifications@github.com] > wrote:
Ok, I'll close this then. If anybody wants to fix it thoroughly, by letting all
the mojos (grunt, gulp, bower etc) use the correct bin path, feel free to send a
PR.

—
Reply to this email directly or view it on GitHub
[https://github.com/eirslett/frontend-maven-plugin/issues/350#issuecomment-175632147] .[https://github.com/notifications/beacon/ABsU_Jo_CDtSCz_I5CN_A_jaJNWigmM_ks5peL_qgaJpZM4HM8Ab.gif]
