### ISSUE TITLE
allow just node to be installed

### ISSUE THREAD

**Issue by jgangemi** [eirslett/frontend-maven-plugin#355]
according to this page, https://www.npmjs.com/package/npm, `npm` is already packaged as part of `node`.

would it be possible to enhance the plugin with an option to use the `npm` that is bundled w/ `node`?

**Comment by eirslett** [comment]
This is more complicated, since it's bundled with node on unix systems, but not on Windows. That's maybe the main historical reason why they're separate.
I don't think it's a very big deal that it downloads npm, even if you for some reason only use node.
