### ISSUE TITLE
Node installation fails in windows with "node.exe is not a valid Win32 application"

### ISSUE THREAD

**Issue by WeiXiao2016** [eirslett/frontend-maven-plugin#358]
We use frontend-maven-plugin 0.0.26 to install node from http://nodejs.org/dist/
    <groupId>com.github.eirslett</groupId>
                <artifactId>frontend-maven-plugin</artifactId>
                <version>0.0.26</version>
                <executions>
                    <execution>
                        <id>install node and npm</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>install-node-and-npm</goal>
                        </goals>
						<configuration>
							<nodeVersion>v0.12.0</nodeVersion>
							<npmVersion>2.6.1</npmVersion>
						</configuration>
                    </execution>

The issue started today. Once we run the plugin on windows machine, it complains "node.exe is not a valid Win32 application"

We ran node/node.exe manually from command line and got the same error message.

**Comment by eirslett** [comment]
Do you download Node through a proxy? It might have been gzip-ed one too few or too many times...

**Comment by WeiXiao2016** [comment]
Actually, the issue disappeared in Saturday.
There is no proxy configured in our environment:
2016-01-29 15:45:57 | [DEBUG]   (f) nodeDownloadRoot = http://nodejs.org/dist/

2016-01-29 15:45:57 | [DEBUG]   (f) nodeVersion = v0.12.0

2016-01-29 15:45:57 | [DEBUG]   (f) npmDownloadRoot = http://registry.npmjs.org/npm/-/


I suspect some artifacts on nodejs.org is changed and wrong file is download. However, I am able to find which file is download and unzipped from nodejs.org.

Is it possible to run the plugin in verbose mode to generate more information?

Thanks,

Wei

**Comment by eirslett** [comment]
No, the output is pretty much as verbose as it can get already. I'm happy to hear it works now!
