### ISSUE TITLE
Multi-Module projects: argument `--prefix` possible? (common node_modules folder)

### ISSUE THREAD

**Issue by Antibrumm** [eirslett/frontend-maven-plugin#359]
Hi
I have to say that I am fairly new to the whole frontend build cycle, so it might be that this is just something I don't understand yet :)

I have a maven project with about 10 'frontend' modules, each containing a `package.json` and `grunt.js` file. And while executing the `frontend-maven-plugin` we are getting a `node_modules` folder in each of them. 

I haven't found a way to declare a common working directory where we could share all the plugins in a shared `node_modules` folder for each execution. 
I have found that the plugin configuration `installDirectory` is only used for the node installation, this seems to work fine. All maven modules are referencing this node installation. Unfortunately this is not true with the npm plugins referenced from `package.json`. I have read one argument of 'Storage is cheap' which I kind of agree, but it also means that each of the 10 executions are downloading around 100mb.

If I understand the docs of npm correctly there is a possibility to declare the location of the `node_modules` folder for an execution by defining the argument **--prefix**? (+ **-g** ?) I have not found a way to declare this in the grunt task. Am I missing something or it this not (yet) possible?

**Comment by eirslett** [comment]
Usually, in the node/npm ecosystem, you'll want one node_modules folder for every package.json file, so the easiest option would be to move the package.json file to the top level. But then you sacrifice isolation between the frontend modules.
