### ISSUE TITLE
support private bower components referenced with git - ssh

### ISSUE THREAD

**Issue by eddedd88** [eirslett/frontend-maven-plugin#362]
In my bower.json, I have an entry to a private bower component, for example: 

"my-lib": "git@bitbucket.org:accountname/repo-name.git#1.0.0"

Normally I would have ssh setup in my environment, allowing me to do bower installs fine. However, when I run it through maven it doesn't have the ssh key loaded, so authentication to this repo fails, and thus the bower install fails.

It would be nice if I could setup some configuration in the pom.xml that would allow me to do a bower install with this private bower component..

**Comment by eirslett** [comment]
That's strange... there should be no difference between running "bower install" directly or via this maven plugin, regarding ssh keys.

**Comment by eddedd88** [comment]
I think the issue comes from these commands being run in a Windows Command Prompt. I couldn't even get the **bower install** to run fine in command prompt, I can only run it from Git Bash or cygwin.

It could be a bower issue in Windows CMD, because I am able to authenticate git commands (for example: git fetch origin) but bower still doesn't get authenticated.

A solution I have is to use a _netrc file and changing bower.json to point to the repo in https instead of ssh. Not an ideal solution though.

**Comment by eirslett** [comment]
Ok, I'm happy to hear you found the cause :-) the bower guys should probably know of it, sounds like it could be a common problem...
