### ISSUE TITLE
Build Fails, with maven version errors

### ISSUE THREAD

**Issue by kambojankit** [eirslett/frontend-maven-plugin#367]
I am trying to integrate angular2 to my spring mvc project, but i get the following errors on executing maven goal: 'mvn clean generate-sources install'

Error:
Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.27:install-node-and-npm (install node and npm) on project manin: The plugin com.github.eirslett:frontend-maven-plugin:0.0.27 requires Maven version 3.1.0

I have maven 3.1.1 installed on my machine.

**Comment by eirslett** [comment]
Do you run maven directly on the command line? Or via something like IntelliJ, which bundles its own (old) version of maven?

**Comment by kambojankit** [comment]
My Bad, as rightly mentioned, It was intelliJ Idea messing up.. Hence closing the issues.

**Comment by tonyjamgle** [comment]
@eirslett I am getting the same problem building on NetBeans. Maven correctly installed, version 3.3.9. Is it possible I am in the same situation as @kambojankit ? If so, is there any workaround to build the project on NetBeans anyway or the command line is the only way?

**Comment by eirslett** [comment]
https://platform.netbeans.org/tutorials/nbm-maven-quickstart68.html#config

> 1. Select the Miscellaneous category in the Options window and click the Maven tab.
2. Specify the location of your local Maven installation (requires 2.0.9 or newer).
3. Check that the location of the local Maven repository is correct.
4. Click OK.

I don't use NetBeans myself, but I think that's the steps ^^ if it doesn't work, then try to google it a bit more.

**Comment by tonyjamgle** [comment]
Eirslett it worked...thank you so much and sorry for bothering!
