### ISSUE TITLE
Modules that run install scripts require node to be on the path. Helper scripts don't cover this.

### ISSUE THREAD

**Issue by arienkock** [eirslett/frontend-maven-plugin#369]
When installing `node-sass` (for example), the process executes `node scripts/install.js` and when node is not on the path this fails... or worse, node IS on the path but is somehow incompatible which causes the module to be installed in a broken state (which happened to me). I could make a pull request for the helper script, but it's a single line change. I suggest this:

```shell
#!/bin/sh
PATH="$PWD/node/":$PATH
node "node/node_modules/npm/bin/npm-cli.js" "$@"
```

It puts the embedded node binary earlier on the path, which should give it precedence over a globally installed version (if any).

**Comment by eirslett** [comment]
This is for the case when you run "npm install" with the npm helper script? Whenever npm install is run via maven, it adds node/npm to the path. (But not in the helper scripts)
Anyways, a PR would be welcome!

**Comment by arienkock** [comment]
Yes exactly, it's when I run `./npm install` using the provided helper scripts. I'm not sure if any of the other helper scripts would benefit from this, but I suppose any node process could try to spawn others.. I'll submit a PR.

**Comment by RobzInadE** [comment]
I'm having the exact same issues using the latest release of this plugin. My "phantomjs-prebuilt" can't be installed, because it runs ` node install.js` and node isn't on the path. I've tried adding a "pre-build step" in my jenkins config, setting the path to the location where node & npm is downloaded to, but to no avail.

Any ideas on how to fix this?

**Comment by eirslett** [comment]
> because it runs node install.js and node isn't on the path

All the recent versions of this plugin are supposed to fix that; node and npm should be added to PATH whenever you run Maven.

Could you try to add phantomjs-prebuilt to this integration test: (basically upgrade the karma/phantomjs dependencies) and see if you can reproduce the problem there?
https://github.com/eirslett/frontend-maven-plugin/tree/master/frontend-maven-plugin/src/it/example%20project

**Comment by RobzInadE** [comment]
It works now, bumped the plugin version (decided to bump node to v4.4.2 and npm to 3.8.3 as well) and it works fine! Sorry for confusion!
I'd have avoided this if you had changelogs ;)

Regards
