### ISSUE TITLE
Starting with version 0.27, self signed certificates are refused

### ISSUE THREAD

**Issue by onigoetz** [eirslett/frontend-maven-plugin#372]
in version 0.27 there was an update of `org.apache.httpcomponents:httpclient` from version `4.3.1` to `4.5.1` Which radically changes the way the certificates are verified.

At my job, we use self-signed certificates and it breaks everything for us.

we get the following error : 
```
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.27:install-node-and-npm (install node and npm) on project sq-web-platform-server: Could not download Node.js: Could not download https://my_domain.com/softwares/node/v5.7.0/node-v5.7.0-darwin-x64.tar.gz: handshake alert:  unrecognized_name -> [Help 1]
```

Can we add a configuration option for self-signed certificates ?
It worked perfectly fine with the previous versions, the certificate was well understood.
And I don't want to disable the security, just allow self-signed certificates

Thanks in advance

BTW. it's the same with version 0.28

**Comment by benediktarnold** [comment]
Can you please check again with a snapshot build from the master branch? I think my [PR](https://github.com/eirslett/frontend-maven-plugin/pull/373) will fix this. I am using this plugin with self signed certificates with a custom truststore.

**Comment by onigoetz** [comment]
Hello,

Sorry for coming back so late on this problem, I used the previous version in the meantime.

It seems that your fix doesn't fix the problem as this error (`handshake alert:  unrecognized_name`) is related to SNI

so this needs a fix on our side.

I will close this issue once I have the final information on that.

**Comment by onigoetz** [comment]
Yes, I confirm that this was caused by a missing SNI configuration.
If someone else reads this, it might be a configuration issue,

For example in Apache Http Server
```
ServerName subdomain.yourserver.com
#OR
ServerAlias subdomain.yourserver.com
```
