### ISSUE TITLE
Plugin is not using property "installDirectory" when installing Node and NPM

### ISSUE THREAD

**Issue by pfernandom** [eirslett/frontend-maven-plugin#376]
Hello,

I have multiple Maven modules, each one with its own package.json. However, I want to only download Node and NPM once for all of them. I'm trying to use the property "installDirectory" to put all NPM and Node installations in the same folder. The problem is that the plugin is ignoring that property and is always installing them to "/node" instead of using the folder "/targetz".

This is my plugin configuration:

```
<plugin>
				<groupId>com.github.eirslett</groupId>
				<artifactId>frontend-maven-plugin</artifactId>
				<version>0.0.22</version>
				<configuration>
						<nodeVersion>v0.12.2</nodeVersion>
						<npmVersion>2.7.6</npmVersion>
						<installDirectory>targetz</installDirectory>
				</configuration>
				<dependencies>
					<dependency>
						<groupId>org.codehaus.plexus</groupId>
						<artifactId>plexus-utils</artifactId>
						<version>2.1</version>
					</dependency>
				</dependencies>
				<executions>
					<execution>
						<!-- optional: you don't really need execution ids, but it looks nice 
							in your build log. -->
						<id>install node and npm</id>
						<goals>
							<goal>install-node-and-npm</goal>
						</goals>
						<!-- optional: default phase is "generate-resources" -->
						<phase>generate-resources</phase>
					</execution>
					<execution>
						<id>npm install</id>
						<goals>
							<goal>npm</goal>
						</goals>
						<!-- Optional configuration which provides for running any npm command -->
						<configuration>
							<arguments>install</arguments>
						</configuration>
					</execution>
					<execution>
						<id>grunt build</id>
						<goals>
							<goal>grunt</goal>
						</goals>

						<!-- optional: the default phase is "generate-resources" -->
						<phase>compile</phase>

						<configuration>
							<!-- optional: if not specified, it will run Grunt's default
							task (and you can remove this whole <configuration> section.) -->
							<arguments>default --no-color</arguments>
						</configuration>
					</execution>
				</executions>
			</plugin>
```

Can you help me check why is this failing?

Thank you.

**Comment by pfernandom** [comment]
I cloned your repository to debug the issue. 

It seems that v0.0.22 of your plugin simply ignores the "installDirectory" property. 

I tried to upgrade to a newer version but I'm using Maven 3.0.5, and since v0.0.23-SNAPSHOT (change SHA-1: 1a586f819221c8cbb069f3321c46673a120893e7, 03-18-2015),  Maven 3.1 is marked as a requisite for the plugin.

I would gladly upgrade Maven, but I cannot say the same of my Jenkins server which also uses 3.0.5.

On my local clone, I removed the <prerequisite> tag and it works as expected, taking the "installDirectory" value from the configuration.
Looking at the logs, I see that the prerequisite of 3.1 was added to support integration tests. Given the fact that the tests are failing anyway, is there a chance to remove this prerequisite?

This is the best Grunt-Maven integration tool I've seen, and I want to keep using it.

Regards.

**Comment by eirslett** [comment]
The reason 3.1 is a prerequisite is that Maven bundles slf4j, which it didn't use to earlier. This plugin uses slf4j, and the two dependencies crashed, so now the one from Maven is used. (Which isn't bundled in older versions of Maven)

https://maven.apache.org/maven-logging.html

Which failing tests are you referring to? There aren't supposed to be any failing tests.

**Comment by klieber** [comment]
The `installDirectory` did not get added to the plugin until version `0.0.24`.

**Comment by eirslett** [comment]
I guess the best solution is to upgrade Jenkins' maven version, or just live with having multiple node instances. Disk space is cheap.
