### ISSUE TITLE
Maven requirement 3.1.0

### ISSUE THREAD

**Issue by eBeyond** [eirslett/frontend-maven-plugin#378]
The plugin requires 3.1.0 but the current version is > 3.3.X.

Can you release a new one which works with mavens other than (preferable > 3.3.X) 3.1.0

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.271s
[INFO] Finished at: Mon Mar 07 18:24:16 CET 2016
[INFO] Final Memory: 7M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.28:install-node-and-npm (install node and npm) on project test: The plugin com.github.eirslett:frontend-maven-plugin:0.0.28 requires Maven version 3.1.0 -> [Help 1]
```

```18:23 $ mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)```

**Comment by eirslett** [comment]
It works with every version newer than 3.1.0. Most people who encounder this problem find it's due to running Maven via an IDE like IntelliJ, which secretly uses another internal, bundled version of Maven...

**Comment by eBeyond** [comment]
Oh... You're right... 3.0.6 is the one used by my ide. Changed and it worked perfectly. Thanks

**Comment by Catechacha** [comment]
How can i change it??? My IDE use 3.0.5

**Comment by ningod** [comment]
Change your IDE or... change it's settings

**Comment by Salman9545** [comment]
<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.5.2.RELEASE</version>
		<relativePath/> 
                
                
	</parent>
i am using maven 3.1.0 but org.springframework.boot version is 1.5.2.RELEASE
plz reply me fast

**Comment by eirslett** [comment]
Try running this without NetBeans, only in the terminal?

**Comment by Salman9545** [comment]
how i can run without netbeans plz tell me

**Comment by EduardoOrtiz89** [comment]
For netbeans download maven from https://maven.apache.org/download.cgi and then go to options
tools > options -> java  
Select tab Maven and set Maven Path
