### ISSUE TITLE
Failed to execute goal - gulp serve

### ISSUE THREAD

**Issue by rsutaria** [eirslett/frontend-maven-plugin#379]
Hello,

I'm getting this error when I'm trying to integrate the frontend-maven-plugin

Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.27:gulp (gulp serve) on project alchemist-web: Failed to run task: 'gulp.js serve --no-color' failed. (error code 1) -> [Help 1]

Any suggestions to fix this will be greatly appreciated..

Rs

**Comment by northamerican** [comment]
same issue. no clue what causes it.

**Comment by eirslett** [comment]
It's probably a misconfiguration in the alchemist-something project.
