### ISSUE TITLE
Allow proxy settings to be ignored

### ISSUE THREAD

**Issue by matthewhubblerose** [eirslett/frontend-maven-plugin#384]
# My Setup

Build running on Jenkins behind a corporate firewall - all external HTTP traffic has to go through a proxy server. We have an internal Nexus repository - all traffic for that cannot go through the proxy server.

For that reason, we have something like this in our settings.xml:
```
<proxy>
  <active>true</active>
  <protocol>http</protocol>
  <host>proxy.company.com</host>
  <port>80</port>
  <nonProxyHosts>maven.company.com|*.other.com</nonProxyHosts>
</proxy>
```

The `nonProxyHosts` part is used to stop traffic for hosts matching the expressions being proxied.

# Problem

As far as I can tell (by grepping though the source code), non proxy hosts are not supported by npm - proxies are supported though. So when I build my maven project with something like this in the pom.xml:

```
<plugin>
    <groupId>com.github.eirslett</groupId>
    <artifactId>frontend-maven-plugin</artifactId>
    <version>0.0.22</version>
    <executions>
        <execution>
            <id>install node and npm</id>
            <goals>
                <goal>install-node-and-npm</goal>
            </goals>
        </execution>
        <execution>
            <id>npm install</id>
            <goals>
                <goal>npm</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
        <nodeVersion>v5.7.1</nodeVersion>
        <npmVersion>3.6.0</npmVersion>
    </configuration>
</plugin>
```

 - install-node-and-npm succeeds as the requests are correctly proxied
 - npm fails as the traffic is incorrectly proxied

Specifically, the command run during npm is like this:
```
Running 'npm install --color=false --proxy=http://proxy.company.com:80' in /path/to/project
```

This means the requests to the Nexus repository are sent through the proxy server and fail.

# Temporary Workaround

It turns out there is a [--no-proxy command line option](https://github.com/npm/npm/commit/fec4c967ee235030bf31393e8605e9e2811f4a39) supported by npm that over-ride the use of a proxy if it has already been specified. So, running:
```
npm install --color=false --proxy=http://proxy.company.com:80 --no-proxy
```
means all of the Nexus HTTP traffic is not proxied. When you try to use the `--no-proxy` argument from the plugin configuration, like this:

```
<execution>
    <id>npm install</id>
    <goals>
        <goal>npm</goal>
    </goals>
    <configuration>
        <arguments>install --no-proxy</arguments>
    </configuration>
</execution>
```

then a command like this gets run:
```
npm install --no-proxy --color=false --proxy=http://proxy.company.com:80
```

Unfortunately swapping the positions of the `--proxy` and `--no-proxy` means the proxy is used, meaning this doesn't work! Fortunately, after a bit of hackery, I figured out you can make it work by specifying the proxy in the arguments before `--no-proxy`:
```
<execution>
    <id>npm install</id>
    <goals>
        <goal>npm</goal>
    </goals>
    <configuration>
        <arguments>install --proxy=http://proxy.company.com:80 --no-proxy</arguments>
    </configuration>
</execution>
```

This results in a command like this:
```
npm install --proxy=http://proxy.company.com:80 --no-proxy --color=false
```

Which correctly ignores the proxy, hurrah! (I haven't looked at the source code as to why this happens, or tried it with versions other than 0.22, so I don't know just how fragile this is).

# Proposed Feature

Add a `noProxy` parameter to the configuration, which means that proxy settings will be ignored for a specific execution. So you could write something in the pom.xml like this:

```
<execution>
    <id>npm install</id>
    <goals>
        <goal>npm</goal>
    </goals>
    <configuration>
        <noProxy>true</noProxy>
    </configuration>
</execution>
```

Which would mean the `--proxy` is not added to the npm command that is run.

**Comment by eirslett** [comment]
Another way of achieving this could be to change the plugin, so npm doesn't inherit proxy settings from maven. Then, bu default, there would be no proxy, and people would have to configure npm proxies in .npmrc.

**Comment by matthewhubble** [comment]
Sure, that sounds like a better solution. How would that affect the `install-node-and-npm` execution? Would it still be proxied as it is now, or would it also need to be configured?

**Comment by eirslett** [comment]
Yes, that goal should still inherit maven settings, I think.
There's also a new nexus function; site mirroring or something, that can be used to create a mirror of nodejs.org. Then you can change the downloadRoot to something like your.maven.proxy/nodejs-mirror/.

**Comment by matthewhubble** [comment]
Just a thought about the proposed changes. To re-state the problem, npm doesn't support non proxy host, but the maven proxy settings do, so it's not always possible to correctly provide the proxy settings to npm.

The 2 options are:
 1. Stop the plugin from passing the proxy settings to the npm executions (essentially - opt in to using a proxy)
   - Pros:
     - For users experiencing issues with this, all they need to do is update the version of the plugin
   - Cons:
     - Potentially breaking change for users that have to proxy all requests
      - Might force some users in having to duplicate their proxy URL in their settings.xml and in the config of the plugin)
 2. Allow users to over-ride the proxy setting from being used in the npm executions (essentially - opt out of using a proxy)
   - Pros
     - Does not change the behaviour of the plugin without users specifically using the new feature
   - Cons
     -  Puts the burden on users to add the extra configuration to opt out
