### ISSUE TITLE
graceful-fs, lodash deprecation warnings

### ISSUE THREAD

**Issue by niels1voo** [eirslett/frontend-maven-plugin#386]
configured plugin with node 5.5.0 and npm 3.5.3

[ERROR] npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
[ERROR] npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
[ERROR] npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
[ERROR] npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.

**Comment by eirslett** [comment]
You'll have to upgrade graceful-js and lodash in your project, I think. In any case, it's due to javascript stuff, not the maven plugin.
