### ISSUE TITLE
no more node_modules at the root.

### ISSUE THREAD

**Issue by sbuisson** [eirslett/frontend-maven-plugin#391]
Your plugin is great, but it create a lot of directories at the project's root.

Can you find a way so the node_modules directory are not create in the root of the project? By duplicate the package.json, gruntfile.js, etc in the installDirectory for example and run the commands-line here. (or create a targetDirectory option where you duplicate the package.json, gruntfile.js , etc and run the commands-line here.)

I think of  something like https://github.com/allegro/grunt-maven-plugin/ where all  the node_modules, bower_components etc are create in a target-grunt directory.

Thank-you !

**Comment by eirslett** [comment]
Unfortunately, that's not possible. It's a limit in the design of npm. https://docs.npmjs.com/files/folders
I suppose it's possible to write a hack to work around it, but I don't think that amount of complexity in the code (for this plugin) can be justifiable.
You could file an issue with npm instead, and ask for a possibility to override the node_modules location, maybe in package.json?
