### ISSUE TITLE
Jenkins build fails when mocha test fails

### ISSUE THREAD

**Issue by pulse00** [eirslett/frontend-maven-plugin#394]
Currently if a javascript test fails, the whole maven build fails too. The resulting message is

```[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.29:npm (javascript tests) on project frontend-test: Failed to run task: 'npm run test' failed. (error code 1) -> [Help 1]```

Is there a way to configure the plugin to not fail the build when this happens? The optimal outcome would be that the plugin recognizes failed builds so jenkins or other ci tools can show show the failed tests.

**Comment by eirslett** [comment]
Yes, it's meant to fail the build when the tests fail. You can ignore the tests by doing  `mvn clean install -DskipTests` or `maven.test.skip=true` (the npm test execution must be in `<phase>test</phase>` for that to work), but then there's no reason to have tests in the first place.
To get pretty reports in CI tools, you should add a karma/mocka plugin that generates junit xml reports.
