### ISSUE TITLE
Changing bower components directory

### ISSUE THREAD

**Issue by paulalex** [eirslett/frontend-maven-plugin#395]
In the bower install I need to change the directory that the bower.json file is located in as I am working from src directory in development then want to minify all my files into a dist folder during my maven build.

For this reason I install my bower.json in project/src/js and then use grunt to concat the vendor files into /dist/js.

Is this possible as from the documentation it only looks possible to change the entire working directory and not to set individual working directories.

**Comment by eirslett** [comment]
No, you'll have to put bower.json in your top-level directory, and then use .bowerrc to change bower directory from there. I think.
