### ISSUE TITLE
Using plugin on Jenkins with the maven release plugin

### ISSUE THREAD

**Issue by ddewaele** [eirslett/frontend-maven-plugin#397]
I'm currently using the plugin on Jenkins and I have 2 doubts (that might have a solution / workaround)

1. Most of our jobs have the "Clean before checkout" enabled in the git plugin, to ensure reproducible builds. I think this is a good practice but obviously it will delete the node and node_modules folders, meaning that on each run the plugin will download node/npm and run a full npm install (taking a long time). Is there a way to avoid that ?

2. We are using the maven release plugin and as you may know, performing releasing requires 2 builds (one "prepare" build and the actual build). The actual build is done in the /target/checkout folder, meaning that it will again need to download node/npm and run a full npm install (taking a long time). Is there a way to avoid that ?

**Comment by eirslett** [comment]
1. You could cache the node binaries on your Jenkins box and set <nodeDownloadRoot> to something like file:///my/cache/dir. Another solution is to commit the node folder into git, but then your build won't be cross-platform compatibly any longer. You could also choose to do the cleaning in maven (configure maven-clean-plugin) and then opt to not clean node and node_modules.

2. Currently, there is no easy way. If you don't release often it's not usually a big problem (more of an annoyance). You could probably make something based on maven profiles that only runs frontend-maven-plugin when not releasing.

**Comment by mriehema** [comment]
You could add `node `and `node_modules` to `.gitignore`. A git clean should ignore them.
We also added a Maven profile to skip this plugin. Just run `mvn clean install -DskipThemes`.

```  
<!-- enabled by default, skip themes with -DskipThemes -->
  <profiles>
    <profile>
      <id>development-themes</id>
      <activation>
        <property>
          <name>!skipThemes</name>
        </property>
      </activation>
      <build>
        <plugins>
          <plugin>
            <groupId>com.github.eirslett</groupId>
            <artifactId>frontend-maven-plugin</artifactId>
            <executions>
              <execution>
                <id>install node, npm and dependencies</id>
                <goals>
                  <goal>install-node-and-npm</goal>
                  <goal>npm</goal>
                </goals>
              </execution>
              <execution>
                <id>grunt build</id>
                <goals>
                  <goal>grunt</goal>
                </goals>
                <configuration>
                  <arguments>build</arguments>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
```

**Comment by ddewaele** [comment]
Thx for the comments. 

1. I've currently disabled the "Clean before checkout".
2. Not ideal but I guess we can live with it.

@mriehema : I think the jenkins git plugin looks at ```.gitignore``` (_Clean up the workspace before every checkout by deleting all untracked files and directories, including those which are specified in .gitignore_)

During a maven release I cannot skip the plugin. (it is already activated through a profile, only when we do releases)

**Comment by ddewaele** [comment]
@eirslett : It seems we're releasing often enought for this to be become an issue :)

So to avoid the overhead of that second npm install during the release:perform (already done in ```target``` and now in ```target/checkout```) the only way this can work is to make the ```node_modules``` folder available in the ```installDirectory```of the plugin (when its run in ```target/checkout```)

I was wondering if you would be open for a PR that would a small piece of logic to NpmMojo:

- check if we are releasing through the maven release plugin (```session.getExecutionProperties().get("performRelease")``` set by the maven release plugin)
- if we are releasing, and there is no ```node_modules``` present, copy the already generated ```node_modules```  to the ```installDirectory```  
- continue normal processing

Only problem I see is that the maven release plugin uses the maven CLI to launch the build in target/checkout, so I don't know if it that point we know what the original ```installDirectory``` was of the frontend-maven-plugin where the ```node_modules``` are stored.

**Comment by eirslett** [comment]
I'd say this is a problem with maven-release-plugin, not frontend-maven-plugin. So if it's supposed to be fixed anywhere, I think that's where the PR has to go.

**Comment by ddewaele** [comment]
Yeah ... we can close this here.... What are your experiences with releasing maven projects ? Do you use maven-release-plugin / another plugin / custom scripting on CI ?

Looking for something that plays nice with frontend-maven-plugin.

**Comment by eirslett** [comment]
I use maven-release-plugin. But then again, I don't release very often, so for me it's not a big deal if it downloads node/npm.
