### ISSUE TITLE
Failed to execute goal node.js

### ISSUE THREAD

**Issue by obila007** [eirslett/frontend-maven-plugin#398]
Hello,
I followed all the tutorials in this same issue but it didn't help me. I can't bypass the SSL in node.js
so I don't know if you have other solution to my probleme. I have to mention I work with the code source of APIMAN and in one of my webapps I need to use the frontend-maven-plugin.
Any other ideas please?

**Comment by eirslett** [comment]
What is the problem? You need to provide a more detailed description.

**Comment by obila007** [comment]
Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.27:install-node-and-npm (install node and npm) on project apiman-manager-ui-war: Could not download Node.js from: https://nodejs.org/dist/v5.6.0/win-x64/node.exe: Could not download https://nodejs.org/dist/v5.6.0/win-x64/node.exe: Unrecognized SSL message, plaintext connection? -> [Help 1]

This is what I have as problem.

**Comment by obila007** [comment]
I'm not sure but can it be a proxy problem?

[INFO] Installing node version v5.6.0
[INFO] Downloading via proxy default{protocol='https', host='proxy.priv.****.fr', port=3128}
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

**Comment by eirslett** [comment]
Yes, looks like a problem with your company proxy.
