### ISSUE TITLE
Support for typings

### ISSUE THREAD

**Issue by tomahim** [eirslett/frontend-maven-plugin#399]
I'm using Typescript for my project. This maven plugin support jspm which is really great, but I think it could be usefull to support the typings tool by using for example : 

```xml
<execution>
    <id>typings install</id>
    <goals>
        <goal>typings</goal>
    </goals>					
    <configuration>
        <arguments>install</arguments>
    </configuration>
</execution>
```

Is it possible or is there another way to achieve this result ?

**Comment by eirslett** [comment]
The easiest way to add new build tools (they seem to pop every day) is to run them via the npm mojo, something like "npm run-script typings". Or running it via gulp or grunt.
