### ISSUE TITLE
Configuration property not passed to grunt

### ISSUE THREAD

**Issue by paulalex** [eirslett/frontend-maven-plugin#400]
I have tried to run a separate grunt goal bound to the pre integration test phase of maven lifecycle, the plugin does not seem to pass the configuration argument to grunt:

<execution>
                        <id>grunt run production build in server</id>
                        <goals>
                            <goal>grunt</goal>
                        </goals>
                        <phase>pre-integration-test</phase>
                        <configuration>
                            <argument>int-test</argument>
                        </configuration>
                    </execution>  

Grunt just runs with the default task and rather than running just the task which kicks off the connect goal it runs my entire default task again. Output from maven below:

[INFO] 
[INFO] --- frontend-maven-plugin:0.0.26:grunt (grunt run production build in server) @ calculator-web ---
[INFO] Running 'grunt --no-color' in D:\STS\workspace\super-pom\calculator\calculator-web
[INFO] >> Local Npm module "grunt-cli" not found. Is it installed?

**Comment by eirslett** [comment]
Yup, looks like a bug in the plugin.
Could you please send a PR to the integration test in this repository, to reproduce the issue there?

**Comment by paulalex** [comment]
Hi you can delete this, it is completely my fault. In face actually I took this from a pom of a large project I am working on and trying to work out how everything works in a smaller project I created myself. NOw I dont know if the elements changed during versions (as I am a first time user) but there is a bug in the pom file which is used by the company I am working for. NOtably they are passing the argument as argument, in fact the element needs to be named arguments... I am really sorry about raising this issue and wasting your time. I dont know how they never noticed but their project only runs the default goal anyway. Apologies again. Paul
