### ISSUE TITLE
Node / npm $PATH fallback ?

### ISSUE THREAD

**Issue by ddewaele** [eirslett/frontend-maven-plugin#402]
When the user opts not to install node/npm via the plugin, the npm goals cannot run, despite the user having npm on its PATH.

```
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.30:npm (npm install) on project project: 
Failed to run task: 'npm install' failed. java.io.IOException: 
Cannot run program "/projects/project/node/node" (in directory "/projects/project"): error=2, No such file or directory -> [Help 1]
```

Would a fallback to $PATH be appropriate ?

**Comment by eirslett** [comment]
No, for a global node/npm installation one should do something like this: https://addyosmani.com/blog/making-maven-grunt/
