### ISSUE TITLE
Not able to Install Node version 4 onwards

### ISSUE THREAD

**Issue by sharathbangera6** [eirslett/frontend-maven-plugin#403]
Hi,

Below is my configuration.

```
<configuration>
    <nodeVersion>v4.4.3</nodeVersion>
    <npmVersion>3.3.3</npmVersion>
</configuration>
```

When **mvn clean install** is done, error is being thrown saying "_**Could not download Node.js from: http://nodejs.org/dist/v4.4.3/x64/node.exe: Got error code 404 from the server**_" .

The path needs to be changed to 

**_http://nodejs.org/dist/v4.4.3/win-x64/node.exe_**

Anyway to do this ?

**Comment by eirslett** [comment]
Which version of the plugin are you using? Try with versoin 1.0?

**Comment by sharathbangera6** [comment]
I think i am using 0.0.20

```
	             <groupId>com.github.eirslett</groupId>
	             <artifactId>frontend-maven-plugin</artifactId>
	             <version>0.0.20</version>
```

Should i change it to 1.0.0

**Comment by eirslett** [comment]
Yes, 1.0 not 1.0.0.

**Comment by lukaszbachman** [comment]
I can confirm that upgrading to 1.0 (and Maven 3.x in the process) solved the same problem for me.

**Comment by wangchuanyin** [comment]
why it's always show "sun.security.validator.ValidatorException: PKIX path building failed:"  when I upgraded  node version to v4.4.3.
