### ISSUE TITLE
allow to set harmony flag for all commands

### ISSUE THREAD

**Issue by rmannibucau** [eirslett/frontend-maven-plugin#407]
Idea is even running node 0.12 to be able to use harmony features (the const one is pretty common) of node

**Comment by eirslett** [comment]
Why not just bump the node version?

**Comment by rmannibucau** [comment]
Cause ops team don't want to do it on the CI machines?

**Comment by eirslett** [comment]
Bumping the node version shouldn't need to involve ops people at all, you only need to configure it in your pom.xml, like in the examples!

**Comment by rmannibucau** [comment]
@eirslett this just doesn't work cause recent versions need a c++11 compiler which is not available on some LTS linux

**Comment by eirslett** [comment]
Ouch, then I guess you're a bit out of luck... With npm, you could do something like

package.json

```
{
  scripts:
    build: "node --harmony_stuff my-build.js"
  }
}
```

And with the npm, mojo, use `<arguments>run-script build</arguments>`.

**Comment by rmannibucau** [comment]
yep but then when it delegates to webpack I loose that feature :(

**Comment by eirslett** [comment]
try
```
scripts: {
  build: "node --harmony_stuff node_modules/webpack/bin/webpack.js"
}
```

**Comment by rmannibucau** [comment]
@eirslett looks like the workaround i was looking for. Thanks a lot!
