### ISSUE TITLE
Node keeps running when killing maven

### ISSUE THREAD

**Issue by fpoliquin** [eirslett/frontend-maven-plugin#41]
When running a Grunt watch task and hitting "Ctrl-C" to stop the process. Node.exe keeps running in the background.

I haven't found a way to kill node.exe other than going manually in the task manager...

We are using a watch task to compile sass files in the background.

**Comment by jrauschenbusch** [comment]
Same problem here.

What is with the possible solution of @tjuerge? Isn't it possible to merge it or isn't it a real solution?
[tjuerge/frontend-maven-plugin/tree/feature/commons-exec](https://github.com/tjuerge/frontend-maven-plugin/tree/feature/commons-exec)
