### ISSUE TITLE
Git is failing

### ISSUE THREAD

**Issue by ad3119** [eirslett/frontend-maven-plugin#414]
I have a node module 'log4javascript' where in I am trying to download it from git. In package.json, i have given git link itself. Since the git support isn't there in the plugin, it is failing to download it. The issue can be solved by installing git in the machine as external s/w. I wanted to know like can you guys provide the support in the same way as doing for Nodejs ?

**Comment by eirslett** [comment]
I don't understand what you mean by "download from git"?

**Comment by gorbeia** [comment]
It seems that several packages are downloaded from a Git repository. If Git is not installed in the system the build fails with the following error:

> ENOGIT git is not installed or not in the PATH bower

It would be great if this plugin could manage the installation of Git for the project as it does with Nodejs.

**Comment by eirslett** [comment]
How can you even fetch your code base in the first place, without git? Do you use Mercurial?
It was discussed earlier to add support for downloading git through this plugin. But it really deserves its own, separate maven plugin.
