### ISSUE TITLE
frontend-maven-plugin assumes target platform is x64?!

### ISSUE THREAD

**Issue by asanjar** [eirslett/frontend-maven-plugin#418]
maven fails to install nodejs-v4.4.4 for ppc64le architecture with the appended  error message:
repository location : http://nodejs.org/dist/v4.4.4/
changing   <nodeVersion>v4.4.4</nodeVersion> to  <nodeVersion>v4.4.4-linux-ppc64le</nodeVersion> does not work either. Please help.
 ------------------------------------------------------------------------
[INFO] Building Zeppelin: web Application 0.5.5-incubating
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ zeppelin-web ---
[INFO] 
[INFO] --- maven-checkstyle-plugin:2.13:check (checkstyle-fail-build) @ zeppelin-web ---
[INFO] 
[INFO] 
[INFO] --- maven-resources-plugin:2.7:copy-resources (copy-resources) @ zeppelin-web ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 17 resources
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce) @ zeppelin-web ---
[INFO] 
[INFO] --- frontend-maven-plugin:1.0:install-node-and-npm (install node and npm) @ zeppelin-web ---
[INFO] Installing node version v4.4.4
[INFO] Unpacking /home/sanjar/.m2/repository/com/github/eirslett/node/4.4.4/node-4.4.4-linux-x64.tar.gz into /home/sanjar/development/zeppelin-0.5.5-incubating/zeppelin-web/node/tmp
[INFO] Copying node binary from /home/sanjar/development/zeppelin-0.5.5-incubating/zeppelin-web/node/tmp/node-v4.4.4-linux-x64/bin/node to /home/sanjar/development/zeppelin-0.5.5-incubating/zeppelin-web/node/node
[INFO] Installed node locally.
[INFO] Installing npm version 2.15.1
[INFO] Downloading http://nodejs.org/dist/npm-2.15.1.tgz to /home/sanjar/.m2/repository/com/github/eirslett/npm/2.15.1/npm-2.15.1.tar.gz
[INFO] No proxies configured
[INFO] No proxy was configured, downloading directly
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.610 s
[INFO] Finished at: 2016-05-14T06:11:52+00:00
[INFO] Final Memory: 23M/316M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:install-node-and-npm (install node and npm) on project zeppelin-web: Could not download npm: Got error code 404 from the server. -> [Help 1]

pom.xml
          <execution>
            <id>install node and npm</id>
            <goals>
              <goal>install-node-and-npm</goal>
            </goals>
            <configuration>
         
              <nodeVersion>v4.4.4</nodeVersion>
              <npmVersion>2.15.1</npmVersion>
              <downloadRoot>http://nodejs.org/dist/</downloadRoot>
            </configuration>
          </execution>

**Comment by eirslett** [comment]
Node.js is fine. Looks like it couldn't find npm. I get 404 too on that URL. What does the pom.xml look like?

**Comment by asanjar** [comment]
Sorry, I thought I had posted the pom.xml as well..   
```
  <execution>
            <id>install node and npm</id>
            <goals>
              <goal>install-node-and-npm</goal>
            </goals>
            <configuration>
              <nodeVersion>v4.4.4</nodeVersion> or <nodeVersion>v4.4.4-linux-ppc64le</nodeVersion> 
              <npmVersion>2.15.1</npmVersion>
              <downloadRoot>http://nodejs.org/dist/</downloadRoot>
            </configuration>
          </execution>


```

**Comment by asanjar** [comment]
also notice the error when "nodeVersion" field is changed to v4.4.4-linux-ppc64le. The generated download link is invalid 
"[INFO] Downloading http://nodejs.org/dist/v4.4.4-linux-ppc64le/node-v4.4.4-linux-ppc64le-linux-x64.tar.gz"
```
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce) @ zeppelin-web ---
[INFO] 
[INFO] --- frontend-maven-plugin:1.0:install-node-and-npm (install node and npm) @ zeppelin-web ---
[INFO] Installing node version v4.4.4-linux-ppc64le
[INFO] Downloading http://nodejs.org/dist/v4.4.4-linux-ppc64le/node-v4.4.4-linux-ppc64le-linux-x64.tar.gz to /home/sanjar/.m2/repository/com/github/eirslett/node/4.4.4-linux-ppc64le/node-4.4.4-linux-ppc64le-linux-x64.tar.gz
[INFO] No proxies configured
[INFO] No proxy was configured, downloading directly
[INFO] ---------------------------------------------------
```

**Comment by eirslett** [comment]
Yes, that's because v4.4.4-linuc-ppc64le is not a node version. The node version os v4.4.4. Putting anything else in `<nodeVersion>` is nonsense :wink:
The download fails because you've set `<downloadRoot>` incorrectly. If you remove it, you should be fine.
If you're trying to run the build on a ppc architecture, that's not something that this plugin currently supports. You would have to add support for it. (Look at Platform.java)

**Comment by asanjar** [comment]
yes, the whole exercise was to include ppc architecture support. A new platform we are adding to Apache Zeppelin. Nevertheless thanks, i will take a look at Platform.java.

**Comment by asanjar** [comment]
I have a patch, what would be the best way to contribute? code change snippet for your review.
```js
enum Architecture {
        x86, x64, ppc64le;
        public static Architecture guess() {
                String arch = System.getProperty("os.arch");
                if (arch.equals("ppc64le")) {
                        return ppc64le;
                } else {
                        return arch.contains("64") ? x64 : x86;
                }
        }
}

```

**Comment by eirslett** [comment]
The best way would be to send a pull request. You also need to update the logic for "getNodeFilename" (or whatever it's called)

**Comment by asanjar** [comment]
@eirslett would you please merge in the pull request #427.  Team has done testing on both Power and X86
