### ISSUE TITLE
Plug-in not working with Maven 3.2.3 org/eclipse/aether/RepositorySystemSession was missing 

### ISSUE THREAD

**Issue by hdzsj2010** [eirslett/frontend-maven-plugin#419]
I use the plugin like this:  
                     <plugin>
                        <groupId>com.github.eirslett</groupId>
                        <artifactId>frontend-maven-plugin</artifactId>

```
                    <configuration>
                        <workingDirectory>${webInterface.path}</workingDirectory>
                    </configuration>

                    <executions>
                        <execution>
                            <id>install node and npm</id>
                            <goals>
                                <goal>install-node-and-npm</goal>
                            </goals>
                            <configuration>
                                <nodeVersion>v4.4.3</nodeVersion>
                                <npmVersion>3.8.6</npmVersion>
                            </configuration>
                        </execution>

                        <execution>
                            <id>npm install</id>
                            <goals>
                                <goal>npm</goal>
                            </goals>
                            <!-- Optional configuration which provides for running any npm command -->
                            <configuration>
                                <arguments>install</arguments>
                            </configuration>
                        </execution>

                        <execution>
                            <id>npm run build</id>
                            <goals>
                                <goal>npm</goal>
                            </goals>
                            <configuration>
                                <arguments>run build</arguments>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
```

but it failed, include execution npm install and execution npm run build, The following is the error information：  
Execution npm install of goal com.github.eirslett:frontend-maven-plugin:1.0:npm failed: A required class was missing while executing com.github.eirslett:frontend-maven-plugin:1.0:npm: Lorg/eclipse/aether/RepositorySystemSession; 
 ----------------------------------------------------- realm = plugin>com.github.eirslett:frontend-maven-plugin:1.0 strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy 
urls[0] = file:/E:/Study/maven-dependcies/com/github/eirslett/
 frontend-maven-plugin/1.0/frontend-maven-plugin-1.0.jar urls[1] = file:/E:/Study/maven-dependcies/com/github/eirslett/
 frontend-plugin-core/1.0/frontend-plugin-core-1.0.jar urls[2] = file:/E:/Study/maven-dependcies/org/codehaus/jackson/
 jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar urls[3] = file:/E:/Study/maven-dependcies/org/codehaus/jackson/
 jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar urls[4] = file:/E:/Study/maven-dependcies/org/apache/commons/
 commons-compress/1.5/commons-compress-1.5.jar urls[5] = file:/E:/Study/maven-dependcies/org/tukaani/xz/1.2/
 xz-1.2.jar
urls[6] = file:/E:/Study/maven-dependcies/commons-io/commons-io/1.3.2/commons-io-1.3.2.jar 
urls[7] = file:/E:/
 Study/maven-dependcies/org/apache/httpcomponents/httpclient/4.5.1/httpclient-4.5.1.jar 
urls[8] = file:/E:/Study/maven-
 dependcies/org/apache/httpcomponents/httpcore/4.4.3/httpcore-4.4.3.jar 
urls[9] = file:/E:/Study/maven-dependcies/
 commons-logging/commons-logging/1.2/commons-logging-1.2.jar 
urls[10] = file:/E:/Study/maven-dependcies/commons-
 codec/commons-codec/1.9/commons-codec-1.9.jar 
urls[11] = file:/E:/Study/maven-dependcies/org/slf4j/slf4j-api/1.7.5/
 slf4j-api-1.7.5.jar 
urls[12] = file:/E:/Study/maven-dependcies/org/eclipse/sisu/org.eclipse.sisu.plexus/0.0.0.M2a/
 org.eclipse.sisu.plexus-0.0.0.M2a.jar 
urls[13] = file:/E:/Study/maven-dependcies/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar 
urls[14] = file:/E:/Study/maven-dependcies/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar 
urls[15] = file:/E:/Study/maven-
 dependcies/javax/inject/javax.inject/1/javax.inject-1.jar 
urls[16] = file:/E:/Study/maven-dependcies/com/google/guava/
 guava/10.0.1/guava-10.0.1.jar 
urls[17] = file:/E:/Study/maven-dependcies/com/google/code/findbugs/jsr305/1.3.9/
 jsr305-1.3.9.jar 
urls[18] = file:/E:/Study/maven-dependcies/org/sonatype/sisu/sisu-guice/3.1.0/sisu-guice-3.1.0-no_aop.jar 
urls[19] = file:/E:/Study/maven-dependcies/aopalliance/aopalliance/1.0/aopalliance-1.0.jar 
urls[20] = file:/E:/Study/maven-
 dependcies/org/eclipse/sisu/org.eclipse.sisu.inject/0.0.0.M2a/org.eclipse.sisu.inject-0.0.0.M2a.jar urls[21] = file:/E:/Study/
 maven-dependcies/asm/asm/3.3.1/asm-3.3.1.jar 
urls[22] = file:/E:/Study/maven-dependcies/org/codehaus/plexus/plexus-
 component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar 
urls[23] = file:/E:/Study/maven-dependcies/org/
 apache/maven/plugin-tools/maven-plugin-annotations/3.2/maven-plugin-annotations-3.2.jar 
urls[24] = file:/E:/Study/maven-
 dependcies/org/codehaus/plexus/plexus-utils/1.5.8/plexus-utils-1.5.8.jar Number of foreign imports: 4 import: 
 Entry[import org.sonatype.plexus.build.incremental from realm ClassRealm[plexus.core, parent: null]] import: Entry[import 
 org.codehaus.plexus.util.Scanner from realm ClassRealm[plexus.core, parent: null]] import: Entry[import 
 org.codehaus.plexus.util.AbstractScanner from realm ClassRealm[plexus.core, parent: null]] import: Entry[import from 
 realm ClassRealm[maven.api, parent: null]] ----------------------------------------------------- (com.github.eirslett:frontend-
 maven-plugin:1.0:npm:npm install:generate-resources)

**Comment by tarwirdur** [comment]
For me too.
It works but there are the same errors in eclipse `Problems` frame.

My maven version is 3.1.1
Eclipse version: Kepler Service Release 2 [20140224-0627]

frontend-maven-plugin 0.0.28 works without such errors. 0.0.29 and 1.0 - with them.

**Comment by gcosarba** [comment]
Same issue, same fix. 0.0.28 gives no error. All subsequent versions up to 1.6 at time of writing give the same error.

**Comment by eirslett** [comment]
Try using a slightly newer version of Maven. The appveyor build uses Maven version 3.2.5.
