### ISSUE TITLE
com.github.eirslett:frontend-maven-plugin:1.0 not found in IntellJ 15.0.3

### ISSUE THREAD

**Issue by avatarr** [eirslett/frontend-maven-plugin#421]
![screenshot from 2016-05-18 22-27-39](https://cloud.githubusercontent.com/assets/1640817/15364940/8e7a7b42-1d48-11e6-93e3-f1cf3c277275.png)

I have config in above image but I try to sync maven many time still get "com.github.eirslett:frontend-maven-plugin:1.0 not found"

System information
Ubuntu 16.04 x64
Maven  3.3.9
IntellJ 15.0.3

How do I fix this problem? 

Thank in advance

**Comment by avatarr** [comment]
My Maven info
![screenshot from 2016-05-18 22-49-27](https://cloud.githubusercontent.com/assets/1640817/15365716/73ad348c-1d4b-11e6-9112-b0eeef7b015e.png)

**Comment by eirslett** [comment]
What happens if you run mvn from the command line?

**Comment by avatarr** [comment]
Thank you for reply. I'm new in maven and Spring boot. I don't know must use mvn. For this issue I use IntellJ create maven project but I try to create another project with Spring Initializr is worked 

I will try again with maven project for investigate

**Comment by Toilal** [comment]
Same issue with latest intellij idea version. 

All is working smoothly from mvn command line though.

**Comment by n00dl3** [comment]
Netbeans uses the same maven version as intelliJ idea: 3.0.5 : doesn't work neither

**Comment by rockneverdies55** [comment]
I had a similar issue with `LATEST_VERSION` as the version. Replacing that with `1.6` in the pom file fixed the problem for me.
