### ISSUE TITLE
plugin 1.0 error when compile 

### ISSUE THREAD

**Issue by shijinkui** [eirslett/frontend-maven-plugin#422]
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:install-node-and-npm (install node and npm) on project example: The plugin com.github.eirslett:frontend-maven-plugin:1.0 requires Maven version 3.1.0 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginIncompatibleException

**Comment by shijinkui** [comment]
the https://github.com/eirslett/frontend-maven-plugin/blob/master/frontend-maven-plugin/src/it/example%20project/pom.xml  can't run complete

**Comment by eirslett** [comment]
I think this is the same as the other issue?
You meed maven 3.1 or newer.
