### ISSUE TITLE
Using the plugin when deploying to Tomcat from IDE's

### ISSUE THREAD

**Issue by micopiira** [eirslett/frontend-maven-plugin#424]
Sorry if this is not the correct place to ask about this.

Is it possible to get this plugin to execute when deploying a web application from IntelliJ IDEA/Eclipse to a Tomcat Server without the need to execute a maven command yourself?

So when I click the Run on server button, whatever the IDE's do, they apparently don't fire the `generate-resources` phase? If I run for example `mvn package` myself, and then run the application, it works fine.

**Comment by eirslett** [comment]
I think it's possible to set a "before run" hook in IntelliJ that runs mvn generate-resources?

**Comment by micopiira** [comment]
@eirslett Okay. I'm looking for a solution that would not need any more actions from any of the developers, so something in the pom.xml I suppose (the ide's atleast read it?). Too bad if that is not possible but would be nice.

**Comment by eirslett** [comment]
You could try to send a [PR to IntelliJ](https://github.com/JetBrains/intellij-community) to add functionality for the editor, so that it runs some maven hook before starting, without involving developers. I think you might have more luck asking over there!
