### ISSUE TITLE
protractor integration tests

### ISSUE THREAD

**Issue by harikusumba** [eirslett/frontend-maven-plugin#425]
Hi,

This not an issue perse.

Thank you much for the plugin, we are successfully using it. Is there a possibility of adding a new goal like protractor e2e tests to the maven. I guess it needs some changes to the Java code. Is that something you plan to add. 

Regards
Hari

**Comment by eirslett** [comment]
Hey! I'm happy to hear that the plugin works for you! I suggest you run Protractor with the npm mojo, with `<arguments>` set to "run-script protractor".
