### ISSUE TITLE
A required class was missing while executing com.github.eirslett:frontend-maven-plugin:0.0.27:install-node-and-npm: org/apache/http/HttpRequest

### ISSUE THREAD

**Issue by monsario** [eirslett/frontend-maven-plugin#426]
I am the last stages of building the application. And I am stuck at getting this error below:

A required class was missing while executing com.github.eirslett:frontend-maven-plugin:0.0.27:install-node-and-npm: org/apache/http/HttpRequest

Anybody encoutered and solved this?

Here are some of my logs:

==================================================

[INFO] Reactor Summary:
[INFO] 
[INFO] com.capitalone.dashboard:Hygieia ................... SUCCESS [  0.742 s]
[INFO] com.capitalone.dashboard:core ...................... SUCCESS [ 42.304 s]
[INFO] com.capitalone.dashboard:api ....................... SUCCESS [ 25.977 s]
[INFO] com.capitalone.dashboard:jenkins-build-collector ... SUCCESS [  2.845 s]
[INFO] com.capitalone.dashboard:sonar-codequality-collector SUCCESS [  1.144 s]
[INFO] com.capitalone.dashboard:subversion-collector ...... SUCCESS [  0.886 s]
[INFO] com.capitalone.dashboard:github-scm-collector ...... SUCCESS [  1.816 s]
[INFO] com.capitalone.dashboard:stash-scm-collector ....... SUCCESS [11:22 min]
[INFO] com.capitalone.dashboard:versionone-feature-collector SUCCESS [  3.309 s]
[INFO] com.capitalone.dashboard:udeploy-deployment-collector SUCCESS [  3.056 s]
[INFO] com.capitalone.dashboard:jira-feature-collector .... SUCCESS [ 27.972 s]
[INFO] com.capitalone.dashboard:jenkins-cucumber-test-collector SUCCESS [  2.239 s]
[INFO] com.capitalone.dashboard:chat-ops-collector ........ SUCCESS [  0.756 s]
[INFO] com.capitalone.dashboard:UI ........................ FAILURE [  0.076 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13:15 min
[INFO] Finished at: 2016-05-26T10:22:18-05:00
[INFO] Final Memory: 123M/1402M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.27:install-node-and-npm (install node and npm) on project UI: Execution install node and npm of goal com.github.eirslett:frontend-maven-plugin:0.0.27:install-node-and-npm failed: A required class was missing while executing com.github.eirslett:frontend-maven-plugin:0.0.27:install-node-and-npm: org/apache/http/HttpRequest
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.github.eirslett:frontend-maven-plugin:0.0.27
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/ljp978/.m2/repository/com/github/eirslett/frontend-maven-plugin/0.0.27/frontend-maven-plugin-0.0.27.jar
[ERROR] urls[1] = file:/Users/ljp978/.m2/repository/com/github/eirslett/frontend-plugin-core/0.0.27/frontend-plugin-core-0.0.27.jar
[ERROR] urls[2] = file:/Users/ljp978/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar
[ERROR] urls[3] = file:/Users/ljp978/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar
[ERROR] urls[4] = file:/Users/ljp978/.m2/repository/org/apache/commons/commons-compress/1.5/commons-compress-1.5.jar
[ERROR] urls[5] = file:/Users/ljp978/.m2/repository/org/tukaani/xz/1.2/xz-1.2.jar
[ERROR] urls[6] = file:/Users/ljp978/.m2/repository/commons-io/commons-io/1.3.2/commons-io-1.3.2.jar
[ERROR] urls[7] = file:/Users/ljp978/.m2/repository/org/apache/httpcomponents/httpclient/4.5.1/httpclient-4.5.1.jar
[ERROR] urls[8] = file:/Users/ljp978/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
[ERROR] urls[9] = file:/Users/ljp978/.m2/repository/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar
[ERROR] urls[10] = file:/Users/ljp978/.m2/repository/com/google/guava/guava/10.0.1/guava-10.0.1.jar
[ERROR] urls[11] = file:/Users/ljp978/.m2/repository/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar
[ERROR] urls[12] = file:/Users/ljp978/.m2/repository/org/sonatype/sisu/sisu-guice/3.1.0/sisu-guice-3.1.0-no_aop.jar
[ERROR] urls[13] = file:/Users/ljp978/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
[ERROR] urls[14] = file:/Users/ljp978/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.0.0.M2a/org.eclipse.sisu.inject-0.0.0.M2a.jar
[ERROR] urls[15] = file:/Users/ljp978/.m2/repository/asm/asm/3.3.1/asm-3.3.1.jar
[ERROR] urls[16] = file:/Users/ljp978/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[17] = file:/Users/ljp978/.m2/repository/org/apache/maven/plugin-tools/maven-plugin-annotations/3.2/maven-plugin-annotations-3.2.jar
[ERROR] urls[18] = file:/Users/ljp978/.m2/repository/org/sonatype/plexus/plexus-build-api/0.0.7/plexus-build-api-0.0.7.jar
[ERROR] urls[19] = file:/Users/ljp978/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.8/plexus-utils-1.5.8.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------: org.apache.http.HttpRequest
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :UI
6c4008975eba:Hygieia ljp978$ cd UI
6c4008975eba:UI ljp978$ mvn clean package integration-test
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building com.capitalone.dashboard:UI 2.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ UI ---
[INFO] 
[INFO] >>> maven-pmd-plugin:3.6:check (default) > :pmd @ UI >>>
[INFO] 
[INFO] --- maven-pmd-plugin:3.6:pmd (pmd) @ UI ---
[INFO] 
[INFO] <<< maven-pmd-plugin:3.6:check (default) < :pmd @ UI <<<
[INFO] 
[INFO] --- maven-pmd-plugin:3.6:check (default) @ UI ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.6.201602180812:prepare-agent (default) @ UI ---
[INFO] argLine set to -javaagent:/Users/ljp978/.m2/repository/org/jacoco/org.jacoco.agent/0.7.6.201602180812/org.jacoco.agent-0.7.6.201602180812-runtime.jar=destfile=/Users/ljp978/workspace/Hygieia/UI/target/jacoco.exec
[INFO] 
[INFO] --- frontend-maven-plugin:0.0.27:install-node-and-npm (install node and npm) @ UI ---
[INFO] Found proxies: []
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.269 s
[INFO] Finished at: 2016-05-26T12:09:32-05:00
[INFO] Final Memory: 20M/309M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.27:install-node-and-npm (install node and npm) on project UI: Execution install node and npm of goal com.github.eirslett:frontend-maven-plugin:0.0.27:install-node-and-npm failed: A required class was missing while executing com.github.eirslett:frontend-maven-plugin:0.0.27:install-node-and-npm: org/apache/http/HttpRequest
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.github.eirslett:frontend-maven-plugin:0.0.27
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/ljp978/.m2/repository/com/github/eirslett/frontend-maven-plugin/0.0.27/frontend-maven-plugin-0.0.27.jar
[ERROR] urls[1] = file:/Users/ljp978/.m2/repository/com/github/eirslett/frontend-plugin-core/0.0.27/frontend-plugin-core-0.0.27.jar
[ERROR] urls[2] = file:/Users/ljp978/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar
[ERROR] urls[3] = file:/Users/ljp978/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar
[ERROR] urls[4] = file:/Users/ljp978/.m2/repository/org/apache/commons/commons-compress/1.5/commons-compress-1.5.jar
[ERROR] urls[5] = file:/Users/ljp978/.m2/repository/org/tukaani/xz/1.2/xz-1.2.jar
[ERROR] urls[6] = file:/Users/ljp978/.m2/repository/commons-io/commons-io/1.3.2/commons-io-1.3.2.jar
[ERROR] urls[7] = file:/Users/ljp978/.m2/repository/org/apache/httpcomponents/httpclient/4.5.1/httpclient-4.5.1.jar
[ERROR] urls[8] = file:/Users/ljp978/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
[ERROR] urls[9] = file:/Users/ljp978/.m2/repository/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar
[ERROR] urls[10] = file:/Users/ljp978/.m2/repository/com/google/guava/guava/10.0.1/guava-10.0.1.jar
[ERROR] urls[11] = file:/Users/ljp978/.m2/repository/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar
[ERROR] urls[12] = file:/Users/ljp978/.m2/repository/org/sonatype/sisu/sisu-guice/3.1.0/sisu-guice-3.1.0-no_aop.jar
[ERROR] urls[13] = file:/Users/ljp978/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
[ERROR] urls[14] = file:/Users/ljp978/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.0.0.M2a/org.eclipse.sisu.inject-0.0.0.M2a.jar
[ERROR] urls[15] = file:/Users/ljp978/.m2/repository/asm/asm/3.3.1/asm-3.3.1.jar
[ERROR] urls[16] = file:/Users/ljp978/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[17] = file:/Users/ljp978/.m2/repository/org/apache/maven/plugin-tools/maven-plugin-annotations/3.2/maven-plugin-annotations-3.2.jar
[ERROR] urls[18] = file:/Users/ljp978/.m2/repository/org/sonatype/plexus/plexus-build-api/0.0.7/plexus-build-api-0.0.7.jar
[ERROR] urls[19] = file:/Users/ljp978/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.8/plexus-utils-1.5.8.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------: org.apache.http.HttpRequest
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException

**Comment by yaodingyd** [comment]
@monsario Have you figured out a way fix this? I run into similar problem.

**Comment by xuelvming** [comment]
Excuse me, why you close this issue without a solution or comment,is it already fixed? Cause I have the same issue here. Thanks.  @monsario

**Comment by dufootball11** [comment]
also running into this issue, would love to know if anyone finds a solution!

**Comment by eirslett** [comment]
Try deleting the .m2 folder?

**Comment by yaodingyd** [comment]
Try add these two dependencies for this plugin:
```xml
<dependencies>
  <dependency>
    <groupId>org.apache.httpcomponents</groupId>
    <artifactId>httpcore</artifactId>
    <version>4.4</version>
  </dependency>
  <dependency>
    <groupId>commons-logging</groupId>
    <artifactId>commons-logging</artifactId>
    <version>1.1.1</version>
  </dependency>
</dependencies>
```

it worked for me.

**Comment by dufootball11** [comment]
Thanks @eirslett and @yaodingyd, upping my httpClient to `4.5.1` and wiping the `.m2/repository` folder worked!

**Comment by mcahornsirup** [comment]
I have fixed it by remove ~/m2/repository/com/github/eirslett and build again with version 1.6.
