### ISSUE TITLE
Clarification on goal execution order - seeing karma after webpack

### ISSUE THREAD

**Issue by icfantv** [eirslett/frontend-maven-plugin#441]
Can someone please clarify the order the goals are executed?  I'm using node, webpack, and karma and I'd expect the `karma` goal to be executed BEFORE the `webpack` goal because I shouldn't be testing my transpiled files and thus there's no reason to have `webpack` run before karma (let alone at all) - but this is precisely what is happening.

The goal order I'm seeing in my console is:  npm, webpack, karma and not npm, karma, webpack.

Not only that, but I would think that running a `mvn test` would not run the `webpack` goal at all.

Can someone please provide some clarity here?  Thanks.

**Comment by eirslett** [comment]
You can see in the mojo source code what the default phases are. You can also override them however you want.

**Comment by icfantv** [comment]
Ok, I'll take a look, thanks.
