### ISSUE TITLE
Doesn't work with maven 3.3.3

### ISSUE THREAD

**Issue by danielekowalik** [eirslett/frontend-maven-plugin#442]
The plugin com.github.eirslett:frontend-maven-plugin:1.0 requires Maven version 3.1.0

**Comment by eirslett** [comment]
It works with every Maven version newer than 3.1.0.

**Comment by hiqbal01** [comment]
Check the version of Maven your IDE is using. I thought I was on 3.3.3 as well which is what is installed on my system, but IntelliJ was using 3.0.5. You can rectify this in the Settings menu on the Maven page in IntelliJ.
