### ISSUE TITLE
How to use "node_modules" in root directory?

### ISSUE THREAD

**Issue by bennyn** [eirslett/frontend-maven-plugin#445]
Hello, I am using your handy plugin and this is my configuration:

```xml
<plugin>
  <groupId>com.github.eirslett</groupId>
  <artifactId>frontend-maven-plugin</artifactId>
  <version>1.0</version>
  <executions>
    <execution>
      <id>install node and npm</id>
      <goals>
        <goal>install-node-and-npm</goal>
      </goals>
      <phase>generate-resources</phase>
      <configuration>
        <nodeVersion>v5.3.0</nodeVersion>
        <npmVersion>3.10.5</npmVersion>
      </configuration>
    </execution>
    <execution>
      <id>npm install</id>
      <goals>
        <goal>npm</goal>
      </goals>
      <configuration>
        <arguments>install</arguments>
      </configuration>
    </execution>
    <execution>
      <id>gulp build</id>
      <goals>
        <goal>gulp</goal>
      </goals>
    </execution>
  </executions>
</plugin>
```

When `install-node-and-npm` runs, it installs all Node dependencies into `node/node_modules`. But I want them to appear in `node_modules`. Any chance to change that?

**Comment by eirslett** [comment]
That's very strange... They are supposed to end up in the root directory by default.

**Comment by bennyn** [comment]
My bad. I think it's just `npm` which is installed there. Because I get these directories:

- `node/node_modules/npm`
- `node_modules/[everything_else]`

Thanks for your fast reply! :smiley:

**Comment by gladsonrobinson** [comment]
HI, Getting same issue can you help me on how you solved it.
