### ISSUE TITLE
node_modules location

### ISSUE THREAD

**Issue by jelohazi** [eirslett/frontend-maven-plugin#449]
By default node would traverse the folder structure to find the dependecy in a node_modules directory, but using this plugin this isn't happening.
Our UI project consists of multiple sub projects. Installing node and downloading node dependencies for each makes the fresh build time 40 minutes. If install node and the dependencies in the root folder of the projects, the build time is only 4 minutes. I don't want to create a maven script that installs node on the machine wherever it's executed.

Just like specifying the node installation directory is there a way to specify the node_modules location? Specifying the working directory would not work in this case.

Thanks for the help!

**Comment by jelohazi** [comment]
Well apparently I found a workaround by using this setting:
`<execution>
  <id>gulp build</id>
  <phase>process-classes</phase>
  <goals>
    <goal>gulp</goal>
  </goals>
  <configuration>
    <arguments>clean-build ${ui_env} --gulpfile ${basedir}/gulpfile.js</arguments>
    <installDirectory>..</installDirectory>
    <workingDirectory>..</workingDirectory>
  </configuration>
</execution>`

By specifying the gulpfile resets the working directory but it will still find my node modules a level up

**Comment by docent** [comment]
I vote for an ability to do this.
Because node_modules ends up in source dir, it is being picked up by Idea and indexed, which takes ages.

**Comment by eirslett** [comment]
You'll have to mark node_modules as an excluded directory in the IDE, then it won't be indexed.
Looks like the issue was resolved! Another way to speed up builds is to use yarn instead of npm.
