### ISSUE TITLE
 Could not download npm

### ISSUE THREAD

**Issue by ashishdoneriya** [eirslett/frontend-maven-plugin#450]
I used node version 6.3.1 and npm version 3.9.5
<pre>&lt;nodeVersion&gt;v6.3.1&lt;/nodeVersion&gt;
&lt;npmVersion&gt;3.9.5&lt;/npmVersion&gt;</pre>

And then build failed
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:install-node-and-npm (install node and npm) on project transactionManager: Could not download npm: Got error code 500 from the server.

It was trying to download from http://registry.npmjs.org/npm/-/npm-3.9.5.tgz

**Comment by ashishdoneriya** [comment]
I tried again and then new error

[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:install-node-and-npm (install node and npm) on project transactionManager: Could not extract the npm archive: Could not extract archive: '/home/impadmin/.m2/repository/com/github/eirslett/npm/3.9.5/npm-3.9.5.tar.gz': EOFException -&gt; [Help 1]

**Comment by randycasburn** [comment]
+1

**Comment by mriehema** [comment]
Sounds like network problems with empty files (EOFException). Please delete all downloaded files in `/home/impadmin/.m2/repository/com/github/eirslett` and retry.

**Comment by randycasburn** [comment]
I think I can confirm the "network problems" in my case. In retrospect, the wifi I was on was having trouble. As soon as both of us (two having the same trouble) moved to a different (wired) network, it worked as advertised.  That's why I deleted my +1.

Thanks for the update.

**Comment by eirslett** [comment]
I'll close this then!

**Comment by mriehema** [comment]
Maybe we can add a file length/checksum check to cached files to identify corrupted files.
