### ISSUE TITLE
Node download url is wrong for Windows

### ISSUE THREAD

**Issue by seetsy** [eirslett/frontend-maven-plugin#451]
When running the "install-node-and-npm" goal from Windows, the download url results in a 404:

> Could not download Node.js from:
> http://nodejs.org/dist/v4.4.7/x64/node.exe: Got error code 404 from the server.

This is specifically a Windows problem, as it works fine on nix and OSX. The correct url is:

http://nodejs.org/dist/v4.4.7/win-x64/node.exe

Is there a way to manually override the download url?

Here's my maven pom example:
`<plugin>
                <groupId>com.github.eirslett</groupId>
                <artifactId>frontend-maven-plugin</artifactId>
                <configuration>
                    <workingDirectory>myDirectory</workingDirectory>
                </configuration>
                <version>0.0.22</version>
                <executions>
                    <execution>
                        <id>install node and npm</id>
                        <goals>
                            <goal>install-node-and-npm</goal>
                        </goals>
                        <configuration>
                            <nodeVersion>v4.4.7</nodeVersion>
                            <npmVersion>2.15.8</npmVersion>
                        </configuration>
                    </execution>`

**Comment by seetsy** [comment]
Ok never mind, I updated from version 0.0.22 to 1.0 and the problem is fixed. Thanks for this very helpful plugin!

**Comment by kevinhooke** [comment]
Is there a fix for 0.0.22? I'm using this version per the Wiki as the last version supported with Maven 2. Can I move to 1.0 and still use with Maven 2? (I'll try it in the meantime and see what happens)

**Comment by eirslett** [comment]
> Is there a fix for 0.0.22? I'm using this version per the Wiki as the last version supported with Maven 2. Can I move to 1.0 and still use with Maven 2? (I'll try it in the meantime and see what happens)

Will you update the wiki if you find out it's possible? I guess we should advise people to be on a somewhat new version of the plugin.
