### ISSUE TITLE
Download Node as Zip on Windows

### ISSUE THREAD

**Issue by MehrCurry** [eirslett/frontend-maven-plugin#457]
Is it possible to download Node.js as a Zip File rather than as Exe on Windows?

Our Corporate firewall blocks downloading Exe files. Is there an option availible to switch between Exe and Zip downloads?

Anyway, thanks for this great plugin.

Guido

**Comment by eirslett** [comment]
No, unfortunately not.You will have to whitelist the node.js binaries in the firewall.

**Comment by ermicioi** [comment]
Looks like it is possible, at least in version 1.8.0 or 1.9.1, it is to not configure npm version, and then plugin will download zip
