### ISSUE TITLE
frontend-maven-plugin in public maven repository 

### ISSUE THREAD

**Issue by asanjar** [eirslett/frontend-maven-plugin#463]
hi,
When should we expect an update to public maven repository with the latest release. Last update was made on April https://mvnrepository.com/artifact/com.github.eirslett/frontend-maven-plugin
we have a dependency on ppc64le architecture support that was added later. 
Regards
Amir Sanjar

**Comment by mriehema** [comment]
I would suggest to create a new release after merging https://github.com/eirslett/frontend-maven-plugin/pull/470. What do you think, @eirslett?

**Comment by eirslett** [comment]
Sounds like a good idea.

**Comment by asanjar** [comment]
If possible, I would like to have an opportunity to conduct a regression test on the latest build (including #470 and any other new patches) on ppc64le platform before assigning a new release. Let me know when ready.

**Comment by aciccarello** [comment]
I think this can be closed :smile:
