### ISSUE TITLE
Is there a way to install npm packages into target directory?

### ISSUE THREAD

**Issue by maurocchi** [eirslett/frontend-maven-plugin#465]
Even using the configuration specified in the readme the `node_modules` folder is created at the `package.json` level:
```
<execution>
    <id>npm install</id>
    <goals>
        <goal>npm</goal>
    </goals>
    <configuration>
        <arguments>install</arguments>
        <installDirectory>target</installDirectory>
    </configuration>
</execution>
```

Is it possible to install these packages into a different directory in a smart way (as example without to copy the `package.json` into such folder)?

**Comment by mriehema** [comment]
Please see [npm docs](https://docs.npmjs.com/files/folders), as this is the default behaviour of npm. Not a frontend-maven-plugin issue.

**Comment by maurocchi** [comment]
It is an issue if the plugin declares to install the modules in a configurable directory. Therefore I suggest to fix the documentation, it gives false hopes.

**Comment by eirslett** [comment]
It installs node/npm into installDirectory, but node modules are installed into node_modules, which is default npm behavior. Maybe the docs should be clearer?

**Comment by mriehema** [comment]
Yes, sounds legit. I still have a branch with some doc changes, I will add this one and open a PR asap.

**Comment by maurocchi** [comment]
Ok I've understood the misunderstanding: the `installDirectory` refers to the installation directory of npm, it doesn't refer to the directory where the modules are installed by npm.
In this case I agree to clarify the docs.

Thanks you all.

**Comment by hwellmann** [comment]
That still doesn't answer the original question.

From the Maven point of view, `package.json` is a source file, whereas `node_modules/**` is derived, and any derived files should be somewhere under `target` instead of polluting `src` or the base directory.

So it doesn't really matter what the default behaviour of npm is, the question is if this default can or should be overridden by `frontend-maven-plugin` so that the npm build step behaves like a good citizen in Maven land.

**Comment by eirslett** [comment]
To answer the original question: No. There is no way.

I'm sorry, there is really nothing this plugin can do. The node/npm guys have really strong opinions about this, including problems with backwards compatibility.

https://tools.ietf.org/doc/npm/misc/npm-faq.html

> ## "node_modules" is the name of my deity's arch-rival, and a Forbidden Word in my religion. Can I configure npm to use a different folder?
> 
> No. This will never happen. This question comes up sometimes, because it seems silly from the outside that npm couldn't just be configured to put stuff somewhere else, and then npm could load them from there. It's an arbitrary spelling choice, right? What's the big deal?
>
> At the time of this writing, the string 'node_modules' appears 151 times in 53 separate files in npm and node core (excluding tests and documentation).
>
> Some of these references are in node's built-in module loader. Since npm is not involved at all at run-time, node itself would have to be configured to know where you've decided to stick stuff. Complexity hurdle `#1`. Since the Node module system is locked, this cannot be changed, and is enough to kill this request. But I'll continue, in deference to your deity's delicate feelings regarding spelling.
>
> Many of the others are in dependencies that npm uses, which are not necessarily tightly coupled to npm (in the sense that they do not read npm's configuration files, etc.) Each of these would have to be configured to take the name of the node_modules folder as a parameter. Complexity hurdle `#2`.
>
> Furthermore, npm has the ability to "bundle" dependencies by adding the dep names to the "bundledDependencies" list in package.json, which causes the folder to be included in the package tarball. What if the author of a module bundles its dependencies, and they use a different spelling for node_modules? npm would have to rename the folder at publish time, and then be smart enough to unpack it using your locally configured name. Complexity hurdle `#3`.
>
> Furthermore, what happens when you change this name? Fine, it's easy enough the first time, just rename the node_modules folders to ./blergyblerp/ or whatever name you choose. But what about when you change it again? npm doesn't currently track any state about past configuration settings, so this would be rather difficult to do properly. It would have to track every previous value for this config, and always accept any of them, or else yesterday's install may be broken tomorrow. Complexity hurdle `#5`.
>
> Never going to happen. The folder is named node_modules. It is written indelibly in the Node Way, handed down from the ancient times of Node 0.3.

If you really don't want to have that node_modules folder, you'll have to use something else than Node.js for your frontend build system (e.g. [JAWR](https://jawr.java.net/)).

If you can live with the node_modules folder being there, in the file system, try .gitignore-ing it, and possibly configure maven-clean-plugin so it removes that directory when you run `mvn clean`. It will be have exactly like if the node_modules were inside the target directory.

**Comment by hwellmann** [comment]
Ok, so this is just another brain-dead feature of npm, just like duplicating dependencies all over the place instead of referencing the from _one_ local repository like Maven does.

I'm glad that `frontend-maven-plugin` shields us Java guys at least from _some_ of that insanity...

Yes, I'm using `.gitignore` already. Thanks for your pointers!

**Comment by arend-von-reinersdorff** [comment]
You could [copy](https://maven.apache.org/plugins/maven-resources-plugin/copy-resources-mojo.html) `package.json` to `target/frontend` and invoke the frontend-maven-plugin there.

**Comment by reflexdemon** [comment]
Try creating a file `.npmrc` in your project folder and add the following,
```
prefix=target/npm
```

See http://stackoverflow.com/questions/14742553/npm-local-install-package-to-custom-location
and https://docs.npmjs.com/files/folders. Hope this helps

**Comment by Nashorn** [comment]
What a serious drawback of the NPM architecture, installing any and everything into a hardcoded "node_modules" folder. Thats just shi* design.

How nice it would of been to declare each dependency in package.json, pointing to it's own target directory?
