### ISSUE TITLE
[WARNING] npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0

### ISSUE THREAD

**Issue by gallaouim** [eirslett/frontend-maven-plugin#472]
Im blocked in this Warnings when i try mvn package 
[INFO] --- frontend-maven-plugin:1.0:npm (npm install) @ Ws_fairNETZ_Java ---
[INFO] Running 'npm install' in /home/gallaoui/SC-fairNETZ-Suchmaschine/Ws_fairNETZ_Java/src/main/Wui_fairNETZ_Js
[WARNING] npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks for all the usage over the years.
[WARNING] npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[WARNING] npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
[WARNING] npm WARN deprecated lodash.isarray@4.0.0: This package is deprecated. Use Array.isArray.
[WARNING] npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[WARNING] npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
[WARNING] npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
[WARNING] npm WARN deprecated lodash.assign@4.2.0: This package is deprecated. Use Object.assign.
[WARNING] npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[WARNING] npm WARN deprecated minimatch@1.0.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[WARNING] npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.

**Comment by eirslett** [comment]
It's not a problem related to this plugin, it's your package.json that had outdated dependencies. Ignore the warnings, or update the dependencies, that will fix it!

**Comment by gallaouim** [comment]
fixed , now i become this one 
[ERROR] gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/6.3.1"
