### ISSUE TITLE
Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.22:install-node-and-npm (install node and npm)  

### ISSUE THREAD

**Issue by dbhovi** [eirslett/frontend-maven-plugin#473]
I am trying to download the node in the using

`<executions>
                    <execution>
                        <id>install node and npm</id>
                        <goals>
                            <goal>install-node-and-npm</goal>
                        </goals>
                        <configuration>
                            <nodeVersion>v4.4.0</nodeVersion>
                            <npmVersion>2.15.1</npmVersion>
                            <downloadRoot>https://nodejs.org/dist/</downloadRoot>
                            </configuration>
                    </execution>
`

the goal is failing since it is downloading from url https://nodejs.org/dist/v4.4.0/x64/node.exe instead of https://nodejs.org/dist/v4.4.0/win-x64/ . when i give a complete url in the downloadRoot like  https://nodejs.org/dist/v4.4.0/win-x64/ the values get appended something like 
https://nodejs.org/dist/v4.4.0/win-x64/v4.4.0/x64

**Comment by mriehema** [comment]
Please update to 1.0. The download URLs of node changed some time ago.
