### ISSUE TITLE
Support for maven version 3.0.3

### ISSUE THREAD

**Issue by findpritz** [eirslett/frontend-maven-plugin#485]
Hi,

I am trying to use the v1.0 of this frontend-maven-plugin on a build system which runs Maven v3.0.3. This results in an results as shown below:

`[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:install-node-and-npm (install node an
 npm) on project abc: The plugin com.github.eirslett:frontend-maven-plugin:1.0 requires Maven version 3.1.0 ->
Help 1]`

Any idea how to use this plugin with the above mentioned maven version??

**Comment by eirslett** [comment]
There are some very old versions of the plugin (version 0.0.10 maybe) that work with older versions of Maven.
