### ISSUE TITLE
Support for yarn

### ISSUE THREAD

**Issue by gunnarvelle** [eirslett/frontend-maven-plugin#490]
Yarn package manager is a new tool wich can replace the npm client. A goal to run yarn would be nice.

https://yarnpkg.com

**Comment by eirslett** [comment]
You could hack this together with the existing plugin. Do npm install yarn (not -g) with the npm mojo, and then have a package.json with (untested pseudocode)

```javascript
{
  scripts: {
    "yarn": "node node_modules/yarn/bin-something/yarn.js"
  }
}
```

And then, with the npm mojo again, do `npm run-script yarn`.

You could commit node_modules/yarn/* into your git repository if you want to skip the npm install yarn step.

It's a bit of work to implement first-class support for yarn. I suppose it's possible, if somebody is willing to take on the work.

**Comment by marcins** [comment]
Ideally it would be first-class support as an alternative to npm rather than just a goal to run yarn - so you could specify which yarn version you want, and it'd be installed like npm gets installed as part of the `install-node-and-npm` goal (`install-node-and-yarn`? 😄 )

In our project we're currently blocked by yarn's lack of private registry support, but once we can use yarn I'll check back in to see where this issue is at. It's something I'd be potentially willing to help with once we need it!

**Comment by mriehema** [comment]
Yarn looks promising. But it's in a very early stage. We should keep this ticket open and keep watching how yarn is developing. Nonetheless feel free to create a pull request for a `install-node-and-yarn` execution. But AFAIK yarn has just installer downloads (at least for Windows) and no simple executables, which are needed for this plugin.

**Comment by mgohin** [comment]
With Yarn, my Jenkins Build (maven) from 1m35 to 25s, pretty nice. I had to remove this plugin to use a custom sh file with commands, I'd to put back this plugin with Yarn support ;)

**Comment by mgohin** [comment]
Any news ? @maybeec made a PR

**Comment by eirslett** [comment]
Just merged #499 which closes this issue.

**Comment by mgohin** [comment]
A release soon ?

**Comment by nanndoj** [comment]
+1 waiting for s release soon

**Comment by eirslett** [comment]
v1.2 will be out now, once Maven central syncs with OSS Sonatype.

**Comment by tatsujb** [comment]
where is this at?

the only people who are going to be using frontend-maven-plugin are employees working on a company project : thus behind proxy.

You can't get yarn via github.

this should be at least in the readme : 
in cmd or Powershell : (so that it at least works locally to boot and get you off the ground)
(you will of course need npm to be proxy-config-ed beforehand)
(change username, password, url, and port to appropriate) 
```
npm i -g yarn
yarn config set proxy=http://USERNAME:PASSWORD@URL:PORT/
yarn config set https-proxy=http://USERNAME:PASSWORD@URL:PORT/
yarn config set strict-ssl=true
```

pom.xml : 
```
                <executions>
	                  <execution>
                        <id>install-node-and-npm</id>
                        <goals>
                            <goal>install-node-and-npm</goal>
                        </goals>
                        <configuration>
                            <nodeVersion>${node.version}</nodeVersion>
                            <npmVersion>${npm.version}</npmVersion>
                            <nodeDownloadRoot>${node.download-root}</nodeDownloadRoot>
                            <npmDownloadRoot>${npm.download-root}</npmDownloadRoot>
                            <npmRegistryURL>${npm.registry-URL}</npmRegistryURL>
                        </configuration>
                    </execution>
                    <execution>
                        <id>install yarn with npm</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <configuration>
                            <arguments>install yarn</arguments>
                        </configuration>
                    </execution>
                    <execution>
                        <id>yarn install</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <configuration>
                            <arguments>run-script yarn --strict-ssl=false</arguments>
                        </configuration>
                    </execution>
                    <execution>
                        <id>npm-build</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <configuration>
                            <arguments>run-script build</arguments>
                        </configuration>
                    </execution>
                </executions>
```

pakage.json : 
```
{
  "name": "myapp",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "parcel": "parcel",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "yarn": "node node_modules/yarn/bin/yarn.js"
  },
  "private": true,
  "dependencies": {
.........
```
