### ISSUE TITLE
Create 1.1 release

### ISSUE THREAD

**Issue by stevenbower** [eirslett/frontend-maven-plugin#491]
Would be nice if we could cut a 1.1 release? Any chance you can do this @eirslett ?

**Comment by eirslett** [comment]
I'll try to get to it!

**Comment by stevenbower** [comment]
Awesome thx!!

**Comment by eirslett** [comment]
To be honest, I'm afraid it can take a couple of days; I got a new computer, and I need to setup all the GPG + maven settings.xml stuff from scratch. I'm a bit short of time nowadays... so if anybody needs to use this in production they would be better off building an internal temporary in-house fork.

**Comment by eirslett** [comment]
Never mind, I actually got it to work now! 1.1 is released.
