### ISSUE TITLE
Code Coverage

### ISSUE THREAD

**Issue by mriehema** [eirslett/frontend-maven-plugin#493]
Hi @eirslett,

I played today a little bit with Travis CI and Sonarqube. It wasn't hard to enable Sonar for this project. What do you think about enabling a code coverage for this project? It will check Pull Requests as well.

See 
- https://travis-ci.org/mriehema/frontend-maven-plugin
- https://sonarqube.com/dashboard?id=com.github.eirslett%3Afrontend-plugins

BTW: It's easy to add linux to Travis CI. This could be a easy replacement for cloudbees.

**Comment by eirslett** [comment]
Code coverage is equal to zero since we have no unit tests though...

It would be much better to use travis for linux as well, I just didn't manage to get it working first time I tried.

**Comment by mriehema** [comment]
Ok, I skipped sonar, but fixed travis config in #496. Runs on OSX and Linux with JDK8.
