### ISSUE TITLE
Eclipse copying thousands of files

### ISSUE THREAD

**Issue by ropoman** [eirslett/frontend-maven-plugin#494]
Hi,

I am using Eclipse neon.1 and version 1.1 of the maven plugin.

<workingDirectory>src/main/resources/static</workingDirectory>
<installDirectory>src/main/resources/static</installDirectory>

I am excluding src/main/resources/static/node_modules in my Eclipse project using <filteredResources>. This works fine, the node_modules does not show up in my target folder, when I build the project

BUT

when I change a .java file and build the project the folder node_modules (and others) are copied to the target folder and Eclipse hangs for minutes.

The pom.xml is here: https://filebin.net/mhhpfna4y5ain570/pom.xml
The Eclipse .project is here: https://filebin.net/racwq10b22uqm6vd/_project

Please help me

Thanks,
Roland

**Comment by mriehema** [comment]
Did you try to move node_modules outside the src folder? I'm not sure, but I think a build will always move files from src/main/resources to the target folder. Nothing special to Eclipse.

Found on stackoverflow something:
http://stackoverflow.com/questions/8727058/maven-resources-not-copying-files

```
    <build>
        <resources>
            <resource>
                <directory>${basedir}/src/main/resources</directory>
                <excludes>
                    <exclude>node_modules/**</exclude>
                </excludes>
            </resource>
        </resources>
    </build>
```

**Comment by ropoman** [comment]
Yeah! I think you found it. Instead of <exclude>node_modules/**</exclude> I wrote <exclude>node_modules</exclude>. Thanks, you're the man!
