### ISSUE TITLE
Grunt command results in Local Npm module grunt-cli not found

### ISSUE THREAD

**Issue by gurnard123** [eirslett/frontend-maven-plugin#497]
I am running the grunt command and it results in this error:

`Local Npm module "grunt-cli" not found. Is it installed?`

I am confused why it asks for a local grunt-cli but there you go.
If I run grunt --version I get this

`grunt-cli v1.2.0
grunt v0.4.5`

Which looks good
Running the where grunt command (this is windows 8.1) shows grunt installed in the correct users directory.

I have been working on this for some time, including refreshing npm cache re-installing grunt and grunt-cli but still end up with the same issue.

Any idea how I can fix this?

This is my maven plugin configuration

&lt;plugin&gt;
    &lt;groupId&gt;com.github.eirslett&lt;/groupId&gt;
    &lt;artifactId&gt;frontend-maven-plugin&lt;/artifactId&gt;
    &lt;version&gt;1.1&lt;/version&gt;
    &lt;executions&gt;
        &lt;execution&gt;
            &lt;id&gt;install node and npm&lt;/id&gt;
            &lt;goals&gt;
                &lt;goal&gt;install-node-and-npm&lt;/goal&gt;
            &lt;/goals&gt;
            &lt;configuration&gt;
                &lt;!-- See https://nodejs.org/en/download/ for latest node and npm (lts) versions --&gt;
                &lt;nodeVersion&gt;v0.12.15&lt;/nodeVersion&gt;
                &lt;npmVersion&gt;2.15.1&lt;/npmVersion&gt;
            &lt;/configuration&gt;
        &lt;/execution&gt;
        &lt;execution&gt;
            &lt;id&gt;npm install&lt;/id&gt;
            &lt;goals&gt;
                &lt;goal&gt;npm&lt;/goal&gt;
            &lt;/goals&gt;
            &lt;!-- Optional configuration which provides for running any npm command --&gt;
            &lt;configuration&gt;
                &lt;arguments&gt;install&lt;/arguments&gt;
            &lt;/configuration&gt;
        &lt;/execution&gt;
        &lt;execution&gt;
            &lt;id&gt;grunt build&lt;/id&gt;
            &lt;goals&gt;
                &lt;goal&gt;grunt&lt;/goal&gt;
            &lt;/goals&gt;
&lt;!--                        &lt;configuration&gt;
                &lt;arguments&gt;no-color&lt;/arguments&gt;
            &lt;/configuration&gt;--&gt;
        &lt;/execution&gt;
    &lt;/executions&gt;
&lt;/plugin&gt;

**Comment by eirslett** [comment]
It is supposed to use a local version of grunt and grunt-cli (are they in your package.json?). That way, the maven build would work even on a machine that hasn't installed grunt globally. Your build can also decide which grunt version to use. (And a number of other reasons)

**Comment by gurnard123** [comment]
Hello. Thanks for the response.
I have grunt-cli locally in my package.json:

`{

  "name": "myapp",
  "version": "1.0.0",
  "devDependencies": {
    "grunt": "^0.4.5",
    "grunt-cache-breaker": "=1.0.1",
    "grunt-cli": "^1.2.0",
    "grunt-contrib-clean": "=0.6.0",
    "grunt-contrib-concat": "=0.5.1",`

But I still get the same:

`Local Npm module "grunt-cli" not found. Is it installed?`

**Comment by eirslett** [comment]
It could be that it's a warning you can ignore - does the build fail as well, or do you only get the message? What does the whole build output look like?

**Comment by gurnard123** [comment]
the build continues... but the point is grunt does not run, which is the whole reason I am implementing this plugin.

**Comment by gurnard123** [comment]
This is the output... it just skips grunt and keeps running.
The next step is a less build (yes I will move this to grunt later but for now it is in maven)

```
[INFO]
[INFO] --- lesscss-maven-plugin:1.7.0.1.1:compile (default) @ myapp ---
[INFO] Bypassing LESS source: idhub.min.css (not modified)
[INFO] Bypassing LESS source: self-service.min.css (not modified)
[INFO] Bypassing LESS source: tbcorp.min.css (not modified)
[INFO] Complete Less compile job finished in 943 ms
[INFO]
[INFO] --- frontend-maven-plugin:1.1:install-node-and-npm (install node and npm) @ myapp---
[INFO] Node v0.12.15 is already installed.
[INFO] NPM 2.15.1 is already installed.
[INFO]
[INFO] --- frontend-maven-plugin:1.1:npm (npm install) @ userportal ---
[INFO] Running 'npm install' in c:\mydir\myapp
[WARNING] npm WARN package.json myapp@1.0.0 No description
[WARNING] npm WARN package.json myapp@1.0.0 No repository field.
[WARNING] npm WARN package.json myapp@1.0.0 No README data
[WARNING] npm WARN package.json myapp@1.0.0 No license field.
[INFO]
[INFO] --- frontend-maven-plugin:1.1:grunt (grunt build) @ userportal ---
[INFO] Running 'grunt ' in c:\mydir\myapp
[INFO] ←[31m>> ←[39mLocal Npm module "grunt-cli" not found. Is it installed?
[INFO]
[INFO] ←[4mRunning "less:tbcorp" (less) task←[24m
[INFO] File src/main/webapp/static/css/myapp.min.css created
[INFO]
[INFO] ←[4mRunning "less:idhub" (less) task←[24m
[INFO] File src/main/webapp/static/css/doo.min.css created
[INFO]
[INFO] ←[4mRunning "less:ssvc" (less) task←[24m
```

**Comment by gurnard123** [comment]
Feel free to close or remove this issue.
