### ISSUE TITLE
nodeVersion always takes 0.12.4

### ISSUE THREAD

**Issue by manoj-mathivanan** [eirslett/frontend-maven-plugin#498]
I am trying to use the plugin to download the latest version but it always takes 0.12.4. I want version: https://nodejs.org/dist/v6.9.1/

My pom.xml plugin looks like below:

```
<plugin>
                <groupId>com.github.eirslett</groupId>
                <artifactId>frontend-maven-plugin</artifactId>
                <version>1.1</version>
                <executions>
                <execution>
                    <id>installing node and npm</id>
                    <goals>
                        <goal>install-node-and-npm</goal>
                    </goals>
                    <configuration>
                        <nodeVersion>6.9.1</nodeVersion>
                    </configuration>
                </execution>
                </executions>
                <configuration>
                        <nodeVersion>6.9.1</nodeVersion>
                    </configuration>

            </plugin>
```

What am I missing here?

**Comment by eirslett** [comment]
Try this:

```xml
<plugin>
                <groupId>com.github.eirslett</groupId>
                <artifactId>frontend-maven-plugin</artifactId>
                <version>1.1</version>
<configuration>
                        <nodeVersion>6.9.1</nodeVersion> <!-- moved over here -->
                    </configuration>
                <executions>
                <execution>
                    <id>installing node and npm</id>
                    <goals>
                        <goal>install-node-and-npm</goal>
                    </goals>
                    <configuration>
                        <nodeVersion>6.9.1</nodeVersion>
                    </configuration>
                </execution>
                </executions>
                

            </plugin>
```

**Comment by manoj-mathivanan** [comment]
Still the same issue. It says: 

[INFO] --- frontend-maven-plugin:1.1:install-node-and-npm (install-node-and-npm) @ model ---
[INFO] Found proxies: [default{protocol='http', host='proxy', port=8080}]
[INFO] Installing node version v0.12.4
[INFO] Downloading https://nodejs.org/dist/v0.12.4/x64/node.exe to C:\Users\asdf\.m2\repository\com\github\eirslett\node\0.12.4\node-0.12.4-win-x64.exe
[INFO] Downloading via proxy default{protocol='http', host='proxy', port=8080}
[INFO] Copying node binary from C:\Users\asdf\.m2\repository\com\github\eirslett\node\0.12.4\node-0.12.4-win-x64.exe to C:\Users\asdf\Desktop\currencies_with_db\model\node\node.exe
[INFO] Installed node locally.
[INFO] Installing npm version 2.11.3
[INFO] Unpacking C:\Users\asdf\.m2\repository\com\github\eirslett\npm\2.11.3\npm-2.11.3.tar.gz into C:\Users\asdf\Desktop\currencies_with_db\model\node\node_modules

**Comment by csvan** [comment]
@manoj-mathivanan it seems that the `id` needs to be `install node and npm` (and exactly that). I tried changing it to `installing node and npm` and the plugin started fetching node 5.9 instead of the specified 6.9.1

**Comment by eirslett** [comment]
My understanding is that I can close this issue then? Feel free to reopen if that's not true.
