### ISSUE TITLE
Yarn - windows tarball support & custom installation path

### ISSUE THREAD

**Issue by kash-raman** [eirslett/frontend-maven-plugin#503]
1. **Windows without admin access** By default in windows, plugin is trying to install yarn msi. With a standard user, I'm not able to install. 
Need a toggle in YarnInstaller.java line no. 127 to switch using tar.gz.  

2. **Custom path support:** Due to above issue, I'm using below execution for installation and need it in global scope. The installation happens under working_folder/node/node_modules/yarn/... which is totally different folder from defaulted target/node/yarn.  And it does not honor workingDirectory or installedDirectory.

```
                  <execution>
                        <id>npm install yarn</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <configuration>
                            <arguments>install grunt/yarn-complete.tgz --verbose -g</arguments>
                            <skip>${skipGruntInstall}</skip>
                        </configuration>
                    </execution>

```
```
public class YarnInstaller {
    public static final String **INSTALL_PATH = "/node/yarn"**;
```

```
final class InstallYarnExecutorConfig implements YarnExecutorConfig {
    private static final String YARN_WINDOWS =
        YarnInstaller.INSTALL_PATH.replaceAll("/", "\\\\") + "\\Yarn\\bin\\yarn.cmd";
```

 
Is anyone facing similar issue? Also, I'm working on the fix.
 
Thanks,
Kasthuri

**Comment by eirslett** [comment]
We should not install yarn globally (that defeats the point with the plugin). But it's strange that the msi creates so much trouble... maybe it only installs programs globally after all?

@maybeec @mriehema Have you experienced this?

**Comment by mriehema** [comment]
Sorry, I hadn't time to test it yet (had some days off). So you have been faster with merging and releasing it. ;) I will test it ASAP.

**Comment by maybeec** [comment]
As far as I understood msi, it will register the installed software globally into the software registry of windows when running the installation properly. What I have done in the yarn deployment in my PR was just extracting the msi, which should skip the software registration. However, due to this issue right management seem to intercept the extraction as well which is a pitty. I am not sure how to circumvent this. I am not sure, maybe I can spend an hour googling at the weekend :)

**Comment by mriehema** [comment]
So, here are my retest results:

Run in git bash and cmd:
Variant 1: No yarn, just frontend-maven-plugin with default yarn settings without admin access: :ok: 
Variant 2: Globally installed yarn via npm, run frontend-maven-plugin with default yarn settings without admin access: :ok: 

So far everything looks fine as aspected and described. But I found two small issues:
- caching yarn in .m2 repo could use less folders, see 
`[INFO] Unpacking C:\Users\mriehema\.m2\repository\com\github\eirslett\**yarn\0.16.1\yarn-0.16.1.\yarn-0.16.1.msi** into C:\dev\test\node\yarn`
- The locally installed yarn in `node\yarn` also includes the msi file. This could be removed.
- the locally installed yarn is in `node\yarn\Yarn\`
But as a said, just small uncritical issues.

**Comment by polarctos** [comment]
I have a build agent running windows here, that is also having problems extracting the .msi file.
Thus I would also favor switching to the .tar.gz file instead.

> `Could not extract the Yarn archive: Could not extract C:\BuildAgent\work\..\..\maven\repository\com\github\eirslett\yarn\0.16.1\yarn-0.16.1.\yarn-0.16.1.msi; return code 1619`

**Comment by maybeec** [comment]
`Error code 1619 = "This installation package could not be opened. Verify that the package exists and that you can access it, or contact the application vendor to verify that this is a valid Windows Installer package."`
Maybe the downloaded file is corrupted? Can you run it manually?

**Comment by polarctos** [comment]
I now checked the SHA1 checksum of the .msi file on my machine and on the build agent and they are identical. (C7E86EE733841BF8EF27B7B612677C3B869F2041)

I can run/extract it in my user account on the build agent, but the build itself is run with a different user account and presumably thus fails.

There are no such issues with extracting plain .tar.gz files. That file is smaller too: 2.68 MB vs. 4.2 MB.

**Comment by mriehema** [comment]
The files of the .tar.gz and the .msi archive are identically? They work with Windows? If yes, it sounds like a good idea to change the archive.

**Comment by eirslett** [comment]
+1 Let's use the tar.gz instead of the msi.

**Comment by kash-raman** [comment]
@eirslett I suppose providing both options would be helpful with default as msi and parameter to switch. I'm testing this, will create a pull request.

**Comment by maybeec** [comment]
if .tar.gz works on windows I would just switch to tar.gz rather than supporting both. Then I do not see any advantage to support both.

**Comment by polarctos** [comment]
I compared the contents, and unfortunately they are note identical. I am not sure if this is a problem.

The .msi contains *.cmd files for the `\yarn\Yarn\node_modules\.bin\` directory.
Whereas extracting the .tar.gz tries to create symbolic links in this directory.

Did someone already check the source that NPM uses for installing Yarn? That should works cross platform right?

**Comment by eirslett** [comment]
We don't really need the cmd files. We do `node ./xxx/xxx/yarn.js` instead.

**Comment by maybeec** [comment]
So I investigated msi installation even further. I restricted the 'installation' to just one user, which already brought some progress. However, it continues writing to the registry some product details, which needs advanced rights regadless whether you use the normal installation `/i` or the administrative installation `/a`.
There is a possibility to suppress such steps by providing a Transformation file to the installation process, which is made for adapting vendor MSI installation processes. However, I was not able to establish the transformation in the build. I am not quite sure why...

Nevertheless, I like the idea to just go for yarn.js. So we should definitively give it a try.

**Comment by kash-raman** [comment]
@eirslett @maybeec @mriehema I have made changes to use tarball in windows.  yarn.js was not working directly in windows, invoking .cmd for that reason. Can you please review the pull request?

**Comment by mriehema** [comment]
@kash-raman Looks good to me.

First build:
```
[INFO] --- frontend-maven-plugin:1.3-SNAPSHOT:install-node-and-yarn (install-node-and-yarn) @ frontend ---
[INFO] Installing node version v6.9.1
[INFO] Copying node binary from C:\Users\mriehema\.m2\repository\com\github\eirslett\node\6.9.1\node-6.9.1-win-x64.exe to C:\dev\cms-alt\blueprint\modules\frontend\node\node.exe
[INFO] Installed node locally.
[INFO] Installing Yarn version v0.16.1
[INFO] Unpacking C:\Users\mriehema\.m2\repository\com\github\eirslett\yarn\0.16.1\yarn-0.16.1.\yarn-v0.16.1.tar.gz into C:\dev\cms-alt\blueprint\modules\frontend\node\yarn
[INFO] Installed Yarn locally.
```

Second build:
```
[INFO] --- frontend-maven-plugin:1.3-SNAPSHOT:install-node-and-yarn (install-node-and-yarn) @ 
[INFO] Node v6.9.1 is already installed.
[INFO] Yarn 0.16.1 is already installed.
```

**Comment by kash-raman** [comment]
Thank you! 
@eirslett Will you be releasing it sometime soon?
