### ISSUE TITLE
Tries to run Bower install in project without Bower

### ISSUE THREAD

**Issue by csvan** [eirslett/frontend-maven-plugin#505]
**Please mention your frontend-maven-plugin and operating system version.**
1.2, Windows 7 Enterprise

EDIT: This is true for Grunt as well. The plugin tries to run "grunt build" even though there is not a single component (not including deps) that uses it. 

I am not certain if this is expected behavior or not, but I have found that the plugin constantly tries to run "bower install" even on projects with zero Bower dependencies. E.g. for the following:

```
<plugin>
        <groupId>com.github.eirslett</groupId>
        <artifactId>frontend-maven-plugin</artifactId>
        <version>1.2</version>
        <executions>
          <!-- Basic setup -->
          <execution>
            <id>install node and npm</id>
            <goals>
              <goal>install-node-and-npm</goal>
            </goals>
            <configuration>
              <nodeVersion>v6.2.2</nodeVersion>
              <npmVersion>3.9.5</npmVersion>
            </configuration>
          </execution>
          <!-- Gulp -->
          <execution>
            <id>gulp build</id>
            <goals>
              <goal>gulp</goal>
            </goals>
            <configuration>
              <arguments>build</arguments>
            </configuration>
          </execution>
        </executions>
</plugin>
```

I get:

```
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.2:bower (bower prune) on project my-project: Failed to run task: 'bower prune failed. (error code 1) -> [Help 1]
```

**Comment by csvan** [comment]
Update: I managed to work around this by essentially adding noops for bower and grunt:

```
<execution>
            <id>bower install</id>
            <goals>
              <goal>bower</goal>
            </goals>
            <configuration>
              <arguments>--version</arguments>
            </configuration>
          </execution>
          <execution>
            <id>grunt build</id>
            <goals>
              <goal>grunt</goal>
            </goals>
            <configuration>
              <arguments>--version</arguments>
            </configuration>
</execution>
```

**Comment by eirslett** [comment]
Does the project pom inherit settings from another parent pom?

**Comment by csvan** [comment]
@eirslett yes, that seems to be the issue. `grunt build` and `bower install` were both used in another module whose POM also use the plugin.

Still, is this intended behavior, i.e. that plugin configs from different modules essentially get merged when you build either one of them?

**Comment by csvan** [comment]
@eirslett scratch that actually. Even if I completely remove all references to bower in the other module, the build still tries to run it.

**Comment by eirslett** [comment]
But is there a parent pom involved here? (Not a sibling pom)
Some devs make company-wide poms that all their projects use, maybe there's plugin config there?

**Comment by csvan** [comment]
@eirslett yes, I meant to say that both modules had the same parent POM.

The only problem is that I was looking at the wrong parent POM - the correct one indeed used bower install, hence the problem. Thanks anyway!
