### ISSUE TITLE
The skip parameter on InstallNodeAndYarnMojo is ignored

### ISSUE THREAD

**Issue by alexcojocaru** [eirslett/frontend-maven-plugin#506]
**Do you want to request a _feature_ or report a _bug_?**
BUG

**What is the current behavior?**
Setting the skip parameter (skip.installyarn) to true in the configuration on InstallNodeAndYarnMojo does not seem to have any effect - the mojo still executes.

**If the current behavior is a bug, please provide the steps to reproduce.**
Create an empty maven project:
`$ mvn archetype:generate -DgroupId=com.github.alexcojocaru -DartifactId=frontend-maven-plugin-test -DarchetypeArtifactId=maven-archetype-quickstart -DinteractiveMode=false`

Change the pom.xml to look like: https://gist.github.com/alexcojocaru/2f24d4f900a9a5fe91121f6a82377db7

**What is the expected behavior?**
Running `$ mvn generate-resources` on the project should skip the installation of node and yarn.

**Please mention your frontend-maven-plugin and operating system version.**
1.3-SNAPSHOT / OSX / Maven 3.2.3

This change seems to fix the issue; since I don't understand why it fixes the problem, I would rather not submit a merge request yet.

```diff --git a/frontend-maven-plugin/src/main/java/com/github/eirslett/maven/plugins/frontend/mojo/InstallNodeAndYarnMojo.java b/frontend-maven-plugin/src/main/java/com/github/eirslett/maven/plugins/frontend/mojo/InstallNodeAndY
index cab3a2d..c609e90 100644
--- a/frontend-maven-plugin/src/main/java/com/github/eirslett/maven/plugins/frontend/mojo/InstallNodeAndYarnMojo.java
+++ b/frontend-maven-plugin/src/main/java/com/github/eirslett/maven/plugins/frontend/mojo/InstallNodeAndYarnMojo.java
@@ -56,7 +56,7 @@ public final class InstallNodeAndYarnMojo extends AbstractFrontendMojo {
     /**
      * Skips execution of this mojo.
      */
-    @Parameter(property = "skip.installyarn", defaultValue = "false")
+    @Parameter(property = "skip.installyarn", alias = "skip.installyarn", defaultValue = "false")
     private Boolean skip;

     @Component(role = SettingsDecrypter.class)```

**Comment by eirslett** [comment]
If you `mvn generate-resources -Dskip.installyarn=true`, on the command line then it works. I don't think we support disabling it in the pom.xml (yet).

Your fix looks good, I'm sure it should be fine to merge it. Looks like the other mojos have the same problem with the skip parameter, so it would be good to get them fixed as well maybe?

**Comment by alexcojocaru** [comment]
I use the skip parameters on other mojos (install-node-and-npm, npm, gulp, yarn) in their config in pom.xml  and they work as expected. That is why I cannot explain why it doesn't work on the install-node-and-yarn mojo unless I add the "alias" attribute (which doesn't exist on any of the other params). I ran a ton of tests and can confirm that, in my env, it doesn't work without the alias attribute.
If the patch looks good to you, I am going to prepare a merge request. Thanks.

**Comment by GRboss** [comment]
Hi all,

I'm trying to make `-Dskip.installyarn=true` work but it ignored. The command I'm running is:
```
mvn --batch-mode clean release:prepare -Dskip.installyarn=true
```
I'm using version 1.11.2 of the plugin. Has anyone figured out an alternative approach?

Regards,
Stefanos
