### ISSUE TITLE
Yarn - there is no support for setting the "registry" on the CLI

### ISSUE THREAD

**Issue by alexcojocaru** [eirslett/frontend-maven-plugin#508]
**Do you want to request a _feature_ or report a _bug_?**
BUG

**What is the current behavior?**
The yarn mojo takes the "npmRegistryURL" parameter and passes it to the yarn runner. The runner uses it as "registry" argument when executing yarn. However, yarn does not support an argument with that name and fails with:
```[INFO] --- frontend-maven-plugin:1.3-SNAPSHOT:yarn (yarn install) @ frontend-maven-plugin-test ---
[INFO] Running 'yarn install --registry=https://registry.npmjs.org/' in /Users/x/temp/frontend-maven-plugin-test/src/main/webapp/assets/react
[ERROR]
[ERROR]   error: unknown option `--registry'
[ERROR]
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Create an empty maven project:
`$ mvn archetype:generate -DgroupId=com.github.alexcojocaru -DartifactId=frontend-maven-plugin-test -DarchetypeArtifactId=maven-archetype-quickstart -DinteractiveMode=false`

Change the pom.xml file to:
https://gist.github.com/alexcojocaru/3c4d4a5f2af5a6353cd43f22c706faaa

Execute `$ mvn generate-resources` inside the project.

Same error occurs when the property is passed as JVM argument: remove line 50 the pom file and pass the registry as JVM arg:
`$ mvn generate-resources -DnpmRegistryURL=https://registry.npmjs.org/`

If the registry is not configured in the pom and not passed as JVM arg, the installation is successful.

**What is the expected behavior?**
Since yarn does not support setting the registry on the command line yet (https://github.com/yarnpkg/yarn/issues/792), it can only be set with another yarn execution, before the yarn install execution:
```<execution>
	<id>yarn configure</id>
	<phase>generate-resources</phase>
	<goals>
		<goal>yarn</goal>
	</goals>
	<configuration>
		<skip.yarn>${skip.yarn}</skip.yarn>
		<workingDirectory>${basedir}/src/main/webapp/assets/scripts/react</workingDirectory>
		<installDirectory>${project.build.directory}</installDirectory>
		<arguments>config set registry https://registry.npmjs.org/</arguments>
	</configuration>
</execution>
```

Based on the comments on the yarn issue (link is above), it looks like support for `--registry` will be added to yarn probably. Therefore, I suggest commenting out the npmRegistryURL parameter on the yarn mojo for now, and use the separate yarn execution I showed above to set up the registry if needed.
If support for `--registry` is not added to yarn, then proper support for the npmRegistryURL can be implemented by having YarnTaskExecutor.execute execute `yarn config set registry XYZ` before executing the requested command.

**Please mention your frontend-maven-plugin and operating system version.**
1.3-SNAPSHOT / OSX

**Comment by alexcojocaru** [comment]
I can submit a merge request, to have the npmRegistryURL parameter on the yarn mojo commented out, and add a note to the README file to to describe how the yarn registry can be set using a separate yarn execution.

**Comment by eirslett** [comment]
> If the registry is not configured in the pom and not passed as JVM arg, the installation is successful.

Maybe this can be the solution then? When using yarn, don't specify the registry?

**Comment by alexcojocaru** [comment]
What I said in my previous comment is that the npmRegistryURL parameter on the yarn mojo is broken - leaving it in (as is) creates false expectations and may break the mojo execution.
I am okay with closing this issue without any code changes.

**Comment by eirslett** [comment]
Let's want and see if yarn implements --registry natively. Then we don't have to worry about it.
