### ISSUE TITLE
Please allow the frontend-maven-plugin to work with newer versions of Maven

### ISSUE THREAD

**Issue by jimbethancourt** [eirslett/frontend-maven-plugin#509]
**Do you want to request a _feature_ or report a _bug_?**
A feature.

**What is the current behavior?**
I get the message *The plugin com.github.eirslett:frontend-maven-plugin:1.2 requires Maven version 3.1.0*

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Use Maven 3.3.9
2. Compile the project
3. Output is *The plugin com.github.eirslett:frontend-maven-plugin:1.2 requires Maven version 3.1.0*

**What is the expected behavior?**
Allow the plugin to work with newer versions of Maven

**Please mention your frontend-maven-plugin and operating system version.**
frontend-maven-plugin version:1.2
OS: Windows 7

**Comment by eirslett** [comment]
How are you compiling? From the command line/terminal? Or via an IDE (IntelliJ)?

**Comment by jimbethancourt** [comment]
Good call -- I'm using IntelliJ -- I should check what version it's using.  I'm pretty sure it defaults to 3.0.5. I will look at it tomorrow.

Thanks,
Jim

**Comment by jimbethancourt** [comment]
Thanks @eirslett -- IntelliJ was defaulting to 3.0.5
