### ISSUE TITLE
Perform a 'yarn install' with HTTPS proxy does not work

### ISSUE THREAD

**Issue by dg-grow-virgiliu-ratoi** [eirslett/frontend-maven-plugin#518]
When trying to perform a `yarn install` via the frontend plugin, while using a corporate proxy, I get the following error:  **error: unknown option `--https-proxy'**.

Here is the output:

>[INFO] --- frontend-maven-plugin:1.2:yarn (yarn install) @ ... ---
[INFO] Found proxies: [https_psbru{protocol='https', host='...', port=..., with username/passport authentication}, optional{protocol='http', host='...', port=..., with username/passport authentication}]
[INFO] Running 'yarn install --https-proxy=http://user:***@...:...--proxy=http://user.***@...:...' in /home/...
[ERROR] 
[ERROR]   error: unknown option `--https-proxy'

As you can see in the output, there are two proxy servers, one for HTTP and the other one for HTTPS.

This is the execution configuration, please note that I am able to run a yarn build with the plugin.
`<execution>
  <id>yarn install</id>
  <goals>
    <goal>yarn</goal>
  </goals>
  <configuration>
    <arguments>install</arguments>
  </configuration>
</execution>`

I am able to perform a manual `yarn install` via the command line.

The frontend-maven-plugin version is 1.2 and the operating system is linux red hat enterprise 6.

**Comment by schue30** [comment]
The Proxy option in yarn is only available in version >= 0.17.0. I think you are using yarn 0.16.1. Update to 0.17.0 and the Proxy option will work.

**Comment by dg-grow-virgiliu-ratoi** [comment]
It seems to work, thanks.
