### ISSUE TITLE
Feature Request: Install git alongside node and npm

### ISSUE THREAD

**Issue by vrushank-desai** [eirslett/frontend-maven-plugin#528]
Probably too much to ask but it would be nice to have a goal to download git command line and add the same to path when running the bower install goal.

Am currently using v1.3, not sure if already present.

**Comment by eirslett** [comment]
This was briefly discussed a while back (it's in a GitHub issue somewhere) - the conclusion was that the git binary is so widely present by now, that you can pretty much assume that it's there on the CI server. Also, the general direction of the industry is to move towards npm-based solutions, or yarn.
