### ISSUE TITLE
Make more classes 'public' and less 'final'

### ISSUE THREAD

**Issue by rupertlssmith** [eirslett/frontend-maven-plugin#533]
It would be helpful if more classes in this library were 'public' so they can be used in different packages.

Basically, all the classes that have the default 'package' scope should be public.

The public classes such as all the Mojos would be better not being 'final'.

I want to write a Mojo to install and build with Elm. Ideally I would just extend the existing NpmAndNodeInstallerMojo (can't its final) for my install Mojo, and write the ElmBuildMojo by extending NodeTaskExecutor (can't its package local).

I am forced to resort to copying classes I need to extend or use, or forking the whole project and re-namespacing it so I can release an independant fork.

The other option is that I contribute my Elm install and build components to this project, which I'd be happy to do. Its just that I want to get my stuff written and released independently without needing to wait for my contribution to be pulled in. It would be easier to contribute anyway, if things were more public and less final, as the pull request would be easier to get right without having made use of copied code.

**Comment by eirslett** [comment]
I can see your point. Classes are hidden and/or final on purpose, to prevent people from using/accessing/extending them; not to restrict what people are able to do with the plugin, but so it's possible to make "breaking" changes to the internal implementations without affecting backwards compatibility.
What you could try with Elm is to make an "elm" script in package.json, and npm run elm with the npm mojo. Does that work?

**Comment by rupertlssmith** [comment]
Thanks for your reply.

What I have done is to just take a copy of the entire frontend plugin, and
build my elm plugin around the copy.

If I write it in the same 'style' as existing plugins, then I don't really
need to change any of your code, except to add my runners into the
FrontendFactory.

When I am done, I can just remove the copy by diffing with the original and
that will leave me with a clean diff to apply on top of the original to
form a pull request.

I did think making your mojos 'final' is a bit too far. I can understand
'fina'l being used in java.security for example, where it is really
important to prevent a class being extended, but build scripts? anyway, I
found a way to work with it, thanks.
