### ISSUE TITLE
Can not select node  is x32 or x64 ?

### ISSUE THREAD

**Issue by heiliuer** [eirslett/frontend-maven-plugin#541]
**Can not select node  version of x32 or x64 ?

i want the maven plugin to download node-x64
![image](https://cloud.githubusercontent.com/assets/6746060/21478738/2bcc7f3c-cb89-11e6-9e54-ca83158158df.png)
but it always download x86
![image](https://cloud.githubusercontent.com/assets/6746060/21478739/35444ae0-cb89-11e6-9811-521b718433d2.png)

**My machine is windows pc of win10 x64**

**Comment by eirslett** [comment]
It doesn't matter. You can use the 32 bit version of node, even if you have a 64 bit windows machine. The plugin doesn't support it for historical reasons. (Very old versions of node.js)

**Comment by heiliuer** [comment]
My machine has installed node-x64  before this. I solved the problem by replacing it of x86.Thanks!
