### ISSUE TITLE
Could not extract the npm archive (using frontend-maven-plugin 1.3)

### ISSUE THREAD

**Issue by ymwang1220** [eirslett/frontend-maven-plugin#545]
I have searched all the existing and closed issues and am using the latest version of frontend-maven-plugin.   But, I still encounter the following error with the maven configuration shown below.
Could someone help me on how to resolve this issue ?

Thanks.

> **[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.3:install-node-and-npm (install node and npm) on project gui-prototype-war: Could not extract the npm archive: Could not extract archive: 'G:\.m2\repository\com\github\eirslett\npm\4.0.3\npm-4.0.3.tar.gz': Input is not in the .gz format** 

> <plugin>
    <groupId>com.github.eirslett</groupId>
    <artifactId>frontend-maven-plugin</artifactId>
    
    <version>1.3</version>
    <configuration>
		<workingDirectory>${basedir}/WebContent</workingDirectory>
		<installDirectory>${basedir}/WebContent/dist</installDirectory>
    </configuration>
	<executions>
		<execution>
			<id>install node and npm</id>
			<goals>
				   <goal>install-node-and-npm</goal>
			</goals>
			<phase>generate-resources</phase>
			<configuration>
				<nodeVersion>v6.9.2</nodeVersion>
				<npmVersion>4.0.3</npmVersion> 
				<nodeDownloadRoot>http://nodejs.org/dist/</nodeDownloadRoot>
				<npmDownloadRoot>http://registry.npmjs.org/npm/-/</npmDownloadRoot>
			</configuration>
		</execution>
		<execution>
			<id>npm install</id>
			<goals>
				 <goal>npm</goal>
			</goals>
			<phase>generate-resources</phase>
			<configuration>
				<arguments>install</arguments>
			</configuration>
		</execution>
		<execution>
		    <id>webpack build</id>
		    <goals>
				<goal>webpack</goal>
		    </goals>
		    <phase>generate-resources</phase>
			<configuration>
				<arguments>-p</arguments>
			</configuration>
		</execution> 
    </executions>
</plugin>

**Comment by tobymurray-nanometrics** [comment]
I have no idea if it has anything to do with anything, but it looks like you're explicitly configuring the `npmDownloadRoot` to be the default value - does it fail similarly when you exclude the `<npmDownloadRoot`> configuration? With a similar pom the plugin is working for us.

**Comment by ymwang1220** [comment]
Thanks for your response.

I excluded the <npmDownloadRoot> configuration and cleared local maven repository.  But, I still got the same error.    It seems to be working for the others based on the answers posted in the closed issues with similar pom configuration.   However, I can't figure out what could have caused this issue for me.

**Comment by tobymurray-nanometrics** [comment]
Have you tried upping the verbosity of Maven with either `-X` or `--debug`? Perhaps it'll provide some insight into the failure?

If you dump the entire plugin execution with the verbose flag, maybe someone will recognize an issue.

**Comment by ymwang1220** [comment]
The following is the log when I turned on the debug mode.   Thanks for your help.


> [INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.3:ins
tall-node-and-npm (install node and npm) on project gui-prototype-war: Could not
 extract the npm archive: Could not extract archive: 'G:\.m2\repository\co
m\github\eirslett\npm\4.0.3\npm-4.0.3.tar.gz': Input is not in the .gz format ->
 [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal c
om.github.eirslett:frontend-maven-plugin:1.3:install-node-and-npm (install node
and npm) on project gui-prototype-war: Could not extract the npm archive: Could
not extract archive: 'G:\.m2\repository\com\github\eirslett\npm\4.0.3\npm-
4.0.3.tar.gz'
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThre
adedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(Lifecycl
eStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laun
cher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jav
a:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La
uncher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:
356)
Caused by: org.apache.maven.plugin.MojoFailureException: Could not extract the n
pm archive: Could not extract archive: 'G:\.m2\repository\com\github\eirsl
ett\npm\4.0.3\npm-4.0.3.tar.gz'
        at com.github.eirslett.maven.plugins.frontend.mojo.MojoUtils.toMojoFailu
reException(MojoUtils.java:27)
        at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.
execute(AbstractFrontendMojo.java:97)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(Default
BuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:208)
        ... 19 more
Caused by: com.github.eirslett.maven.plugins.frontend.lib.InstallationException:
 Could not extract the npm archive
        at com.github.eirslett.maven.plugins.frontend.lib.NPMInstaller.installNp
m(NPMInstaller.java:169)
        at com.github.eirslett.maven.plugins.frontend.lib.NPMInstaller.install(N
PMInstaller.java:82)
        at com.github.eirslett.maven.plugins.frontend.mojo.InstallNodeAndNpmMojo
.execute(InstallNodeAndNpmMojo.java:106)
        at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.
execute(AbstractFrontendMojo.java:89)
        ... 21 more
Caused by: com.github.eirslett.maven.plugins.frontend.lib.ArchiveExtractionExcep
tion: Could not extract archive: 'G:\.m2\repository\com\github\eirslett\np
m\4.0.3\npm-4.0.3.tar.gz'
        at com.github.eirslett.maven.plugins.frontend.lib.DefaultArchiveExtracto
r.extract(ArchiveExtractor.java:131)
        at com.github.eirslett.maven.plugins.frontend.lib.NPMInstaller.extractFi
le(NPMInstaller.java:186)
        at com.github.eirslett.maven.plugins.frontend.lib.NPMInstaller.installNp
m(NPMInstaller.java:142)
        ... 24 more
Caused by: java.io.IOException: Input is not in the .gz format
        at org.apache.commons.compress.compressors.gzip.GzipCompressorInputStrea
m.init(GzipCompressorInputStream.java:149)
        at org.apache.commons.compress.compressors.gzip.GzipCompressorInputStrea
m.<init>(GzipCompressorInputStream.java:132)
        at org.apache.commons.compress.compressors.gzip.GzipCompressorInputStrea
m.<init>(GzipCompressorInputStream.java:97)
        at com.github.eirslett.maven.plugins.frontend.lib.DefaultArchiveExtracto
r.extract(ArchiveExtractor.java:104)
        ... 26 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption

**Comment by tobymurray-nanometrics** [comment]
Hmm... I continue to not have any answers for you. Do you need Node version 4? If so, perhaps try Node version 7? Not sure why that would cause any trouble, but nice to match up with what Node distributes.

Also, looking at the doc on the front page:

    

Does it work if you exclude the `npm` version entirely in the configuration, installing what comes with Node?

**Comment by ymwang1220** [comment]
I did try several different variations as you suggested.  Still no luck yet.
I also tried nodeVersion v4.6.0 and npmVersion 2.15.9 in pom config and got the same error as I posted earlier.

If I remove npmVersion in pom config, then I would get the error on trying to extract the node archive.
The issue seems to be related to the failure on unarchiving either .tar.gz or .zip file format.
I will do some more research later tonight.

Thanks.

> [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.3:ins
tall-node-and-npm (install node and npm) on project gui-prototype-war: Could not
 extract the Node archive: Could not extract archive: 'G:\.m2\repository\c
om\github\eirslett\node\4.6.0\node-4.6.0-win-x64.zip': error in opening zip file
 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal c
om.github.eirslett:frontend-maven-plugin:1.3:install-node-and-npm (install node
and npm) on project gui-prototype-war: Could not extract the Node archive: Could
 not extract archive: 'G:\.m2\repository\com\github\eirslett\node\4.6.0\no
de-4.6.0-win-x64.zip'
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThre
adedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(Lifecycl
eStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laun
cher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jav
a:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La
uncher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:
356)
Caused by: org.apache.maven.plugin.MojoFailureException: Could not extract the N
ode archive: Could not extract archive: 'G:\.m2\repository\com\github\eirs
lett\node\4.6.0\node-4.6.0-win-x64.zip'
        at com.github.eirslett.maven.plugins.frontend.mojo.MojoUtils.toMojoFailu
reException(MojoUtils.java:27)
        at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.
execute(AbstractFrontendMojo.java:97)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(Default
BuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:208)
        ... 19 more
Caused by: com.github.eirslett.maven.plugins.frontend.lib.InstallationException:
 Could not extract the Node archive
        at com.github.eirslett.maven.plugins.frontend.lib.NodeInstaller.installN
odeWithNpmForWindows(NodeInstaller.java:242)
        at com.github.eirslett.maven.plugins.frontend.lib.NodeInstaller.install(
NodeInstaller.java:89)
        at com.github.eirslett.maven.plugins.frontend.mojo.InstallNodeAndNpmMojo
.execute(InstallNodeAndNpmMojo.java:101)
        at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.
execute(AbstractFrontendMojo.java:89)
        ... 21 more
Caused by: com.github.eirslett.maven.plugins.frontend.lib.ArchiveExtractionExcep
tion: Could not extract archive: 'G:\.m2\repository\com\github\eirslett\no
de\4.6.0\node-4.6.0-win-x64.zip'
        at com.github.eirslett.maven.plugins.frontend.lib.DefaultArchiveExtracto
r.extract(ArchiveExtractor.java:131)
        at com.github.eirslett.maven.plugins.frontend.lib.NodeInstaller.extractF
ile(NodeInstaller.java:302)
        at com.github.eirslett.maven.plugins.frontend.lib.NodeInstaller.installN
odeWithNpmForWindows(NodeInstaller.java:210)
        ... 24 more
Caused by: java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:215)
        at java.util.zip.ZipFile.<init>(ZipFile.java:145)
        at java.util.zip.ZipFile.<init>(ZipFile.java:159)
        at com.github.eirslett.maven.plugins.frontend.lib.DefaultArchiveExtracto
r.extract(ArchiveExtractor.java:76)
        ... 26 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption

**Comment by Moustapha918** [comment]
I have the same issue, 
could not extract npm-4.4.1.tar.gz, input is not in gz format.

**Comment by ruizlake** [comment]
I've solved this problem. and when you use Maven to compile. you have to wait for the npm-4.0.3.tar.gz download to complete.

**Comment by Alex88na** [comment]
Hi ruizlake, in which way I have to wait? I run _mvn clean install_ and I get the same error. In my frontedn pom.xml I have:

            _<plugin>
                <groupId>com.github.eirslett</groupId>
                <artifactId>frontend-maven-plugin</artifactId>
                <version>1.5</version>
 
                <configuration>
                    <nodeVersion>v6.11.2</nodeVersion>
                    <npmVersion>5.3.0</npmVersion>
                    <workingDirectory>src/main/frontend</workingDirectory>
                </configuration>
                ..._

**Comment by Szenmu** [comment]
Abit late but my solution was to go in and manually delete the npm and node folders in 
.m2\repository\com\github\eirslett\ and then run mvn clean install, hope this helps!

**Comment by pguevara2017** [comment]
This worked for me too. I just deleted this file in .m2\repository\com\github\eirslett\ and re-run your maven install. The file may have been corrupted during previous the maven download.

**Comment by beckiDev** [comment]
Hi, I have cleaned the whole folder .m2\repository\com\github\eirslett\ but still getting that issue:

Failed to execute goal com.github.test:frontend-maven-plugin:0.0.11:install-node-and-npm (install node and npm) on project test-ui: Could not extract the npm archive: Could not extract archive: 'test/frontend/ui/src/main/nodejs/npm.tar.gz'

**Comment by DanVisan** [comment]
@ShaneMcGowan  your solution worked. You have to manually remove some the maven dirs in .m2\repository\com\github\eirslett\

**Comment by mcahornsirup** [comment]
I have fixed it by remove ~/m2/repository/com/github/eirslett and build again with version 1.6.

**Comment by sruthykc** [comment]
Manually delete the npm and node folders in
.m2\repository\com\github\eirslett\ and then 
run mvn clean install
This fixed my issue
