### ISSUE TITLE
Request Feature - Add failsafe mode to generally manage integration-test

### ISSUE THREAD

**Issue by ningod** [eirslett/frontend-maven-plugin#552]
In my project i use frontend maven plugin to execute integration-test with protractor testing framework, in my configuration i launch protractor using yarn goal and a script in package.json , but if tests fails all build fails and post-integration-test phase is never executed.
Due to this I need something to ignore plugin failure, a failOnError property or something similar to karma behavior with the "maven.test.failure.ignore" property

**Comment by eirslett** [comment]
We do have that property for the karma mojo, I think. I just cannot remember what it's called. Check the examples, or maybe in the code!

**Comment by ningod** [comment]
Yes, we have in karma but I'm not executing karma tests... I need it in other goals.
I'm moving the property from karma mojo to parent class then I'll pull a request to you

**Comment by kaqqao** [comment]
This duplicates my issue https://github.com/eirslett/frontend-maven-plugin/issues/534
but the related pull request seems to have more features than mine (plus examples, it seems), so I'd favor this one over mine.
