### ISSUE TITLE
Behaviour of frontend-maven-plugin(V1.0)  with existing node

### ISSUE THREAD

**Issue by subhashkk** [eirslett/frontend-maven-plugin#559]
Is it possible to run frontend-maven-plugin(V1.0) with existing nodejs(defined in path) and avoid downloading a separate node from repository? If no, can the plugin be enhanced to support the same ?
 
I'm trying to configure Jenkins to run the POM containing frontend-maven-plugin, basically to run "npm" goal (build and install) using built-in node that is available in path (and avoid install-node-and-npm goal i.e. downloading node from repository) ?

**Comment by eirslett** [comment]
No, it's not possible. If you look at the list of github issues in the project, you will find some advice.
