### ISSUE TITLE
 Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.3:yar n (yarn install) on project zeppelin-web

### ISSUE THREAD

**Issue by vishalkin** [eirslett/frontend-maven-plugin#562]
```
[ERROR] error Command failed with exit code 1.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Zeppelin ........................................... SUCCESS [ 50.394 s]
[INFO] Zeppelin: Interpreter .............................. SUCCESS [ 31.632 s]
[INFO] Zeppelin: Zengine .................................. SUCCESS [ 24.134 s]
[INFO] Zeppelin: Display system apis ...................... SUCCESS [ 19.607 s]
[INFO] Zeppelin: Spark dependencies ....................... SUCCESS [01:33 min]
[INFO] Zeppelin: Spark .................................... SUCCESS [ 29.058 s]
[INFO] Zeppelin: Markdown interpreter ..................... SUCCESS [  5.796 s]
[INFO] Zeppelin: Angular interpreter ...................... SUCCESS [  4.361 s]
[INFO] Zeppelin: Shell interpreter ........................ SUCCESS [  4.827 s]
[INFO] Zeppelin: Livy interpreter ......................... SUCCESS [ 50.227 s]
[INFO] Zeppelin: HBase interpreter ........................ SUCCESS [ 11.682 s]
[INFO] Zeppelin: Apache Pig Interpreter ................... SUCCESS [ 10.991 s]
[INFO] Zeppelin: PostgreSQL interpreter ................... SUCCESS [  5.541 s]
[INFO] Zeppelin: JDBC interpreter ......................... SUCCESS [  6.663 s]
[INFO] Zeppelin: File System Interpreters ................. SUCCESS [  6.304 s]
[INFO] Zeppelin: Flink .................................... SUCCESS [ 13.449 s]
[INFO] Zeppelin: Apache Ignite interpreter ................ SUCCESS [  5.955 s]
[INFO] Zeppelin: Kylin interpreter ........................ SUCCESS [  4.915 s]
[INFO] Zeppelin: Python interpreter ....................... SUCCESS [  6.109 s]
[INFO] Zeppelin: Lens interpreter ......................... SUCCESS [ 11.360 s]
[INFO] Zeppelin: Apache Cassandra interpreter ............. SUCCESS [ 58.287 s]
[INFO] Zeppelin: Elasticsearch interpreter ................ SUCCESS [  9.617 s]
[INFO] Zeppelin: BigQuery interpreter ..................... SUCCESS [  5.584 s]
[INFO] Zeppelin: Alluxio interpreter ...................... SUCCESS [  9.001 s]
[INFO] Zeppelin: Scio ..................................... SUCCESS [ 48.425 s]
[INFO] Zeppelin: web Application .......................... FAILURE [28:26 min]
[INFO] Zeppelin: Server ................................... SKIPPED
[INFO] Zeppelin: Packaging distribution ................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 37:14 min
[INFO] Finished at: 2017-02-01T16:21:39+05:30
[INFO] Final Memory: 224M/1792M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.3:yar
n (yarn install) on project zeppelin-web: Failed to run task: 'yarn install --no
-lockfile --https-proxy=http://sg0227823:***@tulsa-proxy.sabre.com:80 --proxy=ht
tp://sg0227823:***@tulsa-proxy.sabre.com:80' failed. (error code 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :zeppelin-web
```

**Comment by jagatsingh** [comment]
Can you try to run with -X and see if its proxy related issue.

Example you might need .bowerc file with proxy 

See http://stackoverflow.com/questions/21705091/bower-behind-a-proxy

**Comment by 1ambda** [comment]
@jagatsingh Hi

1. Does frontend-maven-plugin support script tag in package.json? 

- Zeppelin uses scripts tags like https://github.com/apache/zeppelin/blob/master/zeppelin-web/package.json#L8-L21
- pom.xml in Zeppelin: https://github.com/apache/zeppelin/blob/master/zeppelin-web/pom.xml#L132-#L140

2. If so, it looks like yarn specific problem. :(

**Comment by pouu69** [comment]
i have same issue ㅜㅜ
plz help me

**Comment by ningod** [comment]
I use yarn script from package.json in my project and my pom.xml look ( no run argument ) like this: 

```xml
<execution>
  <id>frontend-yarn-script</id>
  <goals>
    <goal>yarn</goal>
  </goals>
  <configuration>
    <arguments>myscript -- --myscriptargname myscriptargvalue</arguments>
  </configuration>
  <phase>process-resources</phase>
</execution>
```

**Comment by 1ambda** [comment]
Hi. Any update?

**Comment by 1ambda** [comment]
I figured out that only `yarn` causes this problem. NPM installed by frontend-maven-plugins works well.

**Comment by DmytroShkvyra** [comment]
@pouu69 You can try something like this
``
              <execution>
                  <id>yarn add bower</id>
                  <goals>
                      <goal>yarn</goal>
                  </goals>
                  <phase>generate-sources</phase>
                  <configuration>
                      <arguments>add bower karma-phantomjs-launcher --no-lockfile --no-bin-links</arguments>
                  </configuration>
              </execution>

              <execution>
                  <id>bower install</id>
                  <goals>
                      <goal>bower</goal>
                  </goals>
                  <phase>generate-sources</phase>
                  <configuration>
                      <arguments>install --silent --allow-root</arguments>
                  </configuration>
              </execution> 
``

**Comment by qgxiaozhan** [comment]
Hi, how to solve this problem ?

**Comment by andreaTP** [comment]
as a workaround you can go into `zeppelin-web` folder and remove all the present folders but `src`, this worked for me at least, probably the `clean` task should be improved.

**Comment by 1ambda** [comment]
The problem is that `yarn` uses `npm`. So if we install `yarn` only, then it fails. 
In Zeppelin project, we are installing both.

https://github.com/apache/zeppelin/blob/master/zeppelin-web/pom.xml#L70-L71

**Comment by andreaTP** [comment]
I'm from time to time facing again this problem into zeppelin project on `master` branch.
That's why I always fall into this issue :-)

**Comment by 1ambda** [comment]
@andreaTP Which OS do you use?

**Comment by zjffdu** [comment]
Today I hit the same issue on centos 7

**Comment by spencersmith** [comment]
Same problem here. centos7. Using master branch.

**Comment by spencersmith** [comment]
@1ambda Which fix are you referring to?

**Comment by zjffdu** [comment]
Got it, I should use not-root user

**Comment by yang0228** [comment]
Please help i run into a similar failure when compiling zeppelin-0.7.1: 

[INFO] Zeppelin: Scio ..................................... SUCCESS [ 43.334 s]
[INFO] Zeppelin: web Application .......................... FAILURE [  5.521 s]
[INFO] Zeppelin: Server ................................... SKIPPED
[INFO] Zeppelin: Packaging distribution ................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:11 min
[INFO] Finished at: 2017-05-25T01:02:36+08:00
[INFO] Final Memory: 465M/3183M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.3:install-node-and-yarn (install node and yarn) on project zeppelin-web: Could not download Yarn: Could not download https://github.com/yarnpkg/yarn/releases/download/v0.18.1/yarn-v0.18.1.tar.gz: Connect to github-cloud.s3.amazonaws.com:443 [github-cloud.s3.amazonaws.com/54.231.34.41] failed: Connection timed out -> [Help 1]

**Comment by 1ambda** [comment]
@spencersmith 

- https://github.com/apache/zeppelin/issues/2016

I am using OSX. 

@yang0228 Could you update yarn (22.0? or more) and npm installers version in `zeppelin-web/pom.xml` and then try again?

**Comment by tsyrjanen** [comment]
I have also this issue (master branch).
Before
[INFO] Reactor Summary:
I see

[INFO] Installing npm version 4.2.0
[INFO] Downloading https://nodejs.org/dist/npm-4.2.0.tgz to /root/.m2/repository/com/github/eirslett/npm/4.2.0/npm-4.2.0.tar.gz

If you check with browser and go to  https://nodejs.org/dist and try to find npm-4.2.0.tgz, it is not there.

**Comment by tsyrjanen** [comment]
Sorry, I am using also this https://github.com/apache/zeppelin/pull/2483, so what I commented before might be problem in pull request.

**Comment by andreaTP** [comment]
it turned out that there is a bug into the plugin itself using the deprecated parameter `downloadRoot` is bugged, removed it from PR, now it should work.

**Comment by msegel** [comment]
Guys,  its Sept 22, still have the same issue. 
What is the best work around? 
Or better yet... what's the permanent fix?

**Comment by oalam** [comment]
hi all. I'm also facing this issue. is there any workaround yet ?

**Comment by douglaspenna** [comment]
Just discovered that it gets a timeout, when it tries to access angular-viewport-watch

error An unexpected error occurred: "https://raw.githubusercontent.com/shahata/angular-viewport-watch/182923b3934e63817b6fc7b640ecb5c4a011f74c/package.json: ETIMEDOUT"

I'll post more once I've found a fix

**Comment by shral** [comment]
Hi,
I just got this error too, after I deleted the "node_module" and the "node" folder in my project, I could compile without problem.
Best Regards
Shefki

**Comment by Salman9545** [comment]
Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.2:install-node-and-npm (install node and npm) on project dot: The plugin com.github.eirslett:frontend-maven-plugin:1.2 requires Maven version 3.1.0 -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:

![image](https://user-images.githubusercontent.com/32511667/32099648-81ce8c18-bb2a-11e7-8c76-e454af786b99.png)
But this error occour plz help me

**Comment by andreaTP** [comment]
ok, I will just report my experience, basically what is happening is that there is a connection drop by user or by server while downloading dependencies, and this causes an unrecoverable error.
From time to time Python packages server and/or NPM server could be not 100% reliable and that's causing the issue (for a few hours/days) for someone.

We overcome this limitation by configuring properly a locally cached proxy repository (Artifactory) for all of this packages.
A proper retry policy on a package level (especially on wget commands) could eventually ends up with a proper solution.

**Comment by eirslett** [comment]
Maybe we could fetch checksums for node.js/yarn/npm and verify the downloaded package before we extract it...

**Comment by Salman9545** [comment]
than how i can resolve my this error to start work in netbeans for development

**Comment by Salman9545** [comment]
Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.2:install-node-and-npm (install node and npm) on project dot: The plugin com.github.eirslett:frontend-maven-plugin:1.2 requires Maven version 3.1.0 -> [Help 1]
but my maven version is 3.1.0 but this error occour always and my jdk is 8

**Comment by mashhur** [comment]
i got also same issue, it is because of certificate and tried to give download pages (not HTTPS) manually. However, this might not solve your problem if your script is calling another HTTPS download pages.
hope it helps~

`<configuration>
    <nodeVersion>v5.6.0</nodeVersion>
    <npmVersion>3.6.0</npmVersion>
    <nodeDownloadRoot>http://nodejs.org/dist/</nodeDownloadRoot>
    <npmDownloadRoot>http://registry.npmjs.org/npm/-/</npmDownloadRoot>
</configuration>`

**Comment by Tagar** [comment]
https://stackoverflow.com/a/48070980/470583

hope this helps.

**Comment by MahatmaFatalError** [comment]
On my Windows machine the git command was not in $PATH variable which led to the exact same error during build of web Application since npm or bower needs to check out some code. I found out by running mvn command with -e -X for debug.

**Comment by pietermartin** [comment]
Got the same failure on Centos 7. Needed to install bzip2. un-tar of `phantomjs` in the `/tmp` dir was failing.

**Comment by mkhalid12** [comment]
Got the same failure with Ubuntu. Can anyone please help?

**Comment by Tagar** [comment]
@mkhalid12 have you checked my answer on https://stackoverflow.com/a/48070980/470583 
hope this helps you

**Comment by mkhalid12** [comment]
Hi @Tagar thanks for your reply. But I solved this problem no I have following exception 

`[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 3
[ERROR] npm ERR! zeppelin-web@0.0.0 build:dist: `npm-run-all prebuild && grunt pre-webpack-dist && webpack && grunt post-webpack-dist`
[ERROR] npm ERR! Exit status 3
[ERROR] npm ERR!
[ERROR] npm ERR! Failed at the zeppelin-web@0.0.0 build:dist script.`

Can you please help on it ?
Also if you know  When new version 0.8 will release ?

**Comment by chamikaras** [comment]
Already I have faced this Issue in Ubuntu. I moved my  files to home directory and it will fixed the issue. This issue about permissions check that out

**Comment by mcahornsirup** [comment]
I have fixed it by remove ~/m2/repository/com/github/eirslett and build again.

**Comment by RizwanQad** [comment]
I am also facing the same issue:

INFO] --- frontend-maven-plugin:1.6:install-node-and-yarn (install node and yarn) @ common ---
[INFO] Node v8.9.0 is already installed.
[INFO] Installing Yarn version v1.3.2
[INFO] Downloading https://github.com/yarnpkg/yarn/releases/download/v1.3.2/yarn-v1.3.2.tar.gz to C:\Users\sqadri\.m2\repository\com\github\eirslett\yarn\1.3.2\yarn-1.3.2.tar.gz
[INFO] No proxies configured
[INFO] No proxy was configured, downloading directly
Dec 26, 2018 12:35:42 PM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: has_recent_activity=1; path=/; expires=Wed, 26 Dec 2018 10:35:42 -0000". Invalid 'expires' attribute: Wed, 26 Dec 2018 10:35:42 -0000
Dec 26, 2018 12:35:42 PM org.apache.http.client.protocol.ResponseProcessCookies processCookies
WARNING: Invalid cookie header: "Set-Cookie: logged_in=no; domain=.github.com; path=/; expires=Sun, 26 Dec 2038 09:35:42 -0000; secure; HttpOnly". Invalid 'expires' attribute: Sun, 26 Dec 2038 09:35:42 -0000
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 25.929 s
[INFO] Finished at: 2018-12-26T12:35:43+03:00
[INFO] Final Memory: 29M/255M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:install-node-and-yarn (install node and yarn) on project common: Could not download Yarn: Could not download https://github.com/yarnpkg/yarn/releases/download/v1.3.2/yarn-v1.3.2.tar.gz: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]

**Comment by salamswapnil** [comment]
@mcahornsirup It worked for me with your fix. 
Thanks.

**Comment by shazhinde** [comment]
Another successful fix with @mcahornsirup suggestion, thanks!

**Comment by vthinkxie** [comment]
try clear `~/.npm/`

**Comment by ddmx** [comment]
@vthinkxie  it worked, thanks!

**Comment by AaronBotech** [comment]
I have also this issue 

[INFO] Installing npm version 10.16.3
[INFO] Installing jhipster

I have this error, I need help

[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.8.0:npm (webpack build dev) on project app-kibana: Failed to run task: 'npm run webpack:build' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 2 (Exit value: 2) -> [Help 1]

**Comment by anjanas29** [comment]
Getting this issue while compiling opennms 25.0.0

**Comment by zhisheng17** [comment]
@mcahornsirup 
It worked for me with your fix.Thanks.

**Comment by prncoprs** [comment]
Same issue on MacOS 10.15.7.
Removing the `com.github.eirslett:frontend-maven-plugin:1.6` does not work.

**Comment by samanthaherath** [comment]
Dear All'
Already I have faced this Issue in Ubuntu18.04 i am installing opencast when i installing open cast i have faced to this problem please help 

[INFO] Assemblies // Apache Karaf Features ................ SKIPPED
[INFO] Assemblies // Distribution Admin ................... SKIPPED
[INFO] Assemblies // Distribution Admin/Presentation ...... SKIPPED
[INFO] Assemblies // Distribution All-In-One .............. SKIPPED
[INFO] Assemblies // Distribution Ingest .................. SKIPPED
[INFO] Assemblies // Distribution Presentation ............ SKIPPED
[INFO] Assemblies // Distribution Worker .................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:50 min
[INFO] Finished at: 2020-10-14T09:42:13+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.7.6:install-node-and-npm (install node and npm) on project opencast-admin-ui: Could not download Node.js: Got error code 404 from the server. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :opencast-admin-ui

**Comment by emmaearl** [comment]
> I have fixed it by removing ~/m2/repository/com/github/eirslett and build again with version 1.6.

Hm - i don't seem to have this file locally?
