### ISSUE TITLE
frontend-maven-plugin and mvn 3.3.9

### ISSUE THREAD

**Issue by camroe** [eirslett/frontend-maven-plugin#567]
Hi, 

I'm getting the following error from a mvn package command (through IntelliJ 16 on Mac Yosemite 10.10.5)

Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.3:install-node-and-npm (install node and npm) on project wonderville: The plugin com.github.eirslett:frontend-maven-plugin:1.3 requires Maven version 3.1.0

I have tried running under various versions of mvn (3.1.0, 3.1.1, 3.3.9) and get the same error.  If you could point me to the right docs I'll read and apply but I haven't found anything for this particular error (that hasn't claimed to be fixed by the most recent version).;) 

Cheers
Cam

**Comment by eirslett** [comment]
IntelliJ ignores whatever mvn you have installed, it uses its own internal one instead. Try reconfiguring IntelliJ to use your mvn.
