### ISSUE TITLE
Is it possible to configure artifact name to not include arch when downloading npm and node from user specified locations?

### ISSUE THREAD

**Issue by AidanFries** [eirslett/frontend-maven-plugin#569]
Hi,

I am using frontend-maven-plugin to install node and npm during a compilation.

I am using the following versions:

        <frontend-maven-plugin.version>1.3</frontend-maven-plugin.version>
        <node.version>v4.2.6</node.version>
        <npm.version>4.2.0</npm.version>

Initially I was using the default download sites and everything worked fine, but later I had to change to use a local Nexus repository that is hosted in my company, because I need to be able to run the compilation on a Jenkins machine that cannot access external sites.

I have the following in my project pom.xml

```
<plugin>
  <groupId>com.github.eirslett</groupId>
  <artifactId>frontend-maven-plugin</artifactId>
  <version>${frontend-maven-plugin.version}</version>
  <!-- install local installation of node and npm in the target directory -->
  <configuration>
    <installDirectory>target</installDirectory>
   </configuration>
  <executions>
    <execution>
      <id>install node and npm</id>
      <goals>
      <goal>install-node-and-npm</goal>
      </goals>
      <configuration>
        <nodeVersion>${node.version}</nodeVersion>
        <npmVersion>${npm.version}</npmVersion>
        <nodeDownloadRoot>https://nexus.company.net/service/local/repositories/applications/content/org/nodejs/node/</nodeDownloadRoot>
        <npmDownloadRoot>https://nexus.company.net/service/local/repositories/applications/content/com/github/npm/npm/</npmDownloadRoot>
      </configuration>
    </execution>
  </executions>
</plugin>
```

However, the compilation fails with the following error:

[INFO] Downloading https://nexus.company.net/service/local/repositories/applications/content/org/nodejs/node/v4.2.6/node-v4.2.6-linux-x64.tar.gz to /home/user/.m2/repository/com/github/eirslett/node/4.2.6/node-4.2.6-linux-x64.tar.gz

The problem is the arch "x64" that is in the artifact name. On our local Nexus repository, we have artifacts with the name node-4.2.6-linux.tar.gz

My question is: is it possible to configure the plugin to not expect the arch in the name? or what is the correct solution?

Thanks a lot!

**Comment by eirslett** [comment]
No, it's not possible. You'll have to rename the files on Nexus.
