### ISSUE TITLE
"npm --install <package>" not working, due to npm installation directory name containing npm version.

### ISSUE THREAD

**Issue by AidanFries** [eirslett/frontend-maven-plugin#570]
Hi,

I was successfully using installing node and npm (and later using npm to install raml2html) using the following versions:

<node.version>v4.2.6</node.version>
<npm.version>3.5.2</npm.version>
OS: Ubuntu 16.04
java version "1.8.0_121"
Apache Maven 3.3.9

However, I have upgraded the specified version of npm to 4.2.0 (everything else is the same as above) and now I have encounter a problem. When I try to execute "npm install <package>" I get an error.

The root cause of the issue seems to be that with version 4.2.0 of npm, it is installed at the following directory:

node/node_modules/npm-4.2.0

With the older version, it was installed at:

node/node_modules/npm

The exact error that I get is the following:

```
[INFO] Running 'npm install --prefix ./target/node/node_modules/npm-4.2.0 raml2html' in /home/user/work/project/module
[ERROR] module.js:328
[ERROR]     throw err;
[ERROR]     ^
[ERROR] 
[ERROR] Error: Cannot find module '/home/user/workproject/module/target/node/node_modules/npm/bin/npm-cli.js'
[ERROR]     at Function.Module._resolveFilename (module.js:326:15)
[ERROR]     at Function.Module._load (module.js:277:25)
[ERROR]     at Function.Module.runMain (module.js:442:10)
[ERROR]     at startup (node.js:136:18)
[ERROR]     at node.js:966:3
```

I have found that if I manually create a softlink from called "npm" that points to the directory "npm-4.2.0" (in the directory target/node/node_modules) then it works.

What is the suggested solution?

Thanks a lot (again)!!

**Comment by eirslett** [comment]
Correct solution: tell npm to stop breaking their package layout all the time.
Alternative solution: use yarn, or an older version of npm.
