### ISSUE TITLE
maven.frontend.failOnError doesn't work in latest release

### ISSUE THREAD

**Issue by danshome** [eirslett/frontend-maven-plugin#581]
The maven.frontend.failOnError property described in the current Readme doesn't work in the 1.3 release.

**Comment by mriehema** [comment]
It will be part of the next release.

**Comment by danshome** [comment]
When will 1.4 release?


--

Thanks,

Dan McLaughlin
dan@danshome.net
mobile: 512.633.8086

NOTICE: This e-mail message and all attachments transmitted with it are for
the sole use of the intended recipient(s) and may contain confidential and
privileged information. Any unauthorized review, use, disclosure or
distribution is strictly prohibited. The contents of this e-mail are
confidential and may be subject to work product privileges. If you are not
the intended recipient, please contact the sender by reply e-mail and
destroy all copies of the original message.

On Mon, Mar 20, 2017 at 4:52 AM, Michael Riehemann <notifications@github.com

**Comment by danshome** [comment]
Do you have a date for the 1.4 release?

**Comment by mriehema** [comment]
Well, @eirslett is the only one, who can do it. We have to wait until he is back.

**Comment by mriehema** [comment]
Released! Close please.
