### ISSUE TITLE
The documentation for maven.frontend.failOnError is wrong

### ISSUE THREAD

**Issue by KaeruCT** [eirslett/frontend-maven-plugin#583]
**Summary/TL;DR**
The property is `failOnError`, not `maven.frontend.failOnError` as stated in `README.md`

**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behavior?**
An npm execution is failing on my build (but that's to be expected sometimes, for reasons not worth mentioning here)
I noticed the property `maven.frontend.failOnError` was recently added, so I followed the instructions to use it.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Add the following configuration to the npm execution
```xml
<configuration>
    <maven.frontend.failOnError>false</maven.frontend.failOnError>
</configuration>
```
2. Run your build, have the npm execution fail
3. The build fails as well

**What is the expected behavior?**
The npm execution fails but the build doesn't

**Please mention your frontend-maven-plugin and operating system version.**
frontend-maven-plugin version: 1.4
OS: OSX 10.12.3

**Fix**
I was able to fix this by using the following configuration instead
```xml
<configuration>
    <failOnError>false</failOnError>
</configuration>
```
I'm not 100% familiar with how maven plugins work but I guess this is because of this code in `AbstractFrontendMojo.java`:

```java
@Parameter(property = "failOnError")
protected Boolean failOnError;
```

I'm willing to send in a MR to fix this, but I'd like to know if it's preferred to change the documentation or the name of the parameter.

**Comment by eirslett** [comment]
Better to just change the docs for now. Thanks!
