### ISSUE TITLE
yarn test output is marked as [ERROR]

### ISSUE THREAD

**Issue by mihhail-lapushkin** [eirslett/frontend-maven-plugin#584]
**Do you want to request a _feature_ or report a _bug_?**
bug

**What is the current behavior?**
yarn test output is marked as [ERROR]
```
[INFO] yarn test v0.21.3
[INFO] $ react-scripts test --env=jsdom 
[ERROR]  PASS  src/component/SomeComponent.test.js
[ERROR] 
[ERROR] Test Suites: 1 passed, 1 total
[ERROR] Tests:       1 passed, 1 total
[ERROR] Snapshots:   0 total
[ERROR] Time:        1.455s
[ERROR] Ran all test suites.
[INFO] Done in 2.31s.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
1) create an app using create-react-app
2) write some tests in Jest
3) run some tests using:
```
          <execution>
            <id>test</id>
            <goals>
              <goal>yarn</goal>
            </goals>
            <phase>test</phase>
            <configuration>
              <arguments>test</arguments>
              <environmentVariables>
                <CI>true</CI>
              </environmentVariables>
            </configuration>
          </execution>
```

**What is the expected behavior?**
should be on [INFO] I guess

**Please mention your frontend-maven-plugin and operating system version.**
1.4
node 6.10.0
yarn 0.21.3
macOS 10.11.6

**Comment by mriehema** [comment]
This sounds similar to #411.

**Comment by eirslett** [comment]
This is a feature, not a bug.
frontend-maven-plugin takes all output from stderr and forwards it as ERROR logs, and all output from stdout forwarded as INFO logs.
We have no control over where yarn chooses to send its log output.
