### ISSUE TITLE
Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.23:install-node-and-npm

### ISSUE THREAD

**Issue by kavipriya2005** [eirslett/frontend-maven-plugin#594]
Hi,

I am getting this following error while building the project. How should I overcome this?

[INFO] --- lesscss-maven-plugin:1.3.3:compile (default) @ dash ---
[INFO] Nothing to compile - no LESS sources found
[INFO]
[INFO] --- maven-dependency-plugin:2.2:unpack (checkstyle) @ dash ---
[INFO] Configured Artifact: com.netiq.ism:checkstyle:checks:1.0.0:zip
[INFO] checkstyle-1.0.0-checks.zip already unpacked.
[INFO]
[INFO] --- frontend-maven-plugin:0.0.23:install-node-and-npm (install node and n
pm) @ dash ---
[INFO] Node v0.12.7 is already installed.
[INFO] Installing npm version 2.11.3
[INFO] Downloading NPM from http://registry.npmjs.org/npm/-/npm-2.11.3.tgz to E:
\dash\grunt\npm.tar.gz
[INFO] No proxy was configured, downloading directly
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.447 s
[INFO] Finished at: 2017-04-25T12:01:25+05:30
[INFO] Final Memory: 16M/307M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.23:
install-node-and-npm (install node and npm) on project dash: Execution instal
l node and npm of goal com.github.eirslett:frontend-maven-plugin:0.0.23:install-
node-and-npm failed: E:\dash\grunt\.\node\npm is not a directory -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutio
nException

**Comment by mriehema** [comment]
please update to the latest version of frontend-maven-plugin. 0.0.23 is very old...
