### ISSUE TITLE
Yarn installed locally but "yarn install" fails with not found

### ISSUE THREAD

**Issue by vediga** [eirslett/frontend-maven-plugin#600]
I am installing node and yarn which seems to be working fine, but yarn install fails with command not found. Below is the log snippet..

...
[INFO] Installed node locally.
[INFO] Installing Yarn version v0.17.10
...
Installed Yarn locally.
[INFO] 
[INFO] --- frontend-maven-plugin:1.2:yarn (yarn install) @ ...
[INFO] Running 'yarn install' in path/to/client
[ERROR] /path/to/client/node/yarn/dist/bin/yarn: line 2: sed: command not found

Any idea on what could be going on here?

**Comment by eirslett** [comment]
Maybe you changed the PATH variable, so that `sed` isn't found on path any longer. Or maybe you're trying to run the build on a machine that for some reason doesn't have `sed` installed, in which case you can probably apt-get install it etc.

**Comment by vediga** [comment]
I had to add it to the path in the build environment
