### ISSUE TITLE
Error on Installing @microsoft/generator-sharepoint

### ISSUE THREAD

**Issue by haitomahesh** [eirslett/frontend-maven-plugin#606]
While installing SharePoint Framework ("microsoft/generator-sharepoint"), gives the below error.

C:\Users\XXXX>**npm i  "microsoft/generator-sharepoint -g"**

npm WARN deprecated es6-collections@0.5.6: not actively maintained anymore
**npm ERR! tar.unpack untar error C:\Users\XXXX\AppData\Roaming\npm-cache-new\@microsoft\sp-lodash-subset\1.0.0\package.tgz
npm ERR! tar.unpack untar error C:\Users\XXXX\AppData\Roaming\npm-cache-new\@microsoft\sp-module-interfaces\1.0.0\package.tgz**
D:\Program Files\nodejs
`-- (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @microsoft/sp-module-interfaces@1.0.0 (node_modules\@microsoft\generator-sharepoint\node_modules\@microsoft\sp-m
odule-interfaces):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Error: EPERM: operation not permitted, open **'D:\Program Files\nodejs\node_modules\.staging\@microsoft\sp-module-
interfaces-c170f113\EULA\Microsoft Sharepoint Framework - Standalone (free) Use Terms - Korean.docx'
npm ERR! path D:\Program Files\nodejs\node_modules\.staging\@microsoft\sp-lodash-subset-bd0eac78\EULA\Microsoft Sharepoint Framework - Standalone (free) Use Terms - Korean.docx**
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall open
npm ERR! Error: EPERM: operation not permitted, open 'D:\Program Files\nodejs\node_modules\.staging\@microsoft\sp-lodash-subset-bd0eac78\EULA\Microsoft Sharepoi
nt Framework - Standalone (free) Use Terms - Korean.docx'
npm ERR!  { Error: EPERM: operation not permitted, open 'D:\Program Files\nodejs\node_modules\.staging\@microsoft\sp-lodash-subset-bd0eac78\EULA\Microsoft Share
point Framework - Standalone (free) Use Terms - Korean.docx'
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'open',
npm ERR!   path: 'D:\\Program Files\\nodejs\\node_modules\\.staging\\@microsoft\\sp-lodash-subset-bd0eac78\\EULA\\Microsoft Sharepoint Framework - Standalone (f
ree) Use Terms - Korean.docx',
npm ERR!   parent: '@microsoft/generator-sharepoint' }
npm ERR!
**npm ERR! Please try running this command again as root/Administrator.**

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\XXXX\AppData\Roaming\npm-cache-new\_logs\2017-05-18T15_20_17_737Z-debug.log

I did...
1. npm cache clean
2. fresh install in different networks (lan, home, data)
3. running the command with Admin 

Anyone faced the same issue?  Please help with your inputs.

**Comment by eirslett** [comment]
Looks like you're just running plain npm, without this maven plugin?
In that case it's definitely not a problem with the plugin, since it's not being run at all. I think you're asking the question in the wrong place, try some microsoft or typescript forums instead ;-)

**Comment by haitomahesh** [comment]
Oh my bad, raised it in wrong place... thanks for the response....
