### ISSUE TITLE
Don't clean cache with NPM 5

### ISSUE THREAD

**Issue by keirlawson** [eirslett/frontend-maven-plugin#609]
I just tried to use this plugin with Node 8 and NPM 5, however when running a `mvn clean install` I get:

```
[INFO] --- frontend-maven-plugin:1.4:npm (Cleaning cache) @ my-project ---
[INFO] Running 'npm cache clean' in /home/keir/Code/myProject/src/main/react
[ERROR] npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead.
[ERROR] npm ERR! 
[ERROR] npm ERR! If you're sure you want to delete the entire cache, rerun this command with --force.
[ERROR] 
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     /home/keir/.npm/_logs/2017-05-31T08_18_56_026Z-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

```

It would be great if we could change this step to run the verify step mentioned in the error message or skip this step entirely as presently it seems to prevent use of NPM 5 with this plugin.

I am using version 1.4 of the plugin on Fedora 25

**Comment by keirlawson** [comment]
Oops, just realised this is an issue with our local setup

**Comment by mriehema** [comment]
`npm cache clean` shouldn't be a part of this plugin. Could you check your pom (or post the plugin part of it), if you're running this explicit with an `<execution>`.
