### ISSUE TITLE
redirecting bower install to a different folder.

### ISSUE THREAD

**Issue by adamjalred** [eirslett/frontend-maven-plugin#610]
Hey, I had a relatively simple question, currently when I am doing the bower install portion of the frontend-maven-plugin and it is trying to run 'bower install' on /Users/adamalred/WorkFolder/sites-validation and I am wanting it to do 'bower install' on /Users/adamalred/WorkFolder/sites-validation/src/main/resources/public. Do anyone know an easy fix for this issue?

**Comment by adamjalred** [comment]
EDIT: Here is what I am doing and I am getting this error..."ava.io.IOException: Cannot run program "/src/main/resources/public/node/node" (in directory "/Users/adamalred/WorkFolder/sites-validation")"

 <plugin>
                <groupId>com.github.eirslett</groupId>
                <artifactId>frontend-maven-plugin</artifactId>
                <version>1.4</version>
                <executions>
                    <execution>
                        <id>install node and npm</id>
                        <goals>
                            <goal>install-node-and-npm</goal>
                        </goals>
                        <configuration>
                            <nodeVersion>v6.10.3</nodeVersion>
                            <npmVersion>3.10.10</npmVersion>
                        </configuration>
                    </execution>
                    <execution>
                        <id>npm install</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <configuration>
                            <arguments>install</arguments>
                        </configuration>
                    </execution>
                    <execution>
                        <id>bower install</id>
                        <goals>
                            <goal>bower</goal>
                        </goals>
                        <configuration>
                            <arguments>install</arguments>
                            <installDirectory>/src/main/resources/public</installDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

**Comment by SergioArrighi** [comment]
I have the same issue.
In your pom I see that </installDirectory> is repeated twice.
In my case the pom from which I execute the plugin is not exactly were package.json is.
Not sure how to proceed, I though I could specify it with <installDirectory>

**Comment by eirslett** [comment]
installDirectory is not a configuration value for bower, it's for choosing where you want to install node.js (inside the project).
You cannot configure bower installation dir with this plugin, you have to configure it with bower directly. Maybe there's a CLI flag or something.
