### ISSUE TITLE
Why does installDirectory have "node" appended to path at install time?

### ISSUE THREAD

**Issue by hhwebdev** [eirslett/frontend-maven-plugin#622]
Simply, I'm trying to use my local install of Node.js at install time - (instead of reinstalling node  every time I run mvn install). 

First thing I do is remove the `<execution>` with `<id>install node and npm</id>` from pom.

Then, I define a local envioronment var to my win-machine to point at local exe of Node.js . THen I specify var in my pom under plugin's configuration. 
`<installDirectory>${env.NODE_HOME}</installDirectory>`

Next, I run mvn install, but it fails, saying that it's looking for node exec on path of  NODE_HOME/**node**
where **node** was appended to the path. 

Am I missing an obviously different way to configure the plugin to point a specific directy without the addtion of "node" ? 

Working around the issue, I reinstall Node.js to a location to include **node** in the path, and then it works. But doesn't seem desirable in general. I would expect plugin to find exe on path given in env.Variable. 

frontend-maven-plugin:1.3
os: win10

**Comment by eirslett** [comment]
You don't need to reinstall node every time you run mvn install. If it has already downloaded it once, it will use the one it has cached.
If you truly wish to use your local installation of node, then you cannot use this maven plugin, you should use something like exec-maven-plugin instead.

**Comment by hhwebdev** [comment]
Thanks for quick reply! I prefer to continue usage of this plugin, as it meets needs perfectly. My concern is only configuration related, not functional, and I prefer usage of local install of Node.js only because it significantly reduces local build times.

**Comment by Lakshay-Awasthi** [comment]
Hi,
Is there any alternate to use locally installed node, as i am also facing the same issue of path

**Comment by eirslett** [comment]
If the only issue is local build times, that shouldn't be an issue since Node.js is only downloaded for the project on the first build - on subsequent builds, it will reuse whatever is in the `node` folder, if the node version is correct.

**Comment by Ashishk80** [comment]
I completely agree with @hhwebdev  and @Lakshay-Awasthi 

I have provided the installDirectory where exactly is node.exe (installed as per orgnization policy and no manual control), however the plugin appends node/node.exe in the install directory and eventually it does not work. I think plugin should provide a confirg and should give control to developer for defining node.exe path.
<plugin>
            <groupId>com.github.eirslett</groupId>
            <artifactId>frontend-maven-plugin</artifactId>
            <version>1.11.0</version>
            <configuration>
            <nodeVersion>v12.1.0</nodeVersion>
                <workingDirectory>${project.basedir}/src/main/webapp/mswcrui</workingDirectory>
                <installDirectory>C:\FAST\NodeJs\12.1.0</installDirectory>

**Comment by eirslett** [comment]
@Ashishk80 If your organization policy is to always have installed node.exe on an exact path, that's actually easier for Maven - instead of using this plugin, you should then use exec-maven-plugin.
You can try following this guide: https://addyosmani.com/blog/making-maven-grunt/
