### ISSUE TITLE
Maven build not failing on Webpack error.

### ISSUE THREAD

**Issue by dmcgeown** [eirslett/frontend-maven-plugin#627]
Hi,

My maven build is not failing when a webpack error occurs. I've looked at the docs and I can't anything related to this issue. Is it a know problem? 

The following code snippet show a valid webpack failure but the maven build successed.

Any advice would be welcome.

[INFO] ERROR in ./client.js
[INFO] Module not found: Error: Cannot resolve 'file' or 'directory' 
...
[INFO]  @ ./client.js 77:0-62
[INFO] Child html-webpack-plugin for "index.html":
[INFO]         + 3 hidden modules
[INFO]
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 46.046 s
[INFO] Finished at: 2017-07-13T10:29:04+01:00
[INFO] Final Memory: 13M/216M
[INFO] ------------------------------------------------------------------------

**Comment by eirslett** [comment]
This is a known problem with Webpack, not with this plugin.
What this plugin does, is run commands, and check for exit codes - if the exit code is 0, it is regarded as a successful run, it not, it's considered failed.
If you google around a bit, you'll see various people discussion Webpack always existing with code 0, even when it doesn't build properly, and there are a number of workarounds you can use to force it to return a non-zero exit code after errors.

I usually add this to my Webpack config:

```javascript
function failOnCompilationErrorPlugin () {
  this.plugin('done', stats => {
    if (stats.compilation.errors && stats.compilation.errors.length &&
      process.argv.indexOf('--bail') !== -1) {
      console.log(stats.compilation.errors);
      process.exit(1);
    }
  });
}

module.exports = {
  // lots of webpack config here...
  plugins: [
    // other webpack plugins here... and this "plugin" too:
    failOnCompilationError
  ]
}
```

**Comment by dmcgeown** [comment]
Hi Eirik,

That worked perfectly. This plugin has saved me a whole bunch of headaches so thanks million for taking the time build it. Much appreciated!

Best regards,
Darragh
