### ISSUE TITLE
Error: Use of const in strict mode

### ISSUE THREAD

**Issue by mavlesreennap** [eirslett/frontend-maven-plugin#629]
While doing the build using the frontend-maven-plugin version 1.4 along with gulp build, getting the error " SyntaxError: Use of const in strict mode."

run-sequence version used -->   "run-sequence": "~1.1"

Below is the error stack:

[INFO] --- frontend-maven-plugin:1.4:gulp (gulp build) @ proj ---
[INFO] Running 'gulp ' in /Users/ps/Documents/gitlab/proj/
[ERROR] 
[ERROR] /Users/ps/Documents/gitlab/proj/node_modules/run-sequence/node_modules/chalk/index.js:2
[ERROR] const escapeStringRegexp = require('escape-string-regexp');
[ERROR] ^^^^^
[ERROR] SyntaxError: Use of const in strict mode.
[ERROR]     at Module._compile (module.js:439:25)
[ERROR]     at Object.Module._extensions..js (module.js:474:10)
[ERROR]     at Module.load (module.js:356:32)
[ERROR]     at Function.Module._load (module.js:312:12)
[ERROR]     at Module.require (module.js:364:17)
[ERROR]     at require (module.js:380:17)
[ERROR]     at Object.<anonymous> (/Users/ps/Documents/gitlab/proj/node_modules/run-sequence/index.js:5:14)
[ERROR]     at Module._compile (module.js:456:26)
[ERROR]     at Object.Module._extensions..js (module.js:474:10)
[ERROR]     at Module.load (module.js:356:32)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

Please help to resolve this issue.

**Comment by eirslett** [comment]
Maybe you configured it to use a too old verdion of node.js. Try v6?

**Comment by mavlesreennap** [comment]
@eirslett  Thanks eirslett for the update.
Now I am using frontend-maven-plugin v1.4, node v6.11.1 and npm v4.6.1. But getting the below error.

[ERROR] 12 warnings and 16 errors generated.
[ERROR] make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
[ERROR] gyp ERR! build error 
[ERROR] gyp ERR! stack Error: `make` failed with exit code: 2
[ERROR] gyp ERR! stack     at ChildProcess.onExit (/Users/u1/Documents/proj/node/node_modules/npm/node_modules/node-gyp/lib/build.js:285:23)
[ERROR] gyp ERR! stack     at emitTwo (events.js:106:13)
[ERROR] gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
[ERROR] gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
[ERROR] gyp ERR! System Darwin 16.6.0
[ERROR] gyp ERR! command "/Users/u1/Documents/proj/node/node" "/Users/u1/Documents/proj/node/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
[ERROR] gyp ERR! cwd /Users/u1/Documents/proj/node_modules/bufferutil
[ERROR] gyp ERR! node -v v6.11.1
[ERROR] gyp ERR! node-gyp -v v3.6.0
[ERROR] gyp ERR! not ok 

Please let me know if I am missing anything.

**Comment by eirslett** [comment]
Try to delete the node_modules folder and try again?

**Comment by mavlesreennap** [comment]
@eirslett I tried by deleting node_modules. But still the error exists.

**Comment by eirslett** [comment]
Do the commands work when you run them directly in the terminal, without this plugin? It looks like it's a problem with node/npm, not with this plugin.

**Comment by mavlesreennap** [comment]
@eirslett Thanks eirslett. This is an issue with run-sequence. It is fixed in run-sequence v2.0
