### ISSUE TITLE
Maven build won't fail when integration-test fails

### ISSUE THREAD

**Issue by hnuttin** [eirslett/frontend-maven-plugin#631]
When running grunt test during the 'integration-test' phase and some tests are failing, the maven builds is still succesfull. I would expect this not to be de default behaviour. I've tried experimenting with both the 'maven.test.failure.ignore' and 'maven.frontend.failOnError' property but this does not have any impact.

We see this behaviour since upgrading from version 0.0.20 to 1.4.

Strangely enough this is exactly the oposite as reported in #534

Any ideas? Thanks you.

**Comment by eirslett** [comment]
Try the newly released 1.5?

**Comment by hnuttin** [comment]
Same issue. Doing something wrong here? Plugin configuration:

`<plugin>
    <groupId>com.github.eirslett</groupId>
    <artifactId>frontend-maven-plugin</artifactId>
    <version>1.5</version>
    <configuration>
        <workingDirectory>src/test/lib</workingDirectory>
        <nodeDownloadRoot>https://nodejs.org/dist/</nodeDownloadRoot>
    </configuration>
    <executions>
        <execution>
            <id>install node and npm</id>
            <goals>
                <goal>install-node-and-npm</goal>
            </goals>
            <configuration>
                <nodeVersion>v6.11.1</nodeVersion>
                <npmVersion>5.3.0</npmVersion>
            </configuration>
        </execution>
        <execution>
            <id>npm install</id>
            <goals>
                <goal>npm</goal>
            </goals>
        </execution>
        <execution>
            <id>run e2e</id>
            <goals>
                <goal>grunt</goal>
            </goals>
            <phase>integration-test</phase>
            <configuration>
                <arguments>e2e</arguments>
            </configuration>
        </execution>
    </executions>
</plugin>`

**Comment by eirslett** [comment]
Try running `grunt e2e` on the command line and then `echo $?` to show the exit code. If grunt exits with exit code 0, the plugin will regard it as a successful run.

**Comment by hnuttin** [comment]
you are right, grunt exists with code 0, I'll look into it further, no frontend-maven-plugin, thanks alot for helping out!
