### ISSUE TITLE
node binary incompatible with Alpine, specifically Docker maven:alpine

### ISSUE THREAD

**Issue by gsharp** [eirslett/frontend-maven-plugin#633]
**Do you want to request a _feature_ or report a _bug_?**

This is part feature request and bug... but mostly an FYI.

If you're using the Docker maven:alpine version the nodejs binary that this plugin installs will not be happy.

**What is the current behavior?**

* it will install node
* It will give an error that the node file is not found and cause a maven error

**If the current behavior is a bug, please provide the steps to reproduce.**

* it will install an incompatible binary version of node and try to run it
* it will complain that the file is not found and error out

**What is the expected behavior?**

* auto detect / install the Alpine binary (if it exists)
* provide a prerequisites info in the readme that there may be issues with the node binary not being compiled for Alpine Linux (musl)
* provide any workarounds or just say "Alpine is not supported".

**Please mention your frontend-maven-plugin and operating system version.**

* Plugin version: 1.5 
* OS: Docker maven:alpine

**Comment by gsharp** [comment]
btw, the solve for this is to use Docker ```maven:latest```

**Comment by stickycode** [comment]
@gsharp That is not a solution that is a workaround. 

I'm fairly confident the issue is that the default shell in alpine does not do path mapping like bash does. So executing /some/path/bin/node in a directory of /some/path tries to run /some/path/some/path/bin/node, 

If that is the case then the correct solution is to use a relative path to the executable when you provide  a working directory to the process builder.

**Comment by gsharp** [comment]
@stickycode fair enough...it is indeed a workaround. I'll poke about with the paths as well, thanks for path the tip.

**Comment by tholu** [comment]
Same problem here, a PR would be very nice @stickycode !

**Comment by tholu** [comment]
@stickycode Do you recall in what way? We're currently experimenting with moving our Docker images for testing to Alpine and this is currently the only issue left to get everything working again. We are looking into replacing the node/yarn functionality with maven plugins right now.

**Comment by tholu** [comment]
@gsharp Did you find anything regarding the path issue for a real fix? Maven plugins to compile sass and minify JS/CSS are not really working either.

**Comment by stickycode** [comment]
The underlying issue I believe is the expansion of paths in the  shell .
Bash will let you define a working directory and a full path to a binary.
Whereas ash (shell in busybox) expects a relative path for the binary.

It's possible that it is an issue with the process builder. Rather that how
the plugins use it.

A workaround is to install bash in base image and invoke maven in that
shell.

**Comment by flavioschuindt** [comment]
@stickycode not sure if even this workaround works. I am running jenkins inside a docker container and running bash too. Doesn't work.

```
bash-4.3$ mvn install

[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.0:npm (npm print config) on project hc-hccwf-caseexchange-ui: Failed to run task: 'npm config ls -l' failed. java.io.IOException: Cannot run program "/var/jenkins_home/workspace/project/node/node" (in directory "/var/jenkins_home/workspace/project"): error=2, No such file or directory -> [Help 1]
```
Any idea how to put this to work?

**Comment by viktorgt** [comment]
Same issue here, using alpine image. The workaround using a bash shell does not work.

**Comment by tholu** [comment]
We worked around it using `sass-maven-plugin` from `nl.geodienstencentrum.maven` and `minify-maven-plugin` from `com.samaxes.maven`.

**Comment by mjagus** [comment]
Using Alpine with glibc seems to get around the issue as well.

**Comment by visibilityspots** [comment]
@mjagus could you elaborate how using alpine together with glibc fixed this for you? I got stuck on 
```
[ERROR] node: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
```
with a docker alpine based container using 

```
 wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://raw.githubusercontent.com/sgerrand/alpine-pkg-glibc/master/sgerrand.rsa.pub; \
wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.27-r0/glibc-2.27-r0.apk; \
apk add glibc-2.27-r0.apk; \
```

as a RUN command in my Dockerfile

**Comment by mjagus** [comment]
@visibilityspots I created my image based on [alpine-glibc](https://hub.docker.com/r/frolvlad/alpine-glibc/) and it just worked. To be more specific, a different kind of error now appears in logs
```
/usr/lib/libstdc++.so.6: no version information available
```
but it doesn't fail the build so I just learned to ignore it.

**Comment by tomekit** [comment]
Hey @mjagus if you find a way to fix the: `/usr/lib/libstdc++.so.6: no version information available` please let me know. It's working, but annoying. Thanks :)

**Comment by lawsa** [comment]
I think the problem is `ldd node/node` returns
<pre>
bash-4.4# ldd node/node
        /lib64/ld-linux-x86-64.so.2 (0x7f2124252000)
        libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7f2124252000)
        librt.so.1 => /lib64/ld-linux-x86-64.so.2 (0x7f2124252000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7f2123f00000)
        libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f2124252000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7f2123cee000)
        libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f2124252000)
        libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f2124252000)
</pre>but `/lib64` doesn't even exist in alpine. `ld-linux-*` doesn't exist on alpine anywhere. It's not about paths, it's about dynamic linking. One solution would be: use the `node` that's on the path if there is one rather than installing an incompatible one?

**Comment by wezoEtienne** [comment]
Did anyone try to install nodejs with apk and copy the binary to the local project folder?

i.e.
> apk add --update nodejs
> cp /usr/bin/node /myProject/node
> mvn com.github.eirslett:frontend-maven-plugin:install-node-and-npm

Would that work as a temporary workaround?

**Comment by mbraeger** [comment]
frontend-maven-plugin is working for me in my alpine docker image when installing `glibc` like that:
```
apk --no-cache add ca-certificates wget; \
wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://raw.githubusercontent.com/sgerrand/alpine-pkg-glibc/master/sgerrand.rsa.pub; \
wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.27-r0/glibc-2.27-r0.apk; \
wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.27-r0/glibc-bin-2.27-r0.apk; \
wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.27-r0/glibc-i18n-2.27-r0.apk; \
apk add glibc-2.27-r0.apk; \
apk add glibc-bin-2.27-r0.apk; \
apk add glibc-i18n-2.27-r0.apk;
```

So, similar to what @visibilityspots suggested. However, I also see the mentioned warning message:

```
/usr/lib/libstdc++.so.6: no version information available (required by <my-build-directory>/node/node)
```

**Comment by dominiquemongelli** [comment]
For information, the Url of the public signing key has changed. There is also an update version of glibc.
Here is the updated script:
  - apk --no-cache add ca-certificates wget
  - wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
  - wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.28-r0/glibc-2.28-r0.apk
  - wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.28-r0/glibc-bin-2.28-r0.apk
  - wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.28-r0/glibc-i18n-2.28-r0.apk
  - apk add glibc-2.28-r0.apk
  - apk add glibc-bin-2.28-r0.apk
  - apk add glibc-i18n-2.28-r0.apk

I confirm it works like a charm on a maven docker alpine image.

**Comment by bcharfi** [comment]
Hi,
there is already a workaround for the main problem:
`Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.7.6:npm (npm install) on project app.com: Failed to run task: 'npm install' failed. java.io.IOException: Cannot run program "/builds/app/target/node/node" (in directory "/builds/app/angular"): error=2, No such file or directory`

I use:
frontend-maven-plugin version: 1.7.6
node ersion: v10.15.3
npm version: 6.4.1
docker image:  maven:3.6.1-jdk-8-alpine or maven:3-jdk-8-alpine

**Comment by eirslett** [comment]
If you're already using Docker, I suggest that you use a multi-stage build instead:

Dockerfile:

```
FROM node:latest as nodeBuilder

ADD . .

RUN npm ci

RUN npm build

FROM maven:something as mavenBuilder

ADD frontend-built from nodeBuilder // something like that

RUN mvn clean install

FROM java:11

ADD myapp.jar from mavenBuilder

CMD java -jar myapp.jar // something like that
```

That way, you don't run the node.js toolchain at all from maven, you run it in a completely separate step.

**Comment by bcharfi** [comment]
I have solving the problem using the docker image **maven:3-jdk-8** instead of **maven:3-jdk-8-alpine**
