### ISSUE TITLE
Support for pnpm

### ISSUE THREAD

**Issue by netlykos** [eirslett/frontend-maven-plugin#634]
**Do you want to request a _feature_ or report a _bug_?**
A feature

**What is the current behavior?**
Package managers supported are npm and yarn, please also add support for pnpm. 

**If the current behavior is a bug, please provide the steps to reproduce.**
n/a

**What is the expected behavior?**
Execution goal should allow pnpm as well similar to yarn configuration.

**Please mention your frontend-maven-plugin and operating system version.**
frontend-maven-plugin - version 1.4.
OS - Windows 7, x86_64 and Linux (Redhat, 2.6.18-308.el5) x86_64

**Comment by eirslett** [comment]
See this issue, same solution can be used: https://github.com/eirslett/frontend-maven-plugin/issues/630

**Comment by domschmidt** [comment]
pnpm is the current top player for huge projects with many npm modules.
please integrate the call to pnpm.
it should be very easy, as commands can be passed 1:1 by just whitelistening the "pnpm" goal.

**Comment by leonard84** [comment]
The solution of #630 would mix `pnpm` and `npm`, as both use a different structure in `node_modules` this could lead to strange behavior. Furthermore, it makes it quite cumbersome to use `pnpm` if you have to mirror calls as scripts in `package.json`.

**Comment by leonard84** [comment]
@eirslett now that Intellij finally supports this, I'm taking another look at this. In #630 you suggest using something like this:

```
{
  "devDependencies": {
    "pnpm": "some version"
  },
  "scripts": {
    "pnpm-install": "pnpm install"
  }
}
```

However, my `devDependencies` are not empty so how should I install only `pnpm` with `npm` and then use `pnpm` to resolve all the other dependencies as `pnpm` uses the same `package.json`?

Thats more what my `packacke.json` looks like.
```
{
  "dependencies": {
    "@angular/animations": "^8.1.2",
    "@angular/common": "^8.1.2",
    "@angular/compiler": "^8.1.2",
    "@angular/core": "^8.1.2",
    "@angular/forms": "^8.1.2",
    "@angular/platform-browser": "^8.1.2",
    "@angular/platform-browser-dynamic": "^8.1.2",
    "@angular/router": "^8.1.2",
    "bootstrap": "3.3.7",
    "core-js": "^3.1.4",
    "ngx-bootstrap": "^5.1.0",
    "rxjs": "^6.5.2",
    "tslib": "^1.10.0",
    "zone.js": "^0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.801.2",
    "@angular/cli": "^8.1.2",
    "@angular/compiler-cli": "^8.1.2",
    "@angular/language-service": "^8.1.2",
    "@types/jasmine": "~3.3.14",
    "@types/jasminewd2": "~2.0.6",
    "@types/core-js": "^2.5.2",
    "@types/node": "^12.6.8",
    "codelyzer": "^5.0.1",
    "concurrently": "^4.1.1",
    "cpx": "1.5.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.2.0",
    "karma-chrome-launcher": "~3.0.0",
    "karma-coverage-istanbul-reporter": "~2.0.5",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "karma-script-launcher": "^1.0.0",
    "protractor": "^5.4.2",
    "ts-node": "~8.3.0",
    "tslint": "^5.18.0",
    "typescript": "~3.4.5"
  }
}
```

**Comment by noblica** [comment]
Hey guys,
I had the same issue and since i saw that support for `npx` [has been recently added](https://github.com/eirslett/frontend-maven-plugin/pull/867), I just updated my `frontend-maven-plugin` to version `1.10.0`, and replace the npm install executions with the following:

```
                  <executions>
                    <execution>
                        <id>install node and npm</id>
                        <goals>
                            <goal>install-node-and-npm</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>install frontend dependencies</id>
                        <goals>
                            <goal>npx</goal>
                        </goals>
                        <configuration>
                            <arguments>pnpm install</arguments>
                        </configuration>
                    </execution>
                </executions>
```

Hope it helps someone!

**Comment by leonard84** [comment]
@noblica but how do you get `pnpm` installed? Afaik `npx` doesn't install a dependency and just looks in the `node_modules` folder. And a global install is not feasible for us.

**Comment by jjlharrison** [comment]
This solution still doesn't allow for pnpm to be installed separately from other dependencies, does it?

**Comment by noblica** [comment]
@jjlharrison I'm not sure what you mean? `npx` will download pnpm and run it locally. It will not add it to your `package.json`, or install it globally somewhere, if that's what you mean.

**Comment by RiZKiT** [comment]
This way `pnpm` is executed just once and not installed in the `node` folder and therefore can't be reused in the project for other npm tasks.

Btw. I had the issue that I used a run task in the arguments `run taskname`, so i had to move `pnpm install` into that task, because running two tasks in the arguments via `&&` seems to be impossible.

**Comment by noblica** [comment]
@RiZKiT If you need to use it elsewhere, you should probably install it on the machine. `npx` should pick up a global `pnpm` install, and use it. Otherwise, it will behave like you said.
This is just a workaround for people that work in teams, where some developers just want to run the maven task, without worrying about the `pnpm` dependency.

**Comment by bmhm** [comment]
+1 from me for explicit pnpm support. @eirslett  do you accept PRs?

**Comment by bmarwell** [comment]
@eirslett PTAL at the PR.
