### ISSUE TITLE
why need exactly maven 3.1.0

### ISSUE THREAD

**Issue by mcheung63** [eirslett/frontend-maven-plugin#635]
i have this bug, why forcing people to use maven exact 3.1.0?

Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.3:install-node-and-npm (javascript-test_npm-install) on project kettle-sdk-step-plugin: The plugin com.github.eirslett:frontend-maven-plugin:1.3 requires Maven version 3.1.0 -> [Help 1]

**Comment by eirslett** [comment]
It's a bad error message, and I think the error message comes from Maven itself, not from this plugin. (At least I don't think there's an easy way to fix it)
What it really means is just the minimum version; you need 3.1.0 or higher.
