### ISSUE TITLE
Issue to download GitHub release as remote artifactory

### ISSUE THREAD

**Issue by MaxCCC** [eirslett/frontend-maven-plugin#646]
**Do you want to request a _feature_ or report a _bug_?**
issue

**What is the current behavior?**
Not able to download a yarn release [here](https://github.com/yarnpkg/yarn/releases).
I receive a` 404 forbidden (?) `when I go to www.my-artifactory.xx/artifactory/yarnpkg/v0.23.4/yarn-v0.23.4.tar.gz

**If the current behavior is a bug, please provide the steps to reproduce.**
Created remote repository in Artifactory pointing to this URL:
https://github.com/yarnpkg/yarn/releases/download/

**What is the expected behavior?**
Download the version which we specify in our pom.xml (it looks like the example)

We can not use the api of github because defining the version resolves in version/version.tar.gz 

Plugin version 1.4

**Comment by stieler-it** [comment]
Hi @MaxCCC - did you find a solution to this problem?

**Comment by MaxCCC** [comment]
@stieler-it  unfortunately not. We just download the releases manually now at the moment and save them in a local registry in our Artifactory. But maybe this mirror could be useful too: https://npm.taobao.org/mirrors/yarn/ I should reinvestigate it soon.
