### ISSUE TITLE
Cannot use npm newer than 1.4.12

### ISSUE THREAD

**Issue by martin-g** [eirslett/frontend-maven-plugin#65]
It seems there is some problem with installing npm 1.4.13 and newer.
I use pretty much the same pom.xml as the linked sample project in the README and 
using `<npmVersion>1.4.12</npmVersion>` works but `<npmVersion>1.4.13</npmVersion>`. According to `npm info npm` and http://registry.npmjs.org/npm/ the latest version is 1.4.16.

Is it something related to the fact that npm is distributed with node.js since a while ?
If so then please either update the README and/or do not require `npmVersion` for newer node.js.

Thanks for this nice plugin!

**Comment by prashathsenthil** [comment]
Can some please post the solution steps for this issue? I too face the same issue i.e. having older npm version in POM.xml (<nodeVersion>v0.10.18</nodeVersion>;<npmVersion>1.3.8</npmVersion>) if i try to update the version of node and npm in POM.xml and run "maven install" then i could see issues in the log stating that it cannot download the latest npm version and the server throws 404..... the installation is happening behind a proxy, not sure if that's an issue because the node version 0.12.0 is getting installed properly but npm is not getting installed or downloaded. Kind of stuck because of this...

**Comment by bkonkle** [comment]
What version of the frontend-maven-plugin are you using? I'm installing Node 2.9.0 with this and having no trouble now.

**Comment by prashathsenthil** [comment]
@bkonkle i'm using 0.0.15 version of the frontend-maven-plugin and also i hope you are using NPM 2.9.0... Do you think upgrading the version to 0.0.23 or to the latest version of this plugin would resolve the issue.. i.e. after updating the plugin to latest version and then as a next step updating the npm version...

**Comment by bkonkle** [comment]
Ha - yes, npm 2.9.0. Updating to 0.0.23 would almost certainly resolve your issue. 0.0.15 is pretty old, and definitely prior to the fix discussed here.

**Comment by prashathsenthil** [comment]
@bkonkle i have updated the plugin version to 0.0.23 and node version to 0.12.2 and npm version to 2.9.0. It is working as expected when i run mvn install in local. But if it is run in jenkins DEV box there are errors related to npm-cli.js... i tried even wiping out the workspace completely but no luck still the npm-cli error is thrown in the logs,

[ERROR] npm ERR! argv "....Application/client/node/node" "....Application/client/node/npm/bin/npm-cli.js" "install" "--color=false" "--proxy=http://http.proxy.xxxxx.com:8000"
[ERROR] npm ERR! node v0.12.2
[ERROR] npm ERR! npm  v2.9.0
[ERROR] 
[ERROR] npm ERR! Uncaught, unspecified "error" event.
[ERROR] npm ERR! 
[ERROR] npm ERR! If you need help, you may report this error at:
[ERROR] npm ERR!     <https://github.com/npm/npm/issues>
[ERROR] npm ERR! Linux 2.6.32-431.el6.x86_64

**Comment by bkonkle** [comment]
It's possible that you're getting hit with the same spaces-in-path issue as I am. Jenkins uses workspace paths that can easily have spaces in them, and the default argument parsing doesn't take that into account well. Take a look at my [pull request](https://github.com/eirslett/frontend-maven-plugin/pull/209) - you may be able to fork the project like I did and use a custom version of it to fix the spaces until Eirik has a chance to look at it.
