### ISSUE TITLE
npm arguments does not support npm install [<@scope>/]<name>

### ISSUE THREAD

**Issue by rochan** [eirslett/frontend-maven-plugin#653]
I am using 1.6

**What is the current behavior?**
In the project POM
`<execution>
                                <id>npm install</id>
                                <goals>
                                    <goal>npm</goal>
                                </goals>
                                <phase>generate-resources</phase>
                                <configuration>
                                    <arguments>install gm</arguments>
                                    <installDirectory>${project.basedir}</installDirectory>
                                </configuration>
                            </execution>`

**If the current behavior is a bug, please provide the steps to reproduce.**
Run maven install
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:npm (npm install) on project tests: Failed to run task: 'npm install gm'

**What is the expected behavior?**
I am expect that it would behave the same as running npm install gm in the terminal, which the package would be downloaded
**Please mention your frontend-maven-plugin and operating system version.**
This occurs on OSX and Redhat7

**Comment by mriehema** [comment]
Did you install node and npm before running this execution? So the log and your pom would be helpful.

**Comment by eirslett** [comment]
Try putting gm in package.json and just run a plain npm install?

**Comment by rochan** [comment]
The problem that I am having is that one of the item's dependency in the package.json is broken. I am trying to go around that problem. 
https://github.com/EyalAr/lwip/issues/305

I tried to put gm in the package.json and I would still fail at the same point as the link above.
The only solution I found is to do a yarn or npm install on gm in the commandline before I run the pom.xml.
Because of this very reason, I tried to execute the same with the plugin and I get the error in the original post above.

> <plugin>
                        <groupId>com.github.eirslett</groupId>
                        <artifactId>frontend-maven-plugin</artifactId>
                        <version>1.6</version>
                        <executions>
                            <execution>
                                <id>install node and yarn</id>
                                <goals>
                                    <goal>install-node-and-yarn</goal>
                                </goals>
                                
                                <phase>generate-resources</phase>
                                <configuration>
                                    <nodeVersion>v8.5.0</nodeVersion>
                                    <yarnVersion>v1.1.0</yarnVersion>
                                    <installDirectory>${project.basedir}</installDirectory>
                                </configuration>
                            </execution>
                            <execution>
                                <id>yarn install</id>
                                <goals>
                                    <goal>yarn</goal>
                                </goals>
                                <phase>generate-resources</phase>
                                <configuration>
                                    <arguments>install</arguments>
                                    <yarnInheritsProxyConfigFromMaven>false</yarnInheritsProxyConfigFromMaven>
                                    <installDirectory>${project.basedir}</installDirectory>
                                </configuration>
                            </execution>

                        </executions>
                    </plugin>
