### ISSUE TITLE
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:npm (npm run build) on project portal-webui: Failed to run task: 'npm run build' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]

### ISSUE THREAD

**Issue by shafaqkazmi** [eirslett/frontend-maven-plugin#656]
**Do you want to request a _feature_ or report a _bug_?**
BUG
**What is the current behavior?**

> [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:npm (npm run build) on project portal-webui: Failed to run task: 'npm run build' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**If the current behavior is a bug, please provide the steps to reproduce.**
Updated frontend-maven-plugin 1.4 to 1.6

**What is the expected behavior?**

**Please mention your frontend-maven-plugin and operating system version.**
Please find pom.xml on https://gist.github.com/shafaqkazmi/58dd143a24d504fcb08c35dde95abc25

**Comment by bdurrer** [comment]
I get that one too, but with an `yarn run build` script. I did not upgrade yarn, maven, the plugin nor change the build, so I am pretty clueless how that can suddenly happen

**Comment by amolnr1987** [comment]
I am running my application on 
windows 8.1 pro
maven version :- 3.5.2
frontend-maven-plugin:1.6
nodeVersion:- v8.9.1
npmVersion:- 5.5.1

facing below issue : 
 Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:install-node-and-npm (install node and npm) on project mediapp-ui: Execution install node and npm of goal com.github.eirslett:frontend-maven-plugin:1.6:install-node-and-npm failed: A required class was missing while executing com.github.eirslett:frontend-maven-plugin:1.6:install-node-and-npm: org/codehaus/jackson/map/ObjectMapper
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>com.github.eirslett:frontend-maven-plugin:1.6
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/C:/Users/Amol/.m2/repository/com/github/eirslett/frontend-maven-plugin/1.6/frontend-maven-plugin-1.6.jar
[ERROR] urls[1] = file:/C:/Users/Amol/.m2/repository/com/github/eirslett/frontend-plugin-core/1.6/frontend-plugin-core-1.6.jar
[ERROR] urls[2] = file:/C:/Users/Amol/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar
[ERROR] urls[3] = file:/C:/Users/Amol/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar
[ERROR] urls[4] = file:/C:/Users/Amol/.m2/repository/org/apache/commons/commons-compress/1.5/commons-compress-1.5.jar
[ERROR] urls[5] = file:/C:/Users/Amol/.m2/repository/org/tukaani/xz/1.2/xz-1.2.jar
[ERROR] urls[6] = file:/C:/Users/Amol/.m2/repository/commons-io/commons-io/1.3.2/commons-io-1.3.2.jar
[ERROR] urls[7] = file:/C:/Users/Amol/.m2/repository/org/apache/commons/commons-exec/1.3/commons-exec-1.3.jar
[ERROR] urls[8] = file:/C:/Users/Amol/.m2/repository/org/apache/httpcomponents/httpclient/4.5.1/httpclient-4.5.1.jar
[ERROR] urls[9] = file:/C:/Users/Amol/.m2/repository/org/apache/httpcomponents/httpcore/4.4.3/httpcore-4.4.3.jar
[ERROR] urls[10] = file:/C:/Users/Amol/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
[ERROR] urls[11] = file:/C:/Users/Amol/.m2/repository/commons-codec/commons-codec/1.9/commons-codec-1.9.jar
[ERROR] urls[12] = file:/C:/Users/Amol/.m2/repository/org/codehaus/plexus/plexus-utils/3.0.22/plexus-utils-3.0.22.jar
[ERROR] urls[13] = file:/C:/Users/Amol/.m2/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
[ERROR] urls[14] = file:/C:/Users/Amol/.m2/repository/javax/annotation/jsr250-api/1.0/jsr250-api-1.0.jar
[ERROR] urls[15] = file:/C:/Users/Amol/.m2/repository/com/google/guava/guava/10.0.1/guava-10.0.1.jar
[ERROR] urls[16] = file:/C:/Users/Amol/.m2/repository/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar
[ERROR] urls[17] = file:/C:/Users/Amol/.m2/repository/org/sonatype/sisu/sisu-guice/3.1.0/sisu-guice-3.1.0-no_aop.jar
[ERROR] urls[18] = file:/C:/Users/Amol/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar
[ERROR] urls[19] = file:/C:/Users/Amol/.m2/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.0.0.M2a/org.eclipse.sisu.inject-0.0.0.M2a.jar
[ERROR] urls[20] = file:/C:/Users/Amol/.m2/repository/asm/asm/3.3.1/asm-3.3.1.jar
[ERROR] urls[21] = file:/C:/Users/Amol/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[22] = file:/C:/Users/Amol/.m2/repository/org/apache/maven/plugin-tools/maven-plugin-annotations/3.2/maven-plugin-annotations-3.2.jar
[ERROR] urls[23] = file:/C:/Users/Amol/.m2/repository/org/sonatype/plexus/plexus-build-api/0.0.7/plexus-build-api-0.0.7.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]

please let me know the solution

**Comment by rameshanm** [comment]
I'm facing the same issue.
windows 7
maven version :- 3.5.2
frontend-maven-plugin:1.4
nodeVersion:- v8.9.3
npmVersion:- 5.5.1

[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.4:yarn (webpack build prod) on project po-request-tracker: Failed to run task: 'yarn run webpack:prod' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]

**Comment by avinashbasetty** [comment]
any resolution on this ?? i am facing same error

[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:bower (bower install) on project tez-ui: Failed to run task: 'bower install' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :tez-ui

**Comment by ha-a-laoma** [comment]
maybe you can try  compile the front project alone.compile the whole project again when npm run build success

**Comment by AdrianLeeElder** [comment]
I'm using:
```
<configuration>
    <nodeVersion>v12.12.0</nodeVersion>
    <npmVersion>6.14.4</npmVersion>
</configuration>
```
and was able to fix the issue by deleting the `node_modules` folder.

**Comment by spkapil123** [comment]
When running the react-scripts build on the CI, the build script treats warnings as errors because by default process.env.CI = true.

In your package.json, update build as below to override process.env.CI value to false

"scripts": {
    "start": "react-scripts start",
    "build": "CI=false && react-scripts build",  // Add CI=False here
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
