### ISSUE TITLE
yarn install not working with nexus

### ISSUE THREAD

**Issue by ssavajols** [eirslett/frontend-maven-plugin#659]
**Do you want to request a _feature_ or report a _bug_?**
bug

**What is the current behavior?**
Got a 407 with nexus. No proxy is setted but and not necessary. If I install with yarn and outside of maven, it's working correctly. But if I install with maven, it does'nt work.

**If the current behavior is a bug, please provide the steps to reproduce.**
Install from nexus repository as npm registry configured in .npmrc

**What is the expected behavior?**
Expect a working installation.

**Please mention your frontend-maven-plugin and operating system version.**
frontend maven plugin 1.6
yarn 0.23.4 => same with 1.12
node 5.4.1 => same with 6.11.4
windows x64

**Comment by eirslett** [comment]
Does this help?

```
<configuration>
    <npmInheritsProxyConfigFromMaven>false</npmInheritsProxyConfigFromMaven>
</configuration>
```

**Comment by ssavajols** [comment]
No, it doesn't help :(

**Comment by ssavajols** [comment]
We have a proxy setting in edge, but no proxy in environment vars
no HTTP_PROXY
no HTTPS_PROXY
no proxy in maven setting.xml
-X does not help either.

**Comment by eirslett** [comment]
Hm, looks like there's a separate `yarnInheritsProxyConfigFromMaven` option you can set to false?

**Comment by ssavajols** [comment]
We already tried it. And nothing better happened.

This option remove --proxy=[proxy] --https-proxy=[proxy] from the command.

**Comment by ssavajols** [comment]
Any progress on this issue ? I don't understand why yarn is working correctly with the command line terminal and not with maven. No proxy are setted excepted the one in microsoft edge.

**Comment by ssavajols** [comment]
I have news from this issue. The problem is from my yarninstallation.

Yarn get proxy from a configuration file that I can't find. 

npm config list 
```
$ npm config list
; cli configs
user-agent = "npm/3.3.12 node/v5.4.1 win32 x64"

; userconfig C:\Users\X135957\.npmrc
phantomjs_cdnurl = "http://spice.outil.si.socgen/nexus/service/local/repositories/thirdparty-products/content/phantomjs/
registry = "http://spice.outil.si.socgen/nexus/content/groups/central-npm-all/"
sass_binary_site = "https://spice.outil.si.socgen/nexus/content/sites/sass-binaries"

; node bin location = c:\Program Files\nodejs\node.exe
; cwd = d:\x135957\git\sample-app-yarn\modules\front\src\main\webapp\resources\sample_app_yarn
; HOME = C:\Users\X135957
; "npm config ls -l" to show all defaults.
```

yarn config list 
```
yarn config v0.23.4
info yarn config
{ 'version-tag-prefix': 'v',
  'version-git-tag': true,
  'version-git-sign': false,
  'version-git-message': 'v%s',
  'init-version': '1.0.0',
  'init-license': 'MIT',
  'save-prefix': '^',
  'ignore-scripts': false,
  'ignore-optional': false,
  registry: 'https://registry.yarnpkg.com',
  'strict-ssl': true,
  'user-agent': 'yarn/0.23.4 npm/? node/v5.4.1 win32 x64',
  lastUpdateCheck: 1508161167419 }
info npm config
{ proxy: 'http://proxy-sgt.si.socgen:8080/',
  'https-proxy': 'http://proxy-sgt.si.socgen:8080',
  sass_binary_site: 'https://spice.outil.si.socgen/nexus/content/sites/sass-binaries',
  phantomjs_cdnurl: 'http://spice.outil.si.socgen/nexus/service/local/repositories/thirdparty-products/content/phantomjs/phanto
  registry: 'http://spice.outil.si.socgen/nexus/content/groups/central-npm-all/' }
Done in 0.19s.
```

So this is an issue from yarn et and frontend maven plugin. I close this issue.

Thks guys.
