### ISSUE TITLE
Is there a way to make the plugin work with the newest webpack version ?

### ISSUE THREAD

**Issue by andrea-ligios** [eirslett/frontend-maven-plugin#685]
Hi, 
as thousands of others on the web, I'm stuck with the tutorial at https://spring.io/guides/tutorials/react-and-spring-data-rest/  

The article has no date but I've been able to date it with Wayback to November 2015, so it's not a surprise it doesn't work as-is anymore.

I've made the changes needed to adapt it to the latest versions, but while the node and npm parts are working fine, no matter what I try the wepack part is not working.

I'm not an expert on all these frontend tools, and I'm ready to throw in the towel and use them natively; 
I just posted this is a final attempt to see if and how the frontend-maven-plugin can still be able to handle them (I'd definitely like to use this plugin over that jungle of JS tools).

If you are interested, this is the starting webpack file used: 
https://github.com/spring-guides/tut-react-and-spring-data-rest/blob/master/basic/webpack.config.js

Cheers, and thanks a lot

**Comment by eirslett** [comment]
What I would recommend is to use the npm goal of this plugin, instead of the webpack goal, and define a script "webpack" in package.json, and run the npm goal with `<arguments>run webpack</arguments>`? What is the error output you get from Maven?

**Comment by andrea-ligios** [comment]
Thank you @eirslett for your answer.
Well. it works as-is, but it breaks with newer versions of node, npm, and webpack.
I've done several different attempts receiving several errors... there are too much moving parts here. 
So I've decided to go back to the old, as-is version and start upgrading one thing at a time from there (I just refuse to settle on a thing configured in 2015, which has several deprecated components now).
I'll come back here with the details if I'll find a way to make everything work with node 8.9.4 and npm 5.6.0. In the remote case you'd like to take the challenge too, please do the same :)

**Comment by lewie** [comment]
@andrea-ligios, it took me several hours. But I got it solid work with "webpack": "^3.11.0". 

dependencies in package.json
```
  "dependencies": {
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "sockjs-client": "^1.1.4",
    "rest": "^1.3.2",
    "stompjs": "^2.3.3",
    "uglifyjs-webpack-plugin": "^1.2.0",
    "when": "^3.7.8",
    "webpack": "^3.11.0"
  }
...
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-polyfill": "^6.26.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1"
  }

```

In eclipse starting as Spring Boot App and run maven works too: `mvn clean package`.

See: https://github.com/lewie/tut-react-and-spring-data-rest/tree/webpack3

**Comment by andrea-ligios** [comment]
Good job @lewie ! :)

**Comment by ElijahGut** [comment]
Hi @eirslett, I was wondering what should be in the "webpack" script? Thanks.

**Comment by eirslett** [comment]
Today, you could use the `npx` runner instead of the `npm` runner. Then, with npx, you would simply run `webpack` with no additional arguments (unless you need more arguments, for whatever reason).
