### ISSUE TITLE
point to yarn dir

### ISSUE THREAD

**Issue by tatsujb** [eirslett/frontend-maven-plugin#692]
Would it be possible to point to the yarn/npm dir and not their download be part of the process E.G. : 

running  jenkins compile for servers that have yarn node and npm and we just point frontend-maven-plugin to the dir/dirs where they can be found?

**Comment by eirslett** [comment]
For this use case, use exec-maven-plugin instead, which executes arbitrary commands. You could have a maven profile that chooses which plugin to use.
