### ISSUE TITLE
Maven parallel build (-T) will produce notes regarding threadsafety

### ISSUE THREAD

**Issue by mcahornsirup** [eirslett/frontend-maven-plugin#703]
**Do you want to request a _feature_ or report a _bug_?**
Feature

**What is the current behavior?**
Use multiple Threads and Maven 3.5.3 and the output will be:

```
[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that have goals not marked   *
[WARNING] * as @threadSafe to support parallel building.                  *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] *****************************************************************
[WARNING] The following plugins are not marked @threadSafe in my-project:
[WARNING] com.github.eirslett:frontend-maven-plugin:1.6
[WARNING] Enable debug to see more precisely which goals are not marked @threadSafe.
[WARNING] *****************************************************************
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Threadsafety if possible

**Please mention your frontend-maven-plugin and operating system version.**
Maven 3.5.3 macOS high Sierra 10.13.3

**Comment by t196** [comment]
We have the same issue, running Maven 3.5.2.

It would be nice if all Mojos could be extendend with `threadSafe = true`, for example
`@Mojo(name = "...", threadSafe = true)`

**Comment by dascheib** [comment]
Hi,

We see that warning too. But that's not all. On Windows 10 the multithreaded build of our project sometimes fails on this plugin while executing grunt tasks, because the "clean" task has not finished while other tasks are already startet.

Is there a possibility to exclude the plugin from this multihreaded build of maven or enforce the correct execution sequence of all grunt tasks?

Thank you in advance,
Daniel

**Comment by dcsobral** [comment]
I'm getting build failures as well, which seem to be related to parallel builds.

**Comment by famod** [comment]
So it seems the plugin is in deed **not thread safe**! Therefore I should **not** just be marked `threadSafe = true` _before_ the underlying issues are resolved.

**Comment by benhumphrey-okta** [comment]
@dascheib Did you ever get an answer to excluding the plugin ? Seems a shame that any single plugin prevents use of multithreading for the entire build.
> 
> Is there a possibility to exclude the plugin from this multihreaded build of maven or enforce the correct execution sequence of all grunt tasks?
>

**Comment by MarkusTiede** [comment]
We'd also like to see parallel execution being supported (mvn 3.5.4).

**Comment by famod** [comment]
A pretty dumb but also pretty safe solution would be to add `synchronized` to the `execute` methods of _all_ `Mojo` classes (and of course `threadSafe = true`).

WDYT @eirslett?

**Comment by bmhm** [comment]
Hi, I can take a look at removing the synchronized keyword if you wish. Some fields can probably be atomics, other methods may be chopped into smaller methods of you like.

**Comment by famod** [comment]
@eirslett Thanks for releasing this as 1.9.1. Is it intentional that there is no such entry in `CHANGELOG.md`?

@bmhm I cannot speak for @eirslett but PRs improving the very broad `synchronized` approach are certainly welcome.
Please be aware that most of the thread-safety issues are most likely _not_ caused by classic Java concurrency problems but are instead caused by the invoked tools like Grunt.
E.g. by @dascheib:

> On Windows 10 the multithreaded build of our project sometimes fails on this plugin while executing grunt tasks, because the "clean" task has not finished while other tasks are already startet.

**Comment by bmhm** [comment]
That's interesting. This means executions of a single plugin in the same phase are started in parallel? I certainly did not know this.

Another possibility would be to add those executions to a `static final ArrayDequeue` or similar. `clean` executions should run first before the others may be started in parallel, maybe even depending on the frontend goal.

**Comment by eirslett** [comment]
Oops, no I just forgot to add it to the changelog.

**Comment by eirslett** [comment]
Regarding race conditions; I think it's better just to advise people to run their frontend build as a single unit of work (like a webpack build, or a grunt build script) rather than doing multiple invocations of the maven plugin (one for clean, one for build etc.)

**Comment by bmhm** [comment]
@eirslett that is how I also use it.
In that case I suggest we leave it as it is.

**Comment by jazdw** [comment]
Thanks for adding this! I just came to ask about it.
