### ISSUE TITLE
"unable to find valid certification path to requested target" when use latest node version

### ISSUE THREAD

**Issue by zappee** [eirslett/frontend-maven-plugin#709]
**Do you want to request a _feature_ or report a _bug_?**
_BUG_

**What is the current behavior?**
When use the latest node version which is v9.10.1 then frontend-maven-plugin failed with SSL errors.

Error:
```
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:install-node-and-yarn (install node and yarn) on project mock-payment-ui: Could not download Node.js from
: https://nodejs.org/dist/v9.10.1/win-x64/node.exe: Could not download https://nodejs.org/dist/v9.10.1/win-x64/node.exe: sun.security.validator.ValidatorException: PKIX path building
 failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]

```

**If the current behavior is a bug, please provide the steps to reproduce.**
1.  Add frontend-maven-plugin to yout maven project
2. Use the following _execution_, where node version is v9.10.1 and yarn version is v1.5.1:
```
<execution>
    <id>install node and yarn</id>
    <goals>
        <goal>install-node-and-yarn</goal>
    </goals>
    <configuration>
        <nodeVersion>v9.10.1</nodeVersion>
        <yarnVersion>v1.5.1</yarnVersion>
    </configuration>
</execution>
```

**What is the expected behavior?**
Node is downloaded and installed.

**Please mention your frontend-maven-plugin and operating system version.**
Frontend-Maven-Plugin v1.6
OS: Windows 7, Ubuntu 17.10

**Comment by zappee** [comment]
That was my mistake. Proxy settings was missing from maven `settings.xml` config file.

**Comment by slugmandrew** [comment]
@zappee Please close this issue if it's not relevant any more
