### ISSUE TITLE
Artifact repository credentials are ignored when downloading via proxy in install-node-and-yarn/install-node-and-npm goals

### ISSUE THREAD

**Issue by kaeufl** [eirslett/frontend-maven-plugin#724]
**What is the current behavior?**
The `install-node-and-yarn` and `install-node-and-npm` goals ignore credentials provided in settings xml, if in addition a proxy is configured in settings.xml.

 Example configuration:
```xml
<!-- from maven settings.xml-->
<proxy>
    <id>http</id>
    <active>false</active>
    <protocol>http</protocol>
    <host>127.0.0.1</host>
    <port>3128</port>
    <nonProxyHosts></nonProxyHosts>
</proxy>
<!-- ... -->
<servers>
    <server>
        <id>central</id>
        <!-- ... -->
        <username>user</username>
        <password>password</password>
    </server>
</servers>
```
```xml
<!-- from pom.xml -->
<!-- ... -->
<executions>
    <execution>
        <id>install node and yarn</id>
        <goals>
            <goal>install-node-and-yarn</goal>
        </goals>
        <configuration>
            <serverId>central</serverId>
            <nodeVersion>v8.11.1</nodeVersion>
            <yarnVersion>v1.6.0</yarnVersion>
            <nodeDownloadRoot>http://my.custom.nexus/nodeDownloads/</nodeDownloadRoot>
            <yarnDownloadRoot>http://my.custom.nexus/yarnDownloads/</yarnDownloadRoot>
        </configuration>
    </execution>
</executions>
<!-- ... -->
```

**Steps to reproduce.**
Add above configuration snippets to maven settings.xml and project's pom.xml. Point node and/or yarn download root to a custom server that requires basic authentication. Configure a proxy (with or without credentials).

Tested using version 1.6 of the frontend-maven-plugin as well as the current master.

**Comment by Maxouwell** [comment]
Hello, 

Is it possible to merge this fix in #725 ?
We had the same problem for a proxy + nexus + nexus password configuration

Regards

**Comment by Nicothur** [comment]
+1

**Comment by eirslett** [comment]
Could you try with version 1.14.0?

**Comment by Maxouwell** [comment]
Test are ok, thanks for your help !
