### ISSUE TITLE
New Release, please

### ISSUE THREAD

**Issue by mko-x** [eirslett/frontend-maven-plugin#727]
**Do you want to request a _feature_ or report a _bug_?**

Feature: New release

**What is the current behavior?**

Pretty old release.

**If the current behavior is a bug, please provide the steps to reproduce.**

Use great frontend-maven plugin. Throws several errors that are already fixed or in pull requests.

**What is the expected behavior?**

Recent updates to the releases.

**Please mention your frontend-maven-plugin and operating system version.**

_frontend-maven-plugin_ version: 1.6.0
_os_ version: macOS 10.13.4

**Comment by Chido42** [comment]
It would be great to have a new release for example this issue which is already merge breaks regurarly our CI because process are still running.
https://github.com/eirslett/frontend-maven-plugin/issues/41

**Comment by easingthemes** [comment]
New Release, please. A lot of fixes are already merged.

**Comment by devdev-dev** [comment]
We would appreciate a new release of the frontend-maven-plugin to access the merged changes.

**Comment by rob-64** [comment]
+1

**Comment by eirslett** [comment]
I think 1.7 should be released now.

**Comment by eirslett** [comment]
Apparently it didn't work. fml

**Comment by eirslett** [comment]
Finally! 1.7.5 is out there.
