### ISSUE TITLE
ChangeLog would be great

### ISSUE THREAD

**Issue by torarnek** [eirslett/frontend-maven-plugin#74]
ChangeLog would be great! :)

**Comment by torarnek** [comment]
:+1:

**Comment by KostyaSha** [comment]
No changelog at all? :disappointed: 
Of course do it! Or create CHANGELOG.md in root and update it before release or after every PR merge.

**Comment by KostyaSha** [comment]
Plus using milestones and assigning issues/prs to them should help easily track changes for changelog

**Comment by eirslett** [comment]
Yes, a changelog would indeed be great! I guess time is the limiting factor here. For now, people will have to read the git commit log, hopefully in the future, we can have a changelog.

**Comment by lunchboxdc** [comment]
is there a changelog yet?

**Comment by eirslett** [comment]
No, there isn't.
