### ISSUE TITLE
Is there any flag to tell this plugin to install local node iff global is not available ?

### ISSUE THREAD

**Issue by rajjaiswalsaumya** [eirslett/frontend-maven-plugin#754]
**Feature**

**I dont know if there is any such behavior already available**

Windows

Is there any flag which says install node and yarn locally iff globally its not available or its not available of the given version ?

Also a flag which says whether to override global yarn or node or not.

**Comment by delanym** [comment]
This is the default behaviour. I tried setting yarn goal as <argument>global install</argument> and it failed to build. But this works:

            <execution>
              <id>yarn install</id>
              <goals>
                <goal>yarn</goal>
              </goals>
              <configuration>
                <arguments>install --global-folder ${user.home}/.m2/node_modules</arguments>
              </configuration>

**Comment by nikeee** [comment]
Is something like this possible? I'm currently facing a problem where this would help tremendously.

**Comment by eirslett** [comment]
No, it does not support using the global version of Node. This is by design. It would be unnecessarily complex to implement, compared to simply always using the local/downloaded version.

**Comment by delanym** [comment]
I hope you considered the use of https://maven.apache.org/guides/mini/guide-using-toolchains.html before deciding that.
