### ISSUE TITLE
Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:yarn (yarn install) 

### ISSUE THREAD

**Issue by rizwanbpatel** [eirslett/frontend-maven-plugin#757]
Maven build is getting failed for the the plugin execution 

**Error:**

```
[INFO] --- frontend-maven-plugin:1.6:yarn (yarn install) @ dhulai ---
[INFO] Running 'yarn install' in C:\codelab\a2z\dhulai
[ERROR] Access is denied.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.285 s
[INFO] Finished at: 2018-08-04T18:49:19+05:30
[INFO] Final Memory: 35M/396M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:yarn (yarn install) on project dhulai: Failed to run task: 'yarn install' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
```

**What is the expected behavior?**
This should work perfectly as ran without plugin with only yarn install command

**pom.xml ->**

```
<plugin>
                        <groupId>com.github.eirslett</groupId>
                        <artifactId>frontend-maven-plugin</artifactId>
                        <version>${frontend-maven-plugin.version}</version>
                        <executions>
                             <execution>
                                <id>yarn install</id>
                                <goals>
                                    <goal>yarn</goal>
                                </goals>
                                <configuration>
                                    <arguments>install</arguments>
                                </configuration>
                            </execution>
                            <execution>
                                <id>webpack build test</id>
                                <goals>
                                    <goal>yarn</goal>
                                </goals>
                                <phase>test</phase>
                                <configuration>
                                    <arguments>run webpack:test</arguments>
                                    <yarnInheritsProxyConfigFromMaven>false</yarnInheritsProxyConfigFromMaven>
                                </configuration>
                            </execution>
                            <execution>
                                <id>webpack build prod</id>
                                <goals>
                                    <goal>yarn</goal>
                                </goals>
                                <phase>generate-resources</phase>
                                <configuration>
                                    <arguments>run webpack:prod</arguments>
                                    <yarnInheritsProxyConfigFromMaven>false</yarnInheritsProxyConfigFromMaven>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>

```

Please mention your frontend-maven-plugin and operating system version.

**frontend-maven-plugin : version : 1.6**

java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

git version 2.11.0.windows.1
node: v10.4.0
npm: 6.1.0
yeoman: 2.0.2
yarn: 1.9.4
OS : Windows 10 64 bit

**Comment by tubbynl** [comment]
is this the same as #743 ?

**Comment by rizwanbpatel** [comment]
No I have verified this is different on the build lifecycle on windows without docker

**Comment by akuma8** [comment]
I have the same issue, please see here [https://stackoverflow.com/questions/52766229/frontend-maven-plugin-fails-when-building-docker-image](url) @rizwanbpatel did you find a solution?

**Comment by searhiy** [comment]
I have the same issue!

**Comment by akuma8** [comment]
@searhiy Install nodejs in your environment. I had the same issue when building a docker image and I had to install nodejs to solve this

**Comment by searhiy** [comment]
@akuma8 Updated nodejs from 8.11 to 8.12 and it resolved the issue. Thanks!

**Comment by tamerrab2003** [comment]
Upgrading node version to v10.15.3 and using npm version 6.4.1 fixed the issue.
I hope this helps

**Comment by amirensit** [comment]
@tamerrab2003 Thanks, that worked for me.

**Comment by Priyanka-Pruthi** [comment]
> Upgrading node version to v10.15.3 and using npm version 6.4.1 fixed the issue.
> I hope this helps

hi i have same version installed for node and npm ,but still facing the issue

**Comment by neowurkz** [comment]
I followed the instructions on this post:
https://stackoverflow.com/questions/61542102/ambari-2-7-5-installation-failure-on-centos-7

But still getting this error on the ambari-web build part of the process:
[INFO] Reactor Summary:
[INFO]
[INFO] Ambari Main ....................................... SUCCESS [11:41.142s]
[INFO] Apache Ambari Project POM ......................... SUCCESS [0.173s]
[INFO] Ambari Web ........................................ FAILURE [33.222s]
[INFO] Ambari Views ...................................... SKIPPED
[INFO] Ambari Admin View ................................. SKIPPED
[INFO] ambari-utility .................................... SKIPPED
[INFO] ambari-metrics .................................... SKIPPED
[INFO] Ambari Metrics Common ............................. SKIPPED
[INFO] Ambari Metrics Hadoop Sink ........................ SKIPPED
[INFO] Ambari Metrics Flume Sink ......................... SKIPPED
[INFO] Ambari Metrics Kafka Sink ......................... SKIPPED
[INFO] Ambari Metrics Storm Sink ......................... SKIPPED
[INFO] Ambari Metrics Storm Sink (Legacy) ................ SKIPPED
[INFO] Ambari Metrics Collector .......................... SKIPPED
[INFO] Ambari Metrics Monitor ............................ SKIPPED
[INFO] Ambari Metrics Grafana ............................ SKIPPED
[INFO] Ambari Metrics Host Aggregator .................... SKIPPED
[INFO] Ambari Metrics Assembly ........................... SKIPPED
[INFO] Ambari Service Advisor ............................ SKIPPED
[INFO] Ambari Server ..................................... SKIPPED
[INFO] Ambari Functional Tests ........................... SKIPPED
[INFO] Ambari Agent ...................................... SKIPPED
[INFO] ambari-logsearch .................................. SKIPPED
[INFO] Ambari Logsearch Appender ......................... SKIPPED
[INFO] Ambari Logsearch Config Api ....................... SKIPPED
[INFO] Ambari Logsearch Config JSON ...................... SKIPPED
[INFO] Ambari Logsearch Config Solr ...................... SKIPPED
[INFO] Ambari Logsearch Config Zookeeper ................. SKIPPED
[INFO] Ambari Logsearch Config Local ..................... SKIPPED
[INFO] Ambari Logsearch Log Feeder Plugin Api ............ SKIPPED
[INFO] Ambari Logsearch Log Feeder Container Registry .... SKIPPED
[INFO] Ambari Logsearch Log Feeder ....................... SKIPPED
[INFO] Ambari Logsearch Web .............................. SKIPPED
[INFO] Ambari Logsearch Server ........................... SKIPPED
[INFO] Ambari Logsearch Assembly ......................... SKIPPED
[INFO] Ambari Logsearch Integration Test ................. SKIPPED
[INFO] ambari-infra ...................................... SKIPPED
[INFO] Ambari Infra Solr Client .......................... SKIPPED
[INFO] Ambari Infra Solr Plugin .......................... SKIPPED
[INFO] Ambari Infra Manager .............................. SKIPPED
[INFO] Ambari Infra Assembly ............................. SKIPPED
[INFO] Ambari Infra Manager Integration Tests ............ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12:15.037s
[INFO] Finished at: Mon Jun 08 10:27:49 UTC 2020
[INFO] Final Memory: 31M/381M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.4:install-node-and-yarn (install node and yarn) on project ambari-web: The plugin com.github.eirslett:frontend-maven-plugin:1.4 requires Maven version 3.1.0 -> [Help 1]


My environment:

NPM version:
3.10.10

Node version:
v6.17.1

Java version:
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)

Maven version:
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/maven
Java version: 1.8.0_252, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.252.b09-2.el7_8.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-1062.12.1.el7.x86_64", arch: "amd64", family: "unix"

**Comment by pitometsyurii** [comment]
Still have this issue with nodejs v14.4.0

**Comment by Izel** [comment]
I still have the same issue with nodejs 10.19.0

**Comment by akhatri** [comment]
why is this issue closed. I still get the same issue pls fix it as I cannot build the AEM Archetype instance 

```
C:\WINDOWS\System32>npm -v
6.14.10
```

```
C:\WINDOWS\System32>node -v
v12.18.0
```

I've even modified pom.xml in the AEM instance as below

```
                <plugin>
                    <groupId>com.github.eirslett</groupId>
                    <artifactId>frontend-maven-plugin</artifactId>
                    <version>1.7.6</version>
                    <configuration>
                        <nodeVersion>v12.18.0</nodeVersion>
                        <npmVersion>6.14.10</npmVersion>
                    </configuration>
                    <executions>
                        <execution>
                            <id>install node and npm</id>
                            <goals>
                                <goal>install-node-and-npm</goal>
                            </goals>
                        </execution>
                        <execution>
                            <id>npm install</id>
                            <goals>
                                <goal>npm</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>

```

**Comment by jon424** [comment]
@akhatri - same issue with the same config. Has anyone made any progress on this?

**Comment by Christina96** [comment]
I just add on pom.xml the same version of node and npm that I have on my laptop

**Comment by adamabdullah** [comment]
still same issue. 

node version 16.14.2
yarn version 1.22.18
fronten maven plugin version 1.12.1


Caused by: com.github.eirslett.maven.plugins.frontend.lib.TaskRunnerException: 'yarn install' failed.
	at com.github.eirslett.maven.plugins.frontend.lib.YarnTaskExecutor.execute(YarnTaskExecutor.java:64)
	at com.github.eirslett.maven.plugins.frontend.mojo.YarnMojo.execute(YarnMojo.java:65)
	at com.github.eirslett.maven.plugins.frontend.mojo.AbstractFrontendMojo.execute(AbstractFrontendMojo.java:94)
	... 32 more

**Comment by TanishqPorwar** [comment]
@adamabdullah were you able to solve it? I'm getting the same issue

node version 16.4.2
npm version 8.7.0
fronten maven plugin version 1.12.1

**Comment by thjung83** [comment]
@adamabdullah 

Same version for node, npm, and frontend maven plugin for me.

I saw the build log

[INFO] --- frontend-maven-plugin:1.12.1:yarn (yarn install) @ ui-ngx ---
[INFO] Running 'yarn install' in /home/asithjung/thingsboard/ui-ngx
[INFO] yarn install v1.22.18
[INFO] [1/4] Resolving packages...
[INFO] [2/4] Fetching packages...
[INFO] error Command failed.
[INFO] error Command failed.info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[INFO] Exit code: 128
[INFO] Command: git
[INFO] Arguments: ls-remote --tags --heads git://github.com/MichaelZinsmaier/CurvedLines.git
[INFO] Directory: /home/asithjung/thingsboard/ui-ngx
[INFO] Output:
[INFO] fatal: remote error:
[INFO]   The unauthenticated git protocol on port 9418 is no longer supported.
[INFO] Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.


The problem is solved by following the post below:
https://itsmycode.com/the-unauthenticated-git-protocol-on-port-9418-is-no-longer-supported/

git config --global url."https://github.com/".insteadOf git://github.com/

wish you success.

**Comment by hshansha** [comment]
> Upgrading node version to v10.15.3 and using npm version 6.4.1 fixed the issue. I hope this helps

Thank you very much.  This works for me

**Comment by ShreyaPrasad1209** [comment]
I'm still getting this issue even though my versions are -

node: v16.19.0
npm: 8.19.3
yarn: 1.22.19
mvn: 
```
Apache Maven 3.8.7 (b89d5959fcde851dcb1c8946a785a163f14e1e29)
Maven home: /opt/homebrew/Cellar/maven/3.8.7/libexec
Java version: 19.0.1, vendor: Homebrew, runtime: /opt/homebrew/Cellar/openjdk/19.0.1/libexec/openjdk.jdk/Contents/Home
Default locale: en_IN, platform encoding: UTF-8
OS name: "mac os x", version: "13.1", arch: "aarch64", family: "mac"
```

**Comment by cutholm** [comment]
I ran into this issue. I had Yarn 1.22.19 installed and the POM was calling for 1.3.2. I commented out the yarn install goal in my POM and ran mvn clean package and it identified that I needed a new version and installed it with no errors.

<execution>
            
            <configuration>
              <arguments>install</arguments>
            </configuration>
          </execution>

**Comment by bspena** [comment]
I can't find the yarn install goal, can you help me ?

**Comment by bspena** [comment]
> I ran into this issue. I had Yarn 1.22.19 installed and the POM was calling for 1.3.2. I commented out the yarn install goal in my POM and ran mvn clean package and it identified that I needed a new version and installed it with no errors.
> 
> install

I cant'find the yarn install goal, can you help me ?

**Comment by bspena** [comment]
> I ran into this issue. I had Yarn 1.22.19 installed and the POM was calling for 1.3.2. I commented out the yarn install goal in my POM and ran mvn clean package and it identified that I needed a new version and installed it with no errors.
> 
> install

I can't find where POM calling a versione of YARN, can you help me ?

**Comment by cutholm** [comment]
I wasn't sure which application I was referring to but this looks like the one. This is from the relevant pom.xml file. You can see where I commented out the yarn install goal. 

     <plugins>
      <plugin>
        <groupId>com.github.eirslett</groupId>
        <artifactId>frontend-maven-plugin</artifactId>
        <version>1.6</version>
        <configuration>
          <nodeVersion>v9.1.0</nodeVersion>
          <yarnVersion>v1.3.2</yarnVersion>
        </configuration>
        <executions>
          <execution>
            <id>install node and yarn</id>
            <goals>
              <goal>install-node-and-yarn</goal>
            </goals>
            <phase>generate-resources</phase>
          </execution>
          <execution>
            
            <configuration>
              <arguments>install</arguments>
            </configuration>
          </execution>

**Comment by bspena** [comment]
> I wasn't sure which application I was referring to but this looks like the one. This is from the relevant pom.xml file. You can see where I commented out the yarn install goal.
> 
> ```
>  <plugins>
>   <plugin>
>     <groupId>com.github.eirslett</groupId>
>     <artifactId>frontend-maven-plugin</artifactId>
>     <version>1.6</version>
>     <configuration>
>       <nodeVersion>v9.1.0</nodeVersion>
>       <yarnVersion>v1.3.2</yarnVersion>
>     </configuration>
>     <executions>
>       <execution>
>         <id>install node and yarn</id>
>         <goals>
>           <goal>install-node-and-yarn</goal>
>         </goals>
>         <phase>generate-resources</phase>
>       </execution>
>       <execution>
>         
>         <configuration>
>           <arguments>install</arguments>
>         </configuration>
>       </execution>
> ```

Thank you. I'm new to these technologies, so I wanted to ask you: what do those lines you commented on mean? Aren't they important?

**Comment by cutholm** [comment]
My solution helped in getting the correct version installed for me locally. I could probably uncomment that section now that I have the correct version. 

As far as your configuration, you must have the version specified somewhere as referenced by the ${yarnpkg.version} variable. That indicates that the version is specified somewhere else, either near the top of your POM file or in a parent POM if you have one. 

I would refer you to maven front end documentation to learn more. You can start here https://github.com/eirslett/frontend-maven-plugin

**Comment by bspena** [comment]
> My solution helped in getting the correct version installed for me locally. I could probably uncomment that section now that I have the correct version.
> 
> As far as your configuration, you must have the version specified somewhere as referenced by the ${yarnpkg.version} variable. That indicates that the version is specified somewhere else, either near the top of your POM file or in a parent POM if you have one.
> 
> I would refer you to maven front end documentation to learn more. You can start here https://github.com/eirslett/frontend-maven-plugin

I solved the problem through the following steps:
* setting the yarn version instead of ${yarnpkg.version}
 * setting  node version as 14.15.0  instead of ${nodejs.version} 
* I didn't commented  out the yarn install goal
The node version is 14.15.0 because reading the output from the terminal I found this comment "error triple-beam@1.4.1: The engine "node" is incompatible with this module. Expected version ">= 14.0.0". Got "12.22.1" [INFO] error Found incompatible module. ", while node versione installed by Hadoop was 12.12.x.
Thank you for the maven plugin guide.
