### ISSUE TITLE
On PhpStorm IDE when I wanted to install PHP_Codesniffer it shows this createprocess error 193 github http://prntscr.com/km5ran

### ISSUE THREAD

**Issue by samirkhan6468** [eirslett/frontend-maven-plugin#765]
**Do you want to request a _feature_ or report a _bug_?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Please mention your frontend-maven-plugin and operating system version.**

**Comment by eirslett** [comment]
I think this must be the wrong git repository for the issue...
