### ISSUE TITLE
feature request: add flag to skip install-node-and-npm and install-node-and-yarn

### ISSUE THREAD

**Issue by philipreimer** [eirslett/frontend-maven-plugin#768]
**What is the current behavior?**
Currently, there are flags like `-Dskip.npm` to skip a tool's execution. But there does not seem to be a flag to also skip the installation of the respective tool, e.g. to skip the goal `install-node-and-npm`.

Hence, even if npm execution is skipped, node and npm are still installed, although they are not needed.

**What is the expected behavior?**
There should be a flag like `-Dskip.node-and-npm.install` to skip the actual installation goal.

It should be possible to specify this flag both on the command line via `-Dskip.node-and-npm.install` and in the plugin's execution configuration like:
```
<execution>
    <id>install node and npm</id>
    <goals>
        <goal>install-node-and-npm</goal>
    </goals>
    <phase>...</phase>
    <configuration>
        <skip.node-and-npm.install>true</skip.node-and-npm.install>
        <nodeVersion>...</nodeVersion>
        <npmVersion>...</npmVersion>
    </configuration>
</execution>
```

**Please mention your frontend-maven-plugin and operating system version.**
frontend-maven-plugin version 1.6
Maven 3.5.2
OpenJDK 1.8.0_181
Antergos Linux

**Comment by philipreimer** [comment]
D'oh! I just noticed that the configuration option `<skip>` already exists.
```
<execution>
    <id>install node and npm</id>
    <goals>
        <goal>install-node-and-npm</goal>
    </goals>
    <phase>...</phase>
    <configuration>
        <skip>true</skip>
        <nodeVersion>...</nodeVersion>
        <npmVersion>...</npmVersion>
    </configuration>
</execution>
```

**Comment by jamesrwoodruff** [comment]
Good to know the skip configuration option is available. But per your original question, can the skip be invoked from the command line (e.g., -D.skip.install-node-and-npm)?

**Comment by jamesrwoodruff** [comment]
Actually, I found it in InstallNodeAndNpmMojo.java: -Dskip.installnodenpm
