### ISSUE TITLE
Node version check should verify if the node version installed is greater or not

### ISSUE THREAD

**Issue by rajjaiswalsaumya** [eirslett/frontend-maven-plugin#770]
The code to find the node version which is 

```
 private boolean nodeIsAlreadyInstalled() {
        try {
            NodeExecutorConfig executorConfig = new InstallNodeExecutorConfig(this.config);
            File nodeFile = executorConfig.getNodePath();
            if (nodeFile.exists()) {
                final String version =
                    new NodeExecutor(executorConfig, Arrays.asList("--version"), null).executeAndGetResult(logger);

                if (version.equals(this.nodeVersion)) {
                    this.logger.info("Node {} is already installed.", version);
                    return true;
                } else {
                    this.logger.info("Node {} was installed, but we need version {}", version,
                        this.nodeVersion);
                    return false;
                }
            } else {
                return false;
            }
        } catch (ProcessExecutionException e) {
            return false;
        }
    }

```

is comparing version using equals. It should check if installed version is greater than the one mentioned in pom

**Comment by eirslett** [comment]
I believe the behaviour is correct. It should install another version if and only if the version is not equal.

**Comment by rajjaiswalsaumya** [comment]
Not necessary, if the installed version is already greater than the one mentioned in pom, it should not try to install lower version.

**Comment by rajjaiswalsaumya** [comment]
If you think the version to install should be exactly the one mentioned in pom, then there should be a flag to install compatible version. E.g if pom says Node 8.0 and Node 9.0 is the latest version, then it should silently upgrade. This will prevent unnecessary hassle for some of the packages not being updated and causing build failure.

**Comment by eirslett** [comment]
By definition there are no "compatible" versions of node.js, all of them are unique. The reason why is that there can be bugs/regressions in recent releases.
For example, your build might work with node version 10.4.0, but an obscure bug was introduced in 10.4.1, which made your build fail. (This has actually happened to me before, so it's a real problem.) That's a use case where you want to make sure that your version is pinned to 10.4.0. If not, you will sacrifice your build stability.
