### ISSUE TITLE
permission denied, mkdir '/root/.npm/vue-router/3.0.1/package

### ISSUE THREAD

**Issue by Seanid** [eirslett/frontend-maven-plugin#778]
**My project can be built properly under WindowsOS，But error reporting under Linux**
[INFO] Running 'npm install --unsafe-perm=true --allow-root' in “”
[ERROR] npm ERR! Linux 4.9.0-39-custom 
[ERROR] npm ERR! node v6.10.2
[ERROR] npm ERR! npm  v3.10.10
[ERROR] npm ERR! path /root/.npm/vue-router/3.0.1/package
[ERROR] npm ERR! code EACCES
[ERROR] npm ERR! errno -13
[ERROR] npm ERR! syscall mkdir
[ERROR] 
[ERROR] npm ERR! Error: EACCES: permission denied, mkdir '/root/.npm/vue-router/3.0.1/package'
[ERROR] npm ERR!     at Error (native)
[ERROR] npm ERR!  { Error: EACCES: permission denied, mkdir '/root/.npm/vue-router/3.0.1/package'
[ERROR] npm ERR!     at Error (native)
[ERROR] npm ERR!   errno: -13,
[ERROR] npm ERR!   code: 'EACCES',
[ERROR] npm ERR!   syscall: 'mkdir',
[ERROR] npm ERR!   path: '/root/.npm/vue-router/3.0.1/package',
[ERROR] npm ERR!   parent: 'webpack-demo' }
[ERROR] npm ERR! 
[ERROR] npm ERR! Please try running this command again as root/Administrator.
[ERROR] 

It looks like root authority is required，Anybody have this problem

**Comment by eirslett** [comment]
Are you trying to install packages globally? (Which shouldn't be done with this plugin, install them locally instead)

**Comment by Seanid** [comment]
> Are you trying to install packages globally? (Which shouldn't be done with this plugin, install them locally instead)

not，I just want to compile with regular users。My configuration is as follows

 <executions>

                    <execution>
                        <id>install node and npm</id>
                        <goals>
                            <goal>install-node-and-npm</goal>
                        </goals>
                        <configuration>
                            
                            <nodeVersion>v6.10.2</nodeVersion>
                            <npmVersion>3.10.10</npmVersion>
                        </configuration>
                    </execution>





                    <execution>
                        <id>npm install</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>

                        <phase>generate-resources</phase>

                        
                        <configuration>
                            <arguments>install --unsafe-perm=true --allow-root</arguments>
                        </configuration>
                    </execution>

                    <execution>
                        <id>npm run build</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <configuration>
                            <arguments>run build</arguments>
                        </configuration>
                    </execution>

                </executions>

**Comment by eirslett** [comment]
Try removing `--unsafe-perm=true --allow-root`?

**Comment by Seanid** [comment]
> Try removing `--unsafe-perm=true --allow-root`? (Why did you put it there in the first place?)
> And what does package.json look like?

added this configuration because of the error.I deleted it and I got the same result.
the package.json is as follower



{
  "name": "webpack-demo",
  "description": "A Vue.js project",
  "version": "1.1.0",
  "author": "chenshaoling",
  "license": "MIT",
  "private": true,
  "scripts": {
    "dev": "cross-env NODE_ENV=development && webpack-dev-server --hot --port 9980",
    "build": "cross-env NODE_ENV=production && webpack --progress --hide-modules"
  },
  "dependencies": {
    "axios": "^0.18.0",
    "echarts": "^4.1.0",
    "iview": "^2.11.0",
    "lodash": "^4.17.11",
    "sortablejs": "^1.7.0",
    "vue": "^2.5.11",
    "vue-axios": "^2.1.3",
    "vue-router": "^3.0.1"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ],
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-preset-env": "^1.6.0",
    "babel-preset-stage-3": "^6.24.1",
    "copy-webpack-plugin": "^4.5.1",
    "cross-env": "^5.0.5",
    "css-loader": "^0.28.7",
    "extract-text-webpack-plugin": "^3.0.2",
    "file-loader": "^1.1.4",
    "html-loader": "^0.5.5",
    "html-webpack-plugin": "^3.2.0",
    "iview-loader": "^1.1.0",
    "less": "^3.0.1",
    "less-loader": "^4.1.0",
    "style-loader": "^0.21.0",
    "url-loader": "^1.0.1",
    "vue-html-loader": "^1.2.4",
    "vue-loader": "^13.0.5",
    "vue-template-compiler": "^2.4.4",
    "webpack": "^3.6.0",
    "webpack-dev-server": "^2.9.1"
  }
}

**Comment by Seanid** [comment]
hi，I am back. Finally, I found the solution through my own way.

This problem is caused by the NPM's cache mechanism.It is well known that NPM first downloads packages under ~/.npm, and then moves to ${local}/node_modules.Our production program used a user named www-data to execute maven script, while the ~/.npm was /root/.npm. The program was too old to know why.So I have to find another way to solve this problem.

`env JAVA_HOME=${JAVAHOME} MAVEN_OPTS=${MAVEN_OPTS}  HOME={THE_PATH_TO_CACHE_NPM} mvn dependency:tree -DappendOutput=true -DoutputFile=${dependencyTreeFile} -Dmaven.test.skip=true -Dmaven.source.skip=true ${MAVEN_ARGS} -am clean package -U`

I used this method to temporarily change the cache directory to the directory I wanted, and then the problem was solved

Thank you very much for your help
