### ISSUE TITLE
Can I use it to  perform  "npm run start" operation？How to configure?

### ISSUE THREAD

**Issue by GreatGarlic** [eirslett/frontend-maven-plugin#780]
I want  to use frontend-maven-plugin start   UI  in the  frontend  directory，but never succeed.

**Comment by GreatGarlic** [comment]
How to configure " npm run start"?

**Comment by milovtim** [comment]
Maybe you better run npm directly. I suggest this plugin is aimed to **build** application artifacts, not run local dev server.

**Comment by GreatGarlic** [comment]
@milovtim ok,thanks!
