### ISSUE TITLE
Question: how to using --base-href (maven and angular)

### ISSUE THREAD

**Issue by youssefabc** [eirslett/frontend-maven-plugin#790]
Hello everybody,
How i can add options --base-href when using npm run build in pom.xml ?

Best regards

**Comment by Willey1986** [comment]
You could add a new script to the `scripts` section in the `package.json` and then use `npm run build-maven` in your pom.xml

```
"scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "build-maven": "ng build --base-href /your/base/href/" 
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
},
```

**Comment by youssefabc** [comment]
Thanks it's work ;)
