### ISSUE TITLE
Could not extract archive: '/xxx/xyz/.m2/repository/com/github/eirslett/node/11.9.0/node-11.9.0-linux-x64.tar.gz': EOFException

### ISSUE THREAD

**Issue by Santoshbhad** [eirslett/frontend-maven-plugin#794]
Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:install-node-and-npm (default) on project : Could not extract the Node archive: Could not extract archive: '/xxx/xyz/.m2/repository/com/github/eirslett/node/11.9.0/node-11.9.0-linux-x64.tar.gz': EOFException 

Please help me understand and fix this issue.
Thanks

**Comment by Zardoz89** [comment]
See issue #738 . PR https://github.com/eirslett/frontend-maven-plugin/pull/749 should fix it

**Comment by seregamorph** [comment]
@santoshbhad @zardoz89 @eirslett I had the same issue locally and investigated it.
Please take a look https://github.com/eirslett/frontend-maven-plugin/pull/807 with suggested fix.

**Comment by seregamorph** [comment]
This issue can be closed (addressed in #807)
