### ISSUE TITLE
Support for yarn workspaces

### ISSUE THREAD

**Issue by jonkemp** [eirslett/frontend-maven-plugin#799]
https://yarnpkg.com/en/docs/workspaces

Workspaces will allow for multiple package.json files in a single repo and install all dependencies at the root, unless the package.json file specifies a different version, then it will install that package locally. 

Right now when I install webpack with workspaces and run the webpack command, it is looking for webpack in the local node_modules folder and can't find it. Looks like it doesn't respect the symlinks.

Have I missed a configuration which would allow this to work or is this something that could be supported in the future?

**Comment by eirslett** [comment]
Possibly a problem with the webpack mojo... try running the npm mojo instead, and add an npm script that in turns run webpack. That might work.

**Comment by jonkemp** [comment]
Looks like that worked. Thank you!
