### ISSUE TITLE
Question/Feature request: How to run cnpm ?

### ISSUE THREAD

**Issue by paulvi** [eirslett/frontend-maven-plugin#802]
** want to request a _feature_ or maybe it is possible with current version**

I got a web project that has these steps for build:

```
npm install -g cnpm --registry=https://registry.npm.taobao.org
cnpm install
npm run build
```

**What is the current behavior?**

`frontend-maven-plugin` defines `npm` goal, but how to run `cnpm` ? It is not defined/supported goal.

**If the current behavior is a bug, please provide the steps to reproduce.**

not bug.

**What is the expected behavior?**

Special support for `cnpm` or way to install it (better locally, i.e.not with -g) and run.

**Please mention your frontend-maven-plugin and operating system version.**

frontend-maven-plugin 1.6  (i am gong to try 1.7.5 as well)
OS Windows 10  
JDK 8 64 bit

**Comment by paulvi** [comment]
Likely related to #277 (https://stackoverflow.com/questions/37329708/can-frontend-maven-plugin-use-node-npm-already-installed)

But I would prefer NOT to run "the global version of Node", and fully support Eirik @eirslett answer
https://github.com/eirslett/frontend-maven-plugin/issues/277#issuecomment-139529530

**Comment by eirslett** [comment]
Is it possible to solve your use case by adding a `.npmrc` file to the project, which uses the China mirror, and then run `npm` like one would normally do?

What you could do is to add cnpm as a package.json script:

```
{
  "dependencies": { ... },
  "scripts": {
    "cnpm": "cnpm install"
  }
}
```

Then you could use (1) use the npm mojo to run `npm install cnpm`, and (2) the npm mojo to trigger `npm run-script cnpm`.

**Comment by paulvi** [comment]
Thank for hint about `.npmrc`

There are many config options, that can actually be shared with command line and maven usage
https://docs.npmjs.com/misc/config.html


from https://npm.taobao.org/ （https://cnpmjs.org/） `cnpm` is just alias for npm with specific registry:

    alias cnpm="npm --registry=https://registry.npm.taobao.org \
    --cache=$HOME/.npm/.cache/cnpm \
    --disturl=https://npm.taobao.org/dist \
    --userconfig=$HOME/.cnpmrc"

So it is still `npm` under hood.
