### ISSUE TITLE
ERROR in AppModule is not an NgModule

### ISSUE THREAD

**Issue by venkatapatti** [eirslett/frontend-maven-plugin#804]
The following error when trying to build with yarn.

[INFO] ERROR in AppModule is not an NgModule
[INFO] 
[INFO] ERROR in ./src/main.ts
[INFO] Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\Users\vepatti\IdeaProjects\wom-docflow\src\main\frontend\src'
[INFO]  @ ./src/main.ts 4:0-74
[INFO]  @ multi ./src/main.ts

yarn version: 1.6
node version: v8.9.1
pom
![image](https://user-images.githubusercontent.com/24681442/55600033-ff47a980-571f-11e9-9322-efbd8a0dc5be.png)

package.json

"dependencies": {
    "@angular/animations": "4.3.1",
    "@angular/common": "4.3.1",
    "@angular/compiler": "4.3.1",
    "@angular/compiler-cli": "4.3.1",
    "@angular/core": "4.3.1",
    "@angular/forms": "4.3.1",
    "@angular/http": "4.3.1",
    "@angular/platform-browser": "4.3.1",
    "@angular/platform-browser-dynamic": "4.3.1",
    "@angular/platform-server": "4.3.1",
    "@angular/router": "4.3.1",
    "intl": "^1.2.5",
    "ng2-translate": "5.0.0",
    "node-sass": "4.10.0",
    "primeng": "4.2.2",
    "rxjs": "5.1.0",
    "typescript": "2.2.2",
    "underscore": "1.8.3",
    "zone.js": "0.8.5",
    "file-saver": "^1.3.3",
    "jspdf": "1.4.1",
    "html2canvas": "1.0.0-alpha.12"
  },

**Comment by eirslett** [comment]
This looks like a problem with Angular, not with this plugin. What happens if you run `yarn run build` on the command line directly, instead of via this plugin?

**Comment by venkatapatti** [comment]
@eirslett upgraded the typescript version to 2.4.1 it started working with the older version of typescript, it was throwing the same error even from command line. Thanks
