### ISSUE TITLE
I feel like a human again

### ISSUE THREAD

**Issue by YuriGor** [eirslett/frontend-maven-plugin#814]
When I started to create this issue, I found there was the same in the past #448 
That issue is closed, but I still can reproduce the situation described there:
Everything works. Looks like I can do everything. Arbitrary js scripts, rollup with a bunch of plugins, NODE_ENV... 
Next, I'll drop minify-maven-plugin and sass-maven-plugin in favor of rollup plugins, hope this will work too. 
I am not an alien in the Java world anymore!
So, let me say it again, thank you for your perfect work!

**Comment by eirslett** [comment]
You're welcome! :-)
