### ISSUE TITLE
Download url

### ISSUE THREAD

**Issue by crashnick16** [eirslett/frontend-maven-plugin#818]
I am using version 1.7.6 and trying to change the root url to a custom one that does not have the version in it. Is it possible to do that?

Currently it seems that only root url is supported and this will get the version appended to it. Is there any way to disable that and provide the full url ?

Basically, I would like to use the below url for yarn too: 

Https://registry.npmjs.org/yarn/-/

Similar url for npm works but not for yarn

**Comment by eirslett** [comment]
No, the only thing you can change is the base URL. The reason is that the full URL will be different depending on if you need the windows binary, linux or macos binary. If you upload them to your own place somewhere, you need to follow the same filename conventions as on nodejs.org.

**Comment by crashnick16** [comment]
I am pretty sure the same tar is used for both windows and Linux. This works in the same way as NPM

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by crashnick16** [comment]
Why not support Https://registry.npmjs.org/yarn/-/ Https://registry.npmjs.org/yarn/-/ ?

Surely this works with anything

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
