### ISSUE TITLE
Skip npm/yarn install if package.json has not changed

### ISSUE THREAD

**Issue by cowwoc** [eirslett/frontend-maven-plugin#823]
**Do you want to request a _feature_ or report a _bug_?**
feature

**What is the current behavior?**
npm/yarn install always runs

**What is the expected behavior?**
Add an option that enables the following behavior:

If the timestamp of `package.json` is older than the newest file in `node_modules` then skip npm/yarn install. Put another way, if `package.json` has not been edited since `node_modules` was last updated, then there is no point re-running it.

When debugging, we rarely want to update the dependencies across runs. Technically speaking a new version of a dependency may be released that matches a version range, and npm/yarn would download it. But when debugging we prefer to skip such checks, focusing on a fast build over newer dependencies.

**Please mention your frontend-maven-plugin and operating system version.**
Windows 10.0.17763.529, frontend-maven-plugin 1.6

**Comment by eirslett** [comment]
Use `npm ci` instead of `npm install`, which will no-op in cases where there are no changes.

**Comment by cowwoc** [comment]
@eirslett You misunderstood. I am aware of the fact that `npm ci` or `npm install` will no-op if there are no changes, but it is extremely slow (multiple seconds). I noticed that at work it is much faster to configure Gradle to skip the task altogether if the input has not changed. At home, I am using Maven but I have no way of mimicking Gradle's behavior.

**Comment by eirslett** [comment]
Actually, `npm install` will not no-op - even if there are no changes - it will try to check for patch updates. While `npm ci` will not. I'm 95 % sure that's the case. Are you sure you have tried using `npm ci` only?
