### ISSUE TITLE
NPM install fails when running with maven-frontend-plugin

### ISSUE THREAD

**Issue by tuxedo0801** [eirslett/frontend-maven-plugin#826]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behavior?**
"npm install" called by frontend-maven-plugin fails while "npm install" by hand works

**If the current behavior is a bug, please provide the steps to reproduce.**

I have following file:

package.json
```json
{
  "name": "approuter-demo",
  "version": "1.0.0",
  "description": "app router",
  "repository": {
    "type": "git",
    "url": "https://xxxxxxxxxxxxxxxx"
  },
  "engines": {
    "node": "10.15.3",
    "npm": "6.9.0"
  },
  "scripts": {
    "start": "node node_modules/@sap/approuter/approuter.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "license": "ISC",
  "dependencies": {
    "@sap/approuter": "^5.3.0",
    "@sap/node-jwt": "^1.4.13"
  }
}
```

section in pom.xml
```xml
<plugin>
                <groupId>com.github.eirslett</groupId>
                <artifactId>frontend-maven-plugin</artifactId>
                <version>1.7.6</version>
                <executions>
                    <execution>
                        <id>install node and npm</id>
                        <goals>
                            <goal>install-node-and-npm</goal>
                        </goals>
                        <phase>generate-resources</phase>
                    </execution>
                    
                    <execution>
                        <id>run npm install</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <configuration>
                            <arguments>install</arguments>
                        </configuration>
                    </execution>
                    
                </executions>                
                <configuration>
                    <nodeVersion>v10.15.2</nodeVersion>
                    <npmVersion>6.9.0</npmVersion>
                    <installDirectory>target</installDirectory>
                </configuration>
            </plugin>
```

.npmrc
```
@sap:registry=https://npm.sap.com/
```

**What is the expected behavior?**

NPM INSTALL should run fine.

But running ```mvn package``` creates following error:

```
[INFO] --- frontend-maven-plugin:1.7.6:install-node-and-npm (install node and npm) @ sibc-approuter-test ---
[INFO] Installing node version v10.15.2
[INFO] Unpacking /home/yyy/.m2/repository/com/github/eirslett/node/10.15.2/node-10.15.2-linux-x64.tar.gz into /home/yyy/dev/xxxxxxx/myproject/target/node/tmp
[INFO] Copying node binary from /home/yyy/dev/mycustomer/myproject/target/node/tmp/node-v10.15.2-linux-x64/bin/node to /home/yyy/dev/xxxxxxx/myproject/target/node/node
[INFO] Installed node locally.
[INFO] Installing npm version 6.9.0
[INFO] Unpacking /home/yyy/.m2/repository/com/github/eirslett/npm/6.9.0/npm-6.9.0.tar.gz into /home/yyy/dev/xxxxxxx/myproject/target/node/node_modules
[INFO] Installed npm locally.
[INFO] 
[INFO] --- frontend-maven-plugin:1.7.6:npm (run npm install) @ sibc-approuter-test ---
[INFO] Running 'npm install' in /home/yyy/dev/xxxxxxx/myproject
[INFO] 
[INFO] > @sap/node-jwt@1.4.13 install /home/yyy/dev/xxxxxxx/myproject/node_modules/@sap/node-jwt
[INFO] > node ./build.js
[INFO] 
[INFO] `linux-x64-v8-6.8` exists; testing
[INFO] Binary is fine; exiting
[ERROR] Aborted
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 134
[ERROR] npm ERR! @sap/node-jwt@1.4.13 install: `node ./build.js`
[ERROR] npm ERR! Exit status 134
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the @sap/node-jwt@1.4.13 install script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[ERROR] 
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     /home/yyy/.npm/_logs/2019-06-28T08_18_32_234Z-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

When I run "npm install" by hand from command line, it works fine:

```
$ npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!

> @sap/node-jwt@1.4.13 install /home/yyy/dev/xxxxxxx/myproject/node_modules/@sap/node-jwt
> node ./build.js

`linux-x64-v8-6.8` exists; testing
Binary is fine; exiting
added 15 packages from 26 contributors and audited 407 packages in 3.39s
found 0 vulnerabilities
```

Same when not using the system npm, but explicitly using the npm that has been installed by frontend-maven-plugin.
It just fails when frontend maven plugin is calling "npm install" :-(

**Please mention your frontend-maven-plugin and operating system version.**

frontend-maven-plugin: latest 1.7.6
os: debian testing, latest updates,
java: openjdk 11.0.3
maven: 3.6.0

**Comment by tuxedo0801** [comment]
Even switching to npm 6.9.2 let maven fail to run npm install :-(

**Comment by tuxedo0801** [comment]
the mentioned logfile contains:

```
5420 verbose stack Error: @sap/node-jwt@1.5.1 install: `node ./build.js`
5420 verbose stack Exit status 134
5420 verbose stack     at EventEmitter.<anonymous> (/home/yyy/dev/xxxxxxx/sibc_approuter/target/node/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
5420 verbose stack     at EventEmitter.emit (events.js:189:13)
5420 verbose stack     at ChildProcess.<anonymous> (/home/yyy/dev/xxxxxxx/sibc_approuter/target/node/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
5420 verbose stack     at ChildProcess.emit (events.js:189:13)
5420 verbose stack     at maybeClose (internal/child_process.js:970:16)
5420 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
5421 verbose pkgid @sap/node-jwt@1.5.1
```

**Comment by eirslett** [comment]
Looks like it fails at `node ./build.js` which is probably a postinstall step? Maybe the version of Node.js that is used, or the environment variables passed into build.js, are different?
You could change build.js to do `console.log(process.env)` at the top and see if there are any differences?

**Comment by ahbonsu** [comment]
hi,
any news on this? 
I did face the same problem - turned out removing the nodejs and the npm packages solved it for me. 
I used the packages from the debian buster repository.

**Comment by tuxedo0801** [comment]
sorry, nothing happend until now. but this is still an issue for me. I will test the suggestion made by @eirslett 

@ahbonsu 
Means you uninstalled npm and nodejs via "apt remove" from your debian installation?
Hmm, strange, because I was quite sure that I verified hat mvn is running the current binary (the one that was installed by the plugin and not the system one).
But I will check again.
Anyhow: It's not a permament solution to remove npm+nodejs from my debian installation.

br,
Alex

**Comment by ahbonsu** [comment]
@tuxedo0801 
Yes, I did remove the debian packages. 
I also managed to get every working using nodejs from the "official" repo - which you can add following the instructions here: https://github.com/nodesource/distributions

So I guess this problem is related to the debian nodejs package.

**Comment by tuxedo0801** [comment]
> So I guess this problem is related to the debian nodejs package.

I do see this different:

The problem is related to the plugin, as it somehow conflicts with existing installations. The plugin downloads it's own node instance, so it should use this and only this, without conflicting with other things.

At least, it is clearl reproducible. So we have a chance to get this fixed.

**Comment by tuxedo0801** [comment]
I forked and checked-out the plugin source and debugged the issue a bit.

When the maven output reaches:

```
[INFO] --- frontend-maven-plugin:1.8.1-SNAPSHOT:npm (npm install) @ myproject ---
[INFO] Running 'npm install' in /home/d463/dev/mycustomer/myproject
```

it calls the ProcessExecutor-Class with the execute() method

![image](https://user-images.githubusercontent.com/2862906/63009225-5a369d80-be84-11e9-8c74-30cc7c842f9f.png)

which executes the following "commandLine":

```
/home/d463/dev/mycustomer/myproject/target/node/node /home/d463/dev/mycustomer/myproject/target/node/node_modules/npm/bin/npm-cli.js install
```

It of course uses also an environment used:

```
{PATH=/home/d463/dev/mycustomer/myproject/target/node:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/snap/bin:, XAUTHORITY=/run/user/1000/gdm/Xauthority, XDG_DATA_DIRS=/usr/share/gnome:/usr/local/share:/usr/share:/var/lib/snapd/desktop, GDMSESSION=cinnamon, DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus, XDG_CURRENT_DESKTOP=X-Cinnamon, SSH_AGENT_PID=2725, COLORTERM=truecolor, SESSION_MANAGER=local/p1593-debian:@/tmp/.ICE-unix/2680,unix/p1593-debian:/tmp/.ICE-unix/2680, USERNAME=d463, LOGNAME=d463, PWD=/home/d463/dev/mycustomer/myproject, GJS_DEBUG_TOPICS=JS ERROR;JS LOG, SHELL=/bin/bash, OLDPWD=/home/d463/dev/mycustomer/myproject, GNOME_DESKTOP_SESSION_ID=this-is-deprecated, GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/bca195a4_8772_4e3c_a9db_05f82fbf361f, GTK_MODULES=gail:atk-bridge, LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:, XDG_SESSION_DESKTOP=cinnamon, SHLVL=1, JAVA_HOME=/usr/lib/jvm/default-java/, TERM=xterm-256color, GNOME_TERMINAL_SERVICE=:1.86, LANG=de_DE.UTF-8, XDG_SESSION_ID=3, XDG_SESSION_TYPE=x11, MAVEN_OPTS= , DISPLAY=:0, CINNAMON_VERSION=3.8.8, MAVEN_CMD_LINE_ARGS= clean install, XDG_SESSION_CLASS=user, _=/usr/bin/mvnDebug, MAVEN_DEBUG_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=8000, GDM_LANG=de_DE.UTF-8, GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1, MAVEN_PROJECTBASEDIR=/home/d463/dev, DESKTOP_SESSION=cinnamon, USER=d463, VTE_VERSION=5402, QT_ACCESSIBILITY=1, WINDOWPATH=2, GJS_DEBUG_OUTPUT=stderr, SSH_AUTH_SOCK=/run/user/1000/keyring/ssh, XDG_SEAT=seat0, GTK_OVERLAY_SCROLLING=0, XDG_VTNR=2, XDG_RUNTIME_DIR=/run/user/1000, HOME=/home/d463}
```

The only difference I see, is, that there is "/home/d463/dev/mycustomer/myproject/target/node" in the path, compared to run it manually, where this is NOT part of PATh env-var.

So I added a break-point and removed "/home/d463/dev/mycustomer/myproject/target/node" from the environment-map and .... it works. 

So questions are:

1.  Why does this additional path in the PATH env var causes this issue
2.  What's the use-case to add this path to PATH env var

br,
Alex

**Comment by tuxedo0801** [comment]
@eirslett ping

**Comment by eirslett** [comment]
The reason it adds node (and npm) to PATH is to make sure that the plugin will run the locally provided node.js binary, and not the system one, in cases where there are recursive node.js processes - one node.js process forking another one.

The plugin tries its very best to avoid using the global installation of node.js (if there is one installed), but there might be a bug which makes it use the global one anyways... :-/

**Comment by tuxedo0801** [comment]
@eirslett 
``` in cases where there are recursive node.js processes - one node.js process forking another one.
```

hmm, makes sense. But actually does not work :-( I'll try to isolate the issue with a clean setup in a VM, maybe I then see the issue clearer.

**Comment by tuxedo0801** [comment]
Made a clean debian stretch install with virtualbox, installed nothing else than maven+java, run ```mvn package``` and build runs fine without any issues.

That proofs that a local installed nodejs conflicts with the build. 

Question is: how can we track down the issue?!
@eirslett

**Comment by eirslett** [comment]
I would suggest having a look inside the `build.js` file, check what's going on, how it's spawning the child process - maybe it unsets the environment variable somehow?

**Comment by eclipdata-gvillacis** [comment]
Do you have any estimated date for the solution of this?

**Comment by tuxedo0801** [comment]
I tried to check the module, but as I'm by far not an Node developer, I'm struggling a bit with the investigation. 

From my point of view, this should and must be solvable. if it runs directly on command line, I don't see why it the plugin should do something different.

> The plugin tries its very best to avoid using the global installation of node.js (if there is one installed), but there might be a bug which makes it use the global one anyways... :-/

It it's running with pure global nodejs, it runs. If it runs with pure plugin-provided nodejs (and in absence of global nodejs), it runs as well. But why it fails if it runs with a mixture, ... no idea.

**Comment by tuxedo0801** [comment]
Just recently switched to node 10.16.3 due to an CloudFoundry buildpack upgrade and now it mysteriously works. Issue is gone for now. Now it not only works on my local machine, but also in BItbucket build-pipeline with default maven container.

**Comment by magdasmircea** [comment]
`<execution>
						<id>npm build</id>
						<goals>
							<goal>npm</goal>
						</goals>
						<phase>generate-resources</phase>
						<configuration>
							<arguments>run build</arguments>
							<workingDirectory>web/</workingDirectory>
							<installDirectory>web/</installDirectory>
						</configuration>
					</execution>`

you need to specify the workingDirectory and the installDirectory . and it will work properly. I have battled with this a long time.
