### ISSUE TITLE
Node not found after install

### ISSUE THREAD

**Issue by StNekroman** [eirslett/frontend-maven-plugin#830]
I use:
```
<plugin>
    <groupId>com.github.eirslett</groupId>
    <artifactId>frontend-maven-plugin</artifactId>
    <version>1.6</version>
    <executions>
        <execution>
            <id>default-cli</id>
            <goals>
                <goal>install-node-and-npm</goal>
            </goals>
            <configuration>
                <nodeVersion>v8.11.3</nodeVersion>
                <npmVersion>5.8.0</npmVersion>
            </configuration>
        </execution>
        <execution>
            <id>npm-prepare</id>
            <goals>
                <goal>npm</goal>
            </goals>
            <configuration>
                <arguments>run prepare</arguments>
            </configuration>
        </execution>
        <execution>
            <id>npm-install</id>
            <goals>
                <goal>npm</goal>
            </goals>
            <configuration>
                <arguments>install</arguments>
            </configuration>
        </execution>
    </executions>
    <configuration>
        <installDirectory>C:/NodeInstallDir/</installDirectory>
    </configuration>
    </plugin>
```

My console output is next:

> [INFO] --- frontend-maven-plugin:1.6:install-node-and-npm (default-cli) @ artifact-project ---
> [INFO] Node v8.11.3 is already installed.
> [INFO] NPM 5.8.0 is already installed.
> [INFO] 
> [INFO] --- frontend-maven-plugin:1.6:npm (npm-prepare) @ artifact-project ---
> [INFO] Running 'npm run prepare' in C:\projectDir
> [INFO] 
> [INFO] > artifact@1.0 prepare C:\projectDir
> [INFO] > node ./prepare
> [INFO] 
> [INFO] 
> [INFO] --- frontend-maven-plugin:1.6:npm (npm-install) @ artifact-project ---
> [INFO] Running 'npm install' in C:\projectDir
> [INFO] 
> [INFO] > artifact@1.0 prepare C:\projectDir
> [INFO] > node ./prepare
> [INFO] 
> [ERROR] 'node' is not recognized as an internal or external command,
> [ERROR] operable program or batch file.
> [ERROR] npm ERR! code ELIFECYCLE
> [ERROR] npm ERR! errno 1
> [ERROR] npm ERR! artifact@1.0 prepare: `node ./prepare`
> [ERROR] npm ERR! Exit status 1
> [ERROR] npm ERR! 
> [ERROR] npm ERR! Failed at the artifact@1.0 prepare script.
> [ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> [ERROR] 
> [ERROR] npm ERR! A complete log of this run can be found in:
> [ERROR] npm ERR!     C:\..truncated..\_logs\2019-07-15T09_59_45_544Z-debug.log

Question:
How node executable is supposed to be visible from currentWorking directory?
I looked in code of "frontend-maven-plugin" and I found that it only downloads, extracts and moves "node" executable to required "installDirectory". Without any modification of "PATH" variable on Windows.
Then, if node is installed to "C:/NodeInstallDir/", while currently maven executes build in "C:\projectDir", then how node execuable is supposed to be visible there?
Note, if I add NodeInstallDir to PATH manually - everything works.

**Comment by eirslett** [comment]
Maybe you need to reverse the slashes, so it'a `\` instead of `/`?

**Comment by StNekroman** [comment]
It doesn't matter, which slash to use - good Windows supports both variants.

> Anyways, just try not to set installDirectory at all and simply use the default configuration?
No, I need to avoid any 3rd-party files in buildDir, which aren't part of original sources.
That's why I definitely need to use custom "installDirectory".
I'm able to run my setup, but with additional manual modification of PATH variable.
While, as I understood, this plugin must deal with custom install dir without manual interactions.
So I wonder, how it supposed to work.

**Comment by eirslett** [comment]
> No, I need to avoid any 3rd-party files in buildDir, which aren't part of original sources.

That's not a problem. The normal directory setup you get, is like this:

```
pom.xml
src/ <-- this is where your sources are
target/ <-- this is where your built jar files etc will end up
node/ <-- this is where it will put your node.js/npm things
.gitignore <-- in this file, you add node/ so that it won't be part of your git repo.
```

This plugin does modify the PATH variable while running node/npm tasks, so it's strange that it doesn't work for you...

**Comment by StNekroman** [comment]
Anyway, I need to install node separately from buildDir, that's a requirement.

> This plugin does modify the PATH variable while running node/npm tasks
Ok, I just found ProcessExecutor, which modifies the PATH.

Additional information - I run my maven build with maven invoker:
```
<dependency>
      <groupId>org.apache.maven.shared</groupId>
      <artifactId>maven-invoker</artifactId>
      <version>3.0.0</version>
</dependency>
```
I checked now how it works in cmd line - and first build succeeded.
But I run it with maven-invoker, which uses ProcessBuilder for mvn execution.

My two frontend projects use frontend-maven-plugin.
They both inherit config for plugin from parent's pom.
Parent pom contains in 

```
<pluginManagement>
    ...
    <plugins>
        <plugin>
            <groupId>com.github.eirslett</groupId>
            <artifactId>frontend-maven-plugin</artifactId>
            <version>1.6</version>
            <executions>
                <execution>
                    <id>default-cli</id>
                    <goals>
                        <goal>install-node-and-npm</goal>
                    </goals>
                    <configuration>
                        <nodeVersion>v8.11.3</nodeVersion>
                        <npmVersion>5.8.0</npmVersion>
                    </configuration>
                </execution>
                <execution>
                    <id>npm-prepare</id>
                    <goals>
                        <goal>npm</goal>
                    </goals>
                    <configuration>
                        <arguments>run prepare</arguments>
                    </configuration>
                </execution>
                <execution>
                    <id>npm-install</id>
                    <goals>
                        <goal>npm</goal>
                    </goals>
                    <configuration>
                        <arguments>install</arguments>
                    </configuration>
                </execution>
            </executions>
            <configuration>
                <installDirectory>C:/NodeInstallDir/</installDirectory>
            </configuration>
        </plugin>
    </plugins>
</pluginManagement>
```

First frontend project is webpack-based and has:

```
 <plugin>
    <groupId>com.github.eirslett</groupId>
    <artifactId>frontend-maven-plugin</artifactId>
    <executions>
        <execution>
            <id>npm build</id>
            <goals>
                <goal>npm</goal>
            </goals>
            <configuration>
                <arguments>install</arguments>
            </configuration>
        </execution>
    </executions>
</plugin>
```

Second frontend project is Grunt-based and has:

```
<plugin>
    <groupId>com.github.eirslett</groupId>
    <artifactId>frontend-maven-plugin</artifactId>
    <executions>
        <execution>
            <id>grunt</id>
            <goals>
                <goal>grunt</goal>
            </goals>
            <configuration>
                <srcdir>${project.basedir}/src/main/app</srcdir>
                <outputdir>${project.basedir}/target/app</outputdir>
                <triggerfiles>
                    <triggerfile>${project.basedir}/Gruntfile.js</triggerfile>
                    <triggerfile>${project.basedir}/package.json</triggerfile>
                </triggerfiles>
            </configuration>
        </execution>
    </executions>
</plugin>
```

First project builds fine, while second reports about missing node executable.
I'm looking in sources of this plugin and I see that PATH env var is extended with node location by NodeTaskExecutor.
While:
`final class DefaultBowerRunner extends NodeTaskExecutor implements BowerRunner {...`
`final class DefaultNpmRunner extends NodeTaskExecutor implements NpmRunner {...`

I suspect, that Grunt goals doesn't modify PATH with nodejs location. Am I correct?

**Comment by eirslett** [comment]
Try adding `<installDirectory>` to the configurations of all three executions?

**Comment by StNekroman** [comment]
> Try adding <installDirectory> to the configurations of all three executions?
It doesn't matter as soon as this is inherited from parent's pom.

After some debugging of this plugin I found that in my environment two variables are present:
"PATH" and "Path".
While your plugin takes last variables and modifies it.
But when actual command executes in separate process - Windows uses first variable, **sometimes**.
And **sometimes** second. I think, it's possible to have even 3rd variable with name "pAtH".

I suggest you modify all path-like variables.

**Comment by StNekroman** [comment]
Why this happens for me?

Because MavenInvoker, which I use, it uses CommandLineUtils.getSystemEnvVars() from "org.codehaus.plexus:pluxus-utils:3.0.24".
And inside CommandLineUtils.getSystemEnvVars() all var names becomes upper case (while I think, it's incorrect)
After all, upper-case system env vars are inherited from system and passed MavenInvoker and ordinary env variables are passed too.
That's how it works with maven-invoker:3.0.0. I checked 3.0.1 - in that version they changed library pluxus-utils to own "maven-shared-utils". Where just copied all it's bugs.

Actually, this is problem with maven-invoker and underlying "utils", so they ignore "inheritSystemVariables" flag - they always populate system env vars in upper case.
But anyway, frontend-maven-plugin must handle multiple vars in different case on Windows.

**Comment by StNekroman** [comment]
Take this https://github.com/eirslett/frontend-maven-plugin/pull/832

**Comment by balharrie** [comment]
See also https://github.com/sdorra/buildfrontend-maven-plugin/pull/8/files
