### ISSUE TITLE
Always install latest node

### ISSUE THREAD

**Issue by gangadharjannu** [eirslett/frontend-maven-plugin#837]
**Do you want to request a _feature_ or report a _bug_?**
I want to know, is there any way we can always install the latest version of NodeJS instead of explicitly specifying like `<nodeVersion>v8.11.1</nodeVersion>`

What I propose is instead of explicitly specifying the node version we could specify something like `<nodeVersion>LATEST</nodeVersion>` which will install the current stable version.

**What is the current behavior?**
We have to manually search for the latest version of node and add the version in`POM.xml`

`<nodeVersion>v8.11.1</nodeVersion>`

**What is the expected behavior?**
`<nodeVersion>LATEST</nodeVersion>`
**Please mention your frontend-maven-plugin and operating system version.**
I'm using frontend-maven-plugin 1.7.6 and Mac 10.14.5 (Mojave)

**Comment by vmontala** [comment]
What about `<nodeVersion>LTS</nodeVersion>` as the `LATEST` could also mix  `LTS`, `Current`/`Stable`, etc

**Comment by eirslett** [comment]
The reason this isn't supported, is that a new version of node.js could introduce a regression/bug (yes, it happened to me and I wasted hours because of it) so in order to have reproducible builds (no "works on my machine" issues) the plugin is designed so that you have to lock down to a specific version of Node.js. So if there's a newer version, simply update the version in your pom.xml file!

**Comment by vmontala** [comment]
@eirslett thanks for your answer.

I understand your reasoning, although at the same time I don't think it's black or white... If you are attached to a very specific version of node and you don't plan to update it you should specify the version.

Thing is, if you are not, shouldn't there be a way to do so? Manually updating the version on the file it's quite tedious, I would rather rely on forcing automatic updates for my different environments, tagging there the latest lts...

**Comment by eirslett** [comment]
It's 1 line of code in your pom.xml to upgrade the Node.js version. It's hardly tedious?

**Comment by gangadharjannu** [comment]
I agree that it is one line but we have to manually update the NodeJS version every time when there is a new version released which is why I asked for it. 

Do you have any workaround to always install latest NodeJS?

**Comment by eirslett** [comment]
There's really no need to update to every latest version of Node.js, just update the pom.xml to the latest version one or two times a year, and you will be fine. Almost all tools you use (npm, grunt, webpack, parcel, whatever) will work with a somewhat older version of node.js than the latest version. And in the rare case that the Node.js version is too old, it's possible to make another version bump in pom.xml.
