### ISSUE TITLE
Example POM for "Installing node and npm" is missing the `<executions>` plural tag

### ISSUE THREAD

**Issue by basil-bourque** [eirslett/frontend-maven-plugin#838]
The *Installing node and npm* section of the main project page:
https://github.com/eirslett/frontend-maven-plugin

…shows example POM fragment, including an `<execution>` tag. That example will not work. That `<execution>` tag must be nested inside an `<executions>` tag (plural of "execution"). 

This:

    <plugin>
        ...
        <execution>
            
            <id>install node and npm</id>
            <goals>
                <goal>install-node-and-npm</goal>
            </goals>
            
            <phase>generate-resources</phase>
        </execution>
        <configuration>
            <nodeVersion>v4.6.0</nodeVersion>

            
            <npmVersion>2.15.9</npmVersion>
            
            
            <downloadRoot>http://myproxy.example.org/nodejs/</downloadRoot>
        </configuration>
    </plugin>

…should be:

    <plugin>
        ...
        <executions>
            <execution>
                
                <id>install node and npm</id>
                <goals>
                    <goal>install-node-and-npm</goal>
                </goals>
                
                <phase>generate-resources</phase>
            </execution>
        </executions>
        <configuration>
            <nodeVersion>v4.6.0</nodeVersion>

            
            <npmVersion>2.15.9</npmVersion>
            
            
            <downloadRoot>http://myproxy.example.org/nodejs/</downloadRoot>
        </configuration>
    </plugin>

See [this discussion](https://vaadin.com/forum/thread/17797984/error-failed-to-determine-node-tool-with-new-vaadin-14-0-0-rc9-project) on the [Vaadin](https://en.wikipedia.org/wiki/Vaadin) project’s Forum site. That discussion shows before-and-after POM file.

**Comment by eirslett** [comment]
Thanks! Looks better now I guess.
