### ISSUE TITLE
Needs to support nyc and mocha

### ISSUE THREAD

**Issue by kdeng** [eirslett/frontend-maven-plugin#849]
Hi,

Could we require a new feature to support nyc and mocha? As I am currently experiencing the issue as same as this [stackoverflow](https://stackoverflow.com/questions/56145363/testmocha-try-to-run-cygwin-command-on-linux). Which has mentioned the latest plugin doesn't work properly with `nyc` and `mocha`. 

My `package.json` looks as below. 
```json
scripts:{
   ...
   "test:coverage": "nyc --reporter=lcov --all npm run test",
   "test": "npx mocha ./test/unit --recursive --reporter mochawesome --reporter-options reportDir=test/report,reportFilename=unit_test_report --exit",
   ...
}
```

When I run `mvn verify` under the latest macos (even the latest maven 3 docker image) to execute `npm run test:coverage`, it throws an error as following.

```bash
[INFO] > nyc --reporter=lcov --all npm run-script test:all
[INFO]
[INFO] /apps/target/node/npm:2
[INFO] (set -o igncr) 2>/dev/null && set -o igncr; # cygwin encoding fix
[INFO]         ^^^^^
[INFO]
[INFO] SyntaxError: Unexpected identifier
[INFO]     at Module._compile (internal/modules/cjs/loader.js:723:23)
[INFO]     at Module.replacementCompile (/apps/node_modules/nyc/node_modules/append-transform/index.js:58:13)
[INFO]     at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[INFO]     at Object.<anonymous> (/apps/node_modules/nyc/node_modules/append-transform/index.js:62:4)
[INFO]     at Module.load (internal/modules/cjs/loader.js:653:32)
[INFO]     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[INFO]     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[INFO]     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
[INFO]     at runMain (/root/.node-spawn-wrap-3789-33d47f37de31/node:68:10)
[INFO]     at Function.<anonymous> (/root/.node-spawn-wrap-3789-33d47f37de31/node:171:5)
[INFO] npm ERR! code ELIFECYCLE
[INFO] npm ERR! errno 1
[INFO] npm ERR! mobilityos-mock-taxi-service@1.0.11 test: `nyc --reporter=lcov --all npm run-script test:all`
[INFO] npm ERR! Exit status 1
```

Could we please add a new feature into the plugin to support `nyc` and `mocha`? Cheers.

**Comment by eirslett** [comment]
I guess it's not really about lack of support - but rather of some bug with nyc and mocha interacting with the local node.js installation? I'm not sure why, but I don't use nyc myself.

**Comment by kdeng** [comment]
Thanks for your reply. I will have a look on the issues on nyc and mocha. 

Also, I am going to close this issue, as I agree with you that it might be a bug with nyc and mocha.

Cheers.

**Comment by asharron** [comment]
Hey, @kdeng,  were you able to find a work around?

I am using nyc and mocha myself, and have ran into this issue...

**Comment by coreyfarrell** [comment]
spawn-wrap has issues with unexpected environments (especially shells).  I recommend testing nyc@next (the prerelease of 15) which replaces spawn-wrap with an alternative that does not depend on your shell.  if you depend on babel-plugin-istanbul or other istanbul* be sure to upgrade all of them to the next version.  also note that nyc 15 requires node.js 8.

**Comment by asharron** [comment]
Upgrading to `nyc@next` (at the time it is the v15 beta) fixed my issue with this 😄

**Comment by kdeng** [comment]
@asharron nice to know you have found a solution. Thanks for sharing this information.
