### ISSUE TITLE
Support `npm ci` command for stable package-lock

### ISSUE THREAD

**Issue by peacememories** [eirslett/frontend-maven-plugin#855]
**Do you want to request a _feature_ or report a _bug_?**

I want to request a feature

**What is the current behavior?**

Currently the only way to install packages with npm using this plugin is `npm install`

`npm install` potentially rewrites the `package-lock.json` every time it's run, especially when run on different systems (e.g. a local developer machine and a ci server). To sidestep this issue, npm introduced the `ci` command, which never touches the `package-lock.json` and instead errors if it is not compatible with the `package.json`.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Either default to `npm ci` for install tasks or give the option to use it instead of `npm install`

**Please mention your frontend-maven-plugin and operating system version.**
frontend-maven-plugin v1.4
OS Versions:
* Manjaro 18.1.0 Juhraya
* Fedora 29
* Windows 10/1803
* Ubuntu 16.04

**Comment by eirslett** [comment]
Already supported:
```
<execution>
    <id>npm ci</id>
    <goals>
        <goal>npm</goal>
    </goals>
    <configuration>
        <arguments>ci</arguments>
    </configuration>
</execution>
```

**Comment by tsposato** [comment]
Is this supported through the 'install-node-and-npm' goal as well?
Or will that run npm install as part of the goal?
