### ISSUE TITLE
Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:install-node-and-npm (install node and npm) on project tdpco-web-app-ui: Could not download Node.js: Got error code 404 from the server. -> [Help 1]

### ISSUE THREAD

**Issue by riyas90cse** [eirslett/frontend-maven-plugin#857]
Reactor Summary:
[INFO] 
[INFO] tdpco-web-app ...................................... SUCCESS [  0.308 s]
[INFO] tdpco-web-app-model ................................ SUCCESS [  1.013 s]
[INFO] tdpco-web-app-service .............................. SUCCESS [  1.901 s]
[INFO] tdpco-web-app-ui ................................... FAILURE [  1.429 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.414 s
[INFO] Finished at: 2019-10-05T16:45:25+03:00
[INFO] Final Memory: 41M/362M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:install-node-and-npm (install node and npm) on project tdpco-web-app-ui: Could not download Node.js: Got error code 404 from the server. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :tdpco-web-app-ui

Process finished with exit code 1
please find the pom file below...in attachments

[pom-file.zip](https://github.com/eirslett/frontend-maven-plugin/files/3693399/pom-file.zip)

**Comment by danasourasrex** [comment]
I was getting this same error. It turned out to be a typo in the version of npm that I specified.

**Comment by sssarfrazzz** [comment]
Maven tries to download nodejs from location https://nodejs.org/dist/v4.0.0/x64/node.exe But the folder structure to download for windows 64 bit OS is, in fact, http://nodejs.org/dist/v4.0.0/win-x64/node.exe.

>win-x64 added in URL instead of just x64

**Comment by MephistoLynn** [comment]
I met the similar error and have wasted my three days  oh...headache. .
Anyone fixed this problem ?

[ 
Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.8.0:yarn (yarn install) on project dlux-web: Failed to run task: 'yarn install' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
]

**Comment by MadikMayCry** [comment]
If anyone has solved the problem please help

**Comment by prabhat1** [comment]
i tred to change the version to 1.8.0 and its working .

**Comment by ManuelTS** [comment]
Any new insights? I have the same problem with version 1.10.0

**Comment by riddhi2910** [comment]
Facing the same issue.

**Comment by eirslett** [comment]
> Maven tries to download nodejs from location https://nodejs.org/dist/v4.0.0/x64/node.exe But the folder structure to download for windows 64 bit OS is, in fact, http://nodejs.org/dist/v4.0.0/win-x64/node.exe.

Node v4.0.0 is _very_ old. It's not supported by this plugin anymore. Try using v12.18.3, which is the latest long-term-support version.

**Comment by riyas90cse** [comment]
> > Maven tries to download nodejs from location https://nodejs.org/dist/v4.0.0/x64/node.exe But the folder structure to download for windows 64 bit OS is, in fact, http://nodejs.org/dist/v4.0.0/win-x64/node.exe.
> 
> Node v4.0.0 is _very_ old. It's not supported by this plugin anymore. Try using v12.18.3, which is the latest long-term-support version.

thanks

**Comment by maxshuty** [comment]
Since this is a top google result for the error if you're seeing this and you're on a Mac with the M1 chip you need to upgrade the plugin to `v1.11.0` or newer.
