### ISSUE TITLE
webpack build fails during a copy operation

### ISSUE THREAD

**Issue by raul1991** [eirslett/frontend-maven-plugin#865]
**Do you want to request a _feature_ or report a _bug_?**
Bug
**What is the current behavior?**
It fails with the following error
```
[INFO] An unhandled exception occurred: CopyPlugin Invalid Options
[INFO] 
[INFO] options should NOT have fewer than 1 items
[INFO] 
[INFO] See "/tmp/ng-VIGa3f/angular-errors.log" for further details.
[INFO] npm ERR! file sh
[INFO] npm ERR! code ELIFECYCLE
[INFO] npm ERR! errno ENOENT
[INFO] npm ERR! syscall spawn
[INFO] npm ERR! coba@1.0.0-SNAPSHOT build:production: `node ./node_modules/@angular/cli/bin/ng run coba:build-webpack`
[INFO] npm ERR! spawn ENOENT
[INFO] npm ERR! 
[INFO] npm ERR! Failed at the coba@1.0.0-SNAPSHOT build:production script.
[INFO] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```
**If the current behavior is a bug, please provide the steps to reproduce.**
 ``` mvn clean install ```
**What is the expected behavior?**
The webpack build succeeds.
**Please mention your frontend-maven-plugin and operating system version.**
Os: Ubuntu18.04
version: 1.18.0

**Comment by eirslett** [comment]
This is an issue with your Webpack configuration, not with frontend-maven-plugin.
