### ISSUE TITLE
node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by node) on Red Hat 7 ppc64le

### ISSUE THREAD

**Issue by redmark-alt** [eirslett/frontend-maven-plugin#866]
Building Apache Flink I'm getting a node error.

I believe it's similar to issue as #852.  The plugin is installing a ppc64le version of node that's incompatible with Red Hat Linux 7.6 & 7.7 (i.e. libstdc++.so.6).  I suspect this node package was compiled on Ubuntu Linux for ppc64le.

Can the package be configured to use the native/local copy of node? Or add a feature to use the native/local copy?

**What is the current behavior?**
`.m2/repository/com/github/eirslett/node/10.9.0/node-10.9.0-linux-ppc64le.tar.gz` is being copied to `flink/flink-runtime-web/web-dashboard/node`

```
/root/flink/flink-runtime-web/web-dashboard/node/node -v
/root/flink/flink-runtime-web/web-dashboard/node/node: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /root/flink/flink-runtime-web/web-dashboard/node/node)
```

**Steps to reproduce.**
Red Hat 7.6 or 7.7 ppc64le with working local nodejs version 10.17.0

```
git clone https://github.com/apache/flink.git
cd flink
mvn clean package -DskipTests
```

**Comment by redmark-alt** [comment]
Any thoughts on allowing the local copy of node to be used for the build process?

**Comment by eirslett** [comment]
If you want to use the native node.js binary, I suggest using exec-maven-plugin, like in this guide: https://addyosmani.com/blog/making-maven-grunt/
