### ISSUE TITLE
Refer package.json from git repo

### ISSUE THREAD

**Issue by TaniCool** [eirslett/frontend-maven-plugin#874]
**Do you want to request a _feature_ or report a _bug_?**
Ask a question/ Request feature 

**What is the current behavior?**
Location of package.json can be referred from workingDirectory tag
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
With my use case I want to refer package.json from one of my Git repository. Is it possible? 
What would be workaround ? 

**Please mention your frontend-maven-plugin and operating system version.**

**Comment by eirslett** [comment]
I guess you could `git clone` your respository into some folder, and use it from there?

**Comment by TaniCool** [comment]
Yeah, that's the possible thing I can do.
