### ISSUE TITLE
Build Fails with weird error

### ISSUE THREAD

**Issue by MarkusKrug** [eirslett/frontend-maven-plugin#889]
Since a couple days our build fails on Ubuntu 18.04, the error message is:

`[ERROR] /home/mkrug/webATHEN/webEditor/node_modules/grunt/node_modules/mkdirp/index.js:4
[ERROR] const {mkdirpNative, mkdirpNativeSync} = require('./lib/mkdirp-native.js')
[ERROR]       ^
[ERROR]
[ERROR] SyntaxError: Unexpected token {
[ERROR]   at exports.runInThisContext (vm.js:53:16)
[ERROR]   at Module._compile (module.js:373:25)
[ERROR]   at Object.Module._extensions..js (module.js:416:10)`

with the following configuration

`
 <plugin>
                <groupId>com.github.eirslett</groupId>
                <artifactId>frontend-maven-plugin</artifactId>
                <version>1.6</version>
                <executions>
                    <execution>
                        <id>install node and npm</id>
                        <goals>
                            <goal>install-node-and-npm</goal>
                        </goals>
                        
                        <phase>generate-resources</phase>
                        <configuration>
                            <nodeVersion>v4.6.0</nodeVersion>

                            
                            <npmVersion>2.15.9</npmVersion>
                        </configuration>
                    </execution>
                    <execution>
                        <id>npm install</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>grunt build</id>
                        <goals>
                            <goal>grunt</goal>
                        </goals>
                        <configuration>
                            <arguments>--no-color</arguments>
                        </configuration>
                    </execution>

                </executions>

            </plugin>
`

Does anyone haven an idea what could be wrong?

**Comment by holgergp** [comment]
This error basically says that your javascript-runtime cannot parse the [destructuring assignment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) used in mkdirp (which is used by grunt). Judging from the npm version you are using (2.15.9) you are using a fairly old version of node. Node afaik only supports destructuring assignment as of version [6](https://nodejs.org/en/blog/release/v6.0.0/). 
Maybe try a newer version of node (or an older version of grunt).

**Comment by eirslett** [comment]
Yes, upgrade to Node.js v12.18.4 (latest stable release) with npm 6.14.6.
