### ISSUE TITLE
Externalizing custom configurations in React spring boot war

### ISSUE THREAD

**Issue by murali474** [eirslett/frontend-maven-plugin#923]
Currently i am using this plugin to convert react app to spring boot war. Now I need to retrieve/supply backend host and port urls from properties file and use in react ui  code. 

I knew the process for general spring boot application and could not find any documentation/reference related property externalization in case of react based spring boot war.

Quick responses are much appreciated and Please help me in this.

**Comment by eirslett** [comment]
Use this snippet in your React code, which will give you the base URL for your application:

```javascript
const basePath = window.location.protocol + '//' + window.location.hostname + (window.location.port ? ':' + window.location.port: '');
```

Good luck with your project!

**Comment by murali474** [comment]
Hi ,

First of all, thanks for the reply .I think I need to reexplain my issue
here .

I will deploy my UI war at one node and my back end services at another
node or same node .so, now I should read host and port of my server  where
my backend services deployed  . So how can I read them at deployment time
rather build stage

Thanks,
Murali.

**Comment by eirslett** [comment]
Ok so you have a UI .war, which is probably a Spring app? I suggest that you make a REST endpoint in your UI war/app/servlet, for example `/config.json`, and in the response, you return configuration for the frontend - like for example the backend URLs.

**Comment by murali474** [comment]
Thanks Eirslett,  this approach helped me .


Regards,
Murali

**Comment by murali474** [comment]
Hi @eirslett , Sorry to reopen the conversation.

so, is  window.location code part in react code works if configure my application with Load balancer.
will the  **window.location.hostname**  give us the actual node details or LoadBalancer details?
