### ISSUE TITLE
Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.10.0:

### ISSUE THREAD

**Issue by Salahlemangar** [eirslett/frontend-maven-plugin#931]
[INFO] npm ERR! Unexpected end of JSON input while parsing near '...RS5V\r\n-----END PGP '
[INFO] 
[INFO] npm ERR! A complete log of this run can be found in:
[INFO] npm ERR!     /home/salahl/.npm/_logs/2020-09-09T13_06_14_163Z-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  22.308 s
[INFO] Finished at: 2020-09-09T14:06:14+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.10.0:npm (npm install) on project blog: Failed to run task: 'npm install' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]

Hello I'm using the latest version which is 1.10.0 

any suggestions on related issue?

**Comment by seanffy** [comment]
I have the same problem

**Comment by holgergp** [comment]
The content of your package.json seems to be invalid, as in invalid json. Does it contain sth like `RS5V\r\n-----END PGP` in an odd place?

**Comment by Qiming-C** [comment]
> [INFO] npm ERR! Unexpected end of JSON input while parsing near '...RS5V\r\n-----END PGP '
> [INFO]
> [INFO] npm ERR! A complete log of this run can be found in:
> [INFO] npm ERR! /home/salahl/.npm/_logs/2020-09-09T13_06_14_163Z-debug.log
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 22.308 s
> [INFO] Finished at: 2020-09-09T14:06:14+01:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.10.0:npm (npm install) on project blog: Failed to run task: 'npm install' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
> 
> Hello I'm using the latest version which is 1.10.0
> 
> any suggestions on related issue?

did you figure it out? I have same issue
