### ISSUE TITLE
opencast issues

### ISSUE THREAD

**Issue by samanthaherath** [eirslett/frontend-maven-plugin#938]
Already I have faced this Issue in Ubuntu18.04 on that i have tried to install opencast so i have got that 
problem as bellow please help me

[INFO] Assemblies // Distribution Admin/Presentation ...... SKIPPED
[INFO] Assemblies // Distribution All-In-One .............. SKIPPED
[INFO] Assemblies // Distribution Ingest .................. SKIPPED
[INFO] Assemblies // Distribution Presentation ............ SKIPPED
[INFO] Assemblies // Distribution Worker .................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:50 min
[INFO] Finished at: 2020-10-14T09:42:13+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.7.6:install-node-and-npm (install node and npm) on project opencast-admin-ui: Could not download Node.js: Got error code 404 from the server. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :opencast-admin-ui

**Comment by eirslett** [comment]
Try using a newer version of frontend-maven-plugin? The latest version is 1.10.3.

**Comment by samanthaherath** [comment]
Thank you so mach giving the that kind of help Mr.eirslett but i couldn't update the new version of maven plugin.I am not good familiar with Linux i have following this document  "**https://websiteforstudents.com/how-to-install-opencast-on-ubuntu-18-04-16-04/**" to install opencast but still coming the previous error mages. please help to overcome this problem  

Thanks

**Comment by samanthaherath** [comment]
Thanks Mr Eirik Sletteberg
 I have tried to fix the frontend maven plugin problem  but still some
other error message is coming
please help me

thanks
"
[INFO]
------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO]
------------------------------------------------------------------------
[INFO] Total time:  05:50 min
[INFO] Finished at: 2020-11-05T10:42:18+05:30
[INFO]
------------------------------------------------------------------------
[ERROR] Plugin
com.github.eirslett:frontend-maven-plugin:frontend-plugins-1.10.0 or one of
its dependencies could not be resolved: Could not find artifact
com.github.eirslett:frontend-maven-plugin:jar:frontend-plugins-1.10.0 in
central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e
switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions,
please read the following articles:
[ERROR] [Help 1]
http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
cc@cc-HP-Compaq-6200-Pro-MT-PC:/tmp/opencast_source$ "


thanks

**Comment by eirslett** [comment]
Instead of 1.10.0, try 1.10.3?

**Comment by samanthaherath** [comment]
Dear Mr.Eirik Sletteberg

Thanks you very much your elist respond i will try as you instract

Thank

**Comment by samanthaherath** [comment]
Dear Mr.Eirik

I have tred Instead of 1.10.0,  1.10.3 frontend -maven-plugin but still
this error coming please help meto sover this task
thanks
istribution-workflowoperation ......... SUCCESS [  4.956 s]
[INFO] Opencast :: index-service .......................... SUCCESS [01:02
min]
[INFO] Opencast :: presets ................................ SUCCESS [
16.045 s]
[INFO] Opencast :: static-file-service-api ................ SUCCESS [
 5.735 s]
[INFO] Opencast :: statistics-service-api ................. SUCCESS [
 5.197 s]
[INFO] Opencast :: statistics-export-service .............. SUCCESS [
28.562 s]
[INFO] Opencast :: themes ................................. SUCCESS [
14.394 s]
[INFO] Opencast :: smil-api ............................... SUCCESS [
25.060 s]
[INFO] Opencast :: composer-service-api ................... SUCCESS [
20.912 s]
[INFO] Opencast :: solr ................................... SUCCESS [
40.305 s]
[INFO] Opencast :: series-service-impl .................... SUCCESS [
42.302 s]
[INFO] Opencast :: asset-manager-impl ..................... SUCCESS [01:13
min]
[INFO] Opencast :: admin-ui-index ......................... SUCCESS [
23.876 s]
[INFO] Opencast :: admin-ui ............................... FAILURE [
23.111 s]
[INFO] Opencast :: animate-api ............................ SKIPPED
[INFO] Opencast :: animate-impl ........................... SKIPPED
[INFO] Opencast :: animate-remote ......................... SKIPPED
[INFO] Opencast :: inspection-service-api ................. SKIPPED
[INFO] Opencast :: animate-workflowoperation .............. SKIPPED
[INFO] Opencast :: annotation-api ......................... SKIPPED
[INFO] Opencast :: annotation-impl ........................ SKIPPED
[INFO] Opencast :: asset-manager-workflowoperation ........ SKIPPED
[INFO] Opencast :: asset-manager-storage-aws .............. SKIPPED
[INFO] Opencast :: asset-manager-storage-fs ............... SKIPPED
[INFO] Opencast :: caption-api ............................ SKIPPED
[INFO] Opencast :: mpeg7 .................................. SKIPPED
[INFO] Opencast :: caption-impl ........................... SKIPPED
[INFO] Opencast :: caption-remote ......................... SKIPPED
[INFO] Opencast :: capture-admin-service-impl ............. SKIPPED
[INFO] Opencast :: comments-workflowoperation ............. SKIPPED
[INFO] Opencast :: composer-ffmpeg ........................ SKIPPED
[INFO] Opencast :: composer-service-remote ................ SKIPPED
[INFO] Opencast :: inspection-workflowoperation ........... SKIPPED
[INFO] Opencast :: composer-workflowoperation ............. SKIPPED
[INFO] Opencast :: oaipmh-persistence ..................... SKIPPED
[INFO] Opencast :: conductor .............................. SKIPPED
[INFO] Opencast :: cover-image-api ........................ SKIPPED
[INFO] Opencast :: cover-image-impl ....................... SKIPPED
[INFO] Opencast :: cover-image-remote ..................... SKIPPED
[INFO] Opencast :: cover-image-workflowoperation .......... SKIPPED
[INFO] Opencast :: crop-api ............................... SKIPPED
[INFO] Opencast :: inspection-service-ffmpeg .............. SKIPPED
[INFO] Opencast :: crop-ffmpeg ............................ SKIPPED
[INFO] Opencast :: crop-remote ............................ SKIPPED
[INFO] Opencast :: crop-workflowoperation ................. SKIPPED
[INFO] Opencast :: db ..................................... SKIPPED
[INFO] Opencast :: dictionary-api ......................... SKIPPED
[INFO] Opencast :: dictionary-hunspell .................... SKIPPED
[INFO] Opencast :: dictionary-none ........................ SKIPPED
[INFO] Opencast :: dictionary-regexp ...................... SKIPPED
[INFO] Opencast :: distribution-service-aws-s3-api ........ SKIPPED
[INFO] Opencast :: distribution-service-aws-s3 ............ SKIPPED
[INFO] Opencast :: distribution-service-aws-s3-remote ..... SKIPPED
[INFO] Opencast :: distribution-service-download .......... SKIPPED
[INFO] Opencast :: distribution-service-download-remote ... SKIPPED
[INFO] Opencast :: distribution-service-adaptive-streaming-wowza SKIPPED
[INFO] Opencast :: distribution-service-streaming-remote .. SKIPPED
[INFO] Opencast :: email-template-service-api ............. SKIPPED
[INFO] Opencast :: email-template-service-impl ............ SKIPPED
[INFO] Opencast :: engage-paella-player ................... SKIPPED
[INFO] Opencast :: engage-theodul-api ..................... SKIPPED
[INFO] Opencast :: engage-theodul-core .................... SKIPPED
[INFO] Opencast :: engage-theodul-plugin-archetype ........ SKIPPED
[INFO] Opencast :: engage-theodul-plugin-controls ......... SKIPPED
[INFO] Opencast :: engage-theodul-plugin-custom-mhConnection SKIPPED
[INFO] Opencast :: engage-theodul-plugin-custom-notifications SKIPPED
[INFO] Opencast :: engage-theodul-plugin-custom-usertracking SKIPPED
[INFO] Opencast :: engage-theodul-plugin-custom-matomo .... SKIPPED
[INFO] Opencast :: engage-theodul-plugin-description ...... SKIPPED
[INFO] Opencast :: engage-theodul-plugin-tab-description .. SKIPPED
[INFO] Opencast :: engage-theodul-plugin-tab-shortcuts .... SKIPPED
[INFO] Opencast :: engage-theodul-plugin-tab-slidetext .... SKIPPED
[INFO] Opencast :: engage-theodul-plugin-timeline-statistics SKIPPED
[INFO] Opencast :: engage-theodul-plugin-video-videojs .... SKIPPED
[INFO] Opencast :: engage-ui .............................. SKIPPED
[INFO] Opencast :: execute-api ............................ SKIPPED
[INFO] Opencast :: execute-impl ........................... SKIPPED
[INFO] Opencast :: execute-remote ......................... SKIPPED
[INFO] Opencast :: execute-workflowoperation .............. SKIPPED
[INFO] Opencast :: external-api-index ..................... SKIPPED
[INFO] Opencast :: external-api ........................... SKIPPED
[INFO] Opencast :: fileupload ............................. SKIPPED
[INFO] Opencast :: hello-world-api ........................ SKIPPED
[INFO] Opencast :: hello-world-impl ....................... SKIPPED
[INFO] Opencast :: incident-workflowoperation ............. SKIPPED
[INFO] Opencast :: ingest-download-service-api ............ SKIPPED
[INFO] Opencast :: working-file-repository-service-api .... SKIPPED
[INFO] Opencast :: ingest-download-service-impl ........... SKIPPED
[INFO] Opencast :: ingestdownloadservice-remote ........... SKIPPED
[INFO] Opencast :: working-file-repository-service-impl ... SKIPPED
[INFO] Opencast :: ingest-service-impl .................... SKIPPED
[INFO] Opencast :: ingest-download-service-workflowoperation SKIPPED
[INFO] Opencast :: inspection-service-remote .............. SKIPPED
[INFO] Opencast :: statistics-writer-workflowoperation .... SKIPPED
[INFO] Opencast :: live-schedule-api ...................... SKIPPED
[INFO] Opencast :: live-schedule-impl ..................... SKIPPED
[INFO] Opencast :: logging-workflowoperation .............. SKIPPED
[INFO] Opencast :: lti .................................... SKIPPED
[INFO] Opencast :: mattermost-notification-workflowoperation SKIPPED
[INFO] Opencast :: message-broker-impl .................... SKIPPED
[INFO] Opencast :: metadata ............................... SKIPPED
[INFO] Opencast :: migration .............................. SKIPPED
[INFO] Opencast :: notification-workflowoperation ......... SKIPPED
[INFO] Opencast :: oaipmh-api ............................. SKIPPED
[INFO] Opencast :: oaipmh ................................. SKIPPED
[INFO] Opencast :: oaipmh-remote .......................... SKIPPED
[INFO] Opencast :: publication-service-configurable ....... SKIPPED
[INFO] Opencast :: publication-service-configurable-remote  SKIPPED
[INFO] Opencast :: publication-service-oaipmh ............. SKIPPED
[INFO] Opencast :: publication-service-oaipmh-remote ...... SKIPPED
[INFO] Opencast :: publication-service-youtube-remote ..... SKIPPED
[INFO] Opencast :: publication-service-youtube-v3 ......... SKIPPED
[INFO] Opencast :: runtime-info ........................... SKIPPED
[INFO] Opencast :: runtime-info-ui ........................ SKIPPED
[INFO] Opencast :: runtime-info-ui-ng ..................... SKIPPED
[INFO] Opencast :: scheduler-impl ......................... SKIPPED
[INFO] Opencast :: scheduler-conflict-handler ............. SKIPPED
[INFO] Opencast :: scheduler-conflict-notifier-comment .... SKIPPED
[INFO] Opencast :: scheduler-conflict-notifier-email ...... SKIPPED
[INFO] Opencast :: scheduler-remote ....................... SKIPPED
[INFO] Opencast :: schema ................................. SKIPPED
[INFO] Opencast :: search-service-feeds ................... SKIPPED
[INFO] Opencast :: search-service-impl .................... SKIPPED
[INFO] Opencast :: search-service-remote .................. SKIPPED
[INFO] Opencast :: security-shibboleth .................... SKIPPED
[INFO] Opencast :: security-aai ........................... SKIPPED
[INFO] Opencast :: security-cas-client-wrapper ............ SKIPPED
[INFO] Opencast :: security-cas ........................... SKIPPED
[INFO] Opencast :: security-ldap .......................... SKIPPED
[INFO] Opencast :: security-openid ........................ SKIPPED
[INFO] Opencast :: series-service-remote .................. SKIPPED
[INFO] Opencast :: serviceregistry ........................ SKIPPED
[INFO] Opencast :: silencedetection-api ................... SKIPPED
[INFO] Opencast :: silencedetection-impl .................. SKIPPED
[INFO] Opencast :: silencedetection-remote ................ SKIPPED
[INFO] Opencast :: smil-impl .............................. SKIPPED
[INFO] Opencast :: sox-api ................................ SKIPPED
[INFO] Opencast :: sox-impl ............................... SKIPPED
[INFO] Opencast :: sox-remote ............................. SKIPPED
[INFO] Opencast :: sox-workflowoperation .................. SKIPPED
[INFO] Opencast :: static ................................. SKIPPED
[INFO] Opencast :: static-file-service-impl ............... SKIPPED
[INFO] Opencast :: statistics-service-impl ................ SKIPPED
[INFO] Opencast :: statistics-service-remote .............. SKIPPED
[INFO] Opencast :: statistics-provider-influx ............. SKIPPED
[INFO] Opencast :: statistics-provider-random ............. SKIPPED
[INFO] Opencast :: termination-state-api .................. SKIPPED
[INFO] Opencast :: termination-state-aws .................. SKIPPED
[INFO] Opencast :: termination-state-impl ................. SKIPPED
[INFO] Opencast :: textanalyzer-api ....................... SKIPPED
[INFO] Opencast :: textanalyzer-impl ...................... SKIPPED
[INFO] Opencast :: textanalyzer-remote .................... SKIPPED
[INFO] Opencast :: textanalyzer-workflowoperation ......... SKIPPED
[INFO] Opencast :: textextractor-tesseract ................ SKIPPED
[INFO] Opencast :: themes-workflowoperation ............... SKIPPED
[INFO] Opencast :: timelinepreviews-api ................... SKIPPED
[INFO] Opencast :: timelinepreviews-ffmpeg ................ SKIPPED
[INFO] Opencast :: timelinepreviews-remote ................ SKIPPED
[INFO] Opencast :: timelinepreviews-workflowoperation ..... SKIPPED
[INFO] Opencast :: transcription-service-api .............. SKIPPED
[INFO] Opencast :: transcription-service-persistence ...... SKIPPED
[INFO] Opencast :: transcription-service-google-speech-impl SKIPPED
[INFO] Opencast :: transcription-service-ibm-watson-impl .. SKIPPED
[INFO] Opencast :: transcription-service-workflowoperation  SKIPPED
[INFO] Opencast :: urlsigning-service-impl ................ SKIPPED
[INFO] Opencast :: urlsigning-verifier-service-api ........ SKIPPED
[INFO] Opencast :: urlsigning-verifier-service-impl ....... SKIPPED
[INFO] Opencast :: userdirectory-ldap ..................... SKIPPED
[INFO] Opencast :: userdirectory-moodle ................... SKIPPED
[INFO] Opencast :: userdirectory-sakai .................... SKIPPED
[INFO] Opencast :: userdirectory-brightspace .............. SKIPPED
[INFO] Opencast :: user-interface-configuration ........... SKIPPED
[INFO] Opencast :: usertracking-api ....................... SKIPPED
[INFO] Opencast :: usertracking-impl ...................... SKIPPED
[INFO] Opencast :: videoeditor-api ........................ SKIPPED
[INFO] Opencast :: videoeditor-ffmpeg-impl ................ SKIPPED
[INFO] Opencast :: videoeditor-remote ..................... SKIPPED
[INFO] Opencast :: workflow-workflowoperation ............. SKIPPED
[INFO] Opencast :: videoeditor-workflowoperation .......... SKIPPED
[INFO] Opencast :: videosegmenter-api ..................... SKIPPED
[INFO] Opencast :: videosegmenter-ffmpeg .................. SKIPPED
[INFO] Opencast :: videosegmenter-remote .................. SKIPPED
[INFO] Opencast :: videosegmenter-workflowoperation ....... SKIPPED
[INFO] Opencast :: waveform-api ........................... SKIPPED
[INFO] Opencast :: waveform-ffmpeg ........................ SKIPPED
[INFO] Opencast :: waveform-remote ........................ SKIPPED
[INFO] Opencast :: waveform-workflowoperation ............. SKIPPED
[INFO] Opencast :: workflow-condition-parser .............. SKIPPED
[INFO] Opencast :: workflow-service-impl .................. SKIPPED
[INFO] Opencast :: workflow-service-remote ................ SKIPPED
[INFO] Opencast :: working-file-repository-service-remote . SKIPPED
[INFO] Opencast :: workspace-impl ......................... SKIPPED
[INFO] Assemblies ......................................... SKIPPED
[INFO] Assemblies // Apache Karaf Features ................ SKIPPED
[INFO] Assemblies // Distribution Admin ................... SKIPPED
[INFO] Assemblies // Distribution Admin/Presentation ...... SKIPPED
[INFO] Assemblies // Distribution All-In-One .............. SKIPPED
[INFO] Assemblies // Distribution Ingest .................. SKIPPED
[INFO] Assemblies // Distribution Presentation ............ SKIPPED
[INFO] Assemblies // Distribution Worker .................. SKIPPED
[INFO]
------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO]
------------------------------------------------------------------------
[INFO] Total time:  12:59 min
[INFO] Finished at: 2020-12-11T10:36:48+05:30
[INFO]
------------------------------------------------------------------------
[ERROR] Failed to execute goal
com.github.eirslett:frontend-maven-plugin:1.10.3:install-node-and-npm
(install node and npm) on project opencast-admin-ui: Could not download
Node.js: Got error code 404 from the server. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e
switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions,
please read the following articles:
[ERROR] [Help 1]
http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the
command
[ERROR]   mvn <args> -rf :opencast-admin-ui


---------- Forwarded message ---------
From: Samantha Herath <samantha2000@gmail.com>
Date: Fri, Nov 6, 2020 at 9:31 AM
Subject: Re: [eirslett/frontend-maven-plugin] opencast issues (#938)
To: eirslett/frontend-maven-plugin <
reply@reply.github.com>


Dear Mr.Eirik Sletteberg

Thanks you very much your elist respond i will try as you instract

Thank

**Comment by samanthaherath** [comment]
Hello Eirslett,

I received the following email and confirmed my Appointment. Thereafter I
did not hear anyone/anything yet.

[image: image.png]

What is going on?  Kindly advise.

Thanks you,

Samantha

**Comment by eirslett** [comment]
I'm not quite sure what the problem is. It says 404 from the server, so maybe

- the node.js version is wrong
- you have a proxy, but the configuration is wrong
- the machine you are running has some weird architecture (raspberry pi, solaris, I don't know...)

Can you show the entire output of the build? Including the information that frontend-maven-plugin shows before it's failing? It will show the URL that it's trying to download from - if that URL doesn't work in a web browser, the problem is with node version or platform - if the URL does work in a browser, but not in Maven, then it's probably the proxy configuration that is wrong.
