### ISSUE TITLE
Environment based execution

### ISSUE THREAD

**Issue by theunreal** [eirslett/frontend-maven-plugin#941]
**Do you want to request a _feature_ or report a _bug_?**
Feature/Support

**What is the current behavior?**
No doc how to do this.

I have the following execution:

```
<execution>
								<id>angular cli build</id>
								<goals>
									<goal>npm</goal>
								</goals>
								<phase>generate-resources</phase>
								<configuration>
									<arguments>run build-prod-high-memory</arguments>
								</configuration>
							</execution>
```

I also want to add my e2e tests before the build execution, e.g:
```
<execution>
								<id>angular e2e tests</id>
								<goals>
									<goal>npm</goal>
								</goals>
								<phase>generate-resources</phase>
								<configuration>
									<arguments>run e2e</arguments>
								</configuration>
							</execution>
```
The question - How I can conditionally set this execution, only in case an environment variable is set?
I don't want to run the e2e tests for everyone, only on a specific machine.

Any idea?
Thanks!

**Comment by eirslett** [comment]
You can probably use Maven profiles for this.
