### ISSUE TITLE
Version 1.11.1 not available on Maven Central

### ISSUE THREAD

**Issue by breun** [eirslett/frontend-maven-plugin#957]
According to https://github.com/eirslett/frontend-maven-plugin/releases/tag/frontend-plugins-1.11.1 version 1.11.1 was released in January. According to https://search.maven.org/artifact/com.github.eirslett/frontend-maven-plugin 1.11.0 is currently still the latest version on Maven Central.

**Comment by eirslett** [comment]
Looks like you're right! The release script failed. I triggered a release of 1.11.2 now, it should be on Central within a couple of hours.
