### ISSUE TITLE
Wrong node download url

### ISSUE THREAD

**Issue by iMinusMinus** [eirslett/frontend-maven-plugin#958]
**Do you want to request a _feature_ or report a _bug_?**
bug

**What is the current behavior?**
node cannot run correctly, system shows it exits abnormal

**If the current behavior is a bug, please provide the steps to reproduce.**
1. clone https://github.com/spring-io/start.spring.io.git.(version 0.0.1-SNAPSHOT)
2. run 'mvn clean install' under module 'start.spring.io client'

**What is the expected behavior?**
mvn install success

**Please mention your frontend-maven-plugin and operating system version.**
frontend-maven-plugin version: 1.10.0
OS: win10 32bit
Processor: Intel i5-4200U
Arch: x86_64 

Bug may be exist in class com.github.eirslett.maven.plugins.frontend.lib.Platform. 
As arch support 64bit, but os only support 32bit

**Comment by eirslett** [comment]
Uhm, what? Do you run a 32-bit version of Windows 10 on a 64-bit machine? What is the error output you're getting? This sounds like a strange edge case?

**Comment by iMinusMinus** [comment]
> Uhm, what? Do you run a 32-bit version of Windows 10 on a 64-bit machine? What is the error output you're getting? This sounds like a strange edge case?

An old computer, only 4G RAM.
My os locale language is Chinese, the tips what I saw was "此应用无法在你的电脑上运行" “若要找到适用你的电脑的版本，请联系软件发布者”.

**Comment by eirslett** [comment]
I think you might be the only one with this particular problem... try switching to 64 bit OS, then it should work.
