### ISSUE TITLE
Homepage incorrectly lists requirement 'Maven 3.0' instead of 'Maven 3.6'

### ISSUE THREAD

**Issue by timothy-devries-sirca** [eirslett/frontend-maven-plugin#974]
As of 12 May, Maven 3.6 is required. The homepage still suggests that Maven 3.0 is needed.

**Comment by eirslett** [comment]
Which homepage?

**Comment by timothy-devries-sirca** [comment]
It's listed on line 32 of README.md. Ideally it should be updated to list Maven 3.6 if that is the most recent required version

Thanks

**Comment by eirslett** [comment]
ok fixed it!
