### ISSUE TITLE
frontend-maven-plugin:1.12.0:npm (npm run build) on project ops-sahara: Failed to run task

### ISSUE THREAD

**Issue by tchape** [eirslett/frontend-maven-plugin#979]

**Comment by tchape** [comment]
my config pom.xml 

 <build>
        <plugins>
            <plugin>
                <groupId>com.github.eirslett</groupId>
                <artifactId>frontend-maven-plugin</artifactId>
                <version>1.12.0</version>
                <configuration>
                    <workingDirectory>frontend/src/main/angular</workingDirectory>
                    
                    <installDirectory>target</installDirectory>
                </configuration>
                <executions>
                    <execution>
                        <id>install node and npm</id>
                        <goals>
                            <goal>install-node-and-npm</goal>
                        </goals>
                        <configuration>
                            <nodeVersion>v12.18.3</nodeVersion>
                            <npmVersion>6.14.7</npmVersion>
                        </configuration>
                    </execution>
                    <execution>
                        <id>npm install</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>npm run build</id>
                        <goals>
                            <goal>npm</goal>
                        </goals>
                        <configuration>
                            <arguments>run build</arguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-antrun-plugin</artifactId>
                <executions>
                    <execution>
                       <phase>generate-resources</phase>
                       <configuration>
                           <target>
                                <copy todir="${project.build.directory}/classes/public">
                                   <fileset dir="${project.basedir}/frontend/build"/>
                               </copy>
                            </target>
                        </configuration>
                        <goals>
                            <goal>run</goal>
                       </goals>
                    </execution>
                </executions>
                </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>target/frontend</directory>
                <targetPath>static</targetPath>
            </resource>
        </resources>
    </build>

**Comment by eirslett** [comment]
Can you create a reproducible example? With only this error message, it's impossible to debug.

**Comment by tchape** [comment]
I build my projet in Jenkins and I have this error. in my IDE all in wright 

<img width="1381" alt="image" src="https://user-images.githubusercontent.com/12794136/123552207-6de80600-d775-11eb-81af-ac21d43bb69a.png">
